package org.hisrc.jsonix.xjc.plugin.tests.typescript;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;

import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.net.URL;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;

import org.junit.Before;
import org.junit.Test;

import com.sun.codemodel.JCodeModel;
import com.sun.tools.xjc.ConsoleErrorReporter;
import com.sun.tools.xjc.ModelLoader;
import com.sun.tools.xjc.Options;
import com.sun.tools.xjc.model.Model;

/**
 * CR-005: TypeScript declarations output. The purchase order schema is compared
 * against a golden file; the {@code zero} schema exercises enums, wildcards,
 * mixed content and element refs.
 */
public class TypeScriptOutputTest {

	@Before
	public void setUp() {
		System.setProperty("javax.xml.accessExternalSchema", "all");
	}

	private static void compile(String target, String schema, String binding) throws Exception {
		new File(target).mkdirs();
		final URL schemaUrl = TypeScriptOutputTest.class.getResource(schema);
		final String[] arguments = binding == null
				? new String[] { "-xmlschema", schemaUrl.toExternalForm(), "-d", target, "-extension", "-Xjsonix",
						"-Xjsonix-generateTypeScript" }
				: new String[] { "-xmlschema", schemaUrl.toExternalForm(), "-b",
						TypeScriptOutputTest.class.getResource(binding).toExternalForm(), "-d", target, "-extension",
						"-Xjsonix", "-Xjsonix-generateTypeScript" };
		final Options options = new Options();
		options.parseArguments(arguments);
		final ConsoleErrorReporter receiver = new ConsoleErrorReporter();
		final Model model = ModelLoader.load(options, new JCodeModel(), receiver);
		model.generateCode(options, receiver);
		model.codeModel.build(options.createCodeWriter());
	}

	private static String read(File file) throws IOException {
		return new String(Files.readAllBytes(file.toPath()), StandardCharsets.UTF_8).replace("\r\n", "\n");
	}

	private static String readResource(String name) throws IOException {
		final InputStream is = TypeScriptOutputTest.class.getResourceAsStream(name);
		try {
			final StringBuilder sb = new StringBuilder();
			final byte[] buffer = new byte[4096];
			int n;
			while ((n = is.read(buffer)) > 0) {
				sb.append(new String(buffer, 0, n, StandardCharsets.UTF_8));
			}
			return sb.toString().replace("\r\n", "\n");
		} finally {
			is.close();
		}
	}

	@Test
	public void purchaseOrderMatchesGoldenFile() throws Exception {
		final String target = "target/generated-sources/typescript/po";
		compile(target, "/typescript/po/purchaseorder.xsd", "/typescript/po/bindings.xjb");

		assertEquals(readResource("/typescript/po/PurchaseOrder.d.ts"), read(new File(target, "PurchaseOrder.d.ts")));
		// One re-export per output whose name differs from the module's.
		assertEquals("// Generated by jsonix-schema-compiler. Do not edit.\nexport * from './PurchaseOrder';\n",
				read(new File(target, "PurchaseOrder.std.d.ts")));
		assertEquals("// Generated by jsonix-schema-compiler. Do not edit.\nexport * from './PurchaseOrder';\n",
				read(new File(target, "PurchaseOrder.cmp.d.ts")));
		// The ES module output (phase 2) and its .d.mts companion.
		final String esm = read(new File(target, "PurchaseOrder.mjs"));
		assertTrue(esm.startsWith("// Generated by jsonix-schema-compiler: Jsonix mappings of the module [PurchaseOrder] as an ES module. Do not edit.\n"
				+ "export const PO = {\n  name: 'PO',\n"));
		assertTrue(esm.endsWith("};\n"));
		assertFalse(esm.contains("define("));
		assertEquals("// Generated by jsonix-schema-compiler. Do not edit.\nexport * from './PurchaseOrder.js';\n",
				read(new File(target, "PurchaseOrder.d.mts")));
	}

	@Test
	public void zeroSchemaCoversPropertyKinds() throws Exception {
		final String target = "target/generated-sources/typescript/zero";
		compile(target, "/basic/zero/schema.xsd", null);
		final String ts = read(new File(target, "org_hisrc_jsonix_tests_zero.d.ts"));

		// enums as literal unions, normalised like the mapping values
		assertTrue(ts.contains("export type StringEnumType = 'Apple' | 'Bear';"));
		assertTrue(ts.contains("export type TokenEnumType = 'Édition française.' | 'PB&J';"));
		// inheritance and TYPE_NAME discriminant including subtypes
		assertTrue(ts.contains("export interface ExtendedType extends BaseType {"));
		assertTrue(ts.contains("TYPE_NAME?: 'org_hisrc_jsonix_tests_zero.BaseType' | 'org_hisrc_jsonix_tests_zero.ExtendedExtendedType' | 'org_hisrc_jsonix_tests_zero.ExtendedType';"));
		// wildcards, any attributes, mixed element refs, dates
		assertTrue(ts.contains("any: XmlAnyElement;"));
		assertTrue(ts.contains("otherAttributes?: XmlAnyAttributes;"));
		assertTrue(ts.contains("content?: (TypedNamedValue<string> | string)[];"));
		assertTrue(ts.contains("dateTime?: XmlCalendar;"));
		assertTrue(ts.contains("qName?: XmlQName;"));
		// global elements and their union
		assertTrue(ts.contains("export type RootElement = "));
		assertTrue(ts.contains("export declare const org_hisrc_jsonix_tests_zero: JsonixMapping<RootElement>;"));
		// nothing left untyped by accident
		assertFalse(ts.contains(": undefined"));
		assertFalse(new File(target, "org_hisrc_jsonix_tests_zero.std.d.ts").exists());
	}
}
