package org.hisrc.jsonix.compilation.typescript;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import javax.xml.namespace.QName;

import org.apache.commons.lang3.Validate;
import org.hisrc.jsonix.JsonixConstants;
import org.hisrc.jsonix.compilation.typescript.TypeScriptModuleCompiler.GeneratedFile;
import org.hisrc.jsonix.definition.Mapping;
import org.hisrc.jsonix.definition.Module;
import org.hisrc.jsonix.definition.TypeScript;
import org.jvnet.jaxb.xml.bind.model.MClassInfo;
import org.jvnet.jaxb.xml.bind.model.MElementInfo;
import org.jvnet.jaxb.xml.bind.model.MPackagedTypeInfo;
import org.jvnet.jaxb.xml.bind.model.MTypeInfo;
import org.jvnet.jaxb.xml.bind.model.concrete.origin.CMElementInfoOrigin;

import com.sun.tools.xjc.model.CElementInfo;

/**
 * CR-010: the element factories of a module, docx4j's {@code ObjectFactory}
 * for the TypeScript model. Produces {@code <base>.factory.mjs} (creators, one
 * per class, and element wrappers, one per element declaration) and
 * {@code <base>.el.mjs} (per-local-name wrappers for the module's own
 * namespace), each with a {@code .d.mts} declaration file that imports the
 * module's declarations as the namespace {@code M}.
 */
public class FactoryCompiler<T, C extends T> {

	public static final String FACTORY_SUFFIX = ".factory";
	public static final String EL_SUFFIX = ".el";
	/** Alias under which the factory declarations import the module's own declarations. */
	public static final String OWN_ALIAS = "M";
	private static final String OWN_QUALIFIER = OWN_ALIAS + ".";
	private static final String HELPER = "__element";
	private static final String HEADER = "// Generated by jsonix-schema-compiler: ";
	private static final String DO_NOT_EDIT = ". Do not edit.\n";

	/** One exported function: its declaration, its implementation and where it came from. */
	private static final class Entry {
		final String declaration;
		final String implementation;
		final String source;

		Entry(String declaration, String implementation, String source) {
			this.declaration = declaration;
			this.implementation = implementation;
			this.source = source;
		}
	}

	private final TypeScriptModuleCompiler<T, C> moduleCompiler;
	private final Module<T, C> module;
	private final TypeScript typeScript;
	private final CreateTsTypeVisitor<T, C> types;
	/** Namespace URI → constant name in the generated JavaScript. */
	private final Map<String, String> namespaceConstants = new LinkedHashMap<String, String>();

	public FactoryCompiler(TypeScriptModuleCompiler<T, C> moduleCompiler, TypeScript typeScript) {
		this.moduleCompiler = Validate.notNull(moduleCompiler);
		this.module = moduleCompiler.getModule();
		this.typeScript = Validate.notNull(typeScript);
		this.types = new CreateTsTypeVisitor<T, C>(moduleCompiler);
	}

	public List<GeneratedFile> compile() {
		moduleCompiler.setOwnQualifier(OWN_QUALIFIER);
		try {
			final List<GeneratedFile> files = new ArrayList<GeneratedFile>();
			final String base = typeScript.getBaseName();
			final Map<String, Entry> factory = compileFactory();
			files.add(new GeneratedFile(base + FACTORY_SUFFIX + ".mjs", javascript(
					"element factories (creators and element wrappers) for the Jsonix module [" + module.getName() + "]",
					factory)));
			files.add(new GeneratedFile(base + FACTORY_SUFFIX + ".d.mts", declarations(
					"declarations of the element factories for the Jsonix module [" + module.getName() + "]", base,
					factory)));
			final Map<String, Entry> el = compileEl();
			files.add(new GeneratedFile(base + EL_SUFFIX + ".mjs", javascript(
					"per-name element wrappers for the namespace of the Jsonix module [" + module.getName() + "]",
					el)));
			files.add(new GeneratedFile(base + EL_SUFFIX + ".d.mts", declarations(
					"declarations of the per-name element wrappers for the Jsonix module [" + module.getName() + "]",
					base, el)));
			return files;
		} finally {
			moduleCompiler.setOwnQualifier("");
		}
	}

	// --- <base>.factory: creators and element wrappers ---

	private Map<String, Entry> compileFactory() {
		final Map<String, Entry> entries = new LinkedHashMap<String, Entry>();
		final Set<String> creators = new LinkedHashSet<String>();
		for (Mapping<T, C> mapping : module.getMappings()) {
			if (mapping.isEmpty()) {
				continue;
			}
			for (MClassInfo<T, C> classInfo : mapping.getClassInfos()) {
				if (moduleCompiler.isAbstract(classInfo)) {
					// As JAXB's ObjectFactory: no creator for an abstract type.
					continue;
				}
				final String localName = localName(classInfo);
				final String name = "create" + Ts.identifier(localName.replace(".", ""));
				final String type = moduleCompiler.ref(classInfo);
				final String typeName = moduleCompiler.typeName(classInfo);
				creators.add(name);
				add(entries, name, new Entry(
						"/** docx4j ObjectFactory.create" + localName.replace(".", "") + "(): a " + typeName
								+ " with TYPE_NAME set; a literal remains the stricter form (init is partial). */\n"
								+ "export function " + name + "(init?: Partial<Omit<" + type + ", '"
								+ Ts.TYPE_NAME_PROPERTY + "' | '" + Ts.PARENT_PROPERTY + "'>>): " + type + ";",
						"export function " + name + "(init) { return Object.assign({ " + Ts.TYPE_NAME_PROPERTY + ": "
								+ Ts.stringLiteral(typeName) + " }, init); }",
						"the class " + typeName + " of the mapping " + mapping.getMappingName()));
			}
			for (MElementInfo<T, C> elementInfo : mapping.getElementInfos()) {
				final QName elementName = elementInfo.getElementName();
				final MClassInfo<T, C> scope = elementInfo.getScope();
				// XJC's ObjectFactory method name: create + the element's squeezed name, which for a
				// scoped element already starts with the scope class (RT for w:t in R). Without an XJC
				// model the same shape is built from the scope and the local name.
				final String squeezed = squeezedName(elementInfo);
				final String local = squeezed != null ? squeezed
						: (scope == null ? "" : Ts.identifier(localName(scope).replace(".", "")))
								+ Ts.upperFirst(Ts.identifier(elementName.getLocalPart()));
				String name;
				final String doc;
				if (scope == null) {
					name = "create" + local + TypeScriptMappingCompiler.ELEMENT_SUFFIX;
					doc = "The global element " + qualified(elementName) + " (docx4j ObjectFactory.create" + local + "(value))";
				} else {
					name = "create" + local;
					doc = "The element " + qualified(elementName) + " in the scope of " + moduleCompiler.typeName(scope)
							+ " (docx4j ObjectFactory." + name + "(value))";
					if (creators.contains(name)) {
						// A nested class named after the element in the same scope (SdtPr.Alias and w:alias in
						// SdtPr): Java overloads createSdtPrAlias(); here the wrapper takes the Element suffix,
						// the rule the global wrappers already follow.
						name += TypeScriptMappingCompiler.ELEMENT_SUFFIX;
					}
				}
				add(entries, name, wrapper(name, doc, elementName, elementInfo, elementInfo.getTypeInfo(),
						"the element declaration " + qualified(elementName)
								+ (scope == null ? "" : " scoped in " + moduleCompiler.typeName(scope))
								+ " of the mapping " + mapping.getMappingName()));
			}
		}
		return entries;
	}

	// --- <base>.el: per-local-name wrappers for the module's own namespace ---

	private Map<String, Entry> compileEl() {
		// local name → the element declarations carrying it (in the mapping's own namespace)
		final Map<String, List<MElementInfo<T, C>>> byLocalName = new LinkedHashMap<String, List<MElementInfo<T, C>>>();
		final Map<String, String> namespaceOf = new LinkedHashMap<String, String>();
		final Map<String, String> mappingOf = new LinkedHashMap<String, String>();
		for (Mapping<T, C> mapping : module.getMappings()) {
			if (mapping.isEmpty()) {
				continue;
			}
			final String namespaceURI = mapping.getDefaultElementNamespaceURI();
			for (MElementInfo<T, C> elementInfo : mapping.getElementInfos()) {
				final QName elementName = elementInfo.getElementName();
				if (!namespaceURI.equals(elementName.getNamespaceURI())) {
					// A foreign-namespace declaration (m:r held by a WML class): reached through
					// its scoped wrapper or the owning module's el; keying on the local name would
					// conflate it with the module's own element of that name.
					continue;
				}
				final String localPart = elementName.getLocalPart();
				final String previousNamespace = namespaceOf.get(localPart);
				if (previousNamespace != null && !previousNamespace.equals(namespaceURI)) {
					throw new IllegalStateException("The element local name [" + localPart
							+ "] occurs in two namespaces of the module [" + module.getName() + "]: ["
							+ previousNamespace + "] (mapping " + mappingOf.get(localPart) + ") and [" + namespaceURI
							+ "] (mapping " + mapping.getMappingName()
							+ "); the per-name wrappers cannot be generated for a module mixing namespaces this way.");
				}
				namespaceOf.put(localPart, namespaceURI);
				mappingOf.put(localPart, mapping.getMappingName());
				List<MElementInfo<T, C>> list = byLocalName.get(localPart);
				if (list == null) {
					list = new ArrayList<MElementInfo<T, C>>();
					byLocalName.put(localPart, list);
				}
				list.add(elementInfo);
			}
		}
		final Map<String, Entry> entries = new LinkedHashMap<String, Entry>();
		for (Map.Entry<String, List<MElementInfo<T, C>>> entry : byLocalName.entrySet()) {
			final String localPart = entry.getKey();
			if (!Ts.isIdentifier(localPart)) {
				// Not expressible as an export name; the scoped wrappers remain.
				continue;
			}
			final List<MElementInfo<T, C>> declarations = entry.getValue();
			final QName elementName = declarations.get(0).getElementName();
			// The value type is the union of the types the name may carry; TYPE_NAME can be set
			// only when there is one.
			final Set<String> valueTypes = new LinkedHashSet<String>();
			final Set<String> typeNames = new LinkedHashSet<String>();
			for (MElementInfo<T, C> elementInfo : declarations) {
				valueTypes.add(types.typeOf(elementInfo, elementInfo.getTypeInfo()));
				final String typeName = mappedTypeName(elementInfo.getTypeInfo());
				typeNames.add(typeName == null ? "" : typeName);
			}
			final String valueType = Ts.union(valueTypes);
			final String typeName = typeNames.size() == 1 ? typeNames.iterator().next() : "";
			final String name = Ts.identifier(localPart);
			final boolean renamed = !name.equals(localPart);
			final String signature = "(value: " + valueType + "): " + OWN_QUALIFIER + Ts.TYPED_NAMED_VALUE + "<"
					+ valueType + ">";
			final String doc = "/** The element " + qualified(elementName)
					+ (typeNames.size() == 1 ? "" : " (" + typeNames.size()
							+ " types by scope: TYPE_NAME is left to the caller; see the scoped create* wrappers)")
					+ ". */\n";
			final String declaration = renamed
					? doc + "declare function " + name + signature + ";\nexport { " + name + " as " + localPart + " };"
					: doc + "export function " + name + signature + ";";
			final String body = "{ return " + HELPER + "(" + namespaceConstant(elementName.getNamespaceURI()) + ", "
					+ Ts.stringLiteral(localPart) + ", value" + (typeName.isEmpty() ? "" : ", " + Ts.stringLiteral(typeName))
					+ "); }";
			final String implementation = renamed
					? "function " + name + "(value) " + body + "\nexport { " + name + " as " + localPart + " };"
					: "export function " + name + "(value) " + body;
			add(entries, localPart, new Entry(declaration, implementation, "the element " + qualified(elementName)));
		}
		return entries;
	}

	// --- shared ---

	private Entry wrapper(String name, String doc, QName elementName, MElementInfo<T, C> elementInfo,
			MTypeInfo<T, C> typeInfo, String source) {
		final String valueType = types.typeOf(elementInfo, typeInfo);
		final String typeName = mappedTypeName(typeInfo);
		return new Entry(
				"/** " + doc + ". */\nexport function " + name + "(value: " + valueType + "): " + OWN_QUALIFIER
						+ Ts.TYPED_NAMED_VALUE + "<" + valueType + ">;",
				"export function " + name + "(value) { return " + HELPER + "("
						+ namespaceConstant(elementName.getNamespaceURI()) + ", " + Ts.stringLiteral(elementName.getLocalPart())
						+ ", value" + (typeName == null ? "" : ", " + Ts.stringLiteral(typeName)) + "); }",
				source);
	}

	/**
	 * The name XJC's ObjectFactory builds the element's method from: the
	 * {@code CElementInfo} squeezed name (scope class plus the element's local
	 * name capitalised, or plus the {@code jaxb:class} customization on the
	 * element, as docx4j's {@code CTMathRunTrackChangeRPrMath} for {@code m:rPr});
	 * {@code null} when the model is not an XJC model.
	 */
	private static String squeezedName(MElementInfo<?, ?> elementInfo) {
		final Object origin = elementInfo.getOrigin();
		if (origin instanceof CMElementInfoOrigin) {
			final Object source = ((CMElementInfoOrigin<?, ?, ?>) origin).getSource();
			if (source instanceof CElementInfo) {
				final String squeezed = ((CElementInfo) source).getSqueezedName();
				if (squeezed != null && !squeezed.isEmpty()) {
					return Ts.identifier(squeezed);
				}
			}
		}
		return null;
	}

	/** The TYPE_NAME of a class type that belongs to a mapping, else null (builtins, unmapped classes). */
	private String mappedTypeName(MTypeInfo<T, C> typeInfo) {
		if (typeInfo instanceof MClassInfo) {
			final MClassInfo<T, C> classInfo = (MClassInfo<T, C>) typeInfo;
			if (moduleCompiler.isMapped(classInfo)) {
				return moduleCompiler.typeName(classInfo);
			}
		}
		return null;
	}

	private void add(Map<String, Entry> entries, String name, Entry entry) {
		final Entry previous = entries.get(name);
		if (previous != null) {
			throw new IllegalStateException("The generated factory name [" + name + "] of the module ["
					+ module.getName() + "] is produced by two sources: " + previous.source + " and " + entry.source
					+ ". Rename one of them with a jaxb:class or jaxb:property customization (CR-010 does not rename silently).");
		}
		entries.put(name, entry);
	}

	private String namespaceConstant(String namespaceURI) {
		String constant = namespaceConstants.get(namespaceURI);
		if (constant == null) {
			constant = "__ns" + namespaceConstants.size();
			namespaceConstants.put(namespaceURI, constant);
		}
		return constant;
	}

	private String javascript(String title, Map<String, Entry> entries) {
		final StringBuilder sb = new StringBuilder();
		sb.append(HEADER).append(title).append(DO_NOT_EDIT);
		sb.append("// Every export is a pure function; a bundler keeps only the ones a program uses.\n");
		// Namespace constants first (in first-use order, which the entries fixed).
		final StringBuilder body = new StringBuilder();
		for (Entry entry : entries.values()) {
			body.append(entry.implementation).append('\n');
		}
		for (Map.Entry<String, String> entry : namespaceConstants.entrySet()) {
			sb.append("const ").append(entry.getValue()).append(" = ").append(Ts.stringLiteral(entry.getKey()))
					.append(";\n");
		}
		sb.append("function ").append(HELPER).append("(namespaceURI, localPart, value, typeName) {\n")
				.append("  if (typeName !== undefined && value !== null && typeof value === 'object' && value.")
				.append(Ts.TYPE_NAME_PROPERTY).append(" === undefined) { value.").append(Ts.TYPE_NAME_PROPERTY)
				.append(" = typeName; }\n").append("  return { name: { namespaceURI, localPart }, value };\n}\n");
		sb.append(body);
		// The constants are per file: reset for the next one.
		namespaceConstants.clear();
		return sb.toString();
	}

	private String declarations(String title, String base, Map<String, Entry> entries) {
		final StringBuilder sb = new StringBuilder();
		sb.append(HEADER).append(title).append(DO_NOT_EDIT);
		sb.append("import type * as ").append(OWN_ALIAS).append(" from './").append(base).append(".js';\n");
		// The support types are referenced by their bare names, as in the declarations.
		sb.append("import type { ").append(Ts.XML_QNAME).append(", ").append(Ts.XML_CALENDAR).append(", ")
				.append(Ts.XML_DURATION).append(", ").append(Ts.XML_DOM_NODE).append(", ").append(Ts.XML_ANY_ELEMENT)
				.append(", ").append(Ts.XML_ANY_ATTRIBUTES).append(" } from './").append(base).append(".js';\n");
		for (Map.Entry<Module<T, C>, String> entry : moduleCompiler.getImports().entrySet()) {
			sb.append("import type * as ").append(entry.getValue()).append(" from './")
					.append(entry.getKey().getTypeScripts().get(0).getBaseName()).append(".js';\n");
		}
		sb.append('\n');
		for (Entry entry : entries.values()) {
			sb.append(entry.declaration).append('\n');
		}
		return sb.toString();
	}

	private static String localName(MPackagedTypeInfo<?, ?> typeInfo) {
		return typeInfo.getContainerLocalName(JsonixConstants.DEFAULT_SCOPED_NAME_DELIMITER);
	}

	private static String qualified(QName name) {
		return name.getNamespaceURI() == null || name.getNamespaceURI().isEmpty() ? name.getLocalPart()
				: "{" + name.getNamespaceURI() + "}" + name.getLocalPart();
	}
}
