// Generated by jsonix-schema-compiler: TypeScript declarations for the Jsonix module [org_docx4j_docProps_core_dc_elements]. Do not edit.
// Describes the objects Jsonix produces when unmarshalling with this module's mappings.
import type * as Dep_org_docx4j_docProps_core from './org_docx4j_docProps_core';
import type * as Dep_org_docx4j_docProps_core_dc_terms from './org_docx4j_docProps_core_dc_terms';

/** Jsonix.XML.QName */
export interface XmlQName { namespaceURI: string; localPart: string; prefix?: string; key?: string; string?: string; }
/** Jsonix.XML.Calendar: the representation of date, time and dateTime values; unset fields are NaN. */
export interface XmlCalendar { year?: number; month?: number; day?: number; hour?: number; minute?: number; second?: number; fractionalSecond?: number; timezone?: number; }
/** The representation of xs:duration values. */
export interface XmlDuration { sign?: number; years?: number; months?: number; days?: number; hours?: number; minutes?: number; seconds?: number; }
/** An element as returned by an unmarshaller or held by an elementRef property. */
export interface TypedNamedValue<T> { name: XmlQName; value: T; }
/** A DOM node, allowed where the mapping permits DOM content (allowDom). */
export type XmlDomNode = any;
/** The value of an anyElement property: a typed element, a DOM node or (if mixed) text. */
export type XmlAnyElement = any;
/** The value of an anyAttribute property. */
export interface XmlAnyAttributes { [attributeName: string]: string; }
/** A Jsonix mapping object as consumed by new Jsonix.Context([...]); R is the union of its global element types. */
export interface JsonixMapping<R = unknown> { readonly __rootElement?: R; readonly [key: string]: unknown; }

export interface ElementContainer {
  TYPE_NAME?: 'org_docx4j_docProps_core_dc_elements.ElementContainer';
  any?: TypedNamedValue<SimpleLiteral>[];
}

export interface SimpleLiteral {
  TYPE_NAME?: 'org_docx4j_docProps_core_dc_elements.SimpleLiteral' | 'org_docx4j_docProps_core_dc_terms.Box' | 'org_docx4j_docProps_core_dc_terms.DCMIType' | 'org_docx4j_docProps_core_dc_terms.DDC' | 'org_docx4j_docProps_core_dc_terms.IMT' | 'org_docx4j_docProps_core_dc_terms.ISO3166' | 'org_docx4j_docProps_core_dc_terms.ISO6392' | 'org_docx4j_docProps_core_dc_terms.LCC' | 'org_docx4j_docProps_core_dc_terms.LCSH' | 'org_docx4j_docProps_core_dc_terms.MESH' | 'org_docx4j_docProps_core_dc_terms.Period' | 'org_docx4j_docProps_core_dc_terms.Point' | 'org_docx4j_docProps_core_dc_terms.RFC1766' | 'org_docx4j_docProps_core_dc_terms.RFC3066' | 'org_docx4j_docProps_core_dc_terms.TGN' | 'org_docx4j_docProps_core_dc_terms.UDC' | 'org_docx4j_docProps_core_dc_terms.URI' | 'org_docx4j_docProps_core_dc_terms.W3CDTF';
  readonly PARENT?: Dep_org_docx4j_docProps_core.CoreProperties | Dep_org_docx4j_docProps_core_dc_terms.ElementOrRefinementContainer | ElementContainer;
  content?: string[];
  lang?: string;
}

export type AnyElement = TypedNamedValue<SimpleLiteral>;

export type ContributorElement = TypedNamedValue<SimpleLiteral>;

export type CoverageElement = TypedNamedValue<SimpleLiteral>;

export type CreatorElement = TypedNamedValue<SimpleLiteral>;

export type DateElement = TypedNamedValue<SimpleLiteral>;

export type DescriptionElement = TypedNamedValue<SimpleLiteral>;

export type FormatElement = TypedNamedValue<SimpleLiteral>;

export type IdentifierElement = TypedNamedValue<SimpleLiteral>;

export type LanguageElement = TypedNamedValue<SimpleLiteral>;

export type PublisherElement = TypedNamedValue<SimpleLiteral>;

export type RelationElement = TypedNamedValue<SimpleLiteral>;

export type RightsElement = TypedNamedValue<SimpleLiteral>;

export type SourceElement = TypedNamedValue<SimpleLiteral>;

export type SubjectElement = TypedNamedValue<SimpleLiteral>;

export type TitleElement = TypedNamedValue<SimpleLiteral>;

export type TypeElement = TypedNamedValue<SimpleLiteral>;

/** Any global element of this mapping, i.e. what an unmarshaller returns. */
export type RootElement = AnyElement | ContributorElement | CoverageElement | CreatorElement | DateElement | DescriptionElement | FormatElement | IdentifierElement | LanguageElement | PublisherElement | RelationElement | RightsElement | SourceElement | SubjectElement | TitleElement | TypeElement;

/** The Jsonix mapping [org_docx4j_docProps_core_dc_elements] exported by the module's JavaScript file. */
export declare const org_docx4j_docProps_core_dc_elements: JsonixMapping<RootElement>;
