// Generated by jsonix-schema-compiler: TypeScript declarations for the Jsonix module [org_docx4j_com_microsoft_schemas_office_drawing_x2014_main]. Do not edit.
// Describes the objects Jsonix produces when unmarshalling with this module's mappings.

/** Jsonix.XML.QName */
export interface XmlQName { namespaceURI: string; localPart: string; prefix?: string; key?: string; string?: string; }
/** Jsonix.XML.Calendar: the representation of date, time and dateTime values; unset fields are NaN. */
export interface XmlCalendar { year?: number; month?: number; day?: number; hour?: number; minute?: number; second?: number; fractionalSecond?: number; timezone?: number; }
/** The representation of xs:duration values. */
export interface XmlDuration { sign?: number; years?: number; months?: number; days?: number; hours?: number; minutes?: number; seconds?: number; }
/** An element as returned by an unmarshaller or held by an elementRef property. */
export interface TypedNamedValue<T> { name: XmlQName; value: T; }
/** A DOM node, allowed where the mapping permits DOM content (allowDom). */
export type XmlDomNode = any;
/** The value of an anyElement property: a typed element, a DOM node or (if mixed) text. */
export type XmlAnyElement = any;
/** The value of an anyAttribute property. */
export interface XmlAnyAttributes { [attributeName: string]: string; }
/** A Jsonix mapping object as consumed by new Jsonix.Context([...]); R is the union of its global element types. */
export interface JsonixMapping<R = unknown> { readonly __rootElement?: R; readonly [key: string]: unknown; }

export interface CTConnectableReferences {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_main.CTConnectableReferences';
  st?: string;
  end?: string;
}

export interface CTCreationId {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_main.CTCreationId';
  id?: string;
}

export interface CTIdentifier {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_main.CTIdentifier';
  val: number;
}

export interface CTPredecessorDrawingElementReference {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_main.CTPredecessorDrawingElementReference';
  pred?: string;
}

export type ColIdElement = TypedNamedValue<CTIdentifier>;

export type CreationIdElement = TypedNamedValue<CTCreationId>;

export type CxnDERefsElement = TypedNamedValue<CTConnectableReferences>;

export type PredDERefElement = TypedNamedValue<CTPredecessorDrawingElementReference>;

export type RowIdElement = TypedNamedValue<CTIdentifier>;

/** Any global element of this mapping, i.e. what an unmarshaller returns. */
export type RootElement = ColIdElement | CreationIdElement | CxnDERefsElement | PredDERefElement | RowIdElement;

/** The Jsonix mapping [org_docx4j_com_microsoft_schemas_office_drawing_x2014_main] exported by the module's JavaScript file. */
export declare const org_docx4j_com_microsoft_schemas_office_drawing_x2014_main: JsonixMapping<RootElement>;
