// Generated by jsonix-schema-compiler: Jsonix mappings of the module [org_docx4j_com_microsoft_schemas_office_word_x2010_wordprocessingDrawing] as an ES module. Do not edit.
export const org_docx4j_com_microsoft_schemas_office_word_x2010_wordprocessingDrawing = {
  name: 'org_docx4j_com_microsoft_schemas_office_word_x2010_wordprocessingDrawing',
  defaultElementNamespaceURI: 'http:\/\/schemas.microsoft.com\/office\/word\/2010\/wordprocessingDrawing',
  typeInfos: [{
      localName: 'CTSizeRelH',
      typeName: 'CT_SizeRelH',
      propertyInfos: [{
          name: 'pctWidth',
          required: true,
          typeInfo: 'Int'
        }, {
          name: 'relativeFrom',
          required: true,
          typeInfo: '.STSizeRelFromH',
          attributeName: {
            localPart: 'relativeFrom'
          },
          type: 'attribute'
        }]
    }, {
      localName: 'CTSizeRelV',
      typeName: 'CT_SizeRelV',
      propertyInfos: [{
          name: 'pctHeight',
          required: true,
          typeInfo: 'Int'
        }, {
          name: 'relativeFrom',
          required: true,
          typeInfo: '.STSizeRelFromV',
          attributeName: {
            localPart: 'relativeFrom'
          },
          type: 'attribute'
        }]
    }, {
      type: 'enumInfo',
      localName: 'STSizeRelFromH',
      baseTypeInfo: 'Token',
      values: ['margin', 'page', 'leftMargin', 'rightMargin', 'insideMargin', 'outsideMargin']
    }, {
      type: 'enumInfo',
      localName: 'STSizeRelFromV',
      baseTypeInfo: 'Token',
      values: ['margin', 'page', 'topMargin', 'bottomMargin', 'insideMargin', 'outsideMargin']
    }],
  elementInfos: [{
      typeInfo: 'Int',
      elementName: 'pctPosHOffset'
    }, {
      typeInfo: 'Int',
      elementName: 'pctPosVOffset'
    }, {
      typeInfo: '.CTSizeRelH',
      elementName: 'sizeRelH'
    }, {
      typeInfo: '.CTSizeRelV',
      elementName: 'sizeRelV'
    }]
};
