// Generated by jsonix-schema-compiler: TypeScript declarations for the Jsonix module [org_docx4j_docProps_core_dc_terms]. Do not edit.
// Describes the objects Jsonix produces when unmarshalling with this module's mappings.
import type * as Dep_org_docx4j_docProps_core_dc_elements from './org_docx4j_docProps_core_dc_elements';
import type * as Dep_org_docx4j_docProps_core from './org_docx4j_docProps_core';

/** Jsonix.XML.QName */
export interface XmlQName { namespaceURI: string; localPart: string; prefix?: string; key?: string; string?: string; }
/** Jsonix.XML.Calendar: the representation of date, time and dateTime values; unset fields are NaN. */
export interface XmlCalendar { year?: number; month?: number; day?: number; hour?: number; minute?: number; second?: number; fractionalSecond?: number; timezone?: number; }
/** The representation of xs:duration values. */
export interface XmlDuration { sign?: number; years?: number; months?: number; days?: number; hours?: number; minutes?: number; seconds?: number; }
/** An element as returned by an unmarshaller or held by an elementRef property. */
export interface TypedNamedValue<T> { name: XmlQName; value: T; }
/** A DOM node, allowed where the mapping permits DOM content (allowDom). */
export type XmlDomNode = any;
/** The value of an anyElement property: a typed element, a DOM node or (if mixed) text. */
export type XmlAnyElement = any;
/** The value of an anyAttribute property. */
export interface XmlAnyAttributes { [attributeName: string]: string; }
/** A Jsonix mapping object as consumed by new Jsonix.Context([...]); R is the union of its global element types. */
export interface JsonixMapping<R = unknown> { readonly __rootElement?: R; readonly [key: string]: unknown; }

export interface Box extends Dep_org_docx4j_docProps_core_dc_elements.SimpleLiteral {
  TYPE_NAME?: 'org_docx4j_docProps_core_dc_terms.Box';
  readonly PARENT?: Dep_org_docx4j_docProps_core.CoreProperties | Dep_org_docx4j_docProps_core_dc_elements.ElementContainer | ElementOrRefinementContainer;
}

export interface DCMIType extends Dep_org_docx4j_docProps_core_dc_elements.SimpleLiteral {
  TYPE_NAME?: 'org_docx4j_docProps_core_dc_terms.DCMIType';
  readonly PARENT?: Dep_org_docx4j_docProps_core.CoreProperties | Dep_org_docx4j_docProps_core_dc_elements.ElementContainer | ElementOrRefinementContainer;
}

export interface DDC extends Dep_org_docx4j_docProps_core_dc_elements.SimpleLiteral {
  TYPE_NAME?: 'org_docx4j_docProps_core_dc_terms.DDC';
  readonly PARENT?: Dep_org_docx4j_docProps_core.CoreProperties | Dep_org_docx4j_docProps_core_dc_elements.ElementContainer | ElementOrRefinementContainer;
}

export interface ElementOrRefinementContainer {
  TYPE_NAME?: 'org_docx4j_docProps_core_dc_terms.ElementOrRefinementContainer';
  any?: TypedNamedValue<Dep_org_docx4j_docProps_core_dc_elements.SimpleLiteral>[];
}

export interface IMT extends Dep_org_docx4j_docProps_core_dc_elements.SimpleLiteral {
  TYPE_NAME?: 'org_docx4j_docProps_core_dc_terms.IMT';
  readonly PARENT?: Dep_org_docx4j_docProps_core.CoreProperties | Dep_org_docx4j_docProps_core_dc_elements.ElementContainer | ElementOrRefinementContainer;
}

export interface ISO3166 extends Dep_org_docx4j_docProps_core_dc_elements.SimpleLiteral {
  TYPE_NAME?: 'org_docx4j_docProps_core_dc_terms.ISO3166';
  readonly PARENT?: Dep_org_docx4j_docProps_core.CoreProperties | Dep_org_docx4j_docProps_core_dc_elements.ElementContainer | ElementOrRefinementContainer;
}

export interface ISO6392 extends Dep_org_docx4j_docProps_core_dc_elements.SimpleLiteral {
  TYPE_NAME?: 'org_docx4j_docProps_core_dc_terms.ISO6392';
  readonly PARENT?: Dep_org_docx4j_docProps_core.CoreProperties | Dep_org_docx4j_docProps_core_dc_elements.ElementContainer | ElementOrRefinementContainer;
}

export interface LCC extends Dep_org_docx4j_docProps_core_dc_elements.SimpleLiteral {
  TYPE_NAME?: 'org_docx4j_docProps_core_dc_terms.LCC';
  readonly PARENT?: Dep_org_docx4j_docProps_core.CoreProperties | Dep_org_docx4j_docProps_core_dc_elements.ElementContainer | ElementOrRefinementContainer;
}

export interface LCSH extends Dep_org_docx4j_docProps_core_dc_elements.SimpleLiteral {
  TYPE_NAME?: 'org_docx4j_docProps_core_dc_terms.LCSH';
  readonly PARENT?: Dep_org_docx4j_docProps_core.CoreProperties | Dep_org_docx4j_docProps_core_dc_elements.ElementContainer | ElementOrRefinementContainer;
}

export interface MESH extends Dep_org_docx4j_docProps_core_dc_elements.SimpleLiteral {
  TYPE_NAME?: 'org_docx4j_docProps_core_dc_terms.MESH';
  readonly PARENT?: Dep_org_docx4j_docProps_core.CoreProperties | Dep_org_docx4j_docProps_core_dc_elements.ElementContainer | ElementOrRefinementContainer;
}

export interface Period extends Dep_org_docx4j_docProps_core_dc_elements.SimpleLiteral {
  TYPE_NAME?: 'org_docx4j_docProps_core_dc_terms.Period';
  readonly PARENT?: Dep_org_docx4j_docProps_core.CoreProperties | Dep_org_docx4j_docProps_core_dc_elements.ElementContainer | ElementOrRefinementContainer;
}

export interface Point extends Dep_org_docx4j_docProps_core_dc_elements.SimpleLiteral {
  TYPE_NAME?: 'org_docx4j_docProps_core_dc_terms.Point';
  readonly PARENT?: Dep_org_docx4j_docProps_core.CoreProperties | Dep_org_docx4j_docProps_core_dc_elements.ElementContainer | ElementOrRefinementContainer;
}

export interface RFC1766 extends Dep_org_docx4j_docProps_core_dc_elements.SimpleLiteral {
  TYPE_NAME?: 'org_docx4j_docProps_core_dc_terms.RFC1766';
  readonly PARENT?: Dep_org_docx4j_docProps_core.CoreProperties | Dep_org_docx4j_docProps_core_dc_elements.ElementContainer | ElementOrRefinementContainer;
}

export interface RFC3066 extends Dep_org_docx4j_docProps_core_dc_elements.SimpleLiteral {
  TYPE_NAME?: 'org_docx4j_docProps_core_dc_terms.RFC3066';
  readonly PARENT?: Dep_org_docx4j_docProps_core.CoreProperties | Dep_org_docx4j_docProps_core_dc_elements.ElementContainer | ElementOrRefinementContainer;
}

export interface TGN extends Dep_org_docx4j_docProps_core_dc_elements.SimpleLiteral {
  TYPE_NAME?: 'org_docx4j_docProps_core_dc_terms.TGN';
  readonly PARENT?: Dep_org_docx4j_docProps_core.CoreProperties | Dep_org_docx4j_docProps_core_dc_elements.ElementContainer | ElementOrRefinementContainer;
}

export interface UDC extends Dep_org_docx4j_docProps_core_dc_elements.SimpleLiteral {
  TYPE_NAME?: 'org_docx4j_docProps_core_dc_terms.UDC';
  readonly PARENT?: Dep_org_docx4j_docProps_core.CoreProperties | Dep_org_docx4j_docProps_core_dc_elements.ElementContainer | ElementOrRefinementContainer;
}

export interface URI extends Dep_org_docx4j_docProps_core_dc_elements.SimpleLiteral {
  TYPE_NAME?: 'org_docx4j_docProps_core_dc_terms.URI';
  readonly PARENT?: Dep_org_docx4j_docProps_core.CoreProperties | Dep_org_docx4j_docProps_core_dc_elements.ElementContainer | ElementOrRefinementContainer;
}

export interface W3CDTF extends Dep_org_docx4j_docProps_core_dc_elements.SimpleLiteral {
  TYPE_NAME?: 'org_docx4j_docProps_core_dc_terms.W3CDTF';
  readonly PARENT?: Dep_org_docx4j_docProps_core.CoreProperties | Dep_org_docx4j_docProps_core_dc_elements.ElementContainer | ElementOrRefinementContainer;
}

export type AbstractElement = TypedNamedValue<Dep_org_docx4j_docProps_core_dc_elements.SimpleLiteral>;

export type AccessRightsElement = TypedNamedValue<Dep_org_docx4j_docProps_core_dc_elements.SimpleLiteral>;

export type AlternativeElement = TypedNamedValue<Dep_org_docx4j_docProps_core_dc_elements.SimpleLiteral>;

export type AudienceElement = TypedNamedValue<Dep_org_docx4j_docProps_core_dc_elements.SimpleLiteral>;

export type AvailableElement = TypedNamedValue<Dep_org_docx4j_docProps_core_dc_elements.SimpleLiteral>;

export type BibliographicCitationElement = TypedNamedValue<Dep_org_docx4j_docProps_core_dc_elements.SimpleLiteral>;

export type ConformsToElement = TypedNamedValue<Dep_org_docx4j_docProps_core_dc_elements.SimpleLiteral>;

export type CreatedElement = TypedNamedValue<Dep_org_docx4j_docProps_core_dc_elements.SimpleLiteral>;

export type DateAcceptedElement = TypedNamedValue<Dep_org_docx4j_docProps_core_dc_elements.SimpleLiteral>;

export type DateCopyrightedElement = TypedNamedValue<Dep_org_docx4j_docProps_core_dc_elements.SimpleLiteral>;

export type DateSubmittedElement = TypedNamedValue<Dep_org_docx4j_docProps_core_dc_elements.SimpleLiteral>;

export type EducationLevelElement = TypedNamedValue<Dep_org_docx4j_docProps_core_dc_elements.SimpleLiteral>;

export type ExtentElement = TypedNamedValue<Dep_org_docx4j_docProps_core_dc_elements.SimpleLiteral>;

export type HasFormatElement = TypedNamedValue<Dep_org_docx4j_docProps_core_dc_elements.SimpleLiteral>;

export type HasPartElement = TypedNamedValue<Dep_org_docx4j_docProps_core_dc_elements.SimpleLiteral>;

export type HasVersionElement = TypedNamedValue<Dep_org_docx4j_docProps_core_dc_elements.SimpleLiteral>;

export type IsFormatOfElement = TypedNamedValue<Dep_org_docx4j_docProps_core_dc_elements.SimpleLiteral>;

export type IsPartOfElement = TypedNamedValue<Dep_org_docx4j_docProps_core_dc_elements.SimpleLiteral>;

export type IsReferencedByElement = TypedNamedValue<Dep_org_docx4j_docProps_core_dc_elements.SimpleLiteral>;

export type IsReplacedByElement = TypedNamedValue<Dep_org_docx4j_docProps_core_dc_elements.SimpleLiteral>;

export type IsRequiredByElement = TypedNamedValue<Dep_org_docx4j_docProps_core_dc_elements.SimpleLiteral>;

export type IsVersionOfElement = TypedNamedValue<Dep_org_docx4j_docProps_core_dc_elements.SimpleLiteral>;

export type IssuedElement = TypedNamedValue<Dep_org_docx4j_docProps_core_dc_elements.SimpleLiteral>;

export type MediatorElement = TypedNamedValue<Dep_org_docx4j_docProps_core_dc_elements.SimpleLiteral>;

export type MediumElement = TypedNamedValue<Dep_org_docx4j_docProps_core_dc_elements.SimpleLiteral>;

export type ModifiedElement = TypedNamedValue<Dep_org_docx4j_docProps_core_dc_elements.SimpleLiteral>;

export type ReferencesElement = TypedNamedValue<Dep_org_docx4j_docProps_core_dc_elements.SimpleLiteral>;

export type ReplacesElement = TypedNamedValue<Dep_org_docx4j_docProps_core_dc_elements.SimpleLiteral>;

export type RequiresElement = TypedNamedValue<Dep_org_docx4j_docProps_core_dc_elements.SimpleLiteral>;

export type SpatialElement = TypedNamedValue<Dep_org_docx4j_docProps_core_dc_elements.SimpleLiteral>;

export type TableOfContentsElement = TypedNamedValue<Dep_org_docx4j_docProps_core_dc_elements.SimpleLiteral>;

export type TemporalElement = TypedNamedValue<Dep_org_docx4j_docProps_core_dc_elements.SimpleLiteral>;

export type ValidElement = TypedNamedValue<Dep_org_docx4j_docProps_core_dc_elements.SimpleLiteral>;

/** Any global element of this mapping, i.e. what an unmarshaller returns. */
export type RootElement = AbstractElement | AccessRightsElement | AlternativeElement | AudienceElement | AvailableElement | BibliographicCitationElement | ConformsToElement | CreatedElement | DateAcceptedElement | DateCopyrightedElement | DateSubmittedElement | EducationLevelElement | ExtentElement | HasFormatElement | HasPartElement | HasVersionElement | IsFormatOfElement | IsPartOfElement | IsReferencedByElement | IsReplacedByElement | IsRequiredByElement | IsVersionOfElement | IssuedElement | MediatorElement | MediumElement | ModifiedElement | ReferencesElement | ReplacesElement | RequiresElement | SpatialElement | TableOfContentsElement | TemporalElement | ValidElement;

/** The Jsonix mapping [org_docx4j_docProps_core_dc_terms] exported by the module's JavaScript file. */
export declare const org_docx4j_docProps_core_dc_terms: JsonixMapping<RootElement>;
