// Generated by jsonix-schema-compiler: TypeScript declarations for the Jsonix module [org_docx4j_org_w3_x1998_math_mathML]. Do not edit.
// Describes the objects Jsonix produces when unmarshalling with this module's mappings.

/** Jsonix.XML.QName */
export interface XmlQName { namespaceURI: string; localPart: string; prefix?: string; key?: string; string?: string; }
/** Jsonix.XML.Calendar: the representation of date, time and dateTime values; unset fields are NaN. */
export interface XmlCalendar { year?: number; month?: number; day?: number; hour?: number; minute?: number; second?: number; fractionalSecond?: number; timezone?: number; }
/** The representation of xs:duration values. */
export interface XmlDuration { sign?: number; years?: number; months?: number; days?: number; hours?: number; minutes?: number; seconds?: number; }
/** An element as returned by an unmarshaller or held by an elementRef property. */
export interface TypedNamedValue<T> { name: XmlQName; value: T; }
/** A DOM node, allowed where the mapping permits DOM content (allowDom). */
export type XmlDomNode = any;
/** The value of an anyElement property: a typed element, a DOM node or (if mixed) text. */
export type XmlAnyElement = any;
/** The value of an anyAttribute property. */
export interface XmlAnyAttributes { [attributeName: string]: string; }
/** A Jsonix mapping object as consumed by new Jsonix.Context([...]); R is the union of its global element types. */
export interface JsonixMapping<R = unknown> { readonly __rootElement?: R; readonly [key: string]: unknown; }

export interface ApplyType {
  TYPE_NAME?: 'org_docx4j_org_w3_x1998_math_mathML.ApplyType';
  otherAttributes?: XmlAnyAttributes;
  abs: OperatorType;
  floor: OperatorType;
  ceiling: OperatorType;
  quotient: OperatorType;
  divide: OperatorType;
  rem: OperatorType;
  minus: OperatorType;
  plus: OperatorType;
  times: OperatorType;
  power: OperatorType;
  root: OperatorType;
  max: OperatorType;
  min: OperatorType;
  and: OperatorType;
  or: OperatorType;
  xor: OperatorType;
  not: OperatorType;
  exponentiale: ConstantType;
  pi: ConstantType;
  _true: ConstantType;
  _false: ConstantType;
  eq: OperatorType;
  neq: OperatorType;
  leq: OperatorType;
  lt: OperatorType;
  geq: OperatorType;
  gt: OperatorType;
  exp: OperatorType;
  ln: OperatorType;
  log: OperatorType;
  sin: OperatorType;
  cos: OperatorType;
  tan: OperatorType;
  arcsin: OperatorType;
  arccos: OperatorType;
  arctan: OperatorType;
  expressionContent?: (TypedNamedValue<CnType> | TypedNamedValue<CiType> | TypedNamedValue<ConstantType> | TypedNamedValue<ApplyType> | TypedNamedValue<QualifierType>)[];
}

export interface CiType {
  TYPE_NAME?: 'org_docx4j_org_w3_x1998_math_mathML.CiType';
  otherAttributes?: XmlAnyAttributes;
  content?: string;
}

export interface CnType {
  TYPE_NAME?: 'org_docx4j_org_w3_x1998_math_mathML.CnType';
  otherAttributes?: XmlAnyAttributes;
  content?: (TypedNamedValue<SepType> | string)[];
  type?: string;
}

export interface ConstantType {
  TYPE_NAME?: 'org_docx4j_org_w3_x1998_math_mathML.ConstantType';
  otherAttributes?: XmlAnyAttributes;
}

export interface MathType {
  TYPE_NAME?: 'org_docx4j_org_w3_x1998_math_mathML.MathType';
  otherAttributes?: XmlAnyAttributes;
  cn: CnType;
  ci: CiType;
  exponentiale: ConstantType;
  pi: ConstantType;
  _true: ConstantType;
  _false: ConstantType;
  apply: ApplyType;
  logbase: QualifierType;
  degree: QualifierType;
}

export interface OperatorType {
  TYPE_NAME?: 'org_docx4j_org_w3_x1998_math_mathML.OperatorType';
  otherAttributes?: XmlAnyAttributes;
}

export interface QualifierType {
  TYPE_NAME?: 'org_docx4j_org_w3_x1998_math_mathML.QualifierType';
  otherAttributes?: XmlAnyAttributes;
  cn: CnType;
  ci: CiType;
  exponentiale: ConstantType;
  pi: ConstantType;
  _true: ConstantType;
  _false: ConstantType;
  apply: ApplyType;
  logbase: QualifierType;
  degree: QualifierType;
}

export interface SepType {
  TYPE_NAME?: 'org_docx4j_org_w3_x1998_math_mathML.SepType';
}

export type AbsElement = TypedNamedValue<OperatorType>;

export type AndElement = TypedNamedValue<OperatorType>;

export type ApplyElement = TypedNamedValue<ApplyType>;

export type ArccosElement = TypedNamedValue<OperatorType>;

export type ArcsinElement = TypedNamedValue<OperatorType>;

export type ArctanElement = TypedNamedValue<OperatorType>;

export type CeilingElement = TypedNamedValue<OperatorType>;

export type CiElement = TypedNamedValue<CiType>;

export type CnElement = TypedNamedValue<CnType>;

export type CosElement = TypedNamedValue<OperatorType>;

export type DegreeElement = TypedNamedValue<QualifierType>;

export type DivideElement = TypedNamedValue<OperatorType>;

export type EqElement = TypedNamedValue<OperatorType>;

export type ExpElement = TypedNamedValue<OperatorType>;

export type ExponentialeElement = TypedNamedValue<ConstantType>;

export type FalseElement = TypedNamedValue<ConstantType>;

export type FloorElement = TypedNamedValue<OperatorType>;

export type GeqElement = TypedNamedValue<OperatorType>;

export type GtElement = TypedNamedValue<OperatorType>;

export type LeqElement = TypedNamedValue<OperatorType>;

export type LnElement = TypedNamedValue<OperatorType>;

export type LogElement = TypedNamedValue<OperatorType>;

export type LogbaseElement = TypedNamedValue<QualifierType>;

export type LtElement = TypedNamedValue<OperatorType>;

export type MathElement = TypedNamedValue<MathType>;

export type MaxElement = TypedNamedValue<OperatorType>;

export type MinElement = TypedNamedValue<OperatorType>;

export type MinusElement = TypedNamedValue<OperatorType>;

export type NeqElement = TypedNamedValue<OperatorType>;

export type NotElement = TypedNamedValue<OperatorType>;

export type OrElement = TypedNamedValue<OperatorType>;

export type PiElement = TypedNamedValue<ConstantType>;

export type PlusElement = TypedNamedValue<OperatorType>;

export type PowerElement = TypedNamedValue<OperatorType>;

export type ProductElement = TypedNamedValue<OperatorType>;

export type QuotientElement = TypedNamedValue<OperatorType>;

export type RemElement = TypedNamedValue<OperatorType>;

export type RootElement = TypedNamedValue<OperatorType>;

export type SepElement = TypedNamedValue<SepType>;

export type SinElement = TypedNamedValue<OperatorType>;

export type SumElement = TypedNamedValue<OperatorType>;

export type TanElement = TypedNamedValue<OperatorType>;

export type TimesElement = TypedNamedValue<OperatorType>;

export type TrueElement = TypedNamedValue<ConstantType>;

export type XorElement = TypedNamedValue<OperatorType>;

/** Any global element of this mapping, i.e. what an unmarshaller returns. */
export type RootElement2 = AbsElement | AndElement | ApplyElement | ArccosElement | ArcsinElement | ArctanElement | CeilingElement | CiElement | CnElement | CosElement | DegreeElement | DivideElement | EqElement | ExpElement | ExponentialeElement | FalseElement | FloorElement | GeqElement | GtElement | LeqElement | LnElement | LogElement | LogbaseElement | LtElement | MathElement | MaxElement | MinElement | MinusElement | NeqElement | NotElement | OrElement | PiElement | PlusElement | PowerElement | ProductElement | QuotientElement | RemElement | RootElement | SepElement | SinElement | SumElement | TanElement | TimesElement | TrueElement | XorElement;

/** The Jsonix mapping [org_docx4j_org_w3_x1998_math_mathML] exported by the module's JavaScript file. */
export declare const org_docx4j_org_w3_x1998_math_mathML: JsonixMapping<RootElement2>;
