// Generated by jsonix-schema-compiler: TypeScript declarations for the Jsonix module [org_docx4j_docProps_variantTypes]. Do not edit.
// Describes the objects Jsonix produces when unmarshalling with this module's mappings.
import type * as Dep_org_docx4j_docProps_custom from './org_docx4j_docProps_custom';
import type * as Dep_org_docx4j_docProps_extended from './org_docx4j_docProps_extended';

/** Jsonix.XML.QName */
export interface XmlQName { namespaceURI: string; localPart: string; prefix?: string; key?: string; string?: string; }
/** Jsonix.XML.Calendar: the representation of date, time and dateTime values; unset fields are NaN. */
export interface XmlCalendar { year?: number; month?: number; day?: number; hour?: number; minute?: number; second?: number; fractionalSecond?: number; timezone?: number; }
/** The representation of xs:duration values. */
export interface XmlDuration { sign?: number; years?: number; months?: number; days?: number; hours?: number; minutes?: number; seconds?: number; }
/** An element as returned by an unmarshaller or held by an elementRef property. */
export interface TypedNamedValue<T> { name: XmlQName; value: T; }
/** A DOM node, allowed where the mapping permits DOM content (allowDom). */
export type XmlDomNode = any;
/** The value of an anyElement property: a typed element, a DOM node or (if mixed) text. */
export type XmlAnyElement = any;
/** The value of an anyAttribute property. */
export interface XmlAnyAttributes { [attributeName: string]: string; }
/** A Jsonix mapping object as consumed by new Jsonix.Context([...]); R is the union of its global element types. */
export interface JsonixMapping<R = unknown> { readonly __rootElement?: R; readonly [key: string]: unknown; }

export interface Array {
  TYPE_NAME?: 'org_docx4j_docProps_variantTypes.Array';
  readonly PARENT?: Dep_org_docx4j_docProps_custom.Properties.Property | Variant;
  variantOrI1OrI2: (TypedNamedValue<Variant> | TypedNamedValue<number> | TypedNamedValue<string> | TypedNamedValue<boolean>)[];
  lBounds: number;
  uBounds: number;
  baseType: string;
}

export interface Cf {
  TYPE_NAME?: 'org_docx4j_docProps_variantTypes.Cf';
  readonly PARENT?: Dep_org_docx4j_docProps_custom.Properties.Property | Variant | Vector;
  value?: string;
  format?: string;
}

export interface Empty {
  TYPE_NAME?: 'org_docx4j_docProps_variantTypes.Empty';
  readonly PARENT?: Dep_org_docx4j_docProps_custom.Properties.Property | Variant;
}

export interface Null {
  TYPE_NAME?: 'org_docx4j_docProps_variantTypes.Null';
  readonly PARENT?: Dep_org_docx4j_docProps_custom.Properties.Property | Variant;
}

export interface Variant {
  TYPE_NAME?: 'org_docx4j_docProps_variantTypes.Variant';
  readonly PARENT?: Array | Variant | Vector;
  variant: Variant;
  vector: Vector;
  array: Array;
  blob: string;
  oblob: string;
  empty: Empty;
  _null: Null;
  i1: number;
  i2: number;
  i4: number;
  i8: number;
  _int: number;
  ui1: number;
  ui2: number;
  ui4: number;
  ui8: number;
  uint: number;
  r4: number;
  r8: number;
  decimal: number;
  lpstr: string;
  lpwstr: string;
  bstr: string;
  date: XmlCalendar;
  filetime: XmlCalendar;
  bool: boolean;
  cy: string;
  error: string;
  stream: string;
  ostream: string;
  storage: string;
  ostorage: string;
  vstream: Vstream;
  clsid: string;
  cf: Cf;
}

export interface Vector {
  TYPE_NAME?: 'org_docx4j_docProps_variantTypes.Vector';
  readonly PARENT?: Dep_org_docx4j_docProps_custom.Properties.Property | Dep_org_docx4j_docProps_extended.Properties.HLinks | Dep_org_docx4j_docProps_extended.Properties.HeadingPairs | Dep_org_docx4j_docProps_extended.Properties.TitlesOfParts | Variant;
  variantOrI1OrI2: (TypedNamedValue<Variant> | TypedNamedValue<number> | TypedNamedValue<string> | TypedNamedValue<boolean> | TypedNamedValue<Cf>)[];
  baseType: string;
  size: number;
}

export interface Vstream {
  TYPE_NAME?: 'org_docx4j_docProps_variantTypes.Vstream';
  readonly PARENT?: Dep_org_docx4j_docProps_custom.Properties.Property | Variant;
  value?: string;
  version?: string;
}

export type ArrayElement = TypedNamedValue<Array>;

export type BlobElement = TypedNamedValue<string>;

export type BoolElement = TypedNamedValue<boolean>;

export type BstrElement = TypedNamedValue<string>;

export type CfElement = TypedNamedValue<Cf>;

export type ClsidElement = TypedNamedValue<string>;

export type CyElement = TypedNamedValue<string>;

export type DateElement = TypedNamedValue<XmlCalendar>;

export type DecimalElement = TypedNamedValue<number>;

export type EmptyElement = TypedNamedValue<Empty>;

export type ErrorElement = TypedNamedValue<string>;

export type FiletimeElement = TypedNamedValue<XmlCalendar>;

export type I1Element = TypedNamedValue<number>;

export type I2Element = TypedNamedValue<number>;

export type I4Element = TypedNamedValue<number>;

export type I8Element = TypedNamedValue<number>;

export type IntElement = TypedNamedValue<number>;

export type LpstrElement = TypedNamedValue<string>;

export type LpwstrElement = TypedNamedValue<string>;

export type NullElement = TypedNamedValue<Null>;

export type OblobElement = TypedNamedValue<string>;

export type OstorageElement = TypedNamedValue<string>;

export type OstreamElement = TypedNamedValue<string>;

export type R4Element = TypedNamedValue<number>;

export type R8Element = TypedNamedValue<number>;

export type StorageElement = TypedNamedValue<string>;

export type StreamElement = TypedNamedValue<string>;

export type Ui1Element = TypedNamedValue<number>;

export type Ui2Element = TypedNamedValue<number>;

export type Ui4Element = TypedNamedValue<number>;

export type Ui8Element = TypedNamedValue<number>;

export type UintElement = TypedNamedValue<number>;

export type VariantElement = TypedNamedValue<Variant>;

export type VectorElement = TypedNamedValue<Vector>;

export type VstreamElement = TypedNamedValue<Vstream>;

/** Any global element of this mapping, i.e. what an unmarshaller returns. */
export type RootElement = ArrayElement | BlobElement | BoolElement | BstrElement | CfElement | ClsidElement | CyElement | DateElement | DecimalElement | EmptyElement | ErrorElement | FiletimeElement | I1Element | I2Element | I4Element | I8Element | IntElement | LpstrElement | LpwstrElement | NullElement | OblobElement | OstorageElement | OstreamElement | R4Element | R8Element | StorageElement | StreamElement | Ui1Element | Ui2Element | Ui4Element | Ui8Element | UintElement | VariantElement | VectorElement | VstreamElement;

/** The Jsonix mapping [org_docx4j_docProps_variantTypes] exported by the module's JavaScript file. */
export declare const org_docx4j_docProps_variantTypes: JsonixMapping<RootElement>;
