// Generated by jsonix-schema-compiler: Jsonix mappings of the module [org_docx4j_dml_diagram2008] as an ES module. Do not edit.
export const org_docx4j_dml_diagram2008 = {
  name: 'org_docx4j_dml_diagram2008',
  defaultElementNamespaceURI: 'http:\/\/schemas.microsoft.com\/office\/drawing\/2008\/diagram',
  dependencies: ['org_docx4j_dml'],
  typeInfos: [{
      localName: 'CTDataModelExtBlock',
      typeName: 'CT_DataModelExtBlock',
      propertyInfos: [{
          name: 'minVer',
          attributeName: {
            localPart: 'minVer'
          },
          type: 'attribute'
        }, {
          name: 'relId',
          attributeName: {
            localPart: 'relId'
          },
          type: 'attribute'
        }]
    }, {
      localName: 'CTDrawing',
      typeName: 'CT_Drawing',
      propertyInfos: [{
          name: 'spTree',
          required: true,
          typeInfo: '.CTGroupShape'
        }]
    }, {
      localName: 'CTGroupShape',
      typeName: 'CT_GroupShape',
      propertyInfos: [{
          name: 'nvGrpSpPr',
          required: true,
          typeInfo: '.CTGroupShapeNonVisual'
        }, {
          name: 'grpSpPr',
          required: true,
          typeInfo: 'org_docx4j_dml.CTGroupShapeProperties'
        }, {
          name: 'spOrGrpSp',
          minOccurs: 0,
          collection: true,
          elementTypeInfos: [{
              elementName: 'sp',
              typeInfo: '.CTShape'
            }, {
              elementName: 'grpSp',
              typeInfo: '.CTGroupShape'
            }],
          type: 'elements'
        }, {
          name: 'extLst',
          typeInfo: 'org_docx4j_dml.CTOfficeArtExtensionList'
        }]
    }, {
      localName: 'CTGroupShapeNonVisual',
      typeName: 'CT_GroupShapeNonVisual',
      propertyInfos: [{
          name: 'cNvPr',
          required: true,
          typeInfo: 'org_docx4j_dml.CTNonVisualDrawingProps'
        }, {
          name: 'cNvGrpSpPr',
          required: true,
          typeInfo: 'org_docx4j_dml.CTNonVisualGroupDrawingShapeProps'
        }]
    }, {
      localName: 'CTShape',
      typeName: 'CT_Shape',
      propertyInfos: [{
          name: 'nvSpPr',
          required: true,
          typeInfo: '.CTShapeNonVisual'
        }, {
          name: 'spPr',
          required: true,
          typeInfo: 'org_docx4j_dml.CTShapeProperties'
        }, {
          name: 'style',
          typeInfo: 'org_docx4j_dml.CTShapeStyle'
        }, {
          name: 'txBody',
          typeInfo: 'org_docx4j_dml.CTTextBody'
        }, {
          name: 'txXfrm',
          typeInfo: 'org_docx4j_dml.CTTransform2D'
        }, {
          name: 'extLst',
          typeInfo: 'org_docx4j_dml.CTOfficeArtExtensionList'
        }, {
          name: 'modelId',
          required: true,
          attributeName: {
            localPart: 'modelId'
          },
          type: 'attribute'
        }]
    }, {
      localName: 'CTShapeNonVisual',
      typeName: 'CT_ShapeNonVisual',
      propertyInfos: [{
          name: 'cNvPr',
          required: true,
          typeInfo: 'org_docx4j_dml.CTNonVisualDrawingProps'
        }, {
          name: 'cNvSpPr',
          required: true,
          typeInfo: 'org_docx4j_dml.CTNonVisualDrawingShapeProps'
        }]
    }],
  elementInfos: [{
      typeInfo: '.CTDataModelExtBlock',
      elementName: 'dataModelExt'
    }, {
      typeInfo: '.CTDrawing',
      elementName: 'drawing'
    }]
};
