// Generated by jsonix-schema-compiler: TypeScript declarations for the Jsonix module [org_docx4j_com_microsoft_schemas_office_drawing_x201611_diagram]. Do not edit.
// Describes the objects Jsonix produces when unmarshalling with this module's mappings.
import type * as Dep_org_docx4j_dml from './org_docx4j_dml';

/** Jsonix.XML.QName */
export interface XmlQName { namespaceURI: string; localPart: string; prefix?: string; key?: string; string?: string; }
/** Jsonix.XML.Calendar: the representation of date, time and dateTime values; unset fields are NaN. */
export interface XmlCalendar { year?: number; month?: number; day?: number; hour?: number; minute?: number; second?: number; fractionalSecond?: number; timezone?: number; }
/** The representation of xs:duration values. */
export interface XmlDuration { sign?: number; years?: number; months?: number; days?: number; hours?: number; minutes?: number; seconds?: number; }
/** An element as returned by an unmarshaller or held by an elementRef property. */
export interface TypedNamedValue<T> { name: XmlQName; value: T; }
/** A DOM node, allowed where the mapping permits DOM content (allowDom). */
export type XmlDomNode = any;
/** The value of an anyElement property: a typed element, a DOM node or (if mixed) text. */
export type XmlAnyElement = any;
/** The value of an anyAttribute property. */
export interface XmlAnyAttributes { [attributeName: string]: string; }
/** A Jsonix mapping object as consumed by new Jsonix.Context([...]); R is the union of its global element types. */
export interface JsonixMapping<R = unknown> { readonly __rootElement?: R; readonly [key: string]: unknown; }

export interface CTDiagramAutoBullet {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x201611_diagram.CTDiagramAutoBullet';
  readonly PARENT?: CTNumberDiagramInfo;
  buNone: Dep_org_docx4j_dml.CTTextNoBullet;
  buAutoNum: Dep_org_docx4j_dml.CTTextAutonumberBullet;
  buChar: Dep_org_docx4j_dml.CTTextCharBullet;
  buBlip: Dep_org_docx4j_dml.CTTextBlipBullet;
  prefix?: string;
  leadZeros?: boolean;
}

export interface CTNumberDiagramInfo {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x201611_diagram.CTNumberDiagramInfo';
  readonly PARENT?: CTNumberDiagramInfoList;
  buPr: CTDiagramAutoBullet;
  lvl: number;
  ptType: STSTorageType;
}

export interface CTNumberDiagramInfoList {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x201611_diagram.CTNumberDiagramInfoList';
  autoBuNodeInfo?: CTNumberDiagramInfo[];
}

export type STSTorageType = 'sibTrans' | 'parTrans';

export type AutoBuNodeInfoLstElement = TypedNamedValue<CTNumberDiagramInfoList>;

/** Any global element of this mapping, i.e. what an unmarshaller returns. */
export type RootElement = AutoBuNodeInfoLstElement;

/** The Jsonix mapping [org_docx4j_com_microsoft_schemas_office_drawing_x201611_diagram] exported by the module's JavaScript file. */
export declare const org_docx4j_com_microsoft_schemas_office_drawing_x201611_diagram: JsonixMapping<RootElement>;
