// Generated by jsonix-schema-compiler: TypeScript declarations for the Jsonix module [org_docx4j_org_w3_x2003_inkML]. Do not edit.
// Describes the objects Jsonix produces when unmarshalling with this module's mappings.
import type * as Dep_org_docx4j_com_microsoft_schemas_office_powerpoint_x2014_inkAction from './org_docx4j_com_microsoft_schemas_office_powerpoint_x2014_inkAction';
import type * as Dep_org_docx4j_org_w3_x1998_math_mathML from './org_docx4j_org_w3_x1998_math_mathML';

/** Jsonix.XML.QName */
export interface XmlQName { namespaceURI: string; localPart: string; prefix?: string; key?: string; string?: string; }
/** Jsonix.XML.Calendar: the representation of date, time and dateTime values; unset fields are NaN. */
export interface XmlCalendar { year?: number; month?: number; day?: number; hour?: number; minute?: number; second?: number; fractionalSecond?: number; timezone?: number; }
/** The representation of xs:duration values. */
export interface XmlDuration { sign?: number; years?: number; months?: number; days?: number; hours?: number; minutes?: number; seconds?: number; }
/** An element as returned by an unmarshaller or held by an elementRef property. */
export interface TypedNamedValue<T> { name: XmlQName; value: T; }
/** A DOM node, allowed where the mapping permits DOM content (allowDom). */
export type XmlDomNode = any;
/** The value of an anyElement property: a typed element, a DOM node or (if mixed) text. */
export type XmlAnyElement = any;
/** The value of an anyAttribute property. */
export interface XmlAnyAttributes { [attributeName: string]: string; }
/** A Jsonix mapping object as consumed by new Jsonix.Context([...]); R is the union of its global element types. */
export interface JsonixMapping<R = unknown> { readonly __rootElement?: R; readonly [key: string]: unknown; }

export interface ActiveAreaType {
  TYPE_NAME?: 'org_docx4j_org_w3_x2003_inkML.ActiveAreaType';
  readonly PARENT?: InkSourceType;
  size?: string;
  height?: number;
  width?: number;
  units?: string;
}

export interface AffineType {
  TYPE_NAME?: 'org_docx4j_org_w3_x2003_inkML.AffineType';
  readonly PARENT?: MappingType;
  value?: string;
  id?: string;
}

export interface AnnotationType {
  TYPE_NAME?: 'org_docx4j_org_w3_x2003_inkML.AnnotationType';
  readonly PARENT?: BrushType | InkType | TraceGroupType;
  otherAttributes?: XmlAnyAttributes;
  value?: string;
  type?: string;
  encoding?: string;
}

export interface AnnotationXMLType {
  TYPE_NAME?: 'org_docx4j_org_w3_x2003_inkML.AnnotationXMLType';
  readonly PARENT?: BrushType | InkType | TraceGroupType;
  any?: XmlAnyElement[];
  type?: string;
  encoding?: string;
  href?: string;
}

export interface BindType {
  TYPE_NAME?: 'org_docx4j_org_w3_x2003_inkML.BindType';
  readonly PARENT?: MappingType;
  source?: string;
  target?: string;
  column?: string;
  variable?: string;
}

export interface BrushPropertyType {
  TYPE_NAME?: 'org_docx4j_org_w3_x2003_inkML.BrushPropertyType';
  readonly PARENT?: BrushType;
  name: string;
  value: string;
  units?: string;
}

export interface BrushType {
  TYPE_NAME?: 'org_docx4j_org_w3_x2003_inkML.BrushType';
  readonly PARENT?: ContextType | DefinitionsType;
  brushProperty?: BrushPropertyType[];
  annotation?: AnnotationType[];
  annotationXML?: AnnotationXMLType[];
  id?: string;
  brushRef?: string;
}

export interface CTMatrix {
  TYPE_NAME?: 'org_docx4j_org_w3_x2003_inkML.CTMatrix';
  readonly PARENT?: Dep_org_docx4j_com_microsoft_schemas_office_powerpoint_x2014_inkAction.CTActionData;
  value?: string;
  id?: string;
}

export interface CanvasTransformType {
  TYPE_NAME?: 'org_docx4j_org_w3_x2003_inkML.CanvasTransformType';
  readonly PARENT?: ContextType | DefinitionsType;
  content: TypedNamedValue<MappingType>[];
  id?: string;
  invertible?: boolean;
}

export interface CanvasType {
  TYPE_NAME?: 'org_docx4j_org_w3_x2003_inkML.CanvasType';
  readonly PARENT?: ContextType | DefinitionsType;
  traceFormat?: TraceFormatType;
  id?: string;
  traceFormatRef?: string;
}

export interface ChannelPropertiesType {
  TYPE_NAME?: 'org_docx4j_org_w3_x2003_inkML.ChannelPropertiesType';
  readonly PARENT?: InkSourceType;
  channelProperty?: ChannelPropertiesType.ChannelProperty[];
}

export interface ChannelType {
  TYPE_NAME?: 'org_docx4j_org_w3_x2003_inkML.ChannelType';
  readonly PARENT?: IntermittentChannelsType | TraceFormatType;
  mapping?: MappingType;
  id?: string;
  name: string;
  type?: string;
  _default?: string;
  min?: number;
  max?: number;
  orientation?: string;
  respectTo?: string;
  units?: string;
}

export interface ContextType {
  TYPE_NAME?: 'org_docx4j_org_w3_x2003_inkML.ContextType';
  readonly PARENT?: DefinitionsType | InkType;
  canvas?: CanvasType;
  canvasTransform?: CanvasTransformType;
  traceFormat?: TraceFormatType;
  inkSource?: InkSourceType;
  brush?: BrushType;
  timestamp?: TimestampType;
  id?: string;
  contextRef?: string;
  canvasRef?: string;
  canvasTransformRef?: string;
  traceFormatRef?: string;
  inkSourceRef?: string;
  brushRef?: string;
  timestampRef?: string;
}

export interface DefinitionsType {
  TYPE_NAME?: 'org_docx4j_org_w3_x2003_inkML.DefinitionsType';
  readonly PARENT?: Dep_org_docx4j_com_microsoft_schemas_office_powerpoint_x2014_inkAction.CTActions | InkType;
  brushOrCanvasOrCanvasTransform: (BrushType | CanvasType | CanvasTransformType | ContextType | InkSourceType | MappingType | TimestampType | TraceType | TraceFormatType | TraceGroupType | TraceViewType)[];
}

export interface InkSourceType {
  TYPE_NAME?: 'org_docx4j_org_w3_x2003_inkML.InkSourceType';
  readonly PARENT?: ContextType | DefinitionsType;
  traceFormat: TraceFormatType;
  sampleRate?: SampleRateType;
  latency?: LatencyType;
  activeArea?: ActiveAreaType;
  sourceProperty?: SourcePropertyType[];
  channelProperties?: ChannelPropertiesType;
  id: string;
  manufacturer?: string;
  model?: string;
  serialNo?: string;
  specificationRef?: string;
  description?: string;
}

export interface InkType {
  TYPE_NAME?: 'org_docx4j_org_w3_x2003_inkML.InkType';
  definitionsOrContextOrTrace?: (DefinitionsType | ContextType | TraceType | TraceGroupType | TraceViewType | AnnotationType | AnnotationXMLType)[];
  documentID?: string;
}

export interface IntermittentChannelsType {
  TYPE_NAME?: 'org_docx4j_org_w3_x2003_inkML.IntermittentChannelsType';
  readonly PARENT?: TraceFormatType;
  channel: ChannelType[];
}

export interface LatencyType {
  TYPE_NAME?: 'org_docx4j_org_w3_x2003_inkML.LatencyType';
  readonly PARENT?: InkSourceType;
  value: number;
}

export interface MappingType {
  TYPE_NAME?: 'org_docx4j_org_w3_x2003_inkML.MappingType';
  readonly PARENT?: CanvasTransformType | ChannelType | DefinitionsType | MappingType;
  content?: (TypedNamedValue<BindType> | TypedNamedValue<TableType> | TypedNamedValue<AffineType> | TypedNamedValue<Dep_org_docx4j_org_w3_x1998_math_mathML.MathType> | TypedNamedValue<MappingType> | string)[];
  id?: string;
  type?: string;
  mappingRef?: string;
}

export interface SampleRateType {
  TYPE_NAME?: 'org_docx4j_org_w3_x2003_inkML.SampleRateType';
  readonly PARENT?: InkSourceType;
  uniform?: boolean;
  value: number;
}

export interface SourcePropertyType {
  TYPE_NAME?: 'org_docx4j_org_w3_x2003_inkML.SourcePropertyType';
  readonly PARENT?: InkSourceType;
  name: string;
  value: number;
  units?: string;
}

export interface TableType {
  TYPE_NAME?: 'org_docx4j_org_w3_x2003_inkML.TableType';
  readonly PARENT?: MappingType;
  value?: string;
  id?: string;
  apply?: string;
  interpolation?: string;
}

export interface TimestampType {
  TYPE_NAME?: 'org_docx4j_org_w3_x2003_inkML.TimestampType';
  readonly PARENT?: ContextType | DefinitionsType;
  id: string;
  time?: number;
  timestampRef?: string;
  timeString?: XmlCalendar;
  timeOffset?: number;
}

export interface TraceFormatType {
  TYPE_NAME?: 'org_docx4j_org_w3_x2003_inkML.TraceFormatType';
  readonly PARENT?: CanvasType | ContextType | DefinitionsType | InkSourceType;
  channel?: ChannelType[];
  intermittentChannels?: IntermittentChannelsType;
  id?: string;
}

export interface TraceGroupType {
  TYPE_NAME?: 'org_docx4j_org_w3_x2003_inkML.TraceGroupType';
  readonly PARENT?: DefinitionsType | InkType | TraceGroupType;
  traceAndTraceGroupAndTraceView?: (TraceType | TraceGroupType | TraceViewType | AnnotationType | AnnotationXMLType)[];
  id?: string;
  contextRef?: string;
  brushRef?: string;
}

export interface TraceType {
  TYPE_NAME?: 'org_docx4j_org_w3_x2003_inkML.TraceType';
  readonly PARENT?: DefinitionsType | Dep_org_docx4j_com_microsoft_schemas_office_powerpoint_x2014_inkAction.CTActionData | InkType | TraceGroupType;
  value?: string;
  id?: string;
  type?: string;
  continuation?: string;
  priorRef?: string;
  contextRef?: string;
  brushRef?: string;
  duration?: number;
  timeOffset?: number;
}

export interface TraceViewType {
  TYPE_NAME?: 'org_docx4j_org_w3_x2003_inkML.TraceViewType';
  readonly PARENT?: DefinitionsType | Dep_org_docx4j_com_microsoft_schemas_office_powerpoint_x2014_inkAction.CTActionData | InkType | TraceGroupType;
  id?: string;
  traceDataRef?: string;
  from?: string;
  to?: string;
}

export type BooleanStrType = 'F' | 'T';

export type BrushRasterOpType = 'noOperation' | 'copyPen' | 'maskPen';

export type BrushTipType = 'ellipse' | 'rectangle' | 'drop';

export type StandardBrushPropertyNameType = 'width' | 'height' | 'color' | 'transparency' | 'tip' | 'rasterOp' | 'antiAliased' | 'fitToCurve' | 'ignorePressure';

export type StandardChannelNameType = 'X' | 'Y' | 'Z' | 'F' | 'S' | 'B1' | 'B2' | 'B3' | 'B4' | 'OTx' | 'OTy' | 'OA' | 'OE' | 'OR' | 'C' | 'CR' | 'CG' | 'CB' | 'CC' | 'CM' | 'CY' | 'CK' | 'A' | 'W' | 'BW' | 'BH' | 'T';

export type StandardChannelPropertyNameType = 'threshold' | 'resolution' | 'quantization' | 'noise' | 'accuracy' | 'crossCoupling' | 'skew' | 'minBandwidth' | 'peakRate' | 'distortion';

export type DefinitionsElement = TypedNamedValue<DefinitionsType>;

export type InkElement = TypedNamedValue<InkType>;

export type TraceElement = TypedNamedValue<TraceType>;

export type TraceViewElement = TypedNamedValue<TraceViewType>;

/** Any global element of this mapping, i.e. what an unmarshaller returns. */
export type RootElement = DefinitionsElement | InkElement | TraceElement | TraceViewElement;

export namespace ChannelPropertiesType {
  export interface ChannelProperty {
    TYPE_NAME?: 'org_docx4j_org_w3_x2003_inkML.ChannelPropertiesType.ChannelProperty';
    readonly PARENT?: ChannelPropertiesType;
    channel: string;
    name: string;
    value: number;
    units?: string;
  }
}

export namespace MappingType {
  export type AffineElement = TypedNamedValue<AffineType>;

  export type BindElement = TypedNamedValue<BindType>;

  export type MappingElement = TypedNamedValue<MappingType>;

  export type TableElement = TypedNamedValue<TableType>;
}

export namespace CanvasTransformType {
  export type MappingElement = TypedNamedValue<MappingType>;
}

/** The Jsonix mapping [org_docx4j_org_w3_x2003_inkML] exported by the module's JavaScript file. */
export declare const org_docx4j_org_w3_x2003_inkML: JsonixMapping<RootElement>;
