// Generated by jsonix-schema-compiler: TypeScript declarations for the Jsonix module [org_docx4j_dml_chart]. Do not edit.
// Describes the objects Jsonix produces when unmarshalling with this module's mappings.
import type * as Dep_org_docx4j_com_microsoft_schemas_office_drawing_x2012_chart from './org_docx4j_com_microsoft_schemas_office_drawing_x2012_chart';
import type * as Dep_org_docx4j_dml from './org_docx4j_dml';
import type * as Dep_org_docx4j_com_microsoft_schemas_office_drawing_x2014_chart from './org_docx4j_com_microsoft_schemas_office_drawing_x2014_chart';
import type * as Dep_org_docx4j_dml_chartDrawing from './org_docx4j_dml_chartDrawing';

/** Jsonix.XML.QName */
export interface XmlQName { namespaceURI: string; localPart: string; prefix?: string; key?: string; string?: string; }
/** Jsonix.XML.Calendar: the representation of date, time and dateTime values; unset fields are NaN. */
export interface XmlCalendar { year?: number; month?: number; day?: number; hour?: number; minute?: number; second?: number; fractionalSecond?: number; timezone?: number; }
/** The representation of xs:duration values. */
export interface XmlDuration { sign?: number; years?: number; months?: number; days?: number; hours?: number; minutes?: number; seconds?: number; }
/** An element as returned by an unmarshaller or held by an elementRef property. */
export interface TypedNamedValue<T> { name: XmlQName; value: T; }
/** A DOM node, allowed where the mapping permits DOM content (allowDom). */
export type XmlDomNode = any;
/** The value of an anyElement property: a typed element, a DOM node or (if mixed) text. */
export type XmlAnyElement = any;
/** The value of an anyAttribute property. */
export interface XmlAnyAttributes { [attributeName: string]: string; }
/** A Jsonix mapping object as consumed by new Jsonix.Context([...]); R is the union of its global element types. */
export interface JsonixMapping<R = unknown> { readonly __rootElement?: R; readonly [key: string]: unknown; }

export interface CTArea3DChart {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTArea3DChart';
  readonly PARENT?: CTPlotArea;
  grouping?: CTGrouping;
  varyColors?: CTBoolean;
  ser?: CTAreaSer[];
  dLbls?: CTDLbls;
  dropLines?: CTChartLines;
  gapDepth?: CTGapAmount;
  axId: CTUnsignedInt[];
  extLst?: CTExtensionList;
}

export interface CTAreaChart {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTAreaChart';
  readonly PARENT?: CTPlotArea;
  grouping?: CTGrouping;
  varyColors?: CTBoolean;
  ser?: CTAreaSer[];
  dLbls?: CTDLbls;
  dropLines?: CTChartLines;
  axId: CTUnsignedInt[];
  extLst?: CTExtensionList;
}

export interface CTAreaSer {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTAreaSer';
  readonly PARENT?: CTArea3DChart | CTAreaChart | Dep_org_docx4j_com_microsoft_schemas_office_drawing_x2012_chart.CTFilteredAreaSer;
  idx: CTUnsignedInt;
  order: CTUnsignedInt;
  tx?: CTSerTx;
  spPr?: Dep_org_docx4j_dml.CTShapeProperties;
  pictureOptions?: CTPictureOptions;
  dPt?: CTDPt[];
  dLbls?: CTDLbls;
  trendline?: CTTrendline[];
  errBars?: CTErrBars[];
  cat?: CTAxDataSource;
  val?: CTNumDataSource;
  extLst?: CTExtensionList;
}

export interface CTAxDataSource {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTAxDataSource';
  readonly PARENT?: CTAreaSer | CTBarSer | CTBubbleSer | CTLineSer | CTPieSer | CTRadarSer | CTScatterSer | CTSurfaceSer | Dep_org_docx4j_com_microsoft_schemas_office_drawing_x2012_chart.CTFilteredCategoryTitle;
  multiLvlStrRef: CTMultiLvlStrRef;
  numRef: CTNumRef;
  numLit: CTNumData;
  strRef: CTStrRef;
  strLit: CTStrData;
}

export interface CTAxPos {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTAxPos';
  readonly PARENT?: CTCatAx | CTDateAx | CTSerAx | CTValAx;
  val: STAxPos;
}

export interface CTAxisUnit {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTAxisUnit';
  readonly PARENT?: CTDateAx | CTValAx;
  val: number;
}

export interface CTBandFmt {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTBandFmt';
  readonly PARENT?: CTBandFmts;
  idx: CTUnsignedInt;
  spPr?: Dep_org_docx4j_dml.CTShapeProperties;
}

export interface CTBandFmts {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTBandFmts';
  readonly PARENT?: CTSurface3DChart | CTSurfaceChart;
  bandFmt?: CTBandFmt[];
}

export interface CTBar3DChart {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTBar3DChart';
  readonly PARENT?: CTPlotArea;
  barDir: CTBarDir;
  grouping?: CTBarGrouping;
  varyColors?: CTBoolean;
  ser?: CTBarSer[];
  dLbls?: CTDLbls;
  gapWidth?: CTGapAmount;
  gapDepth?: CTGapAmount;
  shape?: CTShape;
  axId: CTUnsignedInt[];
  extLst?: CTExtensionList;
}

export interface CTBarChart {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTBarChart';
  readonly PARENT?: CTPlotArea;
  barDir: CTBarDir;
  grouping?: CTBarGrouping;
  varyColors?: CTBoolean;
  ser?: CTBarSer[];
  dLbls?: CTDLbls;
  gapWidth?: CTGapAmount;
  overlap?: CTOverlap;
  serLines?: CTChartLines[];
  axId: CTUnsignedInt[];
  extLst?: CTExtensionList;
}

export interface CTBarDir {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTBarDir';
  readonly PARENT?: CTBar3DChart | CTBarChart;
  val?: STBarDir;
}

export interface CTBarGrouping {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTBarGrouping';
  readonly PARENT?: CTBar3DChart | CTBarChart;
  val?: STBarGrouping;
}

export interface CTBarSer {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTBarSer';
  readonly PARENT?: CTBar3DChart | CTBarChart | Dep_org_docx4j_com_microsoft_schemas_office_drawing_x2012_chart.CTFilteredBarSer;
  idx: CTUnsignedInt;
  order: CTUnsignedInt;
  tx?: CTSerTx;
  spPr?: Dep_org_docx4j_dml.CTShapeProperties;
  invertIfNegative?: CTBoolean;
  pictureOptions?: CTPictureOptions;
  dPt?: CTDPt[];
  dLbls?: CTDLbls;
  trendline?: CTTrendline[];
  errBars?: CTErrBars;
  cat?: CTAxDataSource;
  val?: CTNumDataSource;
  shape?: CTShape;
  extLst?: CTExtensionList;
}

export interface CTBoolean {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTBoolean';
  readonly PARENT?: CTArea3DChart | CTAreaChart | CTBar3DChart | CTBarChart | CTBarSer | CTBubbleChart | CTBubbleSer | CTCatAx | CTChart | CTChartSpace | CTDLbl | CTDLbls | CTDPt | CTDTable | CTDateAx | CTDoughnutChart | CTErrBars | CTExternalData | CTLegend | CTLegendEntry | CTLine3DChart | CTLineChart | CTLineSer | CTOfPieChart | CTPictureOptions | CTPie3DChart | CTPieChart | CTProtection | CTRadarChart | CTScatterChart | CTScatterSer | CTSerAx | CTSurface3DChart | CTSurfaceChart | CTTitle | CTTrendline | CTValAx | CTView3D | Dep_org_docx4j_com_microsoft_schemas_office_drawing_x2012_chart.CTCategoryFilterException | Dep_org_docx4j_com_microsoft_schemas_office_drawing_x2014_chart.CTCategoryFilterException;
  val?: boolean;
}

export interface CTBubbleChart {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTBubbleChart';
  readonly PARENT?: CTPlotArea;
  varyColors?: CTBoolean;
  ser?: CTBubbleSer[];
  dLbls?: CTDLbls;
  bubble3D?: CTBoolean;
  bubbleScale?: CTBubbleScale;
  showNegBubbles?: CTBoolean;
  sizeRepresents?: CTSizeRepresents;
  axId: CTUnsignedInt[];
  extLst?: CTExtensionList;
}

export interface CTBubbleScale {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTBubbleScale';
  readonly PARENT?: CTBubbleChart;
  val?: number;
}

export interface CTBubbleSer {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTBubbleSer';
  readonly PARENT?: CTBubbleChart | Dep_org_docx4j_com_microsoft_schemas_office_drawing_x2012_chart.CTFilteredBubbleSer;
  idx: CTUnsignedInt;
  order: CTUnsignedInt;
  tx?: CTSerTx;
  spPr?: Dep_org_docx4j_dml.CTShapeProperties;
  invertIfNegative?: CTBoolean;
  dPt?: CTDPt[];
  dLbls?: CTDLbls;
  trendline?: CTTrendline[];
  errBars?: CTErrBars[];
  xVal?: CTAxDataSource;
  yVal?: CTNumDataSource;
  bubbleSize?: CTNumDataSource;
  bubble3D?: CTBoolean;
  extLst?: CTExtensionList;
}

export interface CTBuiltInUnit {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTBuiltInUnit';
  readonly PARENT?: CTDispUnits;
  val?: STBuiltInUnit;
}

export interface CTCatAx {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTCatAx';
  readonly PARENT?: CTPlotArea;
  axId: CTUnsignedInt;
  scaling: CTScaling;
  delete?: CTBoolean;
  axPos: CTAxPos;
  majorGridlines?: CTChartLines;
  minorGridlines?: CTChartLines;
  title?: CTTitle;
  numFmt?: CTNumFmt;
  majorTickMark?: CTTickMark;
  minorTickMark?: CTTickMark;
  tickLblPos?: CTTickLblPos;
  spPr?: Dep_org_docx4j_dml.CTShapeProperties;
  txPr?: Dep_org_docx4j_dml.CTTextBody;
  crossAx: CTUnsignedInt;
  crosses: CTCrosses;
  crossesAt: CTDouble;
  auto?: CTBoolean;
  lblAlgn?: CTLblAlgn;
  lblOffset?: CTLblOffset;
  tickLblSkip?: CTSkip;
  tickMarkSkip?: CTSkip;
  noMultiLvlLbl?: CTBoolean;
  extLst?: CTExtensionList;
}

export interface CTChart {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTChart';
  readonly PARENT?: CTChartSpace;
  title?: CTTitle;
  autoTitleDeleted?: CTBoolean;
  pivotFmts?: CTPivotFmts;
  view3D?: CTView3D;
  floor?: CTSurface;
  sideWall?: CTSurface;
  backWall?: CTSurface;
  plotArea: CTPlotArea;
  legend?: CTLegend;
  plotVisOnly?: CTBoolean;
  dispBlanksAs?: CTDispBlanksAs;
  showDLblsOverMax?: CTBoolean;
  extLst?: CTExtensionList;
}

export interface CTChartLines {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTChartLines';
  readonly PARENT?: CTArea3DChart | CTAreaChart | CTBarChart | CTCatAx | CTDLbls | CTDateAx | CTLine3DChart | CTLineChart | CTOfPieChart | CTSerAx | CTStockChart | CTValAx;
  spPr?: Dep_org_docx4j_dml.CTShapeProperties;
}

export interface CTChartSpace {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTChartSpace';
  date1904?: CTBoolean;
  lang?: CTTextLanguageID;
  roundedCorners?: CTBoolean;
  style?: CTStyle;
  clrMapOvr?: Dep_org_docx4j_dml.CTColorMapping;
  pivotSource?: CTPivotSource;
  protection?: CTProtection;
  chart: CTChart;
  spPr?: Dep_org_docx4j_dml.CTShapeProperties;
  txPr?: Dep_org_docx4j_dml.CTTextBody;
  externalData?: CTExternalData;
  printSettings?: CTPrintSettings;
  userShapes?: CTRelId;
  extLst?: CTExtensionList;
}

export interface CTCrossBetween {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTCrossBetween';
  readonly PARENT?: CTValAx;
  val: STCrossBetween;
}

export interface CTCrosses {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTCrosses';
  readonly PARENT?: CTCatAx | CTDateAx | CTSerAx | CTValAx;
  val: STCrosses;
}

export interface CTCustSplit {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTCustSplit';
  readonly PARENT?: CTOfPieChart;
  secondPiePt?: CTUnsignedInt[];
}

export interface CTDLbl {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTDLbl';
  readonly PARENT?: CTDLbls | CTPivotFmt | Dep_org_docx4j_com_microsoft_schemas_office_drawing_x2012_chart.CTCategoryFilterException | Dep_org_docx4j_com_microsoft_schemas_office_drawing_x2014_chart.CTCategoryFilterException;
  idx: CTUnsignedInt;
  delete: CTBoolean;
  layout?: CTLayout;
  tx?: CTTx;
  numFmt?: CTNumFmt;
  spPr?: Dep_org_docx4j_dml.CTShapeProperties;
  txPr?: Dep_org_docx4j_dml.CTTextBody;
  dLblPos?: CTDLblPos;
  showLegendKey?: CTBoolean;
  showVal?: CTBoolean;
  showCatName?: CTBoolean;
  showSerName?: CTBoolean;
  showPercent?: CTBoolean;
  showBubbleSize?: CTBoolean;
  separator?: string;
  extLst?: CTExtensionList;
}

export interface CTDLblPos {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTDLblPos';
  readonly PARENT?: CTDLbl | CTDLbls;
  val: STDLblPos;
}

export interface CTDLbls {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTDLbls';
  readonly PARENT?: CTArea3DChart | CTAreaChart | CTAreaSer | CTBar3DChart | CTBarChart | CTBarSer | CTBubbleChart | CTBubbleSer | CTDoughnutChart | CTLine3DChart | CTLineChart | CTLineSer | CTOfPieChart | CTPie3DChart | CTPieChart | CTPieSer | CTRadarChart | CTRadarSer | CTScatterChart | CTScatterSer | CTStockChart;
  dLbl?: CTDLbl[];
  delete: CTBoolean;
  numFmt?: CTNumFmt;
  spPr?: Dep_org_docx4j_dml.CTShapeProperties;
  txPr?: Dep_org_docx4j_dml.CTTextBody;
  dLblPos?: CTDLblPos;
  showLegendKey?: CTBoolean;
  showVal?: CTBoolean;
  showCatName?: CTBoolean;
  showSerName?: CTBoolean;
  showPercent?: CTBoolean;
  showBubbleSize?: CTBoolean;
  separator?: string;
  showLeaderLines?: CTBoolean;
  leaderLines?: CTChartLines;
  extLst?: CTExtensionList;
}

export interface CTDPt {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTDPt';
  readonly PARENT?: CTAreaSer | CTBarSer | CTBubbleSer | CTLineSer | CTPieSer | CTRadarSer | CTScatterSer;
  idx: CTUnsignedInt;
  invertIfNegative?: CTBoolean;
  marker?: CTMarker;
  bubble3D?: CTBoolean;
  explosion?: CTUnsignedInt;
  spPr?: Dep_org_docx4j_dml.CTShapeProperties;
  pictureOptions?: CTPictureOptions;
  extLst?: CTExtensionList;
}

export interface CTDTable {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTDTable';
  readonly PARENT?: CTPlotArea;
  showHorzBorder?: CTBoolean;
  showVertBorder?: CTBoolean;
  showOutline?: CTBoolean;
  showKeys?: CTBoolean;
  spPr?: Dep_org_docx4j_dml.CTShapeProperties;
  txPr?: Dep_org_docx4j_dml.CTTextBody;
  extLst?: CTExtensionList;
}

export interface CTDateAx {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTDateAx';
  readonly PARENT?: CTPlotArea;
  axId: CTUnsignedInt;
  scaling: CTScaling;
  delete?: CTBoolean;
  axPos: CTAxPos;
  majorGridlines?: CTChartLines;
  minorGridlines?: CTChartLines;
  title?: CTTitle;
  numFmt?: CTNumFmt;
  majorTickMark?: CTTickMark;
  minorTickMark?: CTTickMark;
  tickLblPos?: CTTickLblPos;
  spPr?: Dep_org_docx4j_dml.CTShapeProperties;
  txPr?: Dep_org_docx4j_dml.CTTextBody;
  crossAx: CTUnsignedInt;
  crosses: CTCrosses;
  crossesAt: CTDouble;
  auto?: CTBoolean;
  lblOffset?: CTLblOffset;
  baseTimeUnit?: CTTimeUnit;
  majorUnit?: CTAxisUnit;
  majorTimeUnit?: CTTimeUnit;
  minorUnit?: CTAxisUnit;
  minorTimeUnit?: CTTimeUnit;
  extLst?: CTExtensionList;
}

export interface CTDepthPercent {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTDepthPercent';
  readonly PARENT?: CTView3D;
  val?: number;
}

export interface CTDispBlanksAs {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTDispBlanksAs';
  readonly PARENT?: CTChart;
  val?: STDispBlanksAs;
}

export interface CTDispUnits {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTDispUnits';
  readonly PARENT?: CTValAx;
  custUnit: CTDouble;
  builtInUnit: CTBuiltInUnit;
  dispUnitsLbl?: CTDispUnitsLbl;
  extLst?: CTExtensionList;
}

export interface CTDispUnitsLbl {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTDispUnitsLbl';
  readonly PARENT?: CTDispUnits;
  layout?: CTLayout;
  tx?: CTTx;
  spPr?: Dep_org_docx4j_dml.CTShapeProperties;
  txPr?: Dep_org_docx4j_dml.CTTextBody;
}

export interface CTDouble {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTDouble';
  readonly PARENT?: CTCatAx | CTDateAx | CTDispUnits | CTErrBars | CTManualLayout | CTOfPieChart | CTScaling | CTSerAx | CTTrendline | CTValAx;
  val: number;
}

export interface CTDoughnutChart {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTDoughnutChart';
  readonly PARENT?: CTPlotArea;
  varyColors?: CTBoolean;
  ser?: CTPieSer[];
  dLbls?: CTDLbls;
  firstSliceAng?: CTFirstSliceAng;
  holeSize?: CTHoleSize;
  extLst?: CTExtensionList;
}

export interface CTErrBarType {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTErrBarType';
  readonly PARENT?: CTErrBars;
  val?: STErrBarType;
}

export interface CTErrBars {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTErrBars';
  readonly PARENT?: CTAreaSer | CTBarSer | CTBubbleSer | CTLineSer | CTScatterSer;
  errDir?: CTErrDir;
  errBarType: CTErrBarType;
  errValType: CTErrValType;
  noEndCap?: CTBoolean;
  plus?: CTNumDataSource;
  minus?: CTNumDataSource;
  val?: CTDouble;
  spPr?: Dep_org_docx4j_dml.CTShapeProperties;
  extLst?: CTExtensionList;
}

export interface CTErrDir {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTErrDir';
  readonly PARENT?: CTErrBars;
  val: STErrDir;
}

export interface CTErrValType {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTErrValType';
  readonly PARENT?: CTErrBars;
  val?: STErrValType;
}

export interface CTExtension {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTExtension';
  readonly PARENT?: CTExtensionList;
  any?: XmlAnyElement[];
  uri?: string;
}

export interface CTExtensionList {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTExtensionList';
  readonly PARENT?: CTArea3DChart | CTAreaChart | CTAreaSer | CTBar3DChart | CTBarChart | CTBarSer | CTBubbleChart | CTBubbleSer | CTCatAx | CTChart | CTChartSpace | CTDLbl | CTDLbls | CTDPt | CTDTable | CTDateAx | CTDispUnits | CTDoughnutChart | CTErrBars | CTLayout | CTLegend | CTLegendEntry | CTLine3DChart | CTLineChart | CTLineSer | CTManualLayout | CTMarker | CTMultiLvlStrData | CTMultiLvlStrRef | CTNumData | CTNumRef | CTOfPieChart | CTPie3DChart | CTPieChart | CTPieSer | CTPivotFmt | CTPivotSource | CTPlotArea | CTRadarChart | CTRadarSer | CTScaling | CTScatterChart | CTScatterSer | CTSerAx | CTStockChart | CTStrData | CTStrRef | CTSurface | CTSurface3DChart | CTSurfaceChart | CTSurfaceSer | CTTitle | CTTrendline | CTTrendlineLbl | CTUpDownBars | CTValAx | CTView3D;
  ext?: CTExtension[];
}

export interface CTExternalData {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTExternalData';
  readonly PARENT?: CTChartSpace;
  autoUpdate?: CTBoolean;
  id: string;
}

export interface CTFirstSliceAng {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTFirstSliceAng';
  readonly PARENT?: CTDoughnutChart | CTPieChart;
  val?: number;
}

export interface CTGapAmount {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTGapAmount';
  readonly PARENT?: CTArea3DChart | CTBar3DChart | CTBarChart | CTLine3DChart | CTOfPieChart | CTUpDownBars;
  val?: number;
}

export interface CTGrouping {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTGrouping';
  readonly PARENT?: CTArea3DChart | CTAreaChart | CTLine3DChart | CTLineChart;
  val?: STGrouping;
}

export interface CTHPercent {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTHPercent';
  readonly PARENT?: CTView3D;
  val?: number;
}

export interface CTHeaderFooter {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTHeaderFooter';
  readonly PARENT?: CTPrintSettings;
  oddHeader?: string;
  oddFooter?: string;
  evenHeader?: string;
  evenFooter?: string;
  firstHeader?: string;
  firstFooter?: string;
  alignWithMargins?: boolean;
  differentOddEven?: boolean;
  differentFirst?: boolean;
}

export interface CTHoleSize {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTHoleSize';
  readonly PARENT?: CTDoughnutChart;
  val?: number;
}

export interface CTLayout {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTLayout';
  readonly PARENT?: CTDLbl | CTDispUnitsLbl | CTLegend | CTPlotArea | CTTitle | CTTrendlineLbl;
  manualLayout?: CTManualLayout;
  extLst?: CTExtensionList;
}

export interface CTLayoutMode {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTLayoutMode';
  readonly PARENT?: CTManualLayout;
  val?: STLayoutMode;
}

export interface CTLayoutTarget {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTLayoutTarget';
  readonly PARENT?: CTManualLayout;
  val?: STLayoutTarget;
}

export interface CTLblAlgn {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTLblAlgn';
  readonly PARENT?: CTCatAx;
  val: STLblAlgn;
}

export interface CTLblOffset {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTLblOffset';
  readonly PARENT?: CTCatAx | CTDateAx;
  val?: number;
}

export interface CTLegend {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTLegend';
  readonly PARENT?: CTChart;
  legendPos?: CTLegendPos;
  legendEntry?: CTLegendEntry[];
  layout?: CTLayout;
  overlay?: CTBoolean;
  spPr?: Dep_org_docx4j_dml.CTShapeProperties;
  txPr?: Dep_org_docx4j_dml.CTTextBody;
  extLst?: CTExtensionList;
}

export interface CTLegendEntry {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTLegendEntry';
  readonly PARENT?: CTLegend;
  idx: CTUnsignedInt;
  delete: CTBoolean;
  txPr?: Dep_org_docx4j_dml.CTTextBody;
  extLst?: CTExtensionList;
}

export interface CTLegendPos {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTLegendPos';
  readonly PARENT?: CTLegend;
  val?: STLegendPos;
}

export interface CTLine3DChart {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTLine3DChart';
  readonly PARENT?: CTPlotArea;
  grouping: CTGrouping;
  varyColors?: CTBoolean;
  ser?: CTLineSer[];
  dLbls?: CTDLbls;
  dropLines?: CTChartLines;
  gapDepth?: CTGapAmount;
  axId: CTUnsignedInt[];
  extLst?: CTExtensionList;
}

export interface CTLineChart {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTLineChart';
  readonly PARENT?: CTPlotArea;
  grouping: CTGrouping;
  varyColors?: CTBoolean;
  ser?: CTLineSer[];
  dLbls?: CTDLbls;
  dropLines?: CTChartLines;
  hiLowLines?: CTChartLines;
  upDownBars?: CTUpDownBars;
  marker?: CTBoolean;
  smooth?: CTBoolean;
  axId: CTUnsignedInt[];
  extLst?: CTExtensionList;
}

export interface CTLineSer {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTLineSer';
  readonly PARENT?: CTLine3DChart | CTLineChart | CTStockChart | Dep_org_docx4j_com_microsoft_schemas_office_drawing_x2012_chart.CTFilteredLineSer;
  idx: CTUnsignedInt;
  order: CTUnsignedInt;
  tx?: CTSerTx;
  spPr?: Dep_org_docx4j_dml.CTShapeProperties;
  marker?: CTMarker;
  dPt?: CTDPt[];
  dLbls?: CTDLbls;
  trendline?: CTTrendline[];
  errBars?: CTErrBars;
  cat?: CTAxDataSource;
  val?: CTNumDataSource;
  smooth?: CTBoolean;
  extLst?: CTExtensionList;
}

export interface CTLogBase {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTLogBase';
  readonly PARENT?: CTScaling;
  val: number;
}

export interface CTLvl {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTLvl';
  readonly PARENT?: CTMultiLvlStrData;
  pt?: CTStrVal[];
}

export interface CTManualLayout {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTManualLayout';
  readonly PARENT?: CTLayout;
  layoutTarget?: CTLayoutTarget;
  xMode?: CTLayoutMode;
  yMode?: CTLayoutMode;
  wMode?: CTLayoutMode;
  hMode?: CTLayoutMode;
  x?: CTDouble;
  y?: CTDouble;
  w?: CTDouble;
  h?: CTDouble;
  extLst?: CTExtensionList;
}

export interface CTMarker {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTMarker';
  readonly PARENT?: CTDPt | CTLineSer | CTPivotFmt | CTRadarSer | CTScatterSer | Dep_org_docx4j_com_microsoft_schemas_office_drawing_x2012_chart.CTCategoryFilterException | Dep_org_docx4j_com_microsoft_schemas_office_drawing_x2014_chart.CTCategoryFilterException;
  symbol?: CTMarkerStyle;
  size?: CTMarkerSize;
  spPr?: Dep_org_docx4j_dml.CTShapeProperties;
  extLst?: CTExtensionList;
}

export interface CTMarkerSize {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTMarkerSize';
  readonly PARENT?: CTMarker;
  val?: number;
}

export interface CTMarkerStyle {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTMarkerStyle';
  readonly PARENT?: CTMarker;
  val: STMarkerStyle;
}

export interface CTMultiLvlStrData {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTMultiLvlStrData';
  readonly PARENT?: CTMultiLvlStrRef | Dep_org_docx4j_com_microsoft_schemas_office_drawing_x2014_chart.CTMultiLvlStrFilteredLiteralCache;
  ptCount?: CTUnsignedInt;
  lvl?: CTLvl[];
  extLst?: CTExtensionList;
}

export interface CTMultiLvlStrRef {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTMultiLvlStrRef';
  readonly PARENT?: CTAxDataSource;
  f: string;
  multiLvlStrCache?: CTMultiLvlStrData;
  extLst?: CTExtensionList;
}

export interface CTNumData {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTNumData';
  readonly PARENT?: CTAxDataSource | CTNumDataSource | CTNumRef | Dep_org_docx4j_com_microsoft_schemas_office_drawing_x2014_chart.CTNumFilteredLiteralCache;
  formatCode?: string;
  ptCount?: CTUnsignedInt;
  pt?: CTNumVal[];
  extLst?: CTExtensionList;
}

export interface CTNumDataSource {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTNumDataSource';
  readonly PARENT?: CTAreaSer | CTBarSer | CTBubbleSer | CTErrBars | CTLineSer | CTPieSer | CTRadarSer | CTScatterSer | CTSurfaceSer;
  numRef: CTNumRef;
  numLit: CTNumData;
}

export interface CTNumFmt {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTNumFmt';
  readonly PARENT?: CTCatAx | CTDLbl | CTDLbls | CTDateAx | CTSerAx | CTTrendlineLbl | CTValAx;
  formatCode: string;
  sourceLinked?: boolean;
}

export interface CTNumRef {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTNumRef';
  readonly PARENT?: CTAxDataSource | CTNumDataSource;
  f: string;
  numCache?: CTNumData;
  extLst?: CTExtensionList;
}

export interface CTNumVal {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTNumVal';
  readonly PARENT?: CTNumData;
  v: string;
  idx: number;
  formatCode?: string;
}

export interface CTOfPieChart {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTOfPieChart';
  readonly PARENT?: CTPlotArea;
  ofPieType: CTOfPieType;
  varyColors?: CTBoolean;
  ser?: CTPieSer[];
  dLbls?: CTDLbls;
  gapWidth?: CTGapAmount;
  splitType?: CTSplitType;
  splitPos?: CTDouble;
  custSplit?: CTCustSplit;
  secondPieSize?: CTSecondPieSize;
  serLines?: CTChartLines[];
  extLst?: CTExtensionList;
}

export interface CTOfPieType {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTOfPieType';
  readonly PARENT?: CTOfPieChart;
  val?: STOfPieType;
}

export interface CTOrder {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTOrder';
  readonly PARENT?: CTTrendline;
  val?: number;
}

export interface CTOrientation {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTOrientation';
  readonly PARENT?: CTScaling;
  val?: STOrientation;
}

export interface CTOverlap {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTOverlap';
  readonly PARENT?: CTBarChart;
  val?: number;
}

export interface CTPageMargins {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTPageMargins';
  readonly PARENT?: CTPrintSettings;
  l: number;
  r: number;
  t: number;
  b: number;
  header: number;
  footer: number;
}

export interface CTPageSetup {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTPageSetup';
  readonly PARENT?: CTPrintSettings;
  paperSize?: number;
  firstPageNumber?: number;
  orientation?: STPageSetupOrientation;
  blackAndWhite?: boolean;
  draft?: boolean;
  useFirstPageNumber?: boolean;
  horizontalDpi?: number;
  verticalDpi?: number;
  copies?: number;
}

export interface CTPeriod {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTPeriod';
  readonly PARENT?: CTTrendline;
  val?: number;
}

export interface CTPerspective {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTPerspective';
  readonly PARENT?: CTView3D;
  val?: number;
}

export interface CTPictureFormat {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTPictureFormat';
  readonly PARENT?: CTPictureOptions;
  val: STPictureFormat;
}

export interface CTPictureOptions {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTPictureOptions';
  readonly PARENT?: CTAreaSer | CTBarSer | CTDPt | CTSurface;
  applyToFront?: CTBoolean;
  applyToSides?: CTBoolean;
  applyToEnd?: CTBoolean;
  pictureFormat?: CTPictureFormat;
  pictureStackUnit?: CTPictureStackUnit;
}

export interface CTPictureStackUnit {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTPictureStackUnit';
  readonly PARENT?: CTPictureOptions;
  val: number;
}

export interface CTPie3DChart {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTPie3DChart';
  readonly PARENT?: CTPlotArea;
  varyColors?: CTBoolean;
  ser?: CTPieSer[];
  dLbls?: CTDLbls;
  extLst?: CTExtensionList;
}

export interface CTPieChart {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTPieChart';
  readonly PARENT?: CTPlotArea;
  varyColors?: CTBoolean;
  ser?: CTPieSer[];
  dLbls?: CTDLbls;
  firstSliceAng?: CTFirstSliceAng;
  extLst?: CTExtensionList;
}

export interface CTPieSer {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTPieSer';
  readonly PARENT?: CTDoughnutChart | CTOfPieChart | CTPie3DChart | CTPieChart | Dep_org_docx4j_com_microsoft_schemas_office_drawing_x2012_chart.CTFilteredPieSer;
  idx: CTUnsignedInt;
  order: CTUnsignedInt;
  tx?: CTSerTx;
  spPr?: Dep_org_docx4j_dml.CTShapeProperties;
  explosion?: CTUnsignedInt;
  dPt?: CTDPt[];
  dLbls?: CTDLbls;
  cat?: CTAxDataSource;
  val?: CTNumDataSource;
  extLst?: CTExtensionList;
}

export interface CTPivotFmt {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTPivotFmt';
  readonly PARENT?: CTPivotFmts;
  idx: CTUnsignedInt;
  spPr?: Dep_org_docx4j_dml.CTShapeProperties;
  txPr?: Dep_org_docx4j_dml.CTTextBody;
  marker?: CTMarker;
  dLbl?: CTDLbl;
  extLst?: CTExtensionList;
}

export interface CTPivotFmts {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTPivotFmts';
  readonly PARENT?: CTChart;
  pivotFmt?: CTPivotFmt[];
}

export interface CTPivotSource {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTPivotSource';
  readonly PARENT?: CTChartSpace;
  name: string;
  fmtId: CTUnsignedInt;
  extLst?: CTExtensionList[];
}

export interface CTPlotArea {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTPlotArea';
  readonly PARENT?: CTChart;
  layout?: CTLayout;
  areaChartOrArea3DChartOrLineChart: (CTAreaChart | CTArea3DChart | CTLineChart | CTLine3DChart | CTStockChart | CTRadarChart | CTScatterChart | CTPieChart | CTPie3DChart | CTDoughnutChart | CTBarChart | CTBar3DChart | CTOfPieChart | CTSurfaceChart | CTSurface3DChart | CTBubbleChart)[];
  valAxOrCatAxOrDateAx?: (CTValAx | CTCatAx | CTDateAx | CTSerAx)[];
  dTable?: CTDTable;
  spPr?: Dep_org_docx4j_dml.CTShapeProperties;
  extLst?: CTExtensionList;
}

export interface CTPrintSettings {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTPrintSettings';
  readonly PARENT?: CTChartSpace;
  headerFooter?: CTHeaderFooter;
  pageMargins?: CTPageMargins;
  pageSetup?: CTPageSetup;
  legacyDrawingHF?: CTRelId;
}

export interface CTProtection {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTProtection';
  readonly PARENT?: CTChartSpace;
  chartObject?: CTBoolean;
  data?: CTBoolean;
  formatting?: CTBoolean;
  selection?: CTBoolean;
  userInterface?: CTBoolean;
}

export interface CTRadarChart {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTRadarChart';
  readonly PARENT?: CTPlotArea;
  radarStyle: CTRadarStyle;
  varyColors?: CTBoolean;
  ser?: CTRadarSer[];
  dLbls?: CTDLbls;
  axId: CTUnsignedInt[];
  extLst?: CTExtensionList;
}

export interface CTRadarSer {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTRadarSer';
  readonly PARENT?: CTRadarChart | Dep_org_docx4j_com_microsoft_schemas_office_drawing_x2012_chart.CTFilteredRadarSer;
  idx: CTUnsignedInt;
  order: CTUnsignedInt;
  tx?: CTSerTx;
  spPr?: Dep_org_docx4j_dml.CTShapeProperties;
  marker?: CTMarker;
  dPt?: CTDPt[];
  dLbls?: CTDLbls;
  cat?: CTAxDataSource;
  val?: CTNumDataSource;
  extLst?: CTExtensionList;
}

export interface CTRadarStyle {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTRadarStyle';
  readonly PARENT?: CTRadarChart;
  val?: STRadarStyle;
}

export interface CTRelId {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTRelId';
  readonly PARENT?: CTChartSpace | CTPrintSettings;
  id: string;
}

export interface CTRotX {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTRotX';
  readonly PARENT?: CTView3D;
  val?: number;
}

export interface CTRotY {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTRotY';
  readonly PARENT?: CTView3D;
  val?: number;
}

export interface CTScaling {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTScaling';
  readonly PARENT?: CTCatAx | CTDateAx | CTSerAx | CTValAx;
  logBase?: CTLogBase;
  orientation?: CTOrientation;
  max?: CTDouble;
  min?: CTDouble;
  extLst?: CTExtensionList;
}

export interface CTScatterChart {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTScatterChart';
  readonly PARENT?: CTPlotArea;
  scatterStyle: CTScatterStyle;
  varyColors?: CTBoolean;
  ser?: CTScatterSer[];
  dLbls?: CTDLbls;
  axId: CTUnsignedInt[];
  extLst?: CTExtensionList;
}

export interface CTScatterSer {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTScatterSer';
  readonly PARENT?: CTScatterChart | Dep_org_docx4j_com_microsoft_schemas_office_drawing_x2012_chart.CTFilteredScatterSer;
  idx: CTUnsignedInt;
  order: CTUnsignedInt;
  tx?: CTSerTx;
  spPr?: Dep_org_docx4j_dml.CTShapeProperties;
  marker?: CTMarker;
  dPt?: CTDPt[];
  dLbls?: CTDLbls;
  trendline?: CTTrendline[];
  errBars?: CTErrBars[];
  xVal?: CTAxDataSource;
  yVal?: CTNumDataSource;
  smooth?: CTBoolean;
  extLst?: CTExtensionList;
}

export interface CTScatterStyle {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTScatterStyle';
  readonly PARENT?: CTScatterChart;
  val?: STScatterStyle;
}

export interface CTSecondPieSize {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTSecondPieSize';
  readonly PARENT?: CTOfPieChart;
  val?: number;
}

export interface CTSerAx {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTSerAx';
  readonly PARENT?: CTPlotArea;
  axId: CTUnsignedInt;
  scaling: CTScaling;
  delete?: CTBoolean;
  axPos: CTAxPos;
  majorGridlines?: CTChartLines;
  minorGridlines?: CTChartLines;
  title?: CTTitle;
  numFmt?: CTNumFmt;
  majorTickMark?: CTTickMark;
  minorTickMark?: CTTickMark;
  tickLblPos?: CTTickLblPos;
  spPr?: Dep_org_docx4j_dml.CTShapeProperties;
  txPr?: Dep_org_docx4j_dml.CTTextBody;
  crossAx: CTUnsignedInt;
  crosses: CTCrosses;
  crossesAt: CTDouble;
  tickLblSkip?: CTSkip;
  tickMarkSkip?: CTSkip;
  extLst?: CTExtensionList;
}

export interface CTSerTx {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTSerTx';
  readonly PARENT?: CTAreaSer | CTBarSer | CTBubbleSer | CTLineSer | CTPieSer | CTRadarSer | CTScatterSer | CTSurfaceSer;
  strRef: CTStrRef;
  v: string;
}

export interface CTShape {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTShape';
  readonly PARENT?: CTBar3DChart | CTBarSer;
  val?: STShape;
}

export interface CTSizeRepresents {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTSizeRepresents';
  readonly PARENT?: CTBubbleChart;
  val?: STSizeRepresents;
}

export interface CTSkip {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTSkip';
  readonly PARENT?: CTCatAx | CTSerAx;
  val: number;
}

export interface CTSplitType {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTSplitType';
  readonly PARENT?: CTOfPieChart;
  val?: STSplitType;
}

export interface CTStockChart {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTStockChart';
  readonly PARENT?: CTPlotArea;
  ser: CTLineSer[];
  dLbls?: CTDLbls;
  dropLines?: CTChartLines;
  hiLowLines?: CTChartLines;
  upDownBars?: CTUpDownBars;
  axId: CTUnsignedInt[];
  extLst?: CTExtensionList;
}

export interface CTStrData {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTStrData';
  readonly PARENT?: CTAxDataSource | CTStrRef | Dep_org_docx4j_com_microsoft_schemas_office_drawing_x2012_chart.CTDataLabelFieldTableEntry | Dep_org_docx4j_com_microsoft_schemas_office_drawing_x2012_chart.CTSeriesDataLabelsRange | Dep_org_docx4j_com_microsoft_schemas_office_drawing_x2014_chart.CTStrFilteredLiteralCache;
  ptCount?: CTUnsignedInt;
  pt?: CTStrVal[];
  extLst?: CTExtensionList;
}

export interface CTStrRef {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTStrRef';
  readonly PARENT?: CTAxDataSource | CTSerTx | CTTx;
  f: string;
  strCache?: CTStrData;
  extLst?: CTExtensionList;
}

export interface CTStrVal {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTStrVal';
  readonly PARENT?: CTLvl | CTStrData;
  v: string;
  idx: number;
}

export interface CTStyle {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTStyle';
  readonly PARENT?: CTChartSpace;
  val: number;
}

export interface CTSurface {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTSurface';
  readonly PARENT?: CTChart;
  thickness?: CTUnsignedInt;
  spPr?: Dep_org_docx4j_dml.CTShapeProperties;
  pictureOptions?: CTPictureOptions;
  extLst?: CTExtensionList;
}

export interface CTSurface3DChart {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTSurface3DChart';
  readonly PARENT?: CTPlotArea;
  wireframe?: CTBoolean;
  ser?: CTSurfaceSer[];
  bandFmts?: CTBandFmts;
  axId: CTUnsignedInt[];
  extLst?: CTExtensionList;
}

export interface CTSurfaceChart {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTSurfaceChart';
  readonly PARENT?: CTPlotArea;
  wireframe?: CTBoolean;
  ser?: CTSurfaceSer[];
  bandFmts?: CTBandFmts;
  axId: CTUnsignedInt[];
  extLst?: CTExtensionList;
}

export interface CTSurfaceSer {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTSurfaceSer';
  readonly PARENT?: CTSurface3DChart | CTSurfaceChart | Dep_org_docx4j_com_microsoft_schemas_office_drawing_x2012_chart.CTFilteredSurfaceSer;
  idx: CTUnsignedInt;
  order: CTUnsignedInt;
  tx?: CTSerTx;
  spPr?: Dep_org_docx4j_dml.CTShapeProperties;
  cat?: CTAxDataSource;
  val?: CTNumDataSource;
  extLst?: CTExtensionList;
}

export interface CTTextLanguageID {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTTextLanguageID';
  readonly PARENT?: CTChartSpace;
  val: string;
}

export interface CTTickLblPos {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTTickLblPos';
  readonly PARENT?: CTCatAx | CTDateAx | CTSerAx | CTValAx;
  val?: STTickLblPos;
}

export interface CTTickMark {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTTickMark';
  readonly PARENT?: CTCatAx | CTDateAx | CTSerAx | CTValAx;
  val?: STTickMark;
}

export interface CTTimeUnit {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTTimeUnit';
  readonly PARENT?: CTDateAx;
  val?: STTimeUnit;
}

export interface CTTitle {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTTitle';
  readonly PARENT?: CTCatAx | CTChart | CTDateAx | CTSerAx | CTValAx;
  tx?: CTTx;
  layout?: CTLayout;
  overlay?: CTBoolean;
  spPr?: Dep_org_docx4j_dml.CTShapeProperties;
  txPr?: Dep_org_docx4j_dml.CTTextBody;
  extLst?: CTExtensionList;
}

export interface CTTrendline {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTTrendline';
  readonly PARENT?: CTAreaSer | CTBarSer | CTBubbleSer | CTLineSer | CTScatterSer;
  name?: string;
  spPr?: Dep_org_docx4j_dml.CTShapeProperties;
  trendlineType: CTTrendlineType;
  order?: CTOrder;
  period?: CTPeriod;
  forward?: CTDouble;
  backward?: CTDouble;
  intercept?: CTDouble;
  dispRSqr?: CTBoolean;
  dispEq?: CTBoolean;
  trendlineLbl?: CTTrendlineLbl;
  extLst?: CTExtensionList;
}

export interface CTTrendlineLbl {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTTrendlineLbl';
  readonly PARENT?: CTTrendline;
  layout?: CTLayout;
  tx?: CTTx;
  numFmt?: CTNumFmt;
  spPr?: Dep_org_docx4j_dml.CTShapeProperties;
  txPr?: Dep_org_docx4j_dml.CTTextBody;
  extLst?: CTExtensionList;
}

export interface CTTrendlineType {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTTrendlineType';
  readonly PARENT?: CTTrendline;
  val?: STTrendlineType;
}

export interface CTTx {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTTx';
  readonly PARENT?: CTDLbl | CTDispUnitsLbl | CTTitle | CTTrendlineLbl | Dep_org_docx4j_com_microsoft_schemas_office_drawing_x2012_chart.CTFilteredSeriesTitle;
  strRef: CTStrRef;
  rich: Dep_org_docx4j_dml.CTTextBody;
}

export interface CTUnsignedInt {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTUnsignedInt';
  readonly PARENT?: CTArea3DChart | CTAreaChart | CTAreaSer | CTBandFmt | CTBar3DChart | CTBarChart | CTBarSer | CTBubbleChart | CTBubbleSer | CTCatAx | CTCustSplit | CTDLbl | CTDPt | CTDateAx | CTLegendEntry | CTLine3DChart | CTLineChart | CTLineSer | CTMultiLvlStrData | CTNumData | CTPieSer | CTPivotFmt | CTPivotSource | CTRadarChart | CTRadarSer | CTScatterChart | CTScatterSer | CTSerAx | CTStockChart | CTStrData | CTSurface | CTSurface3DChart | CTSurfaceChart | CTSurfaceSer | CTValAx | Dep_org_docx4j_com_microsoft_schemas_office_drawing_x2012_chart.CTCategoryFilterException | Dep_org_docx4j_com_microsoft_schemas_office_drawing_x2014_chart.CTCategoryFilterException;
  val: number;
}

export interface CTUpDownBar {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTUpDownBar';
  readonly PARENT?: CTUpDownBars;
  spPr?: Dep_org_docx4j_dml.CTShapeProperties;
}

export interface CTUpDownBars {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTUpDownBars';
  readonly PARENT?: CTLineChart | CTStockChart;
  gapWidth?: CTGapAmount;
  upBars?: CTUpDownBar;
  downBars?: CTUpDownBar;
  extLst?: CTExtensionList;
}

export interface CTValAx {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTValAx';
  readonly PARENT?: CTPlotArea;
  axId: CTUnsignedInt;
  scaling: CTScaling;
  delete?: CTBoolean;
  axPos: CTAxPos;
  majorGridlines?: CTChartLines;
  minorGridlines?: CTChartLines;
  title?: CTTitle;
  numFmt?: CTNumFmt;
  majorTickMark?: CTTickMark;
  minorTickMark?: CTTickMark;
  tickLblPos?: CTTickLblPos;
  spPr?: Dep_org_docx4j_dml.CTShapeProperties;
  txPr?: Dep_org_docx4j_dml.CTTextBody;
  crossAx: CTUnsignedInt;
  crosses: CTCrosses;
  crossesAt: CTDouble;
  crossBetween?: CTCrossBetween;
  majorUnit?: CTAxisUnit;
  minorUnit?: CTAxisUnit;
  dispUnits?: CTDispUnits;
  extLst?: CTExtensionList;
}

export interface CTView3D {
  TYPE_NAME?: 'org_docx4j_dml_chart.CTView3D';
  readonly PARENT?: CTChart;
  rotX?: CTRotX;
  hPercent?: CTHPercent;
  rotY?: CTRotY;
  depthPercent?: CTDepthPercent;
  rAngAx?: CTBoolean;
  perspective?: CTPerspective;
  extLst?: CTExtensionList;
}

export type STAxPos = 'b' | 'l' | 'r' | 't';

export type STBarDir = 'bar' | 'col';

export type STBarGrouping = 'percentStacked' | 'clustered' | 'standard' | 'stacked';

export type STBuiltInUnit = 'hundreds' | 'thousands' | 'tenThousands' | 'hundredThousands' | 'millions' | 'tenMillions' | 'hundredMillions' | 'billions' | 'trillions';

export type STCrossBetween = 'between' | 'midCat';

export type STCrosses = 'autoZero' | 'max' | 'min';

export type STDLblPos = 'bestFit' | 'b' | 'ctr' | 'inBase' | 'inEnd' | 'l' | 'outEnd' | 'r' | 't';

export type STDispBlanksAs = 'span' | 'gap' | 'zero';

export type STErrBarType = 'both' | 'minus' | 'plus';

export type STErrDir = 'x' | 'y';

export type STErrValType = 'cust' | 'fixedVal' | 'percentage' | 'stdDev' | 'stdErr';

export type STGrouping = 'percentStacked' | 'standard' | 'stacked';

export type STLayoutMode = 'edge' | 'factor';

export type STLayoutTarget = 'inner' | 'outer';

export type STLblAlgn = 'ctr' | 'l' | 'r';

export type STLegendPos = 'b' | 'tr' | 'l' | 'r' | 't';

export type STMarkerStyle = 'circle' | 'dash' | 'diamond' | 'dot' | 'none' | 'picture' | 'plus' | 'square' | 'star' | 'triangle' | 'x';

export type STOfPieType = 'pie' | 'bar';

export type STOrientation = 'maxMin' | 'minMax';

export type STPageSetupOrientation = 'default' | 'portrait' | 'landscape';

export type STPictureFormat = 'stretch' | 'stack' | 'stackScale';

export type STRadarStyle = 'standard' | 'marker' | 'filled';

export type STScatterStyle = 'none' | 'line' | 'lineMarker' | 'marker' | 'smooth' | 'smoothMarker';

export type STShape = 'cone' | 'coneToMax' | 'box' | 'cylinder' | 'pyramid' | 'pyramidToMax';

export type STSizeRepresents = 'area' | 'w';

export type STSplitType = 'auto' | 'cust' | 'percent' | 'pos' | 'val';

export type STTickLblPos = 'high' | 'low' | 'nextTo' | 'none';

export type STTickMark = 'cross' | 'in' | 'none' | 'out';

export type STTimeUnit = 'days' | 'months' | 'years';

export type STTrendlineType = 'exp' | 'linear' | 'log' | 'movingAvg' | 'poly' | 'power';

export type ChartElement = TypedNamedValue<CTRelId>;

export type ChartSpaceElement = TypedNamedValue<CTChartSpace>;

export type UserShapesElement = TypedNamedValue<Dep_org_docx4j_dml_chartDrawing.CTDrawing>;

/** Any global element of this mapping, i.e. what an unmarshaller returns. */
export type RootElement = ChartElement | ChartSpaceElement | UserShapesElement;

/** The Jsonix mapping [org_docx4j_dml_chart] exported by the module's JavaScript file. */
export declare const org_docx4j_dml_chart: JsonixMapping<RootElement>;
