// Generated by jsonix-schema-compiler: TypeScript declarations for the Jsonix module [org_pptx4j_com_microsoft_schemas_office_powerpoint_x2013_main_command]. Do not edit.
// Describes the objects Jsonix produces when unmarshalling with this module's mappings.
import type * as Dep_org_docx4j_com_microsoft_schemas_office_drawing_x2013_main_command from './org_docx4j_com_microsoft_schemas_office_drawing_x2013_main_command';
import type * as Dep_org_pptx4j_pml from './org_pptx4j_pml';

/** Jsonix.XML.QName */
export interface XmlQName { namespaceURI: string; localPart: string; prefix?: string; key?: string; string?: string; }
/** Jsonix.XML.Calendar: the representation of date, time and dateTime values; unset fields are NaN. */
export interface XmlCalendar { year?: number; month?: number; day?: number; hour?: number; minute?: number; second?: number; fractionalSecond?: number; timezone?: number; }
/** The representation of xs:duration values. */
export interface XmlDuration { sign?: number; years?: number; months?: number; days?: number; hours?: number; minutes?: number; seconds?: number; }
/** An element as returned by an unmarshaller or held by an elementRef property. */
export interface TypedNamedValue<T> { name: XmlQName; value: T; }
/** A DOM node, allowed where the mapping permits DOM content (allowDom). */
export type XmlDomNode = any;
/** The value of an anyElement property: a typed element, a DOM node or (if mixed) text. */
export type XmlAnyElement = any;
/** The value of an anyAttribute property. */
export interface XmlAnyAttributes { [attributeName: string]: string; }
/** A Jsonix mapping object as consumed by new Jsonix.Context([...]); R is the union of its global element types. */
export interface JsonixMapping<R = unknown> { readonly __rootElement?: R; readonly [key: string]: unknown; }

export interface CTChangesInfo {
  TYPE_NAME?: 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x2013_main_command.CTChangesInfo';
  docChgLst?: CTDocumentChangesList[];
}

export interface CTCommentAuthorChanges {
  TYPE_NAME?: 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x2013_main_command.CTCommentAuthorChanges';
  readonly PARENT?: CTDocumentChanges;
  chgData?: Dep_org_docx4j_com_microsoft_schemas_office_drawing_x2013_main_command.CTChangesData;
  cmAuthorMkLst: CTCommentAuthorMonikerList;
  extLst?: Dep_org_pptx4j_pml.CTExtensionList;
  chg: STCommentAuthorChangeBit[];
}

export interface CTCommentAuthorMoniker {
  TYPE_NAME?: 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x2013_main_command.CTCommentAuthorMoniker';
  id: number;
}

export interface CTCommentAuthorMonikerList {
  TYPE_NAME?: 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x2013_main_command.CTCommentAuthorMonikerList';
  readonly PARENT?: CTCommentAuthorChanges;
  any?: XmlAnyElement[];
}

export interface CTCommentChanges {
  TYPE_NAME?: 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x2013_main_command.CTCommentChanges';
  readonly PARENT?: CTSlideChanges;
  chgData?: Dep_org_docx4j_com_microsoft_schemas_office_drawing_x2013_main_command.CTChangesData;
  cmMkLst: CTCommentMonikerList;
  extLst?: Dep_org_pptx4j_pml.CTExtensionList;
  chg: STCommentChangeBit[];
}

export interface CTCommentMoniker {
  TYPE_NAME?: 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x2013_main_command.CTCommentMoniker';
  authorId: number;
  idx: number;
}

export interface CTCommentMonikerList {
  TYPE_NAME?: 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x2013_main_command.CTCommentMonikerList';
  readonly PARENT?: CTCommentChanges;
  any?: XmlAnyElement[];
}

export interface CTDocumentChanges {
  TYPE_NAME?: 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x2013_main_command.CTDocumentChanges';
  readonly PARENT?: CTDocumentChangesList;
  chgData?: Dep_org_docx4j_com_microsoft_schemas_office_drawing_x2013_main_command.CTChangesData;
  docMkLst: CTDocumentMonikerList;
  sldChg?: CTSlideChanges[];
  sldMasterChg?: CTMainMasterChanges[];
  cmAuthorChg?: CTCommentAuthorChanges[];
  extLst?: Dep_org_pptx4j_pml.CTExtensionList;
  chg: STDocumentChangeBit[];
}

export interface CTDocumentChangesList {
  TYPE_NAME?: 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x2013_main_command.CTDocumentChangesList';
  readonly PARENT?: CTChangesInfo;
  chgData?: Dep_org_docx4j_com_microsoft_schemas_office_drawing_x2013_main_command.CTChangesData;
  docChg?: CTDocumentChanges[];
  extLst?: Dep_org_pptx4j_pml.CTExtensionList;
}

export interface CTDocumentMoniker {
  TYPE_NAME?: 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x2013_main_command.CTDocumentMoniker';
}

export interface CTDocumentMonikerList {
  TYPE_NAME?: 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x2013_main_command.CTDocumentMonikerList';
  readonly PARENT?: CTDocumentChanges;
  any?: XmlAnyElement[];
}

export interface CTMainMasterChanges {
  TYPE_NAME?: 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x2013_main_command.CTMainMasterChanges';
  readonly PARENT?: CTDocumentChanges;
  chgData?: Dep_org_docx4j_com_microsoft_schemas_office_drawing_x2013_main_command.CTChangesData;
  sldMasterMkLst: CTMainMasterMonikerList;
  spChg?: Dep_org_docx4j_com_microsoft_schemas_office_drawing_x2013_main_command.CTShapeChanges[];
  grpChg?: Dep_org_docx4j_com_microsoft_schemas_office_drawing_x2013_main_command.CTGroupShapeChanges[];
  graphicFrameChg?: Dep_org_docx4j_com_microsoft_schemas_office_drawing_x2013_main_command.CTGraphicFrameChanges[];
  picChg?: Dep_org_docx4j_com_microsoft_schemas_office_drawing_x2013_main_command.CTPictureChanges[];
  inkChg?: Dep_org_docx4j_com_microsoft_schemas_office_drawing_x2013_main_command.CTInkChanges[];
  cxnChg?: Dep_org_docx4j_com_microsoft_schemas_office_drawing_x2013_main_command.CTConnectorChanges[];
  sldLayoutChg?: CTSlideLayoutChanges[];
  extLst?: Dep_org_pptx4j_pml.CTExtensionList;
  chg: STMainMasterChangeBit[];
}

export interface CTMainMasterMoniker {
  TYPE_NAME?: 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x2013_main_command.CTMainMasterMoniker';
  cId?: number;
  sldId: number;
}

export interface CTMainMasterMonikerList {
  TYPE_NAME?: 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x2013_main_command.CTMainMasterMonikerList';
  readonly PARENT?: CTMainMasterChanges;
  any?: XmlAnyElement[];
}

export interface CTSlideBaseMonikerList {
  TYPE_NAME?: 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x2013_main_command.CTSlideBaseMonikerList';
  any?: XmlAnyElement[];
}

export interface CTSlideChanges {
  TYPE_NAME?: 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x2013_main_command.CTSlideChanges';
  readonly PARENT?: CTDocumentChanges;
  chgData?: Dep_org_docx4j_com_microsoft_schemas_office_drawing_x2013_main_command.CTChangesData;
  sldMkLst: CTSlideMonikerList;
  spChg?: Dep_org_docx4j_com_microsoft_schemas_office_drawing_x2013_main_command.CTShapeChanges[];
  grpChg?: Dep_org_docx4j_com_microsoft_schemas_office_drawing_x2013_main_command.CTGroupShapeChanges[];
  graphicFrameChg?: Dep_org_docx4j_com_microsoft_schemas_office_drawing_x2013_main_command.CTGraphicFrameChanges[];
  picChg?: Dep_org_docx4j_com_microsoft_schemas_office_drawing_x2013_main_command.CTPictureChanges[];
  inkChg?: Dep_org_docx4j_com_microsoft_schemas_office_drawing_x2013_main_command.CTInkChanges[];
  cxnChg?: Dep_org_docx4j_com_microsoft_schemas_office_drawing_x2013_main_command.CTConnectorChanges[];
  cmChg?: CTCommentChanges[];
  extLst?: Dep_org_pptx4j_pml.CTExtensionList;
  chg: STSlideChangeBit[];
}

export interface CTSlideLayoutChanges {
  TYPE_NAME?: 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x2013_main_command.CTSlideLayoutChanges';
  readonly PARENT?: CTMainMasterChanges;
  chgData?: Dep_org_docx4j_com_microsoft_schemas_office_drawing_x2013_main_command.CTChangesData;
  sldLayoutMkLst: CTSlideLayoutMonikerList;
  spChg?: Dep_org_docx4j_com_microsoft_schemas_office_drawing_x2013_main_command.CTShapeChanges[];
  grpChg?: Dep_org_docx4j_com_microsoft_schemas_office_drawing_x2013_main_command.CTGroupShapeChanges[];
  graphicFrameChg?: Dep_org_docx4j_com_microsoft_schemas_office_drawing_x2013_main_command.CTGraphicFrameChanges[];
  picChg?: Dep_org_docx4j_com_microsoft_schemas_office_drawing_x2013_main_command.CTPictureChanges[];
  inkChg?: Dep_org_docx4j_com_microsoft_schemas_office_drawing_x2013_main_command.CTInkChanges[];
  cxnChg?: Dep_org_docx4j_com_microsoft_schemas_office_drawing_x2013_main_command.CTConnectorChanges[];
  extLst?: Dep_org_pptx4j_pml.CTExtensionList;
  chg: STSlideLayoutChangeBit[];
}

export interface CTSlideLayoutMoniker {
  TYPE_NAME?: 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x2013_main_command.CTSlideLayoutMoniker';
  cId?: number;
  sldId: number;
}

export interface CTSlideLayoutMonikerList {
  TYPE_NAME?: 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x2013_main_command.CTSlideLayoutMonikerList';
  readonly PARENT?: CTSlideLayoutChanges;
  any?: XmlAnyElement[];
}

export interface CTSlideMoniker {
  TYPE_NAME?: 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x2013_main_command.CTSlideMoniker';
  cId?: number;
  sldId: number;
}

export interface CTSlideMonikerList {
  TYPE_NAME?: 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x2013_main_command.CTSlideMonikerList';
  readonly PARENT?: CTSlideChanges;
  any?: XmlAnyElement[];
}

export type STCommentAuthorChangeBit = 'add' | 'del' | 'mod' | 'replId';

export type STCommentChangeBit = 'add' | 'del' | 'mod' | 'replId';

export type STDocumentChangeBit = 'undo' | 'redo' | 'ext' | 'custSel' | 'mod' | 'addSld' | 'delSld' | 'modSld' | 'sldOrd' | 'addMainMaster' | 'delMainMaster' | 'modMainMaster' | 'mainMasterOrd' | 'addSection' | 'delSection' | 'modSection' | 'addCmAuthor' | 'delCmAuthor' | 'modCmAuthor' | 'replTag' | 'delTag' | 'addCustShow' | 'delCustShow' | 'modCustShow' | 'modNotesMaster' | 'modHandout' | 'modShowInfo' | 'addOsfTaskPaneApp' | 'delOsfTaskPaneApp' | 'setSldSz' | 'modRtl' | 'modChgInfo';

export type STMainMasterChangeBit = 'addSp' | 'delSp' | 'modSp' | 'spOrd' | 'new' | 'add' | 'del' | 'mod' | 'ord' | 'replId' | 'modTransition' | 'modMedia' | 'setBg' | 'setFolMasterAnim' | 'setFolMasterObjs' | 'modClrScheme' | 'addAnim' | 'delAnim' | 'modAnim' | 'replTag' | 'delTag' | 'setClrOvrMap' | 'delDesignElem' | 'modShow' | 'addSldLayout' | 'delSldLayout' | 'modSldLayout' | 'sldLayoutOrd';

export type STSlideChangeBit = 'addSp' | 'delSp' | 'modSp' | 'spOrd' | 'new' | 'add' | 'del' | 'mod' | 'ord' | 'replId' | 'modTransition' | 'modMedia' | 'setBg' | 'setFolMasterAnim' | 'setFolMasterObjs' | 'modClrScheme' | 'addAnim' | 'delAnim' | 'modAnim' | 'replTag' | 'delTag' | 'setClrOvrMap' | 'delDesignElem' | 'modShow' | 'addCm' | 'delCm' | 'modCm' | 'chgLayout' | 'modNotes' | 'modNotesTx' | 'setSldSyncInfo' | 'newSectionLinks';

export type STSlideLayoutChangeBit = 'addSp' | 'delSp' | 'modSp' | 'spOrd' | 'new' | 'add' | 'del' | 'mod' | 'ord' | 'replId' | 'modTransition' | 'modMedia' | 'setBg' | 'setFolMasterAnim' | 'setFolMasterObjs' | 'modClrScheme' | 'addAnim' | 'delAnim' | 'modAnim' | 'replTag' | 'delTag' | 'setClrOvrMap' | 'delDesignElem' | 'modShow';

export type ChgInfoElement = TypedNamedValue<CTChangesInfo>;

export type CmAuthorMkLstElement = TypedNamedValue<CTCommentAuthorMonikerList>;

export type CmMkLstElement = TypedNamedValue<CTCommentMonikerList>;

export type DocMkLstElement = TypedNamedValue<CTDocumentMonikerList>;

export type SldBaseMkLstElement = TypedNamedValue<CTSlideBaseMonikerList>;

export type SldLayoutMkLstElement = TypedNamedValue<CTSlideLayoutMonikerList>;

export type SldMasterMkLstElement = TypedNamedValue<CTMainMasterMonikerList>;

export type SldMkLstElement = TypedNamedValue<CTSlideMonikerList>;

/** Any global element of this mapping, i.e. what an unmarshaller returns. */
export type RootElement = ChgInfoElement | CmAuthorMkLstElement | CmMkLstElement | DocMkLstElement | SldBaseMkLstElement | SldLayoutMkLstElement | SldMasterMkLstElement | SldMkLstElement;

/** The Jsonix mapping [org_pptx4j_com_microsoft_schemas_office_powerpoint_x2013_main_command] exported by the module's JavaScript file. */
export declare const org_pptx4j_com_microsoft_schemas_office_powerpoint_x2013_main_command: JsonixMapping<RootElement>;
