var org_docx4j_dml_chart_Module_Factory = function () {
  var org_docx4j_dml_chart = {
    name: 'org_docx4j_dml_chart',
    defaultElementNamespaceURI: 'http:\/\/schemas.openxmlformats.org\/drawingml\/2006\/chart',
    dependencies: ['org_docx4j_dml', 'org_docx4j_dml_chartDrawing'],
    typeInfos: [{
        localName: 'CTArea3DChart',
        typeName: 'CT_Area3DChart',
        propertyInfos: [{
            name: 'grouping',
            typeInfo: '.CTGrouping'
          }, {
            name: 'varyColors',
            typeInfo: '.CTBoolean'
          }, {
            name: 'ser',
            minOccurs: 0,
            collection: true,
            typeInfo: '.CTAreaSer'
          }, {
            name: 'dLbls',
            typeInfo: '.CTDLbls'
          }, {
            name: 'dropLines',
            typeInfo: '.CTChartLines'
          }, {
            name: 'gapDepth',
            typeInfo: '.CTGapAmount'
          }, {
            name: 'axId',
            required: true,
            minOccurs: 2,
            maxOccurs: 3,
            collection: true,
            typeInfo: '.CTUnsignedInt'
          }, {
            name: 'extLst',
            typeInfo: '.CTExtensionList'
          }]
      }, {
        localName: 'CTAreaChart',
        typeName: 'CT_AreaChart',
        propertyInfos: [{
            name: 'grouping',
            typeInfo: '.CTGrouping'
          }, {
            name: 'varyColors',
            typeInfo: '.CTBoolean'
          }, {
            name: 'ser',
            minOccurs: 0,
            collection: true,
            typeInfo: '.CTAreaSer'
          }, {
            name: 'dLbls',
            typeInfo: '.CTDLbls'
          }, {
            name: 'dropLines',
            typeInfo: '.CTChartLines'
          }, {
            name: 'axId',
            required: true,
            minOccurs: 2,
            maxOccurs: 2,
            collection: true,
            typeInfo: '.CTUnsignedInt'
          }, {
            name: 'extLst',
            typeInfo: '.CTExtensionList'
          }]
      }, {
        localName: 'CTAreaSer',
        typeName: 'CT_AreaSer',
        propertyInfos: [{
            name: 'idx',
            required: true,
            typeInfo: '.CTUnsignedInt'
          }, {
            name: 'order',
            required: true,
            typeInfo: '.CTUnsignedInt'
          }, {
            name: 'tx',
            typeInfo: '.CTSerTx'
          }, {
            name: 'spPr',
            typeInfo: 'org_docx4j_dml.CTShapeProperties'
          }, {
            name: 'pictureOptions',
            typeInfo: '.CTPictureOptions'
          }, {
            name: 'dPt',
            minOccurs: 0,
            collection: true,
            typeInfo: '.CTDPt'
          }, {
            name: 'dLbls',
            typeInfo: '.CTDLbls'
          }, {
            name: 'trendline',
            minOccurs: 0,
            collection: true,
            typeInfo: '.CTTrendline'
          }, {
            name: 'errBars',
            minOccurs: 0,
            maxOccurs: 2,
            collection: true,
            typeInfo: '.CTErrBars'
          }, {
            name: 'cat',
            typeInfo: '.CTAxDataSource'
          }, {
            name: 'val',
            typeInfo: '.CTNumDataSource'
          }, {
            name: 'extLst',
            typeInfo: '.CTExtensionList'
          }]
      }, {
        localName: 'CTAxDataSource',
        typeName: 'CT_AxDataSource',
        propertyInfos: [{
            name: 'multiLvlStrRef',
            required: true,
            typeInfo: '.CTMultiLvlStrRef'
          }, {
            name: 'numRef',
            required: true,
            typeInfo: '.CTNumRef'
          }, {
            name: 'numLit',
            required: true,
            typeInfo: '.CTNumData'
          }, {
            name: 'strRef',
            required: true,
            typeInfo: '.CTStrRef'
          }, {
            name: 'strLit',
            required: true,
            typeInfo: '.CTStrData'
          }]
      }, {
        localName: 'CTAxPos',
        typeName: 'CT_AxPos',
        propertyInfos: [{
            name: 'val',
            required: true,
            typeInfo: '.STAxPos',
            attributeName: {
              localPart: 'val'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'CTAxisUnit',
        typeName: 'CT_AxisUnit',
        propertyInfos: [{
            name: 'val',
            required: true,
            typeInfo: 'Double',
            attributeName: {
              localPart: 'val'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'CTBandFmt',
        typeName: 'CT_BandFmt',
        propertyInfos: [{
            name: 'idx',
            required: true,
            typeInfo: '.CTUnsignedInt'
          }, {
            name: 'spPr',
            typeInfo: 'org_docx4j_dml.CTShapeProperties'
          }]
      }, {
        localName: 'CTBandFmts',
        typeName: 'CT_BandFmts',
        propertyInfos: [{
            name: 'bandFmt',
            minOccurs: 0,
            collection: true,
            typeInfo: '.CTBandFmt'
          }]
      }, {
        localName: 'CTBar3DChart',
        typeName: 'CT_Bar3DChart',
        propertyInfos: [{
            name: 'barDir',
            required: true,
            typeInfo: '.CTBarDir'
          }, {
            name: 'grouping',
            typeInfo: '.CTBarGrouping'
          }, {
            name: 'varyColors',
            typeInfo: '.CTBoolean'
          }, {
            name: 'ser',
            minOccurs: 0,
            collection: true,
            typeInfo: '.CTBarSer'
          }, {
            name: 'dLbls',
            typeInfo: '.CTDLbls'
          }, {
            name: 'gapWidth',
            typeInfo: '.CTGapAmount'
          }, {
            name: 'gapDepth',
            typeInfo: '.CTGapAmount'
          }, {
            name: 'shape',
            typeInfo: '.CTShape'
          }, {
            name: 'axId',
            required: true,
            minOccurs: 2,
            maxOccurs: 3,
            collection: true,
            typeInfo: '.CTUnsignedInt'
          }, {
            name: 'extLst',
            typeInfo: '.CTExtensionList'
          }]
      }, {
        localName: 'CTBarChart',
        typeName: 'CT_BarChart',
        propertyInfos: [{
            name: 'barDir',
            required: true,
            typeInfo: '.CTBarDir'
          }, {
            name: 'grouping',
            typeInfo: '.CTBarGrouping'
          }, {
            name: 'varyColors',
            typeInfo: '.CTBoolean'
          }, {
            name: 'ser',
            minOccurs: 0,
            collection: true,
            typeInfo: '.CTBarSer'
          }, {
            name: 'dLbls',
            typeInfo: '.CTDLbls'
          }, {
            name: 'gapWidth',
            typeInfo: '.CTGapAmount'
          }, {
            name: 'overlap',
            typeInfo: '.CTOverlap'
          }, {
            name: 'serLines',
            minOccurs: 0,
            collection: true,
            typeInfo: '.CTChartLines'
          }, {
            name: 'axId',
            required: true,
            minOccurs: 2,
            maxOccurs: 2,
            collection: true,
            typeInfo: '.CTUnsignedInt'
          }, {
            name: 'extLst',
            typeInfo: '.CTExtensionList'
          }]
      }, {
        localName: 'CTBarDir',
        typeName: 'CT_BarDir',
        propertyInfos: [{
            name: 'val',
            typeInfo: '.STBarDir',
            defaultValue: 'col',
            attributeName: {
              localPart: 'val'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'CTBarGrouping',
        typeName: 'CT_BarGrouping',
        propertyInfos: [{
            name: 'val',
            typeInfo: '.STBarGrouping',
            defaultValue: 'clustered',
            attributeName: {
              localPart: 'val'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'CTBarSer',
        typeName: 'CT_BarSer',
        propertyInfos: [{
            name: 'idx',
            required: true,
            typeInfo: '.CTUnsignedInt'
          }, {
            name: 'order',
            required: true,
            typeInfo: '.CTUnsignedInt'
          }, {
            name: 'tx',
            typeInfo: '.CTSerTx'
          }, {
            name: 'spPr',
            typeInfo: 'org_docx4j_dml.CTShapeProperties'
          }, {
            name: 'invertIfNegative',
            typeInfo: '.CTBoolean'
          }, {
            name: 'pictureOptions',
            typeInfo: '.CTPictureOptions'
          }, {
            name: 'dPt',
            minOccurs: 0,
            collection: true,
            typeInfo: '.CTDPt'
          }, {
            name: 'dLbls',
            typeInfo: '.CTDLbls'
          }, {
            name: 'trendline',
            minOccurs: 0,
            collection: true,
            typeInfo: '.CTTrendline'
          }, {
            name: 'errBars',
            typeInfo: '.CTErrBars'
          }, {
            name: 'cat',
            typeInfo: '.CTAxDataSource'
          }, {
            name: 'val',
            typeInfo: '.CTNumDataSource'
          }, {
            name: 'shape',
            typeInfo: '.CTShape'
          }, {
            name: 'extLst',
            typeInfo: '.CTExtensionList'
          }]
      }, {
        localName: 'CTBoolean',
        typeName: 'CT_Boolean',
        propertyInfos: [{
            name: 'val',
            typeInfo: 'Boolean',
            defaultValue: true,
            attributeName: {
              localPart: 'val'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'CTBubbleChart',
        typeName: 'CT_BubbleChart',
        propertyInfos: [{
            name: 'varyColors',
            typeInfo: '.CTBoolean'
          }, {
            name: 'ser',
            minOccurs: 0,
            collection: true,
            typeInfo: '.CTBubbleSer'
          }, {
            name: 'dLbls',
            typeInfo: '.CTDLbls'
          }, {
            name: 'bubble3D',
            typeInfo: '.CTBoolean'
          }, {
            name: 'bubbleScale',
            typeInfo: '.CTBubbleScale'
          }, {
            name: 'showNegBubbles',
            typeInfo: '.CTBoolean'
          }, {
            name: 'sizeRepresents',
            typeInfo: '.CTSizeRepresents'
          }, {
            name: 'axId',
            required: true,
            minOccurs: 2,
            maxOccurs: 2,
            collection: true,
            typeInfo: '.CTUnsignedInt'
          }, {
            name: 'extLst',
            typeInfo: '.CTExtensionList'
          }]
      }, {
        localName: 'CTBubbleScale',
        typeName: 'CT_BubbleScale',
        propertyInfos: [{
            name: 'val',
            typeInfo: 'UnsignedInt',
            defaultValue: 100,
            attributeName: {
              localPart: 'val'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'CTBubbleSer',
        typeName: 'CT_BubbleSer',
        propertyInfos: [{
            name: 'idx',
            required: true,
            typeInfo: '.CTUnsignedInt'
          }, {
            name: 'order',
            required: true,
            typeInfo: '.CTUnsignedInt'
          }, {
            name: 'tx',
            typeInfo: '.CTSerTx'
          }, {
            name: 'spPr',
            typeInfo: 'org_docx4j_dml.CTShapeProperties'
          }, {
            name: 'invertIfNegative',
            typeInfo: '.CTBoolean'
          }, {
            name: 'dPt',
            minOccurs: 0,
            collection: true,
            typeInfo: '.CTDPt'
          }, {
            name: 'dLbls',
            typeInfo: '.CTDLbls'
          }, {
            name: 'trendline',
            minOccurs: 0,
            collection: true,
            typeInfo: '.CTTrendline'
          }, {
            name: 'errBars',
            minOccurs: 0,
            maxOccurs: 2,
            collection: true,
            typeInfo: '.CTErrBars'
          }, {
            name: 'xVal',
            typeInfo: '.CTAxDataSource'
          }, {
            name: 'yVal',
            typeInfo: '.CTNumDataSource'
          }, {
            name: 'bubbleSize',
            typeInfo: '.CTNumDataSource'
          }, {
            name: 'bubble3D',
            typeInfo: '.CTBoolean'
          }, {
            name: 'extLst',
            typeInfo: '.CTExtensionList'
          }]
      }, {
        localName: 'CTBuiltInUnit',
        typeName: 'CT_BuiltInUnit',
        propertyInfos: [{
            name: 'val',
            typeInfo: '.STBuiltInUnit',
            defaultValue: 'thousands',
            attributeName: {
              localPart: 'val'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'CTCatAx',
        typeName: 'CT_CatAx',
        propertyInfos: [{
            name: 'axId',
            required: true,
            typeInfo: '.CTUnsignedInt'
          }, {
            name: 'scaling',
            required: true,
            typeInfo: '.CTScaling'
          }, {
            name: 'delete',
            typeInfo: '.CTBoolean'
          }, {
            name: 'axPos',
            required: true,
            typeInfo: '.CTAxPos'
          }, {
            name: 'majorGridlines',
            typeInfo: '.CTChartLines'
          }, {
            name: 'minorGridlines',
            typeInfo: '.CTChartLines'
          }, {
            name: 'title',
            typeInfo: '.CTTitle'
          }, {
            name: 'numFmt',
            typeInfo: '.CTNumFmt'
          }, {
            name: 'majorTickMark',
            typeInfo: '.CTTickMark'
          }, {
            name: 'minorTickMark',
            typeInfo: '.CTTickMark'
          }, {
            name: 'tickLblPos',
            typeInfo: '.CTTickLblPos'
          }, {
            name: 'spPr',
            typeInfo: 'org_docx4j_dml.CTShapeProperties'
          }, {
            name: 'txPr',
            typeInfo: 'org_docx4j_dml.CTTextBody'
          }, {
            name: 'crossAx',
            required: true,
            typeInfo: '.CTUnsignedInt'
          }, {
            name: 'crosses',
            required: true,
            typeInfo: '.CTCrosses'
          }, {
            name: 'crossesAt',
            required: true,
            typeInfo: '.CTDouble'
          }, {
            name: 'auto',
            typeInfo: '.CTBoolean'
          }, {
            name: 'lblAlgn',
            typeInfo: '.CTLblAlgn'
          }, {
            name: 'lblOffset',
            typeInfo: '.CTLblOffset'
          }, {
            name: 'tickLblSkip',
            typeInfo: '.CTSkip'
          }, {
            name: 'tickMarkSkip',
            typeInfo: '.CTSkip'
          }, {
            name: 'noMultiLvlLbl',
            typeInfo: '.CTBoolean'
          }, {
            name: 'extLst',
            typeInfo: '.CTExtensionList'
          }]
      }, {
        localName: 'CTChart',
        typeName: 'CT_Chart',
        propertyInfos: [{
            name: 'title',
            typeInfo: '.CTTitle'
          }, {
            name: 'autoTitleDeleted',
            typeInfo: '.CTBoolean'
          }, {
            name: 'pivotFmts',
            typeInfo: '.CTPivotFmts'
          }, {
            name: 'view3D',
            typeInfo: '.CTView3D'
          }, {
            name: 'floor',
            typeInfo: '.CTSurface'
          }, {
            name: 'sideWall',
            typeInfo: '.CTSurface'
          }, {
            name: 'backWall',
            typeInfo: '.CTSurface'
          }, {
            name: 'plotArea',
            required: true,
            typeInfo: '.CTPlotArea'
          }, {
            name: 'legend',
            typeInfo: '.CTLegend'
          }, {
            name: 'plotVisOnly',
            typeInfo: '.CTBoolean'
          }, {
            name: 'dispBlanksAs',
            typeInfo: '.CTDispBlanksAs'
          }, {
            name: 'showDLblsOverMax',
            typeInfo: '.CTBoolean'
          }, {
            name: 'extLst',
            typeInfo: '.CTExtensionList'
          }]
      }, {
        localName: 'CTChartLines',
        typeName: 'CT_ChartLines',
        propertyInfos: [{
            name: 'spPr',
            typeInfo: 'org_docx4j_dml.CTShapeProperties'
          }]
      }, {
        localName: 'CTChartSpace',
        typeName: 'CT_ChartSpace',
        propertyInfos: [{
            name: 'date1904',
            typeInfo: '.CTBoolean'
          }, {
            name: 'lang',
            typeInfo: '.CTTextLanguageID'
          }, {
            name: 'roundedCorners',
            typeInfo: '.CTBoolean'
          }, {
            name: 'style',
            typeInfo: '.CTStyle'
          }, {
            name: 'clrMapOvr',
            typeInfo: 'org_docx4j_dml.CTColorMapping'
          }, {
            name: 'pivotSource',
            typeInfo: '.CTPivotSource'
          }, {
            name: 'protection',
            typeInfo: '.CTProtection'
          }, {
            name: 'chart',
            required: true,
            typeInfo: '.CTChart'
          }, {
            name: 'spPr',
            typeInfo: 'org_docx4j_dml.CTShapeProperties'
          }, {
            name: 'txPr',
            typeInfo: 'org_docx4j_dml.CTTextBody'
          }, {
            name: 'externalData',
            typeInfo: '.CTExternalData'
          }, {
            name: 'printSettings',
            typeInfo: '.CTPrintSettings'
          }, {
            name: 'userShapes',
            typeInfo: '.CTRelId'
          }, {
            name: 'extLst',
            typeInfo: '.CTExtensionList'
          }]
      }, {
        localName: 'CTCrossBetween',
        typeName: 'CT_CrossBetween',
        propertyInfos: [{
            name: 'val',
            required: true,
            typeInfo: '.STCrossBetween',
            attributeName: {
              localPart: 'val'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'CTCrosses',
        typeName: 'CT_Crosses',
        propertyInfos: [{
            name: 'val',
            required: true,
            typeInfo: '.STCrosses',
            attributeName: {
              localPart: 'val'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'CTCustSplit',
        typeName: 'CT_CustSplit',
        propertyInfos: [{
            name: 'secondPiePt',
            minOccurs: 0,
            collection: true,
            typeInfo: '.CTUnsignedInt'
          }]
      }, {
        localName: 'CTDLbl',
        typeName: 'CT_DLbl',
        propertyInfos: [{
            name: 'idx',
            required: true,
            typeInfo: '.CTUnsignedInt'
          }, {
            name: 'delete',
            required: true,
            typeInfo: '.CTBoolean'
          }, {
            name: 'layout',
            typeInfo: '.CTLayout'
          }, {
            name: 'tx',
            typeInfo: '.CTTx'
          }, {
            name: 'numFmt',
            typeInfo: '.CTNumFmt'
          }, {
            name: 'spPr',
            typeInfo: 'org_docx4j_dml.CTShapeProperties'
          }, {
            name: 'txPr',
            typeInfo: 'org_docx4j_dml.CTTextBody'
          }, {
            name: 'dLblPos',
            typeInfo: '.CTDLblPos'
          }, {
            name: 'showLegendKey',
            typeInfo: '.CTBoolean'
          }, {
            name: 'showVal',
            typeInfo: '.CTBoolean'
          }, {
            name: 'showCatName',
            typeInfo: '.CTBoolean'
          }, {
            name: 'showSerName',
            typeInfo: '.CTBoolean'
          }, {
            name: 'showPercent',
            typeInfo: '.CTBoolean'
          }, {
            name: 'showBubbleSize',
            typeInfo: '.CTBoolean'
          }, {
            name: 'separator'
          }, {
            name: 'extLst',
            typeInfo: '.CTExtensionList'
          }]
      }, {
        localName: 'CTDLblPos',
        typeName: 'CT_DLblPos',
        propertyInfos: [{
            name: 'val',
            required: true,
            typeInfo: '.STDLblPos',
            attributeName: {
              localPart: 'val'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'CTDLbls',
        typeName: 'CT_DLbls',
        propertyInfos: [{
            name: 'dLbl',
            minOccurs: 0,
            collection: true,
            typeInfo: '.CTDLbl'
          }, {
            name: 'delete',
            required: true,
            typeInfo: '.CTBoolean'
          }, {
            name: 'numFmt',
            typeInfo: '.CTNumFmt'
          }, {
            name: 'spPr',
            typeInfo: 'org_docx4j_dml.CTShapeProperties'
          }, {
            name: 'txPr',
            typeInfo: 'org_docx4j_dml.CTTextBody'
          }, {
            name: 'dLblPos',
            typeInfo: '.CTDLblPos'
          }, {
            name: 'showLegendKey',
            typeInfo: '.CTBoolean'
          }, {
            name: 'showVal',
            typeInfo: '.CTBoolean'
          }, {
            name: 'showCatName',
            typeInfo: '.CTBoolean'
          }, {
            name: 'showSerName',
            typeInfo: '.CTBoolean'
          }, {
            name: 'showPercent',
            typeInfo: '.CTBoolean'
          }, {
            name: 'showBubbleSize',
            typeInfo: '.CTBoolean'
          }, {
            name: 'separator'
          }, {
            name: 'showLeaderLines',
            typeInfo: '.CTBoolean'
          }, {
            name: 'leaderLines',
            typeInfo: '.CTChartLines'
          }, {
            name: 'extLst',
            typeInfo: '.CTExtensionList'
          }]
      }, {
        localName: 'CTDPt',
        typeName: 'CT_DPt',
        propertyInfos: [{
            name: 'idx',
            required: true,
            typeInfo: '.CTUnsignedInt'
          }, {
            name: 'invertIfNegative',
            typeInfo: '.CTBoolean'
          }, {
            name: 'marker',
            typeInfo: '.CTMarker'
          }, {
            name: 'bubble3D',
            typeInfo: '.CTBoolean'
          }, {
            name: 'explosion',
            typeInfo: '.CTUnsignedInt'
          }, {
            name: 'spPr',
            typeInfo: 'org_docx4j_dml.CTShapeProperties'
          }, {
            name: 'pictureOptions',
            typeInfo: '.CTPictureOptions'
          }, {
            name: 'extLst',
            typeInfo: '.CTExtensionList'
          }]
      }, {
        localName: 'CTDTable',
        typeName: 'CT_DTable',
        propertyInfos: [{
            name: 'showHorzBorder',
            typeInfo: '.CTBoolean'
          }, {
            name: 'showVertBorder',
            typeInfo: '.CTBoolean'
          }, {
            name: 'showOutline',
            typeInfo: '.CTBoolean'
          }, {
            name: 'showKeys',
            typeInfo: '.CTBoolean'
          }, {
            name: 'spPr',
            typeInfo: 'org_docx4j_dml.CTShapeProperties'
          }, {
            name: 'txPr',
            typeInfo: 'org_docx4j_dml.CTTextBody'
          }, {
            name: 'extLst',
            typeInfo: '.CTExtensionList'
          }]
      }, {
        localName: 'CTDateAx',
        typeName: 'CT_DateAx',
        propertyInfos: [{
            name: 'axId',
            required: true,
            typeInfo: '.CTUnsignedInt'
          }, {
            name: 'scaling',
            required: true,
            typeInfo: '.CTScaling'
          }, {
            name: 'delete',
            typeInfo: '.CTBoolean'
          }, {
            name: 'axPos',
            required: true,
            typeInfo: '.CTAxPos'
          }, {
            name: 'majorGridlines',
            typeInfo: '.CTChartLines'
          }, {
            name: 'minorGridlines',
            typeInfo: '.CTChartLines'
          }, {
            name: 'title',
            typeInfo: '.CTTitle'
          }, {
            name: 'numFmt',
            typeInfo: '.CTNumFmt'
          }, {
            name: 'majorTickMark',
            typeInfo: '.CTTickMark'
          }, {
            name: 'minorTickMark',
            typeInfo: '.CTTickMark'
          }, {
            name: 'tickLblPos',
            typeInfo: '.CTTickLblPos'
          }, {
            name: 'spPr',
            typeInfo: 'org_docx4j_dml.CTShapeProperties'
          }, {
            name: 'txPr',
            typeInfo: 'org_docx4j_dml.CTTextBody'
          }, {
            name: 'crossAx',
            required: true,
            typeInfo: '.CTUnsignedInt'
          }, {
            name: 'crosses',
            required: true,
            typeInfo: '.CTCrosses'
          }, {
            name: 'crossesAt',
            required: true,
            typeInfo: '.CTDouble'
          }, {
            name: 'auto',
            typeInfo: '.CTBoolean'
          }, {
            name: 'lblOffset',
            typeInfo: '.CTLblOffset'
          }, {
            name: 'baseTimeUnit',
            typeInfo: '.CTTimeUnit'
          }, {
            name: 'majorUnit',
            typeInfo: '.CTAxisUnit'
          }, {
            name: 'majorTimeUnit',
            typeInfo: '.CTTimeUnit'
          }, {
            name: 'minorUnit',
            typeInfo: '.CTAxisUnit'
          }, {
            name: 'minorTimeUnit',
            typeInfo: '.CTTimeUnit'
          }, {
            name: 'extLst',
            typeInfo: '.CTExtensionList'
          }]
      }, {
        localName: 'CTDepthPercent',
        typeName: 'CT_DepthPercent',
        propertyInfos: [{
            name: 'val',
            typeInfo: 'UnsignedShort',
            defaultValue: 100,
            attributeName: {
              localPart: 'val'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'CTDispBlanksAs',
        typeName: 'CT_DispBlanksAs',
        propertyInfos: [{
            name: 'val',
            typeInfo: '.STDispBlanksAs',
            defaultValue: 'zero',
            attributeName: {
              localPart: 'val'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'CTDispUnits',
        typeName: 'CT_DispUnits',
        propertyInfos: [{
            name: 'custUnit',
            required: true,
            typeInfo: '.CTDouble'
          }, {
            name: 'builtInUnit',
            required: true,
            typeInfo: '.CTBuiltInUnit'
          }, {
            name: 'dispUnitsLbl',
            typeInfo: '.CTDispUnitsLbl'
          }, {
            name: 'extLst',
            typeInfo: '.CTExtensionList'
          }]
      }, {
        localName: 'CTDispUnitsLbl',
        typeName: 'CT_DispUnitsLbl',
        propertyInfos: [{
            name: 'layout',
            typeInfo: '.CTLayout'
          }, {
            name: 'tx',
            typeInfo: '.CTTx'
          }, {
            name: 'spPr',
            typeInfo: 'org_docx4j_dml.CTShapeProperties'
          }, {
            name: 'txPr',
            typeInfo: 'org_docx4j_dml.CTTextBody'
          }]
      }, {
        localName: 'CTDouble',
        typeName: 'CT_Double',
        propertyInfos: [{
            name: 'val',
            required: true,
            typeInfo: 'Double',
            attributeName: {
              localPart: 'val'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'CTDoughnutChart',
        typeName: 'CT_DoughnutChart',
        propertyInfos: [{
            name: 'varyColors',
            typeInfo: '.CTBoolean'
          }, {
            name: 'ser',
            minOccurs: 0,
            collection: true,
            typeInfo: '.CTPieSer'
          }, {
            name: 'dLbls',
            typeInfo: '.CTDLbls'
          }, {
            name: 'firstSliceAng',
            typeInfo: '.CTFirstSliceAng'
          }, {
            name: 'holeSize',
            typeInfo: '.CTHoleSize'
          }, {
            name: 'extLst',
            typeInfo: '.CTExtensionList'
          }]
      }, {
        localName: 'CTErrBarType',
        typeName: 'CT_ErrBarType',
        propertyInfos: [{
            name: 'val',
            typeInfo: '.STErrBarType',
            defaultValue: 'both',
            attributeName: {
              localPart: 'val'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'CTErrBars',
        typeName: 'CT_ErrBars',
        propertyInfos: [{
            name: 'errDir',
            typeInfo: '.CTErrDir'
          }, {
            name: 'errBarType',
            required: true,
            typeInfo: '.CTErrBarType'
          }, {
            name: 'errValType',
            required: true,
            typeInfo: '.CTErrValType'
          }, {
            name: 'noEndCap',
            typeInfo: '.CTBoolean'
          }, {
            name: 'plus',
            typeInfo: '.CTNumDataSource'
          }, {
            name: 'minus',
            typeInfo: '.CTNumDataSource'
          }, {
            name: 'val',
            typeInfo: '.CTDouble'
          }, {
            name: 'spPr',
            typeInfo: 'org_docx4j_dml.CTShapeProperties'
          }, {
            name: 'extLst',
            typeInfo: '.CTExtensionList'
          }]
      }, {
        localName: 'CTErrDir',
        typeName: 'CT_ErrDir',
        propertyInfos: [{
            name: 'val',
            required: true,
            typeInfo: '.STErrDir',
            attributeName: {
              localPart: 'val'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'CTErrValType',
        typeName: 'CT_ErrValType',
        propertyInfos: [{
            name: 'val',
            typeInfo: '.STErrValType',
            defaultValue: 'fixedVal',
            attributeName: {
              localPart: 'val'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'CTExtension',
        typeName: 'CT_Extension',
        propertyInfos: [{
            name: 'any',
            minOccurs: 0,
            collection: true,
            mixed: false,
            type: 'anyElement'
          }, {
            name: 'uri',
            typeInfo: 'Token',
            attributeName: {
              localPart: 'uri'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'CTExtensionList',
        typeName: 'CT_ExtensionList',
        propertyInfos: [{
            name: 'ext',
            minOccurs: 0,
            collection: true,
            typeInfo: '.CTExtension'
          }]
      }, {
        localName: 'CTExternalData',
        typeName: 'CT_ExternalData',
        propertyInfos: [{
            name: 'autoUpdate',
            typeInfo: '.CTBoolean'
          }, {
            name: 'id',
            required: true,
            attributeName: {
              localPart: 'id',
              namespaceURI: 'http:\/\/schemas.openxmlformats.org\/officeDocument\/2006\/relationships'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'CTFirstSliceAng',
        typeName: 'CT_FirstSliceAng',
        propertyInfos: [{
            name: 'val',
            typeInfo: 'UnsignedShort',
            defaultValue: 0,
            attributeName: {
              localPart: 'val'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'CTGapAmount',
        typeName: 'CT_GapAmount',
        propertyInfos: [{
            name: 'val',
            typeInfo: 'UnsignedShort',
            defaultValue: 150,
            attributeName: {
              localPart: 'val'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'CTGrouping',
        typeName: 'CT_Grouping',
        propertyInfos: [{
            name: 'val',
            typeInfo: '.STGrouping',
            defaultValue: 'standard',
            attributeName: {
              localPart: 'val'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'CTHPercent',
        typeName: 'CT_HPercent',
        propertyInfos: [{
            name: 'val',
            typeInfo: 'UnsignedShort',
            defaultValue: 100,
            attributeName: {
              localPart: 'val'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'CTHeaderFooter',
        typeName: 'CT_HeaderFooter',
        propertyInfos: [{
            name: 'oddHeader'
          }, {
            name: 'oddFooter'
          }, {
            name: 'evenHeader'
          }, {
            name: 'evenFooter'
          }, {
            name: 'firstHeader'
          }, {
            name: 'firstFooter'
          }, {
            name: 'alignWithMargins',
            typeInfo: 'Boolean',
            defaultValue: true,
            attributeName: {
              localPart: 'alignWithMargins'
            },
            type: 'attribute'
          }, {
            name: 'differentFirst',
            typeInfo: 'Boolean',
            defaultValue: false,
            attributeName: {
              localPart: 'differentFirst'
            },
            type: 'attribute'
          }, {
            name: 'differentOddEven',
            typeInfo: 'Boolean',
            defaultValue: false,
            attributeName: {
              localPart: 'differentOddEven'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'CTHoleSize',
        typeName: 'CT_HoleSize',
        propertyInfos: [{
            name: 'val',
            typeInfo: 'UnsignedByte',
            defaultValue: 10,
            attributeName: {
              localPart: 'val'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'CTLayout',
        typeName: 'CT_Layout',
        propertyInfos: [{
            name: 'manualLayout',
            typeInfo: '.CTManualLayout'
          }, {
            name: 'extLst',
            typeInfo: '.CTExtensionList'
          }]
      }, {
        localName: 'CTLayoutMode',
        typeName: 'CT_LayoutMode',
        propertyInfos: [{
            name: 'val',
            typeInfo: '.STLayoutMode',
            defaultValue: 'factor',
            attributeName: {
              localPart: 'val'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'CTLayoutTarget',
        typeName: 'CT_LayoutTarget',
        propertyInfos: [{
            name: 'val',
            typeInfo: '.STLayoutTarget',
            defaultValue: 'outer',
            attributeName: {
              localPart: 'val'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'CTLblAlgn',
        typeName: 'CT_LblAlgn',
        propertyInfos: [{
            name: 'val',
            required: true,
            typeInfo: '.STLblAlgn',
            attributeName: {
              localPart: 'val'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'CTLblOffset',
        typeName: 'CT_LblOffset',
        propertyInfos: [{
            name: 'val',
            typeInfo: 'UnsignedShort',
            defaultValue: 100,
            attributeName: {
              localPart: 'val'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'CTLegend',
        typeName: 'CT_Legend',
        propertyInfos: [{
            name: 'legendPos',
            typeInfo: '.CTLegendPos'
          }, {
            name: 'legendEntry',
            minOccurs: 0,
            collection: true,
            typeInfo: '.CTLegendEntry'
          }, {
            name: 'layout',
            typeInfo: '.CTLayout'
          }, {
            name: 'overlay',
            typeInfo: '.CTBoolean'
          }, {
            name: 'spPr',
            typeInfo: 'org_docx4j_dml.CTShapeProperties'
          }, {
            name: 'txPr',
            typeInfo: 'org_docx4j_dml.CTTextBody'
          }, {
            name: 'extLst',
            typeInfo: '.CTExtensionList'
          }]
      }, {
        localName: 'CTLegendEntry',
        typeName: 'CT_LegendEntry',
        propertyInfos: [{
            name: 'idx',
            required: true,
            typeInfo: '.CTUnsignedInt'
          }, {
            name: 'delete',
            required: true,
            typeInfo: '.CTBoolean'
          }, {
            name: 'txPr',
            typeInfo: 'org_docx4j_dml.CTTextBody'
          }, {
            name: 'extLst',
            typeInfo: '.CTExtensionList'
          }]
      }, {
        localName: 'CTLegendPos',
        typeName: 'CT_LegendPos',
        propertyInfos: [{
            name: 'val',
            typeInfo: '.STLegendPos',
            defaultValue: 'r',
            attributeName: {
              localPart: 'val'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'CTLine3DChart',
        typeName: 'CT_Line3DChart',
        propertyInfos: [{
            name: 'grouping',
            required: true,
            typeInfo: '.CTGrouping'
          }, {
            name: 'varyColors',
            typeInfo: '.CTBoolean'
          }, {
            name: 'ser',
            minOccurs: 0,
            collection: true,
            typeInfo: '.CTLineSer'
          }, {
            name: 'dLbls',
            typeInfo: '.CTDLbls'
          }, {
            name: 'dropLines',
            typeInfo: '.CTChartLines'
          }, {
            name: 'gapDepth',
            typeInfo: '.CTGapAmount'
          }, {
            name: 'axId',
            required: true,
            minOccurs: 3,
            maxOccurs: 3,
            collection: true,
            typeInfo: '.CTUnsignedInt'
          }, {
            name: 'extLst',
            typeInfo: '.CTExtensionList'
          }]
      }, {
        localName: 'CTLineChart',
        typeName: 'CT_LineChart',
        propertyInfos: [{
            name: 'grouping',
            required: true,
            typeInfo: '.CTGrouping'
          }, {
            name: 'varyColors',
            typeInfo: '.CTBoolean'
          }, {
            name: 'ser',
            minOccurs: 0,
            collection: true,
            typeInfo: '.CTLineSer'
          }, {
            name: 'dLbls',
            typeInfo: '.CTDLbls'
          }, {
            name: 'dropLines',
            typeInfo: '.CTChartLines'
          }, {
            name: 'hiLowLines',
            typeInfo: '.CTChartLines'
          }, {
            name: 'upDownBars',
            typeInfo: '.CTUpDownBars'
          }, {
            name: 'marker',
            typeInfo: '.CTBoolean'
          }, {
            name: 'smooth',
            typeInfo: '.CTBoolean'
          }, {
            name: 'axId',
            required: true,
            minOccurs: 2,
            maxOccurs: 2,
            collection: true,
            typeInfo: '.CTUnsignedInt'
          }, {
            name: 'extLst',
            typeInfo: '.CTExtensionList'
          }]
      }, {
        localName: 'CTLineSer',
        typeName: 'CT_LineSer',
        propertyInfos: [{
            name: 'idx',
            required: true,
            typeInfo: '.CTUnsignedInt'
          }, {
            name: 'order',
            required: true,
            typeInfo: '.CTUnsignedInt'
          }, {
            name: 'tx',
            typeInfo: '.CTSerTx'
          }, {
            name: 'spPr',
            typeInfo: 'org_docx4j_dml.CTShapeProperties'
          }, {
            name: 'marker',
            typeInfo: '.CTMarker'
          }, {
            name: 'dPt',
            minOccurs: 0,
            collection: true,
            typeInfo: '.CTDPt'
          }, {
            name: 'dLbls',
            typeInfo: '.CTDLbls'
          }, {
            name: 'trendline',
            minOccurs: 0,
            collection: true,
            typeInfo: '.CTTrendline'
          }, {
            name: 'errBars',
            typeInfo: '.CTErrBars'
          }, {
            name: 'cat',
            typeInfo: '.CTAxDataSource'
          }, {
            name: 'val',
            typeInfo: '.CTNumDataSource'
          }, {
            name: 'smooth',
            typeInfo: '.CTBoolean'
          }, {
            name: 'extLst',
            typeInfo: '.CTExtensionList'
          }]
      }, {
        localName: 'CTLogBase',
        typeName: 'CT_LogBase',
        propertyInfos: [{
            name: 'val',
            required: true,
            typeInfo: 'Double',
            attributeName: {
              localPart: 'val'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'CTLvl',
        typeName: 'CT_Lvl',
        propertyInfos: [{
            name: 'pt',
            minOccurs: 0,
            collection: true,
            typeInfo: '.CTStrVal'
          }]
      }, {
        localName: 'CTManualLayout',
        typeName: 'CT_ManualLayout',
        propertyInfos: [{
            name: 'layoutTarget',
            typeInfo: '.CTLayoutTarget'
          }, {
            name: 'xMode',
            typeInfo: '.CTLayoutMode'
          }, {
            name: 'yMode',
            typeInfo: '.CTLayoutMode'
          }, {
            name: 'wMode',
            typeInfo: '.CTLayoutMode'
          }, {
            name: 'hMode',
            typeInfo: '.CTLayoutMode'
          }, {
            name: 'x',
            typeInfo: '.CTDouble'
          }, {
            name: 'y',
            typeInfo: '.CTDouble'
          }, {
            name: 'w',
            typeInfo: '.CTDouble'
          }, {
            name: 'h',
            typeInfo: '.CTDouble'
          }, {
            name: 'extLst',
            typeInfo: '.CTExtensionList'
          }]
      }, {
        localName: 'CTMarker',
        typeName: 'CT_Marker',
        propertyInfos: [{
            name: 'symbol',
            typeInfo: '.CTMarkerStyle'
          }, {
            name: 'size',
            typeInfo: '.CTMarkerSize'
          }, {
            name: 'spPr',
            typeInfo: 'org_docx4j_dml.CTShapeProperties'
          }, {
            name: 'extLst',
            typeInfo: '.CTExtensionList'
          }]
      }, {
        localName: 'CTMarkerSize',
        typeName: 'CT_MarkerSize',
        propertyInfos: [{
            name: 'val',
            typeInfo: 'UnsignedByte',
            defaultValue: 5,
            attributeName: {
              localPart: 'val'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'CTMarkerStyle',
        typeName: 'CT_MarkerStyle',
        propertyInfos: [{
            name: 'val',
            required: true,
            typeInfo: '.STMarkerStyle',
            attributeName: {
              localPart: 'val'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'CTMultiLvlStrData',
        typeName: 'CT_MultiLvlStrData',
        propertyInfos: [{
            name: 'ptCount',
            typeInfo: '.CTUnsignedInt'
          }, {
            name: 'lvl',
            minOccurs: 0,
            collection: true,
            typeInfo: '.CTLvl'
          }, {
            name: 'extLst',
            typeInfo: '.CTExtensionList'
          }]
      }, {
        localName: 'CTMultiLvlStrRef',
        typeName: 'CT_MultiLvlStrRef',
        propertyInfos: [{
            name: 'f',
            required: true
          }, {
            name: 'multiLvlStrCache',
            typeInfo: '.CTMultiLvlStrData'
          }, {
            name: 'extLst',
            typeInfo: '.CTExtensionList'
          }]
      }, {
        localName: 'CTNumData',
        typeName: 'CT_NumData',
        propertyInfos: [{
            name: 'formatCode'
          }, {
            name: 'ptCount',
            typeInfo: '.CTUnsignedInt'
          }, {
            name: 'pt',
            minOccurs: 0,
            collection: true,
            typeInfo: '.CTNumVal'
          }, {
            name: 'extLst',
            typeInfo: '.CTExtensionList'
          }]
      }, {
        localName: 'CTNumDataSource',
        typeName: 'CT_NumDataSource',
        propertyInfos: [{
            name: 'numRef',
            required: true,
            typeInfo: '.CTNumRef'
          }, {
            name: 'numLit',
            required: true,
            typeInfo: '.CTNumData'
          }]
      }, {
        localName: 'CTNumFmt',
        typeName: 'CT_NumFmt',
        propertyInfos: [{
            name: 'formatCode',
            required: true,
            attributeName: {
              localPart: 'formatCode'
            },
            type: 'attribute'
          }, {
            name: 'sourceLinked',
            typeInfo: 'Boolean',
            attributeName: {
              localPart: 'sourceLinked'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'CTNumRef',
        typeName: 'CT_NumRef',
        propertyInfos: [{
            name: 'f',
            required: true
          }, {
            name: 'numCache',
            typeInfo: '.CTNumData'
          }, {
            name: 'extLst',
            typeInfo: '.CTExtensionList'
          }]
      }, {
        localName: 'CTNumVal',
        typeName: 'CT_NumVal',
        propertyInfos: [{
            name: 'v',
            required: true
          }, {
            name: 'formatCode',
            attributeName: {
              localPart: 'formatCode'
            },
            type: 'attribute'
          }, {
            name: 'idx',
            required: true,
            typeInfo: 'UnsignedInt',
            attributeName: {
              localPart: 'idx'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'CTOfPieChart',
        typeName: 'CT_OfPieChart',
        propertyInfos: [{
            name: 'ofPieType',
            required: true,
            typeInfo: '.CTOfPieType'
          }, {
            name: 'varyColors',
            typeInfo: '.CTBoolean'
          }, {
            name: 'ser',
            minOccurs: 0,
            collection: true,
            typeInfo: '.CTPieSer'
          }, {
            name: 'dLbls',
            typeInfo: '.CTDLbls'
          }, {
            name: 'gapWidth',
            typeInfo: '.CTGapAmount'
          }, {
            name: 'splitType',
            typeInfo: '.CTSplitType'
          }, {
            name: 'splitPos',
            typeInfo: '.CTDouble'
          }, {
            name: 'custSplit',
            typeInfo: '.CTCustSplit'
          }, {
            name: 'secondPieSize',
            typeInfo: '.CTSecondPieSize'
          }, {
            name: 'serLines',
            minOccurs: 0,
            collection: true,
            typeInfo: '.CTChartLines'
          }, {
            name: 'extLst',
            typeInfo: '.CTExtensionList'
          }]
      }, {
        localName: 'CTOfPieType',
        typeName: 'CT_OfPieType',
        propertyInfos: [{
            name: 'val',
            typeInfo: '.STOfPieType',
            defaultValue: 'pie',
            attributeName: {
              localPart: 'val'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'CTOrder',
        typeName: 'CT_Order',
        propertyInfos: [{
            name: 'val',
            typeInfo: 'UnsignedByte',
            defaultValue: 2,
            attributeName: {
              localPart: 'val'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'CTOrientation',
        typeName: 'CT_Orientation',
        propertyInfos: [{
            name: 'val',
            typeInfo: '.STOrientation',
            defaultValue: 'minMax',
            attributeName: {
              localPart: 'val'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'CTOverlap',
        typeName: 'CT_Overlap',
        propertyInfos: [{
            name: 'val',
            typeInfo: 'Byte',
            defaultValue: 0,
            attributeName: {
              localPart: 'val'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'CTPageMargins',
        typeName: 'CT_PageMargins',
        propertyInfos: [{
            name: 'b',
            required: true,
            typeInfo: 'Double',
            attributeName: {
              localPart: 'b'
            },
            type: 'attribute'
          }, {
            name: 'footer',
            required: true,
            typeInfo: 'Double',
            attributeName: {
              localPart: 'footer'
            },
            type: 'attribute'
          }, {
            name: 'header',
            required: true,
            typeInfo: 'Double',
            attributeName: {
              localPart: 'header'
            },
            type: 'attribute'
          }, {
            name: 'l',
            required: true,
            typeInfo: 'Double',
            attributeName: {
              localPart: 'l'
            },
            type: 'attribute'
          }, {
            name: 'r',
            required: true,
            typeInfo: 'Double',
            attributeName: {
              localPart: 'r'
            },
            type: 'attribute'
          }, {
            name: 't',
            required: true,
            typeInfo: 'Double',
            attributeName: {
              localPart: 't'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'CTPageSetup',
        typeName: 'CT_PageSetup',
        propertyInfos: [{
            name: 'blackAndWhite',
            typeInfo: 'Boolean',
            defaultValue: false,
            attributeName: {
              localPart: 'blackAndWhite'
            },
            type: 'attribute'
          }, {
            name: 'copies',
            typeInfo: 'UnsignedInt',
            defaultValue: 1,
            attributeName: {
              localPart: 'copies'
            },
            type: 'attribute'
          }, {
            name: 'draft',
            typeInfo: 'Boolean',
            defaultValue: false,
            attributeName: {
              localPart: 'draft'
            },
            type: 'attribute'
          }, {
            name: 'firstPageNumber',
            typeInfo: 'UnsignedInt',
            defaultValue: 1,
            attributeName: {
              localPart: 'firstPageNumber'
            },
            type: 'attribute'
          }, {
            name: 'horizontalDpi',
            typeInfo: 'Int',
            defaultValue: 600,
            attributeName: {
              localPart: 'horizontalDpi'
            },
            type: 'attribute'
          }, {
            name: 'orientation',
            typeInfo: '.STPageSetupOrientation',
            defaultValue: 'default',
            attributeName: {
              localPart: 'orientation'
            },
            type: 'attribute'
          }, {
            name: 'paperSize',
            typeInfo: 'UnsignedInt',
            defaultValue: 1,
            attributeName: {
              localPart: 'paperSize'
            },
            type: 'attribute'
          }, {
            name: 'useFirstPageNumber',
            typeInfo: 'Boolean',
            defaultValue: false,
            attributeName: {
              localPart: 'useFirstPageNumber'
            },
            type: 'attribute'
          }, {
            name: 'verticalDpi',
            typeInfo: 'Int',
            defaultValue: 600,
            attributeName: {
              localPart: 'verticalDpi'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'CTPeriod',
        typeName: 'CT_Period',
        propertyInfos: [{
            name: 'val',
            typeInfo: 'UnsignedByte',
            defaultValue: 2,
            attributeName: {
              localPart: 'val'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'CTPerspective',
        typeName: 'CT_Perspective',
        propertyInfos: [{
            name: 'val',
            typeInfo: 'UnsignedByte',
            defaultValue: 30,
            attributeName: {
              localPart: 'val'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'CTPictureFormat',
        typeName: 'CT_PictureFormat',
        propertyInfos: [{
            name: 'val',
            required: true,
            typeInfo: '.STPictureFormat',
            attributeName: {
              localPart: 'val'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'CTPictureOptions',
        typeName: 'CT_PictureOptions',
        propertyInfos: [{
            name: 'applyToFront',
            typeInfo: '.CTBoolean'
          }, {
            name: 'applyToSides',
            typeInfo: '.CTBoolean'
          }, {
            name: 'applyToEnd',
            typeInfo: '.CTBoolean'
          }, {
            name: 'pictureFormat',
            typeInfo: '.CTPictureFormat'
          }, {
            name: 'pictureStackUnit',
            typeInfo: '.CTPictureStackUnit'
          }]
      }, {
        localName: 'CTPictureStackUnit',
        typeName: 'CT_PictureStackUnit',
        propertyInfos: [{
            name: 'val',
            required: true,
            typeInfo: 'Double',
            attributeName: {
              localPart: 'val'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'CTPie3DChart',
        typeName: 'CT_Pie3DChart',
        propertyInfos: [{
            name: 'varyColors',
            typeInfo: '.CTBoolean'
          }, {
            name: 'ser',
            minOccurs: 0,
            collection: true,
            typeInfo: '.CTPieSer'
          }, {
            name: 'dLbls',
            typeInfo: '.CTDLbls'
          }, {
            name: 'extLst',
            typeInfo: '.CTExtensionList'
          }]
      }, {
        localName: 'CTPieChart',
        typeName: 'CT_PieChart',
        propertyInfos: [{
            name: 'varyColors',
            typeInfo: '.CTBoolean'
          }, {
            name: 'ser',
            minOccurs: 0,
            collection: true,
            typeInfo: '.CTPieSer'
          }, {
            name: 'dLbls',
            typeInfo: '.CTDLbls'
          }, {
            name: 'firstSliceAng',
            typeInfo: '.CTFirstSliceAng'
          }, {
            name: 'extLst',
            typeInfo: '.CTExtensionList'
          }]
      }, {
        localName: 'CTPieSer',
        typeName: 'CT_PieSer',
        propertyInfos: [{
            name: 'idx',
            required: true,
            typeInfo: '.CTUnsignedInt'
          }, {
            name: 'order',
            required: true,
            typeInfo: '.CTUnsignedInt'
          }, {
            name: 'tx',
            typeInfo: '.CTSerTx'
          }, {
            name: 'spPr',
            typeInfo: 'org_docx4j_dml.CTShapeProperties'
          }, {
            name: 'explosion',
            typeInfo: '.CTUnsignedInt'
          }, {
            name: 'dPt',
            minOccurs: 0,
            collection: true,
            typeInfo: '.CTDPt'
          }, {
            name: 'dLbls',
            typeInfo: '.CTDLbls'
          }, {
            name: 'cat',
            typeInfo: '.CTAxDataSource'
          }, {
            name: 'val',
            typeInfo: '.CTNumDataSource'
          }, {
            name: 'extLst',
            typeInfo: '.CTExtensionList'
          }]
      }, {
        localName: 'CTPivotFmt',
        typeName: 'CT_PivotFmt',
        propertyInfos: [{
            name: 'idx',
            required: true,
            typeInfo: '.CTUnsignedInt'
          }, {
            name: 'spPr',
            typeInfo: 'org_docx4j_dml.CTShapeProperties'
          }, {
            name: 'txPr',
            typeInfo: 'org_docx4j_dml.CTTextBody'
          }, {
            name: 'marker',
            typeInfo: '.CTMarker'
          }, {
            name: 'dLbl',
            typeInfo: '.CTDLbl'
          }, {
            name: 'extLst',
            typeInfo: '.CTExtensionList'
          }]
      }, {
        localName: 'CTPivotFmts',
        typeName: 'CT_PivotFmts',
        propertyInfos: [{
            name: 'pivotFmt',
            minOccurs: 0,
            collection: true,
            typeInfo: '.CTPivotFmt'
          }]
      }, {
        localName: 'CTPivotSource',
        typeName: 'CT_PivotSource',
        propertyInfos: [{
            name: 'name',
            required: true
          }, {
            name: 'fmtId',
            required: true,
            typeInfo: '.CTUnsignedInt'
          }, {
            name: 'extLst',
            minOccurs: 0,
            collection: true,
            typeInfo: '.CTExtensionList'
          }]
      }, {
        localName: 'CTPlotArea',
        typeName: 'CT_PlotArea',
        propertyInfos: [{
            name: 'layout',
            typeInfo: '.CTLayout'
          }, {
            name: 'areaChartOrArea3DChartOrLineChart',
            required: true,
            collection: true,
            elementTypeInfos: [{
                elementName: 'areaChart',
                typeInfo: '.CTAreaChart'
              }, {
                elementName: 'area3DChart',
                typeInfo: '.CTArea3DChart'
              }, {
                elementName: 'lineChart',
                typeInfo: '.CTLineChart'
              }, {
                elementName: 'line3DChart',
                typeInfo: '.CTLine3DChart'
              }, {
                elementName: 'stockChart',
                typeInfo: '.CTStockChart'
              }, {
                elementName: 'radarChart',
                typeInfo: '.CTRadarChart'
              }, {
                elementName: 'scatterChart',
                typeInfo: '.CTScatterChart'
              }, {
                elementName: 'pieChart',
                typeInfo: '.CTPieChart'
              }, {
                elementName: 'pie3DChart',
                typeInfo: '.CTPie3DChart'
              }, {
                elementName: 'doughnutChart',
                typeInfo: '.CTDoughnutChart'
              }, {
                elementName: 'barChart',
                typeInfo: '.CTBarChart'
              }, {
                elementName: 'bar3DChart',
                typeInfo: '.CTBar3DChart'
              }, {
                elementName: 'ofPieChart',
                typeInfo: '.CTOfPieChart'
              }, {
                elementName: 'surfaceChart',
                typeInfo: '.CTSurfaceChart'
              }, {
                elementName: 'surface3DChart',
                typeInfo: '.CTSurface3DChart'
              }, {
                elementName: 'bubbleChart',
                typeInfo: '.CTBubbleChart'
              }],
            type: 'elements'
          }, {
            name: 'valAxOrCatAxOrDateAx',
            minOccurs: 0,
            collection: true,
            elementTypeInfos: [{
                elementName: 'valAx',
                typeInfo: '.CTValAx'
              }, {
                elementName: 'catAx',
                typeInfo: '.CTCatAx'
              }, {
                elementName: 'dateAx',
                typeInfo: '.CTDateAx'
              }, {
                elementName: 'serAx',
                typeInfo: '.CTSerAx'
              }],
            type: 'elements'
          }, {
            name: 'dTable',
            typeInfo: '.CTDTable'
          }, {
            name: 'spPr',
            typeInfo: 'org_docx4j_dml.CTShapeProperties'
          }, {
            name: 'extLst',
            typeInfo: '.CTExtensionList'
          }]
      }, {
        localName: 'CTPrintSettings',
        typeName: 'CT_PrintSettings',
        propertyInfos: [{
            name: 'headerFooter',
            typeInfo: '.CTHeaderFooter'
          }, {
            name: 'pageMargins',
            typeInfo: '.CTPageMargins'
          }, {
            name: 'pageSetup',
            typeInfo: '.CTPageSetup'
          }, {
            name: 'legacyDrawingHF',
            typeInfo: '.CTRelId'
          }]
      }, {
        localName: 'CTProtection',
        typeName: 'CT_Protection',
        propertyInfos: [{
            name: 'chartObject',
            typeInfo: '.CTBoolean'
          }, {
            name: 'data',
            typeInfo: '.CTBoolean'
          }, {
            name: 'formatting',
            typeInfo: '.CTBoolean'
          }, {
            name: 'selection',
            typeInfo: '.CTBoolean'
          }, {
            name: 'userInterface',
            typeInfo: '.CTBoolean'
          }]
      }, {
        localName: 'CTRadarChart',
        typeName: 'CT_RadarChart',
        propertyInfos: [{
            name: 'radarStyle',
            required: true,
            typeInfo: '.CTRadarStyle'
          }, {
            name: 'varyColors',
            typeInfo: '.CTBoolean'
          }, {
            name: 'ser',
            minOccurs: 0,
            collection: true,
            typeInfo: '.CTRadarSer'
          }, {
            name: 'dLbls',
            typeInfo: '.CTDLbls'
          }, {
            name: 'axId',
            required: true,
            minOccurs: 2,
            maxOccurs: 2,
            collection: true,
            typeInfo: '.CTUnsignedInt'
          }, {
            name: 'extLst',
            typeInfo: '.CTExtensionList'
          }]
      }, {
        localName: 'CTRadarSer',
        typeName: 'CT_RadarSer',
        propertyInfos: [{
            name: 'idx',
            required: true,
            typeInfo: '.CTUnsignedInt'
          }, {
            name: 'order',
            required: true,
            typeInfo: '.CTUnsignedInt'
          }, {
            name: 'tx',
            typeInfo: '.CTSerTx'
          }, {
            name: 'spPr',
            typeInfo: 'org_docx4j_dml.CTShapeProperties'
          }, {
            name: 'marker',
            typeInfo: '.CTMarker'
          }, {
            name: 'dPt',
            minOccurs: 0,
            collection: true,
            typeInfo: '.CTDPt'
          }, {
            name: 'dLbls',
            typeInfo: '.CTDLbls'
          }, {
            name: 'cat',
            typeInfo: '.CTAxDataSource'
          }, {
            name: 'val',
            typeInfo: '.CTNumDataSource'
          }, {
            name: 'extLst',
            typeInfo: '.CTExtensionList'
          }]
      }, {
        localName: 'CTRadarStyle',
        typeName: 'CT_RadarStyle',
        propertyInfos: [{
            name: 'val',
            typeInfo: '.STRadarStyle',
            defaultValue: 'standard',
            attributeName: {
              localPart: 'val'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'CTRelId',
        typeName: 'CT_RelId',
        propertyInfos: [{
            name: 'id',
            required: true,
            attributeName: {
              localPart: 'id',
              namespaceURI: 'http:\/\/schemas.openxmlformats.org\/officeDocument\/2006\/relationships'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'CTRotX',
        typeName: 'CT_RotX',
        propertyInfos: [{
            name: 'val',
            typeInfo: 'Byte',
            defaultValue: 0,
            attributeName: {
              localPart: 'val'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'CTRotY',
        typeName: 'CT_RotY',
        propertyInfos: [{
            name: 'val',
            typeInfo: 'UnsignedShort',
            defaultValue: 0,
            attributeName: {
              localPart: 'val'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'CTScaling',
        typeName: 'CT_Scaling',
        propertyInfos: [{
            name: 'logBase',
            typeInfo: '.CTLogBase'
          }, {
            name: 'orientation',
            typeInfo: '.CTOrientation'
          }, {
            name: 'max',
            typeInfo: '.CTDouble'
          }, {
            name: 'min',
            typeInfo: '.CTDouble'
          }, {
            name: 'extLst',
            typeInfo: '.CTExtensionList'
          }]
      }, {
        localName: 'CTScatterChart',
        typeName: 'CT_ScatterChart',
        propertyInfos: [{
            name: 'scatterStyle',
            required: true,
            typeInfo: '.CTScatterStyle'
          }, {
            name: 'varyColors',
            typeInfo: '.CTBoolean'
          }, {
            name: 'ser',
            minOccurs: 0,
            collection: true,
            typeInfo: '.CTScatterSer'
          }, {
            name: 'dLbls',
            typeInfo: '.CTDLbls'
          }, {
            name: 'axId',
            required: true,
            minOccurs: 2,
            maxOccurs: 2,
            collection: true,
            typeInfo: '.CTUnsignedInt'
          }, {
            name: 'extLst',
            typeInfo: '.CTExtensionList'
          }]
      }, {
        localName: 'CTScatterSer',
        typeName: 'CT_ScatterSer',
        propertyInfos: [{
            name: 'idx',
            required: true,
            typeInfo: '.CTUnsignedInt'
          }, {
            name: 'order',
            required: true,
            typeInfo: '.CTUnsignedInt'
          }, {
            name: 'tx',
            typeInfo: '.CTSerTx'
          }, {
            name: 'spPr',
            typeInfo: 'org_docx4j_dml.CTShapeProperties'
          }, {
            name: 'marker',
            typeInfo: '.CTMarker'
          }, {
            name: 'dPt',
            minOccurs: 0,
            collection: true,
            typeInfo: '.CTDPt'
          }, {
            name: 'dLbls',
            typeInfo: '.CTDLbls'
          }, {
            name: 'trendline',
            minOccurs: 0,
            collection: true,
            typeInfo: '.CTTrendline'
          }, {
            name: 'errBars',
            minOccurs: 0,
            maxOccurs: 2,
            collection: true,
            typeInfo: '.CTErrBars'
          }, {
            name: 'xVal',
            typeInfo: '.CTAxDataSource'
          }, {
            name: 'yVal',
            typeInfo: '.CTNumDataSource'
          }, {
            name: 'smooth',
            typeInfo: '.CTBoolean'
          }, {
            name: 'extLst',
            typeInfo: '.CTExtensionList'
          }]
      }, {
        localName: 'CTScatterStyle',
        typeName: 'CT_ScatterStyle',
        propertyInfos: [{
            name: 'val',
            typeInfo: '.STScatterStyle',
            defaultValue: 'marker',
            attributeName: {
              localPart: 'val'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'CTSecondPieSize',
        typeName: 'CT_SecondPieSize',
        propertyInfos: [{
            name: 'val',
            typeInfo: 'UnsignedShort',
            defaultValue: 75,
            attributeName: {
              localPart: 'val'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'CTSerAx',
        typeName: 'CT_SerAx',
        propertyInfos: [{
            name: 'axId',
            required: true,
            typeInfo: '.CTUnsignedInt'
          }, {
            name: 'scaling',
            required: true,
            typeInfo: '.CTScaling'
          }, {
            name: 'delete',
            typeInfo: '.CTBoolean'
          }, {
            name: 'axPos',
            required: true,
            typeInfo: '.CTAxPos'
          }, {
            name: 'majorGridlines',
            typeInfo: '.CTChartLines'
          }, {
            name: 'minorGridlines',
            typeInfo: '.CTChartLines'
          }, {
            name: 'title',
            typeInfo: '.CTTitle'
          }, {
            name: 'numFmt',
            typeInfo: '.CTNumFmt'
          }, {
            name: 'majorTickMark',
            typeInfo: '.CTTickMark'
          }, {
            name: 'minorTickMark',
            typeInfo: '.CTTickMark'
          }, {
            name: 'tickLblPos',
            typeInfo: '.CTTickLblPos'
          }, {
            name: 'spPr',
            typeInfo: 'org_docx4j_dml.CTShapeProperties'
          }, {
            name: 'txPr',
            typeInfo: 'org_docx4j_dml.CTTextBody'
          }, {
            name: 'crossAx',
            required: true,
            typeInfo: '.CTUnsignedInt'
          }, {
            name: 'crosses',
            required: true,
            typeInfo: '.CTCrosses'
          }, {
            name: 'crossesAt',
            required: true,
            typeInfo: '.CTDouble'
          }, {
            name: 'tickLblSkip',
            typeInfo: '.CTSkip'
          }, {
            name: 'tickMarkSkip',
            typeInfo: '.CTSkip'
          }, {
            name: 'extLst',
            typeInfo: '.CTExtensionList'
          }]
      }, {
        localName: 'CTSerTx',
        typeName: 'CT_SerTx',
        propertyInfos: [{
            name: 'strRef',
            required: true,
            typeInfo: '.CTStrRef'
          }, {
            name: 'v',
            required: true
          }]
      }, {
        localName: 'CTShape',
        typeName: 'CT_Shape',
        propertyInfos: [{
            name: 'val',
            typeInfo: '.STShape',
            defaultValue: 'box',
            attributeName: {
              localPart: 'val'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'CTSizeRepresents',
        typeName: 'CT_SizeRepresents',
        propertyInfos: [{
            name: 'val',
            typeInfo: '.STSizeRepresents',
            defaultValue: 'area',
            attributeName: {
              localPart: 'val'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'CTSkip',
        typeName: 'CT_Skip',
        propertyInfos: [{
            name: 'val',
            required: true,
            typeInfo: 'UnsignedShort',
            attributeName: {
              localPart: 'val'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'CTSplitType',
        typeName: 'CT_SplitType',
        propertyInfos: [{
            name: 'val',
            typeInfo: '.STSplitType',
            defaultValue: 'auto',
            attributeName: {
              localPart: 'val'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'CTStockChart',
        typeName: 'CT_StockChart',
        propertyInfos: [{
            name: 'ser',
            required: true,
            minOccurs: 3,
            maxOccurs: 4,
            collection: true,
            typeInfo: '.CTLineSer'
          }, {
            name: 'dLbls',
            typeInfo: '.CTDLbls'
          }, {
            name: 'dropLines',
            typeInfo: '.CTChartLines'
          }, {
            name: 'hiLowLines',
            typeInfo: '.CTChartLines'
          }, {
            name: 'upDownBars',
            typeInfo: '.CTUpDownBars'
          }, {
            name: 'axId',
            required: true,
            minOccurs: 2,
            maxOccurs: 2,
            collection: true,
            typeInfo: '.CTUnsignedInt'
          }, {
            name: 'extLst',
            typeInfo: '.CTExtensionList'
          }]
      }, {
        localName: 'CTStrData',
        typeName: 'CT_StrData',
        propertyInfos: [{
            name: 'ptCount',
            typeInfo: '.CTUnsignedInt'
          }, {
            name: 'pt',
            minOccurs: 0,
            collection: true,
            typeInfo: '.CTStrVal'
          }, {
            name: 'extLst',
            typeInfo: '.CTExtensionList'
          }]
      }, {
        localName: 'CTStrRef',
        typeName: 'CT_StrRef',
        propertyInfos: [{
            name: 'f',
            required: true
          }, {
            name: 'strCache',
            typeInfo: '.CTStrData'
          }, {
            name: 'extLst',
            typeInfo: '.CTExtensionList'
          }]
      }, {
        localName: 'CTStrVal',
        typeName: 'CT_StrVal',
        propertyInfos: [{
            name: 'v',
            required: true
          }, {
            name: 'idx',
            required: true,
            typeInfo: 'UnsignedInt',
            attributeName: {
              localPart: 'idx'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'CTStyle',
        typeName: 'CT_Style',
        propertyInfos: [{
            name: 'val',
            required: true,
            typeInfo: 'UnsignedByte',
            attributeName: {
              localPart: 'val'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'CTSurface',
        typeName: 'CT_Surface',
        propertyInfos: [{
            name: 'thickness',
            typeInfo: '.CTUnsignedInt'
          }, {
            name: 'spPr',
            typeInfo: 'org_docx4j_dml.CTShapeProperties'
          }, {
            name: 'pictureOptions',
            typeInfo: '.CTPictureOptions'
          }, {
            name: 'extLst',
            typeInfo: '.CTExtensionList'
          }]
      }, {
        localName: 'CTSurface3DChart',
        typeName: 'CT_Surface3DChart',
        propertyInfos: [{
            name: 'wireframe',
            typeInfo: '.CTBoolean'
          }, {
            name: 'ser',
            minOccurs: 0,
            collection: true,
            typeInfo: '.CTSurfaceSer'
          }, {
            name: 'bandFmts',
            typeInfo: '.CTBandFmts'
          }, {
            name: 'axId',
            required: true,
            minOccurs: 3,
            maxOccurs: 3,
            collection: true,
            typeInfo: '.CTUnsignedInt'
          }, {
            name: 'extLst',
            typeInfo: '.CTExtensionList'
          }]
      }, {
        localName: 'CTSurfaceChart',
        typeName: 'CT_SurfaceChart',
        propertyInfos: [{
            name: 'wireframe',
            typeInfo: '.CTBoolean'
          }, {
            name: 'ser',
            minOccurs: 0,
            collection: true,
            typeInfo: '.CTSurfaceSer'
          }, {
            name: 'bandFmts',
            typeInfo: '.CTBandFmts'
          }, {
            name: 'axId',
            required: true,
            minOccurs: 2,
            maxOccurs: 3,
            collection: true,
            typeInfo: '.CTUnsignedInt'
          }, {
            name: 'extLst',
            typeInfo: '.CTExtensionList'
          }]
      }, {
        localName: 'CTSurfaceSer',
        typeName: 'CT_SurfaceSer',
        propertyInfos: [{
            name: 'idx',
            required: true,
            typeInfo: '.CTUnsignedInt'
          }, {
            name: 'order',
            required: true,
            typeInfo: '.CTUnsignedInt'
          }, {
            name: 'tx',
            typeInfo: '.CTSerTx'
          }, {
            name: 'spPr',
            typeInfo: 'org_docx4j_dml.CTShapeProperties'
          }, {
            name: 'cat',
            typeInfo: '.CTAxDataSource'
          }, {
            name: 'val',
            typeInfo: '.CTNumDataSource'
          }, {
            name: 'extLst',
            typeInfo: '.CTExtensionList'
          }]
      }, {
        localName: 'CTTextLanguageID',
        typeName: 'CT_TextLanguageID',
        propertyInfos: [{
            name: 'val',
            required: true,
            attributeName: {
              localPart: 'val'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'CTTickLblPos',
        typeName: 'CT_TickLblPos',
        propertyInfos: [{
            name: 'val',
            typeInfo: '.STTickLblPos',
            defaultValue: 'nextTo',
            attributeName: {
              localPart: 'val'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'CTTickMark',
        typeName: 'CT_TickMark',
        propertyInfos: [{
            name: 'val',
            typeInfo: '.STTickMark',
            defaultValue: 'cross',
            attributeName: {
              localPart: 'val'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'CTTimeUnit',
        typeName: 'CT_TimeUnit',
        propertyInfos: [{
            name: 'val',
            typeInfo: '.STTimeUnit',
            defaultValue: 'days',
            attributeName: {
              localPart: 'val'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'CTTitle',
        typeName: 'CT_Title',
        propertyInfos: [{
            name: 'tx',
            typeInfo: '.CTTx'
          }, {
            name: 'layout',
            typeInfo: '.CTLayout'
          }, {
            name: 'overlay',
            typeInfo: '.CTBoolean'
          }, {
            name: 'spPr',
            typeInfo: 'org_docx4j_dml.CTShapeProperties'
          }, {
            name: 'txPr',
            typeInfo: 'org_docx4j_dml.CTTextBody'
          }, {
            name: 'extLst',
            typeInfo: '.CTExtensionList'
          }]
      }, {
        localName: 'CTTrendline',
        typeName: 'CT_Trendline',
        propertyInfos: [{
            name: 'name'
          }, {
            name: 'spPr',
            typeInfo: 'org_docx4j_dml.CTShapeProperties'
          }, {
            name: 'trendlineType',
            required: true,
            typeInfo: '.CTTrendlineType'
          }, {
            name: 'order',
            typeInfo: '.CTOrder'
          }, {
            name: 'period',
            typeInfo: '.CTPeriod'
          }, {
            name: 'forward',
            typeInfo: '.CTDouble'
          }, {
            name: 'backward',
            typeInfo: '.CTDouble'
          }, {
            name: 'intercept',
            typeInfo: '.CTDouble'
          }, {
            name: 'dispRSqr',
            typeInfo: '.CTBoolean'
          }, {
            name: 'dispEq',
            typeInfo: '.CTBoolean'
          }, {
            name: 'trendlineLbl',
            typeInfo: '.CTTrendlineLbl'
          }, {
            name: 'extLst',
            typeInfo: '.CTExtensionList'
          }]
      }, {
        localName: 'CTTrendlineLbl',
        typeName: 'CT_TrendlineLbl',
        propertyInfos: [{
            name: 'layout',
            typeInfo: '.CTLayout'
          }, {
            name: 'tx',
            typeInfo: '.CTTx'
          }, {
            name: 'numFmt',
            typeInfo: '.CTNumFmt'
          }, {
            name: 'spPr',
            typeInfo: 'org_docx4j_dml.CTShapeProperties'
          }, {
            name: 'txPr',
            typeInfo: 'org_docx4j_dml.CTTextBody'
          }, {
            name: 'extLst',
            typeInfo: '.CTExtensionList'
          }]
      }, {
        localName: 'CTTrendlineType',
        typeName: 'CT_TrendlineType',
        propertyInfos: [{
            name: 'val',
            typeInfo: '.STTrendlineType',
            defaultValue: 'linear',
            attributeName: {
              localPart: 'val'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'CTTx',
        typeName: 'CT_Tx',
        propertyInfos: [{
            name: 'strRef',
            required: true,
            typeInfo: '.CTStrRef'
          }, {
            name: 'rich',
            required: true,
            typeInfo: 'org_docx4j_dml.CTTextBody'
          }]
      }, {
        localName: 'CTUnsignedInt',
        typeName: 'CT_UnsignedInt',
        propertyInfos: [{
            name: 'val',
            required: true,
            typeInfo: 'UnsignedInt',
            attributeName: {
              localPart: 'val'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'CTUpDownBar',
        typeName: 'CT_UpDownBar',
        propertyInfos: [{
            name: 'spPr',
            typeInfo: 'org_docx4j_dml.CTShapeProperties'
          }]
      }, {
        localName: 'CTUpDownBars',
        typeName: 'CT_UpDownBars',
        propertyInfos: [{
            name: 'gapWidth',
            typeInfo: '.CTGapAmount'
          }, {
            name: 'upBars',
            typeInfo: '.CTUpDownBar'
          }, {
            name: 'downBars',
            typeInfo: '.CTUpDownBar'
          }, {
            name: 'extLst',
            typeInfo: '.CTExtensionList'
          }]
      }, {
        localName: 'CTValAx',
        typeName: 'CT_ValAx',
        propertyInfos: [{
            name: 'axId',
            required: true,
            typeInfo: '.CTUnsignedInt'
          }, {
            name: 'scaling',
            required: true,
            typeInfo: '.CTScaling'
          }, {
            name: 'delete',
            typeInfo: '.CTBoolean'
          }, {
            name: 'axPos',
            required: true,
            typeInfo: '.CTAxPos'
          }, {
            name: 'majorGridlines',
            typeInfo: '.CTChartLines'
          }, {
            name: 'minorGridlines',
            typeInfo: '.CTChartLines'
          }, {
            name: 'title',
            typeInfo: '.CTTitle'
          }, {
            name: 'numFmt',
            typeInfo: '.CTNumFmt'
          }, {
            name: 'majorTickMark',
            typeInfo: '.CTTickMark'
          }, {
            name: 'minorTickMark',
            typeInfo: '.CTTickMark'
          }, {
            name: 'tickLblPos',
            typeInfo: '.CTTickLblPos'
          }, {
            name: 'spPr',
            typeInfo: 'org_docx4j_dml.CTShapeProperties'
          }, {
            name: 'txPr',
            typeInfo: 'org_docx4j_dml.CTTextBody'
          }, {
            name: 'crossAx',
            required: true,
            typeInfo: '.CTUnsignedInt'
          }, {
            name: 'crosses',
            required: true,
            typeInfo: '.CTCrosses'
          }, {
            name: 'crossesAt',
            required: true,
            typeInfo: '.CTDouble'
          }, {
            name: 'crossBetween',
            typeInfo: '.CTCrossBetween'
          }, {
            name: 'majorUnit',
            typeInfo: '.CTAxisUnit'
          }, {
            name: 'minorUnit',
            typeInfo: '.CTAxisUnit'
          }, {
            name: 'dispUnits',
            typeInfo: '.CTDispUnits'
          }, {
            name: 'extLst',
            typeInfo: '.CTExtensionList'
          }]
      }, {
        localName: 'CTView3D',
        typeName: 'CT_View3D',
        propertyInfos: [{
            name: 'rotX',
            typeInfo: '.CTRotX'
          }, {
            name: 'hPercent',
            typeInfo: '.CTHPercent'
          }, {
            name: 'rotY',
            typeInfo: '.CTRotY'
          }, {
            name: 'depthPercent',
            typeInfo: '.CTDepthPercent'
          }, {
            name: 'rAngAx',
            typeInfo: '.CTBoolean'
          }, {
            name: 'perspective',
            typeInfo: '.CTPerspective'
          }, {
            name: 'extLst',
            typeInfo: '.CTExtensionList'
          }]
      }, {
        type: 'enumInfo',
        localName: 'STAxPos',
        values: ['b', 'l', 'r', 't']
      }, {
        type: 'enumInfo',
        localName: 'STBarDir',
        values: ['bar', 'col']
      }, {
        type: 'enumInfo',
        localName: 'STBarGrouping',
        values: ['percentStacked', 'clustered', 'standard', 'stacked']
      }, {
        type: 'enumInfo',
        localName: 'STBuiltInUnit',
        values: ['hundreds', 'thousands', 'tenThousands', 'hundredThousands', 'millions', 'tenMillions', 'hundredMillions', 'billions', 'trillions']
      }, {
        type: 'enumInfo',
        localName: 'STCrossBetween',
        values: ['between', 'midCat']
      }, {
        type: 'enumInfo',
        localName: 'STCrosses',
        values: ['autoZero', 'max', 'min']
      }, {
        type: 'enumInfo',
        localName: 'STDLblPos',
        values: ['bestFit', 'b', 'ctr', 'inBase', 'inEnd', 'l', 'outEnd', 'r', 't']
      }, {
        type: 'enumInfo',
        localName: 'STDispBlanksAs',
        values: ['span', 'gap', 'zero']
      }, {
        type: 'enumInfo',
        localName: 'STErrBarType',
        values: ['both', 'minus', 'plus']
      }, {
        type: 'enumInfo',
        localName: 'STErrDir',
        values: ['x', 'y']
      }, {
        type: 'enumInfo',
        localName: 'STErrValType',
        values: ['cust', 'fixedVal', 'percentage', 'stdDev', 'stdErr']
      }, {
        type: 'enumInfo',
        localName: 'STGrouping',
        values: ['percentStacked', 'standard', 'stacked']
      }, {
        type: 'enumInfo',
        localName: 'STLayoutMode',
        values: ['edge', 'factor']
      }, {
        type: 'enumInfo',
        localName: 'STLayoutTarget',
        values: ['inner', 'outer']
      }, {
        type: 'enumInfo',
        localName: 'STLblAlgn',
        values: ['ctr', 'l', 'r']
      }, {
        type: 'enumInfo',
        localName: 'STLegendPos',
        values: ['b', 'tr', 'l', 'r', 't']
      }, {
        type: 'enumInfo',
        localName: 'STMarkerStyle',
        values: ['circle', 'dash', 'diamond', 'dot', 'none', 'picture', 'plus', 'square', 'star', 'triangle', 'x']
      }, {
        type: 'enumInfo',
        localName: 'STOfPieType',
        values: ['pie', 'bar']
      }, {
        type: 'enumInfo',
        localName: 'STOrientation',
        values: ['maxMin', 'minMax']
      }, {
        type: 'enumInfo',
        localName: 'STPageSetupOrientation',
        values: ['default', 'portrait', 'landscape']
      }, {
        type: 'enumInfo',
        localName: 'STPictureFormat',
        values: ['stretch', 'stack', 'stackScale']
      }, {
        type: 'enumInfo',
        localName: 'STRadarStyle',
        values: ['standard', 'marker', 'filled']
      }, {
        type: 'enumInfo',
        localName: 'STScatterStyle',
        values: ['none', 'line', 'lineMarker', 'marker', 'smooth', 'smoothMarker']
      }, {
        type: 'enumInfo',
        localName: 'STShape',
        values: ['cone', 'coneToMax', 'box', 'cylinder', 'pyramid', 'pyramidToMax']
      }, {
        type: 'enumInfo',
        localName: 'STSizeRepresents',
        values: ['area', 'w']
      }, {
        type: 'enumInfo',
        localName: 'STSplitType',
        values: ['auto', 'cust', 'percent', 'pos', 'val']
      }, {
        type: 'enumInfo',
        localName: 'STTickLblPos',
        values: ['high', 'low', 'nextTo', 'none']
      }, {
        type: 'enumInfo',
        localName: 'STTickMark',
        values: ['cross', 'in', 'none', 'out']
      }, {
        type: 'enumInfo',
        localName: 'STTimeUnit',
        values: ['days', 'months', 'years']
      }, {
        type: 'enumInfo',
        localName: 'STTrendlineType',
        values: ['exp', 'linear', 'log', 'movingAvg', 'poly', 'power']
      }],
    elementInfos: [{
        typeInfo: '.CTRelId',
        elementName: 'chart'
      }, {
        typeInfo: '.CTChartSpace',
        elementName: 'chartSpace'
      }, {
        typeInfo: 'org_docx4j_dml_chartDrawing.CTDrawing',
        elementName: 'userShapes'
      }]
  };
  return {
    org_docx4j_dml_chart: org_docx4j_dml_chart
  };
};
if (typeof define === 'function' && define.amd) {
  define([], org_docx4j_dml_chart_Module_Factory);
}
else {
  var org_docx4j_dml_chart_Module = org_docx4j_dml_chart_Module_Factory();
  if (typeof module !== 'undefined' && module.exports) {
    module.exports.org_docx4j_dml_chart = org_docx4j_dml_chart_Module.org_docx4j_dml_chart;
  }
  else {
    var org_docx4j_dml_chart = org_docx4j_dml_chart_Module.org_docx4j_dml_chart;
  }
}