// Generated by jsonix-schema-compiler: TypeScript declarations for the Jsonix module [org_docx4j_docProps_custom]. Do not edit.
// Describes the objects Jsonix produces when unmarshalling with this module's mappings.
import type * as Dep_org_docx4j_docProps_variantTypes from './org_docx4j_docProps_variantTypes';

/** Jsonix.XML.QName */
export interface XmlQName { namespaceURI: string; localPart: string; prefix?: string; key?: string; string?: string; }
/** Jsonix.XML.Calendar: the representation of date, time and dateTime values; unset fields are NaN. */
export interface XmlCalendar { year?: number; month?: number; day?: number; hour?: number; minute?: number; second?: number; fractionalSecond?: number; timezone?: number; }
/** The representation of xs:duration values. */
export interface XmlDuration { sign?: number; years?: number; months?: number; days?: number; hours?: number; minutes?: number; seconds?: number; }
/** An element as returned by an unmarshaller or held by an elementRef property. */
export interface TypedNamedValue<T> { name: XmlQName; value: T; }
/** A DOM node, allowed where the mapping permits DOM content (allowDom). */
export type XmlDomNode = any;
/** The value of an anyElement property: a typed element, a DOM node or (if mixed) text. */
export type XmlAnyElement = any;
/** The value of an anyAttribute property. */
export interface XmlAnyAttributes { [attributeName: string]: string; }
/** A Jsonix mapping object as consumed by new Jsonix.Context([...]); R is the union of its global element types. */
export interface JsonixMapping<R = unknown> { readonly __rootElement?: R; readonly [key: string]: unknown; }

export interface Properties {
  TYPE_NAME?: 'org_docx4j_docProps_custom.Properties';
  property?: Properties.Property[];
}

export type PropertiesElement = TypedNamedValue<Properties>;

/** Any global element of this mapping, i.e. what an unmarshaller returns. */
export type RootElement = PropertiesElement;

export namespace Properties {
  export interface Property {
    TYPE_NAME?: 'org_docx4j_docProps_custom.Properties.Property';
    readonly PARENT?: Properties;
    vector: Dep_org_docx4j_docProps_variantTypes.Vector;
    array: Dep_org_docx4j_docProps_variantTypes.Array;
    blob: string;
    oblob: string;
    empty: Dep_org_docx4j_docProps_variantTypes.Empty;
    _null: Dep_org_docx4j_docProps_variantTypes.Null;
    i1: number;
    i2: number;
    i4: number;
    i8: number;
    _int: number;
    ui1: number;
    ui2: number;
    ui4: number;
    ui8: number;
    uint: number;
    r4: number;
    r8: number;
    decimal: number;
    lpstr: string;
    lpwstr: string;
    bstr: string;
    date: XmlCalendar;
    filetime: XmlCalendar;
    bool: boolean;
    cy: string;
    error: string;
    stream: string;
    ostream: string;
    storage: string;
    ostorage: string;
    vstream: Dep_org_docx4j_docProps_variantTypes.Vstream;
    clsid: string;
    cf: Dep_org_docx4j_docProps_variantTypes.Cf;
    fmtid: string;
    pid: number;
    name?: string;
    linkTarget?: string;
  }
}

/** The Jsonix mapping [org_docx4j_docProps_custom] exported by the module's JavaScript file. */
export declare const org_docx4j_docProps_custom: JsonixMapping<RootElement>;
