// Generated by jsonix-schema-compiler: TypeScript declarations for the Jsonix module [org_docx4j_vml]. Do not edit.
// Describes the objects Jsonix produces when unmarshalling with this module's mappings.
import type * as Dep_org_docx4j_vml_officedrawing from './org_docx4j_vml_officedrawing';
import type * as Dep_org_docx4j_vml_wordprocessingDrawing from './org_docx4j_vml_wordprocessingDrawing';
import type * as Dep_org_docx4j_vml_spreadsheetDrawing from './org_docx4j_vml_spreadsheetDrawing';
import type * as Dep_org_docx4j_vml_presentationDrawing from './org_docx4j_vml_presentationDrawing';
import type * as Dep_org_docx4j_wml from './org_docx4j_wml';

/** Jsonix.XML.QName */
export interface XmlQName { namespaceURI: string; localPart: string; prefix?: string; key?: string; string?: string; }
/** Jsonix.XML.Calendar: the representation of date, time and dateTime values; unset fields are NaN. */
export interface XmlCalendar { year?: number; month?: number; day?: number; hour?: number; minute?: number; second?: number; fractionalSecond?: number; timezone?: number; }
/** The representation of xs:duration values. */
export interface XmlDuration { sign?: number; years?: number; months?: number; days?: number; hours?: number; minutes?: number; seconds?: number; }
/** An element as returned by an unmarshaller or held by an elementRef property. */
export interface TypedNamedValue<T> { name: XmlQName; value: T; }
/** A DOM node, allowed where the mapping permits DOM content (allowDom). */
export type XmlDomNode = any;
/** The value of an anyElement property: a typed element, a DOM node or (if mixed) text. */
export type XmlAnyElement = any;
/** The value of an anyAttribute property. */
export interface XmlAnyAttributes { [attributeName: string]: string; }
/** A Jsonix mapping object as consumed by new Jsonix.Context([...]); R is the union of its global element types. */
export interface JsonixMapping<R = unknown> { readonly __rootElement?: R; readonly [key: string]: unknown; }

export interface CTArc {
  TYPE_NAME?: 'org_docx4j_vml.CTArc';
  readonly PARENT?: CTGroup;
  egShapeElements?: (TypedNamedValue<CTPath> | TypedNamedValue<CTFormulas> | TypedNamedValue<CTHandles> | TypedNamedValue<CTFill> | TypedNamedValue<CTStroke> | TypedNamedValue<CTShadow> | TypedNamedValue<CTTextbox> | TypedNamedValue<CTTextPath> | TypedNamedValue<CTImageData> | TypedNamedValue<Dep_org_docx4j_vml_officedrawing.CTSkew> | TypedNamedValue<Dep_org_docx4j_vml_officedrawing.CTExtrusion> | TypedNamedValue<Dep_org_docx4j_vml_officedrawing.CTCallout> | TypedNamedValue<Dep_org_docx4j_vml_officedrawing.CTLock> | TypedNamedValue<Dep_org_docx4j_vml_officedrawing.CTClipPath> | TypedNamedValue<Dep_org_docx4j_vml_officedrawing.CTSignatureLine> | TypedNamedValue<Dep_org_docx4j_vml_wordprocessingDrawing.CTWrap> | TypedNamedValue<Dep_org_docx4j_vml_wordprocessingDrawing.CTAnchorLock> | TypedNamedValue<Dep_org_docx4j_vml_wordprocessingDrawing.CTBorder> | TypedNamedValue<Dep_org_docx4j_vml_spreadsheetDrawing.CTClientData> | TypedNamedValue<Dep_org_docx4j_vml_presentationDrawing.CTRel>)[];
  startAngle?: number;
  endAngle?: number;
  opacity?: string;
  stroked?: STTrueFalse;
  strokecolor?: string;
  strokeweight?: string;
  insetpen?: STTrueFalse;
  chromakey?: string;
  filled?: STTrueFalse;
  fillcolor?: string;
  spt?: number;
  connectortype?: Dep_org_docx4j_vml_officedrawing.STConnectorType;
  bwmode?: Dep_org_docx4j_vml_officedrawing.STBWMode;
  bwpure?: Dep_org_docx4j_vml_officedrawing.STBWMode;
  bwnormal?: Dep_org_docx4j_vml_officedrawing.STBWMode;
  forcedash?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  oleicon?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  ole?: string;
  preferrelative?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  cliptowrap?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  clip?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  spid?: string;
  oned?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  regroupid?: number;
  doubleclicknotify?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  button?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  userhidden?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  bullet?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  hr?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  hrstd?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  hrnoshade?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  hrpct?: number;
  hralign?: Dep_org_docx4j_vml_officedrawing.STHrAlign;
  allowincell?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  allowoverlap?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  userdrawn?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  bordertopcolor?: string;
  borderleftcolor?: string;
  borderbottomcolor?: string;
  borderrightcolor?: string;
  dgmlayout?: number;
  dgmnodekind?: number;
  dgmlayoutmru?: number;
  insetmode?: Dep_org_docx4j_vml_officedrawing.STInsetMode;
  href?: string;
  target?: string;
  clazz?: string;
  title?: string;
  alt?: string;
  coordsize?: string;
  coordorigin?: string;
  wrapcoords?: string;
  print?: STTrueFalse;
  vmlId?: string;
  style?: string;
}

export interface CTBackground {
  TYPE_NAME?: 'org_docx4j_vml.CTBackground';
  fill?: CTFill;
  bwmode?: Dep_org_docx4j_vml_officedrawing.STBWMode;
  bwpure?: Dep_org_docx4j_vml_officedrawing.STBWMode;
  bwnormal?: Dep_org_docx4j_vml_officedrawing.STBWMode;
  targetscreensize?: string;
  filled?: STTrueFalse;
  fillcolor?: string;
  vmlId?: string;
}

export interface CTCurve {
  TYPE_NAME?: 'org_docx4j_vml.CTCurve';
  readonly PARENT?: CTGroup;
  egShapeElements?: (TypedNamedValue<CTPath> | TypedNamedValue<CTFormulas> | TypedNamedValue<CTHandles> | TypedNamedValue<CTFill> | TypedNamedValue<CTStroke> | TypedNamedValue<CTShadow> | TypedNamedValue<CTTextbox> | TypedNamedValue<CTTextPath> | TypedNamedValue<CTImageData> | TypedNamedValue<Dep_org_docx4j_vml_officedrawing.CTSkew> | TypedNamedValue<Dep_org_docx4j_vml_officedrawing.CTExtrusion> | TypedNamedValue<Dep_org_docx4j_vml_officedrawing.CTCallout> | TypedNamedValue<Dep_org_docx4j_vml_officedrawing.CTLock> | TypedNamedValue<Dep_org_docx4j_vml_officedrawing.CTClipPath> | TypedNamedValue<Dep_org_docx4j_vml_officedrawing.CTSignatureLine> | TypedNamedValue<Dep_org_docx4j_vml_wordprocessingDrawing.CTWrap> | TypedNamedValue<Dep_org_docx4j_vml_wordprocessingDrawing.CTAnchorLock> | TypedNamedValue<Dep_org_docx4j_vml_wordprocessingDrawing.CTBorder> | TypedNamedValue<Dep_org_docx4j_vml_spreadsheetDrawing.CTClientData> | TypedNamedValue<Dep_org_docx4j_vml_presentationDrawing.CTRel>)[];
  from?: string;
  control1?: string;
  control2?: string;
  to?: string;
  spid?: string;
  oned?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  regroupid?: number;
  doubleclicknotify?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  button?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  userhidden?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  bullet?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  hr?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  hrstd?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  hrnoshade?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  hrpct?: number;
  hralign?: Dep_org_docx4j_vml_officedrawing.STHrAlign;
  allowincell?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  allowoverlap?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  userdrawn?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  bordertopcolor?: string;
  borderleftcolor?: string;
  borderbottomcolor?: string;
  borderrightcolor?: string;
  dgmlayout?: number;
  dgmnodekind?: number;
  dgmlayoutmru?: number;
  insetmode?: Dep_org_docx4j_vml_officedrawing.STInsetMode;
  href?: string;
  target?: string;
  clazz?: string;
  title?: string;
  alt?: string;
  coordsize?: string;
  coordorigin?: string;
  wrapcoords?: string;
  print?: STTrueFalse;
  vmlId?: string;
  style?: string;
  opacity?: string;
  stroked?: STTrueFalse;
  strokecolor?: string;
  strokeweight?: string;
  insetpen?: STTrueFalse;
  chromakey?: string;
  filled?: STTrueFalse;
  fillcolor?: string;
  spt?: number;
  connectortype?: Dep_org_docx4j_vml_officedrawing.STConnectorType;
  bwmode?: Dep_org_docx4j_vml_officedrawing.STBWMode;
  bwpure?: Dep_org_docx4j_vml_officedrawing.STBWMode;
  bwnormal?: Dep_org_docx4j_vml_officedrawing.STBWMode;
  forcedash?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  oleicon?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  ole?: string;
  preferrelative?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  cliptowrap?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  clip?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
}

export interface CTF {
  TYPE_NAME?: 'org_docx4j_vml.CTF';
  readonly PARENT?: CTFormulas;
  eqn?: string;
}

export interface CTFill {
  TYPE_NAME?: 'org_docx4j_vml.CTFill';
  readonly PARENT?: CTArc | CTBackground | CTCurve | CTGroup | CTImage | CTLine | CTOval | CTPolyLine | CTRect | CTRoundRect | CTShape | CTShapetype | Dep_org_docx4j_vml_officedrawing.CTShapeDefaults;
  fill?: Dep_org_docx4j_vml_officedrawing.CTFill;
  type?: STFillType;
  on?: STTrueFalse;
  color?: string;
  opacity?: string;
  color2?: string;
  src?: string;
  href?: string;
  althref?: string;
  size?: string;
  origin?: string;
  position?: string;
  aspect?: STImageAspect;
  colors?: string;
  angle?: number;
  alignshape?: STTrueFalse;
  focus?: string;
  focussize?: string;
  focusposition?: string;
  method?: STFillMethod;
  detectmouseclick?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  title?: string;
  opacity2?: string;
  recolor?: STTrueFalse;
  rotate?: STTrueFalse;
  id?: string;
  relid?: string;
  vmlId?: string;
}

export interface CTFormulas {
  TYPE_NAME?: 'org_docx4j_vml.CTFormulas';
  readonly PARENT?: CTArc | CTCurve | CTGroup | CTImage | CTLine | CTOval | CTPolyLine | CTRect | CTRoundRect | CTShape | CTShapetype;
  f?: CTF[];
}

export interface CTGroup {
  TYPE_NAME?: 'org_docx4j_vml.CTGroup';
  readonly PARENT?: CTGroup;
  pathOrFormulasOrHandles?: (TypedNamedValue<CTPath> | TypedNamedValue<CTFormulas> | TypedNamedValue<CTHandles> | TypedNamedValue<CTFill> | TypedNamedValue<CTStroke> | TypedNamedValue<CTShadow> | TypedNamedValue<CTTextbox> | TypedNamedValue<CTTextPath> | TypedNamedValue<CTImageData> | TypedNamedValue<Dep_org_docx4j_vml_officedrawing.CTSkew> | TypedNamedValue<Dep_org_docx4j_vml_officedrawing.CTExtrusion> | TypedNamedValue<Dep_org_docx4j_vml_officedrawing.CTCallout> | TypedNamedValue<Dep_org_docx4j_vml_officedrawing.CTLock> | TypedNamedValue<Dep_org_docx4j_vml_officedrawing.CTClipPath> | TypedNamedValue<Dep_org_docx4j_vml_officedrawing.CTSignatureLine> | TypedNamedValue<Dep_org_docx4j_vml_wordprocessingDrawing.CTWrap> | TypedNamedValue<Dep_org_docx4j_vml_wordprocessingDrawing.CTAnchorLock> | TypedNamedValue<Dep_org_docx4j_vml_wordprocessingDrawing.CTBorder> | TypedNamedValue<Dep_org_docx4j_vml_spreadsheetDrawing.CTClientData> | TypedNamedValue<Dep_org_docx4j_vml_presentationDrawing.CTRel> | TypedNamedValue<CTGroup> | TypedNamedValue<CTShape> | TypedNamedValue<CTShapetype> | TypedNamedValue<CTArc> | TypedNamedValue<CTCurve> | TypedNamedValue<CTImage> | TypedNamedValue<CTLine> | TypedNamedValue<CTOval> | TypedNamedValue<CTPolyLine> | TypedNamedValue<CTRect> | TypedNamedValue<CTRoundRect> | TypedNamedValue<Dep_org_docx4j_vml_officedrawing.CTDiagram>)[];
  editas?: STEditAs;
  tableproperties?: string;
  tablelimits?: string;
  filled?: STTrueFalse;
  fillcolor?: string;
  spid?: string;
  oned?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  regroupid?: number;
  doubleclicknotify?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  button?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  userhidden?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  bullet?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  hr?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  hrstd?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  hrnoshade?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  hrpct?: number;
  hralign?: Dep_org_docx4j_vml_officedrawing.STHrAlign;
  allowincell?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  allowoverlap?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  userdrawn?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  bordertopcolor?: string;
  borderleftcolor?: string;
  borderbottomcolor?: string;
  borderrightcolor?: string;
  dgmlayout?: number;
  dgmnodekind?: number;
  dgmlayoutmru?: number;
  insetmode?: Dep_org_docx4j_vml_officedrawing.STInsetMode;
  href?: string;
  target?: string;
  clazz?: string;
  title?: string;
  alt?: string;
  coordsize?: string;
  coordorigin?: string;
  wrapcoords?: string;
  print?: STTrueFalse;
  vmlId?: string;
  style?: string;
}

export interface CTH {
  TYPE_NAME?: 'org_docx4j_vml.CTH';
  readonly PARENT?: CTHandles;
  position?: string;
  polar?: string;
  map?: string;
  invx?: STTrueFalse;
  invy?: STTrueFalse;
  _switch?: string;
  xrange?: string;
  yrange?: string;
  radiusrange?: string;
}

export interface CTHandles {
  TYPE_NAME?: 'org_docx4j_vml.CTHandles';
  readonly PARENT?: CTArc | CTCurve | CTGroup | CTImage | CTLine | CTOval | CTPolyLine | CTRect | CTRoundRect | CTShape | CTShapetype;
  h?: CTH[];
}

export interface CTImage {
  TYPE_NAME?: 'org_docx4j_vml.CTImage';
  readonly PARENT?: CTGroup;
  egShapeElements?: (TypedNamedValue<CTPath> | TypedNamedValue<CTFormulas> | TypedNamedValue<CTHandles> | TypedNamedValue<CTFill> | TypedNamedValue<CTStroke> | TypedNamedValue<CTShadow> | TypedNamedValue<CTTextbox> | TypedNamedValue<CTTextPath> | TypedNamedValue<CTImageData> | TypedNamedValue<Dep_org_docx4j_vml_officedrawing.CTSkew> | TypedNamedValue<Dep_org_docx4j_vml_officedrawing.CTExtrusion> | TypedNamedValue<Dep_org_docx4j_vml_officedrawing.CTCallout> | TypedNamedValue<Dep_org_docx4j_vml_officedrawing.CTLock> | TypedNamedValue<Dep_org_docx4j_vml_officedrawing.CTClipPath> | TypedNamedValue<Dep_org_docx4j_vml_officedrawing.CTSignatureLine> | TypedNamedValue<Dep_org_docx4j_vml_wordprocessingDrawing.CTWrap> | TypedNamedValue<Dep_org_docx4j_vml_wordprocessingDrawing.CTAnchorLock> | TypedNamedValue<Dep_org_docx4j_vml_wordprocessingDrawing.CTBorder> | TypedNamedValue<Dep_org_docx4j_vml_spreadsheetDrawing.CTClientData> | TypedNamedValue<Dep_org_docx4j_vml_presentationDrawing.CTRel>)[];
  opacity?: string;
  stroked?: STTrueFalse;
  strokecolor?: string;
  strokeweight?: string;
  insetpen?: STTrueFalse;
  chromakey?: string;
  filled?: STTrueFalse;
  fillcolor?: string;
  spt?: number;
  connectortype?: Dep_org_docx4j_vml_officedrawing.STConnectorType;
  bwmode?: Dep_org_docx4j_vml_officedrawing.STBWMode;
  bwpure?: Dep_org_docx4j_vml_officedrawing.STBWMode;
  bwnormal?: Dep_org_docx4j_vml_officedrawing.STBWMode;
  forcedash?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  oleicon?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  ole?: string;
  preferrelative?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  cliptowrap?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  clip?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  spid?: string;
  oned?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  regroupid?: number;
  doubleclicknotify?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  button?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  userhidden?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  bullet?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  hr?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  hrstd?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  hrnoshade?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  hrpct?: number;
  hralign?: Dep_org_docx4j_vml_officedrawing.STHrAlign;
  allowincell?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  allowoverlap?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  userdrawn?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  bordertopcolor?: string;
  borderleftcolor?: string;
  borderbottomcolor?: string;
  borderrightcolor?: string;
  dgmlayout?: number;
  dgmnodekind?: number;
  dgmlayoutmru?: number;
  insetmode?: Dep_org_docx4j_vml_officedrawing.STInsetMode;
  href?: string;
  target?: string;
  clazz?: string;
  title?: string;
  alt?: string;
  coordsize?: string;
  coordorigin?: string;
  wrapcoords?: string;
  print?: STTrueFalse;
  vmlId?: string;
  style?: string;
  src?: string;
  cropleft?: string;
  croptop?: string;
  cropright?: string;
  cropbottom?: string;
  gain?: string;
  blacklevel?: string;
  gamma?: string;
  grayscale?: STTrueFalse;
  bilevel?: STTrueFalse;
}

export interface CTImageData {
  TYPE_NAME?: 'org_docx4j_vml.CTImageData';
  readonly PARENT?: CTArc | CTCurve | CTGroup | CTImage | CTLine | CTOval | CTPolyLine | CTRect | CTRoundRect | CTShape | CTShapetype;
  embosscolor?: string;
  recolortarget?: string;
  ohref?: string;
  althref?: string;
  title?: string;
  oleid?: number;
  detectmouseclick?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  movie?: number;
  relid?: string;
  id?: string;
  pict?: string;
  href?: string;
  vmlId?: string;
  src?: string;
  cropleft?: string;
  croptop?: string;
  cropright?: string;
  cropbottom?: string;
  gain?: string;
  blacklevel?: string;
  gamma?: string;
  grayscale?: STTrueFalse;
  bilevel?: STTrueFalse;
  chromakey?: string;
}

export interface CTLine {
  TYPE_NAME?: 'org_docx4j_vml.CTLine';
  readonly PARENT?: CTGroup;
  egShapeElements?: (TypedNamedValue<CTPath> | TypedNamedValue<CTFormulas> | TypedNamedValue<CTHandles> | TypedNamedValue<CTFill> | TypedNamedValue<CTStroke> | TypedNamedValue<CTShadow> | TypedNamedValue<CTTextbox> | TypedNamedValue<CTTextPath> | TypedNamedValue<CTImageData> | TypedNamedValue<Dep_org_docx4j_vml_officedrawing.CTSkew> | TypedNamedValue<Dep_org_docx4j_vml_officedrawing.CTExtrusion> | TypedNamedValue<Dep_org_docx4j_vml_officedrawing.CTCallout> | TypedNamedValue<Dep_org_docx4j_vml_officedrawing.CTLock> | TypedNamedValue<Dep_org_docx4j_vml_officedrawing.CTClipPath> | TypedNamedValue<Dep_org_docx4j_vml_officedrawing.CTSignatureLine> | TypedNamedValue<Dep_org_docx4j_vml_wordprocessingDrawing.CTWrap> | TypedNamedValue<Dep_org_docx4j_vml_wordprocessingDrawing.CTAnchorLock> | TypedNamedValue<Dep_org_docx4j_vml_wordprocessingDrawing.CTBorder> | TypedNamedValue<Dep_org_docx4j_vml_spreadsheetDrawing.CTClientData> | TypedNamedValue<Dep_org_docx4j_vml_presentationDrawing.CTRel>)[];
  from?: string;
  to?: string;
  spid?: string;
  oned?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  regroupid?: number;
  doubleclicknotify?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  button?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  userhidden?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  bullet?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  hr?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  hrstd?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  hrnoshade?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  hrpct?: number;
  hralign?: Dep_org_docx4j_vml_officedrawing.STHrAlign;
  allowincell?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  allowoverlap?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  userdrawn?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  bordertopcolor?: string;
  borderleftcolor?: string;
  borderbottomcolor?: string;
  borderrightcolor?: string;
  dgmlayout?: number;
  dgmnodekind?: number;
  dgmlayoutmru?: number;
  insetmode?: Dep_org_docx4j_vml_officedrawing.STInsetMode;
  href?: string;
  target?: string;
  clazz?: string;
  title?: string;
  alt?: string;
  coordsize?: string;
  coordorigin?: string;
  wrapcoords?: string;
  print?: STTrueFalse;
  vmlId?: string;
  style?: string;
  opacity?: string;
  stroked?: STTrueFalse;
  strokecolor?: string;
  strokeweight?: string;
  insetpen?: STTrueFalse;
  chromakey?: string;
  filled?: STTrueFalse;
  fillcolor?: string;
  spt?: number;
  connectortype?: Dep_org_docx4j_vml_officedrawing.STConnectorType;
  bwmode?: Dep_org_docx4j_vml_officedrawing.STBWMode;
  bwpure?: Dep_org_docx4j_vml_officedrawing.STBWMode;
  bwnormal?: Dep_org_docx4j_vml_officedrawing.STBWMode;
  forcedash?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  oleicon?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  ole?: string;
  preferrelative?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  cliptowrap?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  clip?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
}

export interface CTOval {
  TYPE_NAME?: 'org_docx4j_vml.CTOval';
  readonly PARENT?: CTGroup;
  pathOrFormulasOrHandles?: (TypedNamedValue<CTPath> | TypedNamedValue<CTFormulas> | TypedNamedValue<CTHandles> | TypedNamedValue<CTFill> | TypedNamedValue<CTStroke> | TypedNamedValue<CTShadow> | TypedNamedValue<CTTextbox> | TypedNamedValue<CTTextPath> | TypedNamedValue<CTImageData> | TypedNamedValue<Dep_org_docx4j_vml_officedrawing.CTSkew> | TypedNamedValue<Dep_org_docx4j_vml_officedrawing.CTExtrusion> | TypedNamedValue<Dep_org_docx4j_vml_officedrawing.CTCallout> | TypedNamedValue<Dep_org_docx4j_vml_officedrawing.CTLock> | TypedNamedValue<Dep_org_docx4j_vml_officedrawing.CTClipPath> | TypedNamedValue<Dep_org_docx4j_vml_officedrawing.CTSignatureLine> | TypedNamedValue<Dep_org_docx4j_vml_wordprocessingDrawing.CTWrap> | TypedNamedValue<Dep_org_docx4j_vml_wordprocessingDrawing.CTAnchorLock> | TypedNamedValue<Dep_org_docx4j_vml_wordprocessingDrawing.CTBorder> | TypedNamedValue<Dep_org_docx4j_vml_spreadsheetDrawing.CTClientData> | TypedNamedValue<Dep_org_docx4j_vml_presentationDrawing.CTRel>)[];
  opacity?: string;
  stroked?: STTrueFalse;
  strokecolor?: string;
  strokeweight?: string;
  insetpen?: STTrueFalse;
  chromakey?: string;
  filled?: STTrueFalse;
  fillcolor?: string;
  spt?: number;
  connectortype?: Dep_org_docx4j_vml_officedrawing.STConnectorType;
  bwmode?: Dep_org_docx4j_vml_officedrawing.STBWMode;
  bwpure?: Dep_org_docx4j_vml_officedrawing.STBWMode;
  bwnormal?: Dep_org_docx4j_vml_officedrawing.STBWMode;
  forcedash?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  oleicon?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  ole?: string;
  preferrelative?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  cliptowrap?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  clip?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  spid?: string;
  oned?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  regroupid?: number;
  doubleclicknotify?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  button?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  userhidden?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  bullet?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  hr?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  hrstd?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  hrnoshade?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  hrpct?: number;
  hralign?: Dep_org_docx4j_vml_officedrawing.STHrAlign;
  allowincell?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  allowoverlap?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  userdrawn?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  bordertopcolor?: string;
  borderleftcolor?: string;
  borderbottomcolor?: string;
  borderrightcolor?: string;
  dgmlayout?: number;
  dgmnodekind?: number;
  dgmlayoutmru?: number;
  insetmode?: Dep_org_docx4j_vml_officedrawing.STInsetMode;
  href?: string;
  target?: string;
  clazz?: string;
  title?: string;
  alt?: string;
  coordsize?: string;
  coordorigin?: string;
  wrapcoords?: string;
  print?: STTrueFalse;
  vmlId?: string;
  style?: string;
}

export interface CTPath {
  TYPE_NAME?: 'org_docx4j_vml.CTPath';
  readonly PARENT?: CTArc | CTCurve | CTGroup | CTImage | CTLine | CTOval | CTPolyLine | CTRect | CTRoundRect | CTShape | CTShapetype;
  v?: string;
  limo?: string;
  textboxrect?: string;
  fillok?: STTrueFalse;
  strokeok?: STTrueFalse;
  shadowok?: STTrueFalse;
  arrowok?: STTrueFalse;
  gradientshapeok?: STTrueFalse;
  textpathok?: STTrueFalse;
  insetpenok?: STTrueFalse;
  connecttype?: Dep_org_docx4j_vml_officedrawing.STConnectType;
  connectlocs?: string;
  connectangles?: string;
  extrusionok?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  vmlId?: string;
}

export interface CTPolyLine {
  TYPE_NAME?: 'org_docx4j_vml.CTPolyLine';
  readonly PARENT?: CTGroup;
  pathOrFormulasOrHandles?: (TypedNamedValue<CTPath> | TypedNamedValue<CTFormulas> | TypedNamedValue<CTHandles> | TypedNamedValue<CTFill> | TypedNamedValue<CTStroke> | TypedNamedValue<CTShadow> | TypedNamedValue<CTTextbox> | TypedNamedValue<CTTextPath> | TypedNamedValue<CTImageData> | TypedNamedValue<Dep_org_docx4j_vml_officedrawing.CTSkew> | TypedNamedValue<Dep_org_docx4j_vml_officedrawing.CTExtrusion> | TypedNamedValue<Dep_org_docx4j_vml_officedrawing.CTCallout> | TypedNamedValue<Dep_org_docx4j_vml_officedrawing.CTLock> | TypedNamedValue<Dep_org_docx4j_vml_officedrawing.CTClipPath> | TypedNamedValue<Dep_org_docx4j_vml_officedrawing.CTSignatureLine> | TypedNamedValue<Dep_org_docx4j_vml_wordprocessingDrawing.CTWrap> | TypedNamedValue<Dep_org_docx4j_vml_wordprocessingDrawing.CTAnchorLock> | TypedNamedValue<Dep_org_docx4j_vml_wordprocessingDrawing.CTBorder> | TypedNamedValue<Dep_org_docx4j_vml_spreadsheetDrawing.CTClientData> | TypedNamedValue<Dep_org_docx4j_vml_presentationDrawing.CTRel> | TypedNamedValue<Dep_org_docx4j_vml_officedrawing.CTInk>)[];
  points?: string;
  opacity?: string;
  stroked?: STTrueFalse;
  strokecolor?: string;
  strokeweight?: string;
  insetpen?: STTrueFalse;
  chromakey?: string;
  filled?: STTrueFalse;
  fillcolor?: string;
  spt?: number;
  connectortype?: Dep_org_docx4j_vml_officedrawing.STConnectorType;
  bwmode?: Dep_org_docx4j_vml_officedrawing.STBWMode;
  bwpure?: Dep_org_docx4j_vml_officedrawing.STBWMode;
  bwnormal?: Dep_org_docx4j_vml_officedrawing.STBWMode;
  forcedash?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  oleicon?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  ole?: string;
  preferrelative?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  cliptowrap?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  clip?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  spid?: string;
  oned?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  regroupid?: number;
  doubleclicknotify?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  button?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  userhidden?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  bullet?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  hr?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  hrstd?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  hrnoshade?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  hrpct?: number;
  hralign?: Dep_org_docx4j_vml_officedrawing.STHrAlign;
  allowincell?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  allowoverlap?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  userdrawn?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  bordertopcolor?: string;
  borderleftcolor?: string;
  borderbottomcolor?: string;
  borderrightcolor?: string;
  dgmlayout?: number;
  dgmnodekind?: number;
  dgmlayoutmru?: number;
  insetmode?: Dep_org_docx4j_vml_officedrawing.STInsetMode;
  href?: string;
  target?: string;
  clazz?: string;
  title?: string;
  alt?: string;
  coordsize?: string;
  coordorigin?: string;
  wrapcoords?: string;
  print?: STTrueFalse;
  vmlId?: string;
  style?: string;
}

export interface CTRect {
  TYPE_NAME?: 'org_docx4j_vml.CTRect';
  readonly PARENT?: CTGroup;
  pathOrFormulasOrHandles?: (TypedNamedValue<CTPath> | TypedNamedValue<CTFormulas> | TypedNamedValue<CTHandles> | TypedNamedValue<CTFill> | TypedNamedValue<CTStroke> | TypedNamedValue<CTShadow> | TypedNamedValue<CTTextbox> | TypedNamedValue<CTTextPath> | TypedNamedValue<CTImageData> | TypedNamedValue<Dep_org_docx4j_vml_officedrawing.CTSkew> | TypedNamedValue<Dep_org_docx4j_vml_officedrawing.CTExtrusion> | TypedNamedValue<Dep_org_docx4j_vml_officedrawing.CTCallout> | TypedNamedValue<Dep_org_docx4j_vml_officedrawing.CTLock> | TypedNamedValue<Dep_org_docx4j_vml_officedrawing.CTClipPath> | TypedNamedValue<Dep_org_docx4j_vml_officedrawing.CTSignatureLine> | TypedNamedValue<Dep_org_docx4j_vml_wordprocessingDrawing.CTWrap> | TypedNamedValue<Dep_org_docx4j_vml_wordprocessingDrawing.CTAnchorLock> | TypedNamedValue<Dep_org_docx4j_vml_wordprocessingDrawing.CTBorder> | TypedNamedValue<Dep_org_docx4j_vml_spreadsheetDrawing.CTClientData> | TypedNamedValue<Dep_org_docx4j_vml_presentationDrawing.CTRel>)[];
  opacity?: string;
  stroked?: STTrueFalse;
  strokecolor?: string;
  strokeweight?: string;
  insetpen?: STTrueFalse;
  chromakey?: string;
  filled?: STTrueFalse;
  fillcolor?: string;
  spt?: number;
  connectortype?: Dep_org_docx4j_vml_officedrawing.STConnectorType;
  bwmode?: Dep_org_docx4j_vml_officedrawing.STBWMode;
  bwpure?: Dep_org_docx4j_vml_officedrawing.STBWMode;
  bwnormal?: Dep_org_docx4j_vml_officedrawing.STBWMode;
  forcedash?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  oleicon?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  ole?: string;
  preferrelative?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  cliptowrap?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  clip?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  spid?: string;
  oned?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  regroupid?: number;
  doubleclicknotify?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  button?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  userhidden?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  bullet?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  hr?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  hrstd?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  hrnoshade?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  hrpct?: number;
  hralign?: Dep_org_docx4j_vml_officedrawing.STHrAlign;
  allowincell?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  allowoverlap?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  userdrawn?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  bordertopcolor?: string;
  borderleftcolor?: string;
  borderbottomcolor?: string;
  borderrightcolor?: string;
  dgmlayout?: number;
  dgmnodekind?: number;
  dgmlayoutmru?: number;
  insetmode?: Dep_org_docx4j_vml_officedrawing.STInsetMode;
  href?: string;
  target?: string;
  clazz?: string;
  title?: string;
  alt?: string;
  coordsize?: string;
  coordorigin?: string;
  wrapcoords?: string;
  print?: STTrueFalse;
  vmlId?: string;
  style?: string;
}

export interface CTRoundRect {
  TYPE_NAME?: 'org_docx4j_vml.CTRoundRect';
  readonly PARENT?: CTGroup;
  pathOrFormulasOrHandles?: (TypedNamedValue<CTPath> | TypedNamedValue<CTFormulas> | TypedNamedValue<CTHandles> | TypedNamedValue<CTFill> | TypedNamedValue<CTStroke> | TypedNamedValue<CTShadow> | TypedNamedValue<CTTextbox> | TypedNamedValue<CTTextPath> | TypedNamedValue<CTImageData> | TypedNamedValue<Dep_org_docx4j_vml_officedrawing.CTSkew> | TypedNamedValue<Dep_org_docx4j_vml_officedrawing.CTExtrusion> | TypedNamedValue<Dep_org_docx4j_vml_officedrawing.CTCallout> | TypedNamedValue<Dep_org_docx4j_vml_officedrawing.CTLock> | TypedNamedValue<Dep_org_docx4j_vml_officedrawing.CTClipPath> | TypedNamedValue<Dep_org_docx4j_vml_officedrawing.CTSignatureLine> | TypedNamedValue<Dep_org_docx4j_vml_wordprocessingDrawing.CTWrap> | TypedNamedValue<Dep_org_docx4j_vml_wordprocessingDrawing.CTAnchorLock> | TypedNamedValue<Dep_org_docx4j_vml_wordprocessingDrawing.CTBorder> | TypedNamedValue<Dep_org_docx4j_vml_spreadsheetDrawing.CTClientData> | TypedNamedValue<Dep_org_docx4j_vml_presentationDrawing.CTRel>)[];
  arcsize?: string;
  opacity?: string;
  stroked?: STTrueFalse;
  strokecolor?: string;
  strokeweight?: string;
  insetpen?: STTrueFalse;
  chromakey?: string;
  filled?: STTrueFalse;
  fillcolor?: string;
  spt?: number;
  connectortype?: Dep_org_docx4j_vml_officedrawing.STConnectorType;
  bwmode?: Dep_org_docx4j_vml_officedrawing.STBWMode;
  bwpure?: Dep_org_docx4j_vml_officedrawing.STBWMode;
  bwnormal?: Dep_org_docx4j_vml_officedrawing.STBWMode;
  forcedash?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  oleicon?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  ole?: string;
  preferrelative?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  cliptowrap?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  clip?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  spid?: string;
  oned?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  regroupid?: number;
  doubleclicknotify?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  button?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  userhidden?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  bullet?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  hr?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  hrstd?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  hrnoshade?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  hrpct?: number;
  hralign?: Dep_org_docx4j_vml_officedrawing.STHrAlign;
  allowincell?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  allowoverlap?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  userdrawn?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  bordertopcolor?: string;
  borderleftcolor?: string;
  borderbottomcolor?: string;
  borderrightcolor?: string;
  dgmlayout?: number;
  dgmnodekind?: number;
  dgmlayoutmru?: number;
  insetmode?: Dep_org_docx4j_vml_officedrawing.STInsetMode;
  href?: string;
  target?: string;
  clazz?: string;
  title?: string;
  alt?: string;
  coordsize?: string;
  coordorigin?: string;
  wrapcoords?: string;
  print?: STTrueFalse;
  vmlId?: string;
  style?: string;
}

export interface CTShadow {
  TYPE_NAME?: 'org_docx4j_vml.CTShadow';
  readonly PARENT?: CTArc | CTCurve | CTGroup | CTImage | CTLine | CTOval | CTPolyLine | CTRect | CTRoundRect | CTShape | CTShapetype | Dep_org_docx4j_vml_officedrawing.CTShapeDefaults;
  on?: STTrueFalse;
  type?: STShadowType;
  obscured?: STTrueFalse;
  color?: string;
  opacity?: string;
  offset?: string;
  color2?: string;
  offset2?: string;
  origin?: string;
  matrix?: string;
  vmlId?: string;
}

export interface CTShape {
  TYPE_NAME?: 'org_docx4j_vml.CTShape';
  readonly PARENT?: CTGroup;
  pathOrFormulasOrHandles?: (TypedNamedValue<CTPath> | TypedNamedValue<CTFormulas> | TypedNamedValue<CTHandles> | TypedNamedValue<CTFill> | TypedNamedValue<CTStroke> | TypedNamedValue<CTShadow> | TypedNamedValue<CTTextbox> | TypedNamedValue<CTTextPath> | TypedNamedValue<CTImageData> | TypedNamedValue<Dep_org_docx4j_vml_officedrawing.CTSkew> | TypedNamedValue<Dep_org_docx4j_vml_officedrawing.CTExtrusion> | TypedNamedValue<Dep_org_docx4j_vml_officedrawing.CTCallout> | TypedNamedValue<Dep_org_docx4j_vml_officedrawing.CTLock> | TypedNamedValue<Dep_org_docx4j_vml_officedrawing.CTClipPath> | TypedNamedValue<Dep_org_docx4j_vml_officedrawing.CTSignatureLine> | TypedNamedValue<Dep_org_docx4j_vml_wordprocessingDrawing.CTWrap> | TypedNamedValue<Dep_org_docx4j_vml_wordprocessingDrawing.CTAnchorLock> | TypedNamedValue<Dep_org_docx4j_vml_wordprocessingDrawing.CTBorder> | TypedNamedValue<Dep_org_docx4j_vml_spreadsheetDrawing.CTClientData> | TypedNamedValue<Dep_org_docx4j_vml_presentationDrawing.CTRel> | TypedNamedValue<Dep_org_docx4j_vml_officedrawing.CTInk> | TypedNamedValue<Dep_org_docx4j_vml_presentationDrawing.CTEmpty>)[];
  gfxdata?: string;
  equationxml?: string;
  opacity?: string;
  stroked?: STTrueFalse;
  strokecolor?: string;
  strokeweight?: string;
  insetpen?: STTrueFalse;
  chromakey?: string;
  filled?: STTrueFalse;
  fillcolor?: string;
  spt?: number;
  connectortype?: Dep_org_docx4j_vml_officedrawing.STConnectorType;
  bwmode?: Dep_org_docx4j_vml_officedrawing.STBWMode;
  bwpure?: Dep_org_docx4j_vml_officedrawing.STBWMode;
  bwnormal?: Dep_org_docx4j_vml_officedrawing.STBWMode;
  forcedash?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  oleicon?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  ole?: string;
  preferrelative?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  cliptowrap?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  clip?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  path?: string;
  type?: string;
  spid?: string;
  oned?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  regroupid?: number;
  doubleclicknotify?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  button?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  userhidden?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  bullet?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  hr?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  hrstd?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  hrnoshade?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  hrpct?: number;
  hralign?: Dep_org_docx4j_vml_officedrawing.STHrAlign;
  allowincell?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  allowoverlap?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  userdrawn?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  bordertopcolor?: string;
  borderleftcolor?: string;
  borderbottomcolor?: string;
  borderrightcolor?: string;
  dgmlayout?: number;
  dgmnodekind?: number;
  dgmlayoutmru?: number;
  insetmode?: Dep_org_docx4j_vml_officedrawing.STInsetMode;
  href?: string;
  target?: string;
  clazz?: string;
  title?: string;
  alt?: string;
  coordsize?: string;
  coordorigin?: string;
  wrapcoords?: string;
  print?: STTrueFalse;
  vmlId?: string;
  style?: string;
  adj?: string;
}

export interface CTShapetype {
  TYPE_NAME?: 'org_docx4j_vml.CTShapetype';
  readonly PARENT?: CTGroup;
  egShapeElements?: (TypedNamedValue<CTPath> | TypedNamedValue<CTFormulas> | TypedNamedValue<CTHandles> | TypedNamedValue<CTFill> | TypedNamedValue<CTStroke> | TypedNamedValue<CTShadow> | TypedNamedValue<CTTextbox> | TypedNamedValue<CTTextPath> | TypedNamedValue<CTImageData> | TypedNamedValue<Dep_org_docx4j_vml_officedrawing.CTSkew> | TypedNamedValue<Dep_org_docx4j_vml_officedrawing.CTExtrusion> | TypedNamedValue<Dep_org_docx4j_vml_officedrawing.CTCallout> | TypedNamedValue<Dep_org_docx4j_vml_officedrawing.CTLock> | TypedNamedValue<Dep_org_docx4j_vml_officedrawing.CTClipPath> | TypedNamedValue<Dep_org_docx4j_vml_officedrawing.CTSignatureLine> | TypedNamedValue<Dep_org_docx4j_vml_wordprocessingDrawing.CTWrap> | TypedNamedValue<Dep_org_docx4j_vml_wordprocessingDrawing.CTAnchorLock> | TypedNamedValue<Dep_org_docx4j_vml_wordprocessingDrawing.CTBorder> | TypedNamedValue<Dep_org_docx4j_vml_spreadsheetDrawing.CTClientData> | TypedNamedValue<Dep_org_docx4j_vml_presentationDrawing.CTRel>)[];
  complex?: Dep_org_docx4j_vml_officedrawing.CTComplex;
  master?: string;
  spid?: string;
  oned?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  regroupid?: number;
  doubleclicknotify?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  button?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  userhidden?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  bullet?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  hr?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  hrstd?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  hrnoshade?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  hrpct?: number;
  hralign?: Dep_org_docx4j_vml_officedrawing.STHrAlign;
  allowincell?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  allowoverlap?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  userdrawn?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  bordertopcolor?: string;
  borderleftcolor?: string;
  borderbottomcolor?: string;
  borderrightcolor?: string;
  dgmlayout?: number;
  dgmnodekind?: number;
  dgmlayoutmru?: number;
  insetmode?: Dep_org_docx4j_vml_officedrawing.STInsetMode;
  href?: string;
  target?: string;
  clazz?: string;
  title?: string;
  alt?: string;
  coordsize?: string;
  coordorigin?: string;
  wrapcoords?: string;
  print?: STTrueFalse;
  vmlId?: string;
  style?: string;
  opacity?: string;
  stroked?: STTrueFalse;
  strokecolor?: string;
  strokeweight?: string;
  insetpen?: STTrueFalse;
  chromakey?: string;
  filled?: STTrueFalse;
  fillcolor?: string;
  spt?: number;
  connectortype?: Dep_org_docx4j_vml_officedrawing.STConnectorType;
  bwmode?: Dep_org_docx4j_vml_officedrawing.STBWMode;
  bwpure?: Dep_org_docx4j_vml_officedrawing.STBWMode;
  bwnormal?: Dep_org_docx4j_vml_officedrawing.STBWMode;
  forcedash?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  oleicon?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  ole?: string;
  preferrelative?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  cliptowrap?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  clip?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  adj?: string;
  path?: string;
}

export interface CTStroke {
  TYPE_NAME?: 'org_docx4j_vml.CTStroke';
  readonly PARENT?: CTArc | CTCurve | CTGroup | CTImage | CTLine | CTOval | CTPolyLine | CTRect | CTRoundRect | CTShape | CTShapetype | Dep_org_docx4j_vml_officedrawing.CTShapeDefaults;
  left?: Dep_org_docx4j_vml_officedrawing.CTStrokeChild;
  top?: Dep_org_docx4j_vml_officedrawing.CTStrokeChild;
  right?: Dep_org_docx4j_vml_officedrawing.CTStrokeChild;
  bottom?: Dep_org_docx4j_vml_officedrawing.CTStrokeChild;
  column?: Dep_org_docx4j_vml_officedrawing.CTStrokeChild;
  vmlId?: string;
  on?: STTrueFalse;
  weight?: string;
  color?: string;
  opacity?: string;
  linestyle?: STStrokeLineStyle;
  miterlimit?: string;
  joinstyle?: STStrokeJoinStyle;
  endcap?: STStrokeEndCap;
  dashstyle?: string;
  filltype?: STFillType;
  src?: string;
  imageaspect?: STImageAspect;
  imagesize?: string;
  imagealignshape?: STTrueFalse;
  color2?: string;
  startarrow?: STStrokeArrowType;
  startarrowwidth?: STStrokeArrowWidth;
  startarrowlength?: STStrokeArrowLength;
  endarrow?: STStrokeArrowType;
  endarrowwidth?: STStrokeArrowWidth;
  endarrowlength?: STStrokeArrowLength;
  href?: string;
  althref?: string;
  title?: string;
  forcedash?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  id?: string;
  insetpen?: STTrueFalse;
  relid?: string;
}

export interface CTTextPath {
  TYPE_NAME?: 'org_docx4j_vml.CTTextPath';
  readonly PARENT?: CTArc | CTCurve | CTGroup | CTImage | CTLine | CTOval | CTPolyLine | CTRect | CTRoundRect | CTShape | CTShapetype;
  on?: STTrueFalse;
  fitshape?: STTrueFalse;
  fitpath?: STTrueFalse;
  trim?: STTrueFalse;
  xscale?: STTrueFalse;
  string?: string;
  style?: string;
  vmlId?: string;
}

export interface CTTextbox {
  TYPE_NAME?: 'org_docx4j_vml.CTTextbox';
  readonly PARENT?: CTArc | CTCurve | CTGroup | CTImage | CTLine | CTOval | CTPolyLine | CTRect | CTRoundRect | CTShape | CTShapetype | Dep_org_docx4j_vml_officedrawing.CTShapeDefaults;
  txbxContent?: Dep_org_docx4j_wml.CTTxbxContent;
  any: XmlAnyElement;
  inset?: string;
  singleclick?: Dep_org_docx4j_vml_officedrawing.STTrueFalse;
  insetmode?: Dep_org_docx4j_vml_officedrawing.STInsetMode;
  vmlId?: string;
  style?: string;
}

export type STEditAs = 'canvas' | 'orgchart' | 'radial' | 'cycle' | 'stacked' | 'venn' | 'bullseye';

export type STExt = 'view' | 'edit' | 'backwardCompatible';

export type STFillMethod = 'none' | 'linear' | 'sigma' | 'any' | 'linear sigma';

export type STFillType = 'solid' | 'gradient' | 'gradientRadial' | 'tile' | 'pattern' | 'frame';

export type STImageAspect = 'ignore' | 'atMost' | 'atLeast';

export type STShadowType = 'single' | 'double' | 'emboss' | 'perspective';

export type STStrokeArrowLength = 'short' | 'medium' | 'long';

export type STStrokeArrowType = 'none' | 'block' | 'classic' | 'oval' | 'diamond' | 'open';

export type STStrokeArrowWidth = 'narrow' | 'medium' | 'wide';

export type STStrokeEndCap = 'flat' | 'square' | 'round';

export type STStrokeJoinStyle = 'round' | 'bevel' | 'miter';

export type STStrokeLineStyle = 'single' | 'thinThin' | 'thinThick' | 'thickThin' | 'thickBetweenThin';

export type STTrueFalse = 't' | 'f' | 'true' | 'false';

export type ArcElement = TypedNamedValue<CTArc>;

export type BackgroundElement = TypedNamedValue<CTBackground>;

export type CurveElement = TypedNamedValue<CTCurve>;

export type FillElement = TypedNamedValue<CTFill>;

export type FormulasElement = TypedNamedValue<CTFormulas>;

export type GroupElement = TypedNamedValue<CTGroup>;

export type HandlesElement = TypedNamedValue<CTHandles>;

export type ImageElement = TypedNamedValue<CTImage>;

export type ImagedataElement = TypedNamedValue<CTImageData>;

export type LineElement = TypedNamedValue<CTLine>;

export type OvalElement = TypedNamedValue<CTOval>;

export type PathElement = TypedNamedValue<CTPath>;

export type PolylineElement = TypedNamedValue<CTPolyLine>;

export type RectElement = TypedNamedValue<CTRect>;

export type RoundrectElement = TypedNamedValue<CTRoundRect>;

export type ShadowElement = TypedNamedValue<CTShadow>;

export type ShapeElement = TypedNamedValue<CTShape>;

export type ShapetypeElement = TypedNamedValue<CTShapetype>;

export type StrokeElement = TypedNamedValue<CTStroke>;

export type TextboxElement = TypedNamedValue<CTTextbox>;

export type TextpathElement = TypedNamedValue<CTTextPath>;

/** Any global element of this mapping, i.e. what an unmarshaller returns. */
export type RootElement = ArcElement | BackgroundElement | CurveElement | FillElement | FormulasElement | GroupElement | HandlesElement | ImageElement | ImagedataElement | LineElement | OvalElement | PathElement | PolylineElement | RectElement | RoundrectElement | ShadowElement | ShapeElement | ShapetypeElement | StrokeElement | TextboxElement | TextpathElement;

/** The Jsonix mapping [org_docx4j_vml] exported by the module's JavaScript file. */
export declare const org_docx4j_vml: JsonixMapping<RootElement>;
