// Generated by jsonix-schema-compiler: TypeScript declarations for the Jsonix module [org_docx4j_com_microsoft_schemas_office_drawing_x2010_main]. Do not edit.
// Describes the objects Jsonix produces when unmarshalling with this module's mappings.
import type * as Dep_org_docx4j_dml from './org_docx4j_dml';
import type * as Dep_org_docx4j_w14 from './org_docx4j_w14';
import type * as Dep_org_docx4j_com_microsoft_schemas_office_drawing_x2010_chartDrawing from './org_docx4j_com_microsoft_schemas_office_drawing_x2010_chartDrawing';
import type * as Dep_org_xlsx4j_schemas_microsoft_com_office_excel_x2010_spreadsheetDrawing from './org_xlsx4j_schemas_microsoft_com_office_excel_x2010_spreadsheetDrawing';
import type * as Dep_org_pptx4j_com_microsoft_schemas_office_powerpoint_x2010_main from './org_pptx4j_com_microsoft_schemas_office_powerpoint_x2010_main';

/** Jsonix.XML.QName */
export interface XmlQName { namespaceURI: string; localPart: string; prefix?: string; key?: string; string?: string; }
/** Jsonix.XML.Calendar: the representation of date, time and dateTime values; unset fields are NaN. */
export interface XmlCalendar { year?: number; month?: number; day?: number; hour?: number; minute?: number; second?: number; fractionalSecond?: number; timezone?: number; }
/** The representation of xs:duration values. */
export interface XmlDuration { sign?: number; years?: number; months?: number; days?: number; hours?: number; minutes?: number; seconds?: number; }
/** An element as returned by an unmarshaller or held by an elementRef property. */
export interface TypedNamedValue<T> { name: XmlQName; value: T; }
/** A DOM node, allowed where the mapping permits DOM content (allowDom). */
export type XmlDomNode = any;
/** The value of an anyElement property: a typed element, a DOM node or (if mixed) text. */
export type XmlAnyElement = any;
/** The value of an anyAttribute property. */
export interface XmlAnyAttributes { [attributeName: string]: string; }
/** A Jsonix mapping object as consumed by new Jsonix.Context([...]); R is the union of its global element types. */
export interface JsonixMapping<R = unknown> { readonly __rootElement?: R; readonly [key: string]: unknown; }

export interface CTCameraTool {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2010_main.CTCameraTool';
  cellRange?: string;
  spid?: string;
}

export interface CTCompatExt {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2010_main.CTCompatExt';
  spid?: string;
}

export interface CTContentPartLocking {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2010_main.CTContentPartLocking';
  readonly PARENT?: CTNonVisualInkContentPartProperties;
  extLst?: Dep_org_docx4j_dml.CTOfficeArtExtensionList;
  noAdjustHandles?: boolean;
  noChangeArrowheads?: boolean;
  noChangeAspect?: boolean;
  noChangeShapeType?: boolean;
  noEditPoints?: boolean;
  noGrp?: boolean;
  noMove?: boolean;
  noResize?: boolean;
  noRot?: boolean;
  noSelect?: boolean;
}

export interface CTGvmlContentPart {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2010_main.CTGvmlContentPart';
  nvContentPartPr?: CTGvmlContentPartNonVisual;
  xfrm?: Dep_org_docx4j_dml.CTTransform2D;
  extLst?: Dep_org_docx4j_dml.CTOfficeArtExtensionList;
  bwMode?: Dep_org_docx4j_dml.STBlackWhiteMode;
  id: string;
}

export interface CTGvmlContentPartNonVisual {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2010_main.CTGvmlContentPartNonVisual';
  readonly PARENT?: CTGvmlContentPart;
  cNvPr: Dep_org_docx4j_dml.CTNonVisualDrawingProps;
  cNvContentPartPr?: CTNonVisualInkContentPartProperties;
}

export interface CTIsGvmlCanvas {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2010_main.CTIsGvmlCanvas';
  val: boolean;
}

export interface CTNonVisualInkContentPartProperties {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2010_main.CTNonVisualInkContentPartProperties';
  readonly PARENT?: CTGvmlContentPartNonVisual | Dep_org_docx4j_com_microsoft_schemas_office_drawing_x2010_chartDrawing.CTContentPartNonVisual | Dep_org_docx4j_w14.CTWordContentPartNonVisual | Dep_org_pptx4j_com_microsoft_schemas_office_powerpoint_x2010_main.CTContentPartNonVisual | Dep_org_xlsx4j_schemas_microsoft_com_office_excel_x2010_spreadsheetDrawing.CTContentPartNonVisual;
  cpLocks?: CTContentPartLocking;
  extLst?: Dep_org_docx4j_dml.CTOfficeArtExtensionList;
  isComment?: boolean;
}

export interface CTPhoto {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2010_main.CTPhoto';
  imgLayer: CTPictureLayer;
}

export interface CTPictureEffect {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2010_main.CTPictureEffect';
  readonly PARENT?: CTPictureLayer;
  artisticBlur: CTPictureEffectBlur;
  artisticCement: CTPictureEffectCement;
  artisticChalkSketch: CTPictureEffectChalkSketch;
  artisticCrisscrossEtching: CTPictureEffectCrisscrossEtching;
  artisticCutout: CTPictureEffectCutout;
  artisticFilmGrain: CTPictureEffectFilmGrain;
  artisticGlass: CTPictureEffectGlass;
  artisticGlowDiffused: CTPictureEffectGlowDiffused;
  artisticGlowEdges: CTPictureEffectGlowEdges;
  artisticLightScreen: CTPictureEffectLightScreen;
  artisticLineDrawing: CTPictureEffectLineDrawing;
  artisticMarker: CTPictureEffectMarker;
  artisticMosiaicBubbles: CTPictureEffectMosiaicBubbles;
  artisticPaintStrokes: CTPictureEffectPaintStrokes;
  artisticPaintBrush: CTPictureEffectPaintBrush;
  artisticPastelsSmooth: CTPictureEffectPastelsSmooth;
  artisticPencilGrayscale: CTPictureEffectPencilGrayscale;
  artisticPencilSketch: CTPictureEffectPencilSketch;
  artisticPhotocopy: CTPictureEffectPhotocopy;
  artisticPlasticWrap: CTPictureEffectPlasticWrap;
  artisticTexturizer: CTPictureEffectTexturizer;
  artisticWatercolorSponge: CTPictureEffectWatercolorSponge;
  backgroundRemoval: CTPictureEffectBackgroundRemoval;
  brightnessContrast: CTPictureEffectBrightnessContrast;
  colorTemperature: CTPictureEffectColorTemperature;
  saturation: CTPictureEffectSaturation;
  sharpenSoften: CTPictureEffectSharpenSoften;
  visible?: boolean;
}

export interface CTPictureEffectBackgroundRemoval {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2010_main.CTPictureEffectBackgroundRemoval';
  readonly PARENT?: CTPictureEffect;
  foregroundMark?: CTPictureEffectBackgroundRemovalForegroundMark[];
  backgroundMark?: CTPictureEffectBackgroundRemovalBackgroundMark[];
  b: number;
  l: number;
  r: number;
  t: number;
}

export interface CTPictureEffectBackgroundRemovalBackgroundMark {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2010_main.CTPictureEffectBackgroundRemovalBackgroundMark';
  readonly PARENT?: CTPictureEffectBackgroundRemoval;
  x1: number;
  x2: number;
  y1: number;
  y2: number;
}

export interface CTPictureEffectBackgroundRemovalForegroundMark {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2010_main.CTPictureEffectBackgroundRemovalForegroundMark';
  readonly PARENT?: CTPictureEffectBackgroundRemoval;
  x1: number;
  x2: number;
  y1: number;
  y2: number;
}

export interface CTPictureEffectBlur {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2010_main.CTPictureEffectBlur';
  readonly PARENT?: CTPictureEffect;
  radius?: number;
}

export interface CTPictureEffectBrightnessContrast {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2010_main.CTPictureEffectBrightnessContrast';
  readonly PARENT?: CTPictureEffect;
  bright?: number;
  contrast?: number;
}

export interface CTPictureEffectCement {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2010_main.CTPictureEffectCement';
  readonly PARENT?: CTPictureEffect;
  crackSpacing?: number;
  trans?: number;
}

export interface CTPictureEffectChalkSketch {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2010_main.CTPictureEffectChalkSketch';
  readonly PARENT?: CTPictureEffect;
  pressure?: number;
  trans?: number;
}

export interface CTPictureEffectColorTemperature {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2010_main.CTPictureEffectColorTemperature';
  readonly PARENT?: CTPictureEffect;
  colorTemp?: number;
}

export interface CTPictureEffectCrisscrossEtching {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2010_main.CTPictureEffectCrisscrossEtching';
  readonly PARENT?: CTPictureEffect;
  pressure?: number;
  trans?: number;
}

export interface CTPictureEffectCutout {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2010_main.CTPictureEffectCutout';
  readonly PARENT?: CTPictureEffect;
  numberOfShades?: number;
  trans?: number;
}

export interface CTPictureEffectFilmGrain {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2010_main.CTPictureEffectFilmGrain';
  readonly PARENT?: CTPictureEffect;
  grainSize?: number;
  trans?: number;
}

export interface CTPictureEffectGlass {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2010_main.CTPictureEffectGlass';
  readonly PARENT?: CTPictureEffect;
  scaling?: number;
  trans?: number;
}

export interface CTPictureEffectGlowDiffused {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2010_main.CTPictureEffectGlowDiffused';
  readonly PARENT?: CTPictureEffect;
  intensity?: number;
  trans?: number;
}

export interface CTPictureEffectGlowEdges {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2010_main.CTPictureEffectGlowEdges';
  readonly PARENT?: CTPictureEffect;
  smoothness?: number;
  trans?: number;
}

export interface CTPictureEffectLightScreen {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2010_main.CTPictureEffectLightScreen';
  readonly PARENT?: CTPictureEffect;
  gridSize?: number;
  trans?: number;
}

export interface CTPictureEffectLineDrawing {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2010_main.CTPictureEffectLineDrawing';
  readonly PARENT?: CTPictureEffect;
  pencilSize?: number;
  trans?: number;
}

export interface CTPictureEffectMarker {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2010_main.CTPictureEffectMarker';
  readonly PARENT?: CTPictureEffect;
  size?: number;
  trans?: number;
}

export interface CTPictureEffectMosiaicBubbles {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2010_main.CTPictureEffectMosiaicBubbles';
  readonly PARENT?: CTPictureEffect;
  pressure?: number;
  trans?: number;
}

export interface CTPictureEffectPaintBrush {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2010_main.CTPictureEffectPaintBrush';
  readonly PARENT?: CTPictureEffect;
  brushSize?: number;
  trans?: number;
}

export interface CTPictureEffectPaintStrokes {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2010_main.CTPictureEffectPaintStrokes';
  readonly PARENT?: CTPictureEffect;
  intensity?: number;
  trans?: number;
}

export interface CTPictureEffectPastelsSmooth {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2010_main.CTPictureEffectPastelsSmooth';
  readonly PARENT?: CTPictureEffect;
  scaling?: number;
  trans?: number;
}

export interface CTPictureEffectPencilGrayscale {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2010_main.CTPictureEffectPencilGrayscale';
  readonly PARENT?: CTPictureEffect;
  pencilSize?: number;
  trans?: number;
}

export interface CTPictureEffectPencilSketch {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2010_main.CTPictureEffectPencilSketch';
  readonly PARENT?: CTPictureEffect;
  pressure?: number;
  trans?: number;
}

export interface CTPictureEffectPhotocopy {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2010_main.CTPictureEffectPhotocopy';
  readonly PARENT?: CTPictureEffect;
  detail?: number;
  trans?: number;
}

export interface CTPictureEffectPlasticWrap {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2010_main.CTPictureEffectPlasticWrap';
  readonly PARENT?: CTPictureEffect;
  smoothness?: number;
  trans?: number;
}

export interface CTPictureEffectSaturation {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2010_main.CTPictureEffectSaturation';
  readonly PARENT?: CTPictureEffect;
  sat?: number;
}

export interface CTPictureEffectSharpenSoften {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2010_main.CTPictureEffectSharpenSoften';
  readonly PARENT?: CTPictureEffect;
  amount?: number;
}

export interface CTPictureEffectTexturizer {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2010_main.CTPictureEffectTexturizer';
  readonly PARENT?: CTPictureEffect;
  scaling?: number;
  trans?: number;
}

export interface CTPictureEffectWatercolorSponge {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2010_main.CTPictureEffectWatercolorSponge';
  readonly PARENT?: CTPictureEffect;
  brushSize?: number;
  trans?: number;
}

export interface CTPictureLayer {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2010_main.CTPictureLayer';
  readonly PARENT?: CTPhoto;
  imgEffect?: CTPictureEffect[];
  embed?: string;
}

export interface CTShadowObscured {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2010_main.CTShadowObscured';
  val?: boolean;
}

export interface CTTextMath {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2010_main.CTTextMath';
}

export interface CTUseLocalDpi {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2010_main.CTUseLocalDpi';
  val?: boolean;
}

export type CameraToolElement = TypedNamedValue<CTCameraTool>;

export type CompatExtElement = TypedNamedValue<CTCompatExt>;

export type ContentPartElement = TypedNamedValue<CTGvmlContentPart>;

export type HiddenEffectsElement = TypedNamedValue<Dep_org_docx4j_dml.CTEffectProperties>;

export type HiddenFillElement = TypedNamedValue<Dep_org_docx4j_dml.CTFillProperties>;

export type HiddenLineElement = TypedNamedValue<Dep_org_docx4j_dml.CTLineProperties>;

export type HiddenScene3dElement = TypedNamedValue<Dep_org_docx4j_dml.CTScene3D>;

export type HiddenSp3dElement = TypedNamedValue<Dep_org_docx4j_dml.CTShape3D>;

export type ImgPropsElement = TypedNamedValue<CTPhoto>;

export type IsCanvasElement = TypedNamedValue<CTIsGvmlCanvas>;

export type MElement = TypedNamedValue<CTTextMath>;

export type ShadowObscuredElement = TypedNamedValue<CTShadowObscured>;

export type UseLocalDpiElement = TypedNamedValue<CTUseLocalDpi>;

/** Any global element of this mapping, i.e. what an unmarshaller returns. */
export type RootElement = CameraToolElement | CompatExtElement | ContentPartElement | HiddenEffectsElement | HiddenFillElement | HiddenLineElement | HiddenScene3dElement | HiddenSp3dElement | ImgPropsElement | IsCanvasElement | MElement | ShadowObscuredElement | UseLocalDpiElement;

/** The Jsonix mapping [org_docx4j_com_microsoft_schemas_office_drawing_x2010_main] exported by the module's JavaScript file. */
export declare const org_docx4j_com_microsoft_schemas_office_drawing_x2010_main: JsonixMapping<RootElement>;
