// Generated by jsonix-schema-compiler: Jsonix mappings of the module [org_pptx4j_com_microsoft_schemas_office_powerpoint_x201710_main] as an ES module. Do not edit.
export const org_pptx4j_com_microsoft_schemas_office_powerpoint_x201710_main = {
  name: 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x201710_main',
  defaultElementNamespaceURI: 'http:\/\/schemas.microsoft.com\/office\/powerpoint\/2017\/10\/main',
  typeInfos: [{
      localName: 'CTReadonlyRecommended',
      typeName: 'CT_ReadonlyRecommended',
      propertyInfos: [{
          name: 'val',
          required: true,
          typeInfo: 'Boolean',
          attributeName: {
            localPart: 'val'
          },
          type: 'attribute'
        }]
    }],
  elementInfos: [{
      typeInfo: '.CTReadonlyRecommended',
      elementName: 'readonlyRecommended'
    }]
};
