// Generated by jsonix-schema-compiler: Jsonix mappings of the module [org_docx4j_com_microsoft_schemas_office_drawing_x2014_chart] as an ES module. Do not edit.
export const org_docx4j_com_microsoft_schemas_office_drawing_x2014_chart = {
  name: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chart',
  defaultElementNamespaceURI: 'http:\/\/schemas.microsoft.com\/office\/drawing\/2014\/chart',
  dependencies: ['org_docx4j_dml', 'org_docx4j_dml_chart'],
  typeInfos: [{
      localName: 'CTBooleanFalse',
      typeName: 'CT_BooleanFalse',
      propertyInfos: [{
          name: 'val',
          typeInfo: 'Boolean',
          defaultValue: false,
          attributeName: {
            localPart: 'val'
          },
          type: 'attribute'
        }]
    }, {
      localName: 'CTCategoryFilterException',
      typeName: 'CT_CategoryFilterException',
      propertyInfos: [{
          name: 'uniqueId',
          required: true,
          typeInfo: '.CTChartUniqueID'
        }, {
          name: 'spPr',
          typeInfo: 'org_docx4j_dml.CTShapeProperties'
        }, {
          name: 'explosion',
          typeInfo: 'org_docx4j_dml_chart.CTUnsignedInt'
        }, {
          name: 'invertIfNegative',
          typeInfo: 'org_docx4j_dml_chart.CTBoolean'
        }, {
          name: 'bubble3D',
          typeInfo: 'org_docx4j_dml_chart.CTBoolean'
        }, {
          name: 'marker',
          typeInfo: 'org_docx4j_dml_chart.CTMarker'
        }, {
          name: 'dLbl',
          typeInfo: 'org_docx4j_dml_chart.CTDLbl'
        }]
    }, {
      localName: 'CTCategoryFilterExceptions',
      typeName: 'CT_CategoryFilterExceptions',
      propertyInfos: [{
          name: 'categoryFilterException',
          required: true,
          collection: true,
          typeInfo: '.CTCategoryFilterException'
        }]
    }, {
      localName: 'CTChartDataPointUniqueIDMap',
      typeName: 'CT_ChartDataPointUniqueIDMap',
      propertyInfos: [{
          name: 'ptentry',
          minOccurs: 0,
          collection: true,
          typeInfo: '.CTChartDataPointUniqueIDMapEntry'
        }]
    }, {
      localName: 'CTChartDataPointUniqueIDMapEntry',
      typeName: 'CT_ChartDataPointUniqueIDMapEntry',
      propertyInfos: [{
          name: 'ptidx',
          required: true,
          typeInfo: 'UnsignedInt'
        }, {
          name: 'uniqueID',
          required: true,
          typeInfo: '.CTChartUniqueID'
        }]
    }, {
      localName: 'CTChartUniqueID',
      typeName: 'CT_ChartUniqueID',
      propertyInfos: [{
          name: 'val',
          required: true,
          attributeName: {
            localPart: 'val'
          },
          type: 'attribute'
        }]
    }, {
      localName: 'CTLiteralDataChart',
      typeName: 'CT_LiteralDataChart',
      propertyInfos: [{
          name: 'val',
          required: true,
          typeInfo: 'Boolean',
          attributeName: {
            localPart: 'val'
          },
          type: 'attribute'
        }]
    }, {
      localName: 'CTMultiLvlStrFilteredLiteralCache',
      typeName: 'CT_MultiLvlStrFilteredLiteralCache',
      propertyInfos: [{
          name: 'multiLvlStrCache',
          required: true,
          typeInfo: 'org_docx4j_dml_chart.CTMultiLvlStrData'
        }]
    }, {
      localName: 'CTNumFilteredLiteralCache',
      typeName: 'CT_NumFilteredLiteralCache',
      propertyInfos: [{
          name: 'numCache',
          required: true,
          typeInfo: 'org_docx4j_dml_chart.CTNumData'
        }]
    }, {
      localName: 'CTPivotOptions16',
      typeName: 'CT_PivotOptions16',
      propertyInfos: [{
          name: 'showExpandCollapseFieldButtons',
          typeInfo: '.CTBooleanFalse'
        }]
    }, {
      localName: 'CTStrFilteredLiteralCache',
      typeName: 'CT_StrFilteredLiteralCache',
      propertyInfos: [{
          name: 'strCache',
          required: true,
          typeInfo: 'org_docx4j_dml_chart.CTStrData'
        }]
    }],
  elementInfos: [{
      typeInfo: 'org_docx4j_dml_chart.CTBoolean',
      elementName: 'bubble3D'
    }, {
      typeInfo: '.CTCategoryFilterExceptions',
      elementName: 'categoryFilterExceptions'
    }, {
      typeInfo: 'org_docx4j_dml_chart.CTDLbl',
      elementName: 'dLbl'
    }, {
      typeInfo: '.CTChartDataPointUniqueIDMap',
      elementName: 'datapointuniqueidmap'
    }, {
      typeInfo: 'org_docx4j_dml_chart.CTUnsignedInt',
      elementName: 'explosion'
    }, {
      typeInfo: 'org_docx4j_dml_chart.CTBoolean',
      elementName: 'invertIfNegative'
    }, {
      typeInfo: 'org_docx4j_dml_chart.CTMarker',
      elementName: 'marker'
    }, {
      typeInfo: '.CTPivotOptions16',
      elementName: 'pivotOptions16'
    }, {
      typeInfo: 'org_docx4j_dml.CTShapeProperties',
      elementName: 'spPr'
    }]
};
