// Generated by jsonix-schema-compiler: TypeScript declarations for the Jsonix module [org_pptx4j_com_microsoft_schemas_office_powerpoint_x2012_main]. Do not edit.
// Describes the objects Jsonix produces when unmarshalling with this module's mappings.
import type * as Dep_org_docx4j_dml from './org_docx4j_dml';
import type * as Dep_org_pptx4j_pml from './org_pptx4j_pml';

/** Jsonix.XML.QName */
export interface XmlQName { namespaceURI: string; localPart: string; prefix?: string; key?: string; string?: string; }
/** Jsonix.XML.Calendar: the representation of date, time and dateTime values; unset fields are NaN. */
export interface XmlCalendar { year?: number; month?: number; day?: number; hour?: number; minute?: number; second?: number; fractionalSecond?: number; timezone?: number; }
/** The representation of xs:duration values. */
export interface XmlDuration { sign?: number; years?: number; months?: number; days?: number; hours?: number; minutes?: number; seconds?: number; }
/** An element as returned by an unmarshaller or held by an elementRef property. */
export interface TypedNamedValue<T> { name: XmlQName; value: T; }
/** A DOM node, allowed where the mapping permits DOM content (allowDom). */
export type XmlDomNode = any;
/** The value of an anyElement property: a typed element, a DOM node or (if mixed) text. */
export type XmlAnyElement = any;
/** The value of an anyAttribute property. */
export interface XmlAnyAttributes { [attributeName: string]: string; }
/** A Jsonix mapping object as consumed by new Jsonix.Context([...]); R is the union of its global element types. */
export interface JsonixMapping<R = unknown> { readonly __rootElement?: R; readonly [key: string]: unknown; }

export interface CTChartTrackingRefBased {
  TYPE_NAME?: 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x2012_main.CTChartTrackingRefBased';
  val: boolean;
}

export interface CTCommentThreading {
  TYPE_NAME?: 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x2012_main.CTCommentThreading';
  parentCm?: CTParentCommentIdentifier;
  timeZoneBias?: number;
}

export interface CTExtendedGuide {
  TYPE_NAME?: 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x2012_main.CTExtendedGuide';
  readonly PARENT?: CTExtendedGuideList;
  clr: Dep_org_docx4j_dml.CTColor;
  extLst?: Dep_org_pptx4j_pml.CTExtensionList;
  id: number;
  name?: string;
  orient?: Dep_org_pptx4j_pml.STDirection;
  pos?: number;
  userDrawn?: boolean;
}

export interface CTExtendedGuideList {
  TYPE_NAME?: 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x2012_main.CTExtendedGuideList';
  guide?: CTExtendedGuide[];
  extLst?: Dep_org_pptx4j_pml.CTExtensionList;
}

export interface CTParentCommentIdentifier {
  TYPE_NAME?: 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x2012_main.CTParentCommentIdentifier';
  readonly PARENT?: CTCommentThreading;
  authorId?: number;
  idx?: number;
}

export interface CTPresenceInfo {
  TYPE_NAME?: 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x2012_main.CTPresenceInfo';
  providerId: string;
  userId: string;
}

export interface CTPresetTransition {
  TYPE_NAME?: 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x2012_main.CTPresetTransition';
  invX?: boolean;
  invY?: boolean;
  prst?: string;
}

export type ChartTrackingRefBasedElement = TypedNamedValue<CTChartTrackingRefBased>;

export type NotesGuideLstElement = TypedNamedValue<CTExtendedGuideList>;

export type PresenceInfoElement = TypedNamedValue<CTPresenceInfo>;

export type PrstTransElement = TypedNamedValue<CTPresetTransition>;

export type SldGuideLstElement = TypedNamedValue<CTExtendedGuideList>;

export type ThreadingInfoElement = TypedNamedValue<CTCommentThreading>;

/** Any global element of this mapping, i.e. what an unmarshaller returns. */
export type RootElement = ChartTrackingRefBasedElement | NotesGuideLstElement | PresenceInfoElement | PrstTransElement | SldGuideLstElement | ThreadingInfoElement;

/** The Jsonix mapping [org_pptx4j_com_microsoft_schemas_office_powerpoint_x2012_main] exported by the module's JavaScript file. */
export declare const org_pptx4j_com_microsoft_schemas_office_powerpoint_x2012_main: JsonixMapping<RootElement>;
