// Generated by jsonix-schema-compiler: TypeScript declarations for the Jsonix module [org_pptx4j_com_microsoft_schemas_office_powerpoint_x201510_main]. Do not edit.
// Describes the objects Jsonix produces when unmarshalling with this module's mappings.
import type * as Dep_org_pptx4j_pml from './org_pptx4j_pml';

/** Jsonix.XML.QName */
export interface XmlQName { namespaceURI: string; localPart: string; prefix?: string; key?: string; string?: string; }
/** Jsonix.XML.Calendar: the representation of date, time and dateTime values; unset fields are NaN. */
export interface XmlCalendar { year?: number; month?: number; day?: number; hour?: number; minute?: number; second?: number; fractionalSecond?: number; timezone?: number; }
/** The representation of xs:duration values. */
export interface XmlDuration { sign?: number; years?: number; months?: number; days?: number; hours?: number; minutes?: number; seconds?: number; }
/** An element as returned by an unmarshaller or held by an elementRef property. */
export interface TypedNamedValue<T> { name: XmlQName; value: T; }
/** A DOM node, allowed where the mapping permits DOM content (allowDom). */
export type XmlDomNode = any;
/** The value of an anyElement property: a typed element, a DOM node or (if mixed) text. */
export type XmlAnyElement = any;
/** The value of an anyAttribute property. */
export interface XmlAnyAttributes { [attributeName: string]: string; }
/** A Jsonix mapping object as consumed by new Jsonix.Context([...]); R is the union of its global element types. */
export interface JsonixMapping<R = unknown> { readonly __rootElement?: R; readonly [key: string]: unknown; }

export interface CTClientRevision {
  TYPE_NAME?: 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x201510_main.CTClientRevision';
  readonly PARENT?: CTClientRevisionList;
  dt: XmlCalendar;
  id: string;
  v?: number;
  vWet?: number;
}

export interface CTClientRevisionList {
  TYPE_NAME?: 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x201510_main.CTClientRevisionList';
  readonly PARENT?: CTRevisionInfo;
  client?: CTClientRevision[];
}

export interface CTRevisionInfo {
  TYPE_NAME?: 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x201510_main.CTRevisionInfo';
  revLst?: CTClientRevisionList;
  extLst?: Dep_org_pptx4j_pml.CTExtensionList;
}

export type RevInfoElement = TypedNamedValue<CTRevisionInfo>;

/** Any global element of this mapping, i.e. what an unmarshaller returns. */
export type RootElement = RevInfoElement;

/** The Jsonix mapping [org_pptx4j_com_microsoft_schemas_office_powerpoint_x201510_main] exported by the module's JavaScript file. */
export declare const org_pptx4j_com_microsoft_schemas_office_powerpoint_x201510_main: JsonixMapping<RootElement>;
