// Generated by jsonix-schema-compiler: Jsonix mappings of the module [org_docx4j_com_microsoft_schemas_office_word_x2010_wordprocessingShape] as an ES module. Do not edit.
export const org_docx4j_com_microsoft_schemas_office_word_x2010_wordprocessingShape = {
  name: 'org_docx4j_com_microsoft_schemas_office_word_x2010_wordprocessingShape',
  defaultElementNamespaceURI: 'http:\/\/schemas.microsoft.com\/office\/word\/2010\/wordprocessingShape',
  dependencies: ['org_docx4j_dml', 'org_docx4j_wml'],
  typeInfos: [{
      localName: 'CTLinkedTextboxInformation',
      typeName: 'CT_LinkedTextboxInformation',
      propertyInfos: [{
          name: 'extLst',
          typeInfo: 'org_docx4j_dml.CTOfficeArtExtensionList'
        }, {
          name: 'id',
          required: true,
          typeInfo: 'UnsignedShort',
          attributeName: {
            localPart: 'id'
          },
          type: 'attribute'
        }, {
          name: 'seq',
          required: true,
          typeInfo: 'UnsignedShort',
          attributeName: {
            localPart: 'seq'
          },
          type: 'attribute'
        }]
    }, {
      localName: 'CTTextboxInfo',
      typeName: 'CT_TextboxInfo',
      propertyInfos: [{
          name: 'txbxContent',
          elementName: {
            localPart: 'txbxContent',
            namespaceURI: 'http:\/\/schemas.openxmlformats.org\/wordprocessingml\/2006\/main'
          },
          typeInfo: 'org_docx4j_wml.CTTxbxContent'
        }, {
          name: 'extLst',
          typeInfo: 'org_docx4j_dml.CTOfficeArtExtensionList'
        }, {
          name: 'id',
          typeInfo: 'UnsignedShort',
          defaultValue: 0,
          attributeName: {
            localPart: 'id'
          },
          type: 'attribute'
        }]
    }, {
      localName: 'CTWordprocessingShape',
      typeName: 'CT_WordprocessingShape',
      propertyInfos: [{
          name: 'cNvPr',
          typeInfo: 'org_docx4j_dml.CTNonVisualDrawingProps'
        }, {
          name: 'cNvSpPr',
          required: true,
          typeInfo: 'org_docx4j_dml.CTNonVisualDrawingShapeProps'
        }, {
          name: 'cNvCnPr',
          required: true,
          typeInfo: 'org_docx4j_dml.CTNonVisualConnectorProperties'
        }, {
          name: 'spPr',
          required: true,
          typeInfo: 'org_docx4j_dml.CTShapeProperties'
        }, {
          name: 'style',
          typeInfo: 'org_docx4j_dml.CTShapeStyle'
        }, {
          name: 'extLst',
          typeInfo: 'org_docx4j_dml.CTOfficeArtExtensionList'
        }, {
          name: 'txbx',
          required: true,
          typeInfo: '.CTTextboxInfo'
        }, {
          name: 'linkedTxbx',
          required: true,
          typeInfo: '.CTLinkedTextboxInformation'
        }, {
          name: 'bodyPr',
          required: true,
          typeInfo: 'org_docx4j_dml.CTTextBodyProperties'
        }, {
          name: 'normalEastAsianFlow',
          typeInfo: 'Boolean',
          defaultValue: false,
          attributeName: {
            localPart: 'normalEastAsianFlow'
          },
          type: 'attribute'
        }]
    }],
  elementInfos: [{
      typeInfo: '.CTWordprocessingShape',
      elementName: 'wsp'
    }]
};
