// Generated by jsonix-schema-compiler: TypeScript declarations for the Jsonix module [org_docx4j_dml_spreadsheetdrawing]. Do not edit.
// Describes the objects Jsonix produces when unmarshalling with this module's mappings.
import type * as Dep_org_docx4j_dml from './org_docx4j_dml';

/** Jsonix.XML.QName */
export interface XmlQName { namespaceURI: string; localPart: string; prefix?: string; key?: string; string?: string; }
/** Jsonix.XML.Calendar: the representation of date, time and dateTime values; unset fields are NaN. */
export interface XmlCalendar { year?: number; month?: number; day?: number; hour?: number; minute?: number; second?: number; fractionalSecond?: number; timezone?: number; }
/** The representation of xs:duration values. */
export interface XmlDuration { sign?: number; years?: number; months?: number; days?: number; hours?: number; minutes?: number; seconds?: number; }
/** An element as returned by an unmarshaller or held by an elementRef property. */
export interface TypedNamedValue<T> { name: XmlQName; value: T; }
/** A DOM node, allowed where the mapping permits DOM content (allowDom). */
export type XmlDomNode = any;
/** The value of an anyElement property: a typed element, a DOM node or (if mixed) text. */
export type XmlAnyElement = any;
/** The value of an anyAttribute property. */
export interface XmlAnyAttributes { [attributeName: string]: string; }
/** A Jsonix mapping object as consumed by new Jsonix.Context([...]); R is the union of its global element types. */
export interface JsonixMapping<R = unknown> { readonly __rootElement?: R; readonly [key: string]: unknown; }

export interface CTAbsoluteAnchor {
  TYPE_NAME?: 'org_docx4j_dml_spreadsheetdrawing.CTAbsoluteAnchor';
  pos: Dep_org_docx4j_dml.CTPoint2D;
  ext: Dep_org_docx4j_dml.CTPositiveSize2D;
  sp: CTShape;
  grpSp: CTGroupShape;
  graphicFrame: CTGraphicalObjectFrame;
  cxnSp: CTConnector;
  pic: CTPicture;
  clientData: CTAnchorClientData;
}

export interface CTAnchorClientData {
  TYPE_NAME?: 'org_docx4j_dml_spreadsheetdrawing.CTAnchorClientData';
  fLocksWithSheet?: boolean;
  fPrintsWithSheet?: boolean;
}

export interface CTConnector {
  TYPE_NAME?: 'org_docx4j_dml_spreadsheetdrawing.CTConnector';
  nvCxnSpPr: CTConnectorNonVisual;
  spPr: Dep_org_docx4j_dml.CTShapeProperties;
  style?: Dep_org_docx4j_dml.CTShapeStyle;
  macro?: string;
  fPublished?: boolean;
}

export interface CTConnectorNonVisual {
  TYPE_NAME?: 'org_docx4j_dml_spreadsheetdrawing.CTConnectorNonVisual';
  cNvPr: Dep_org_docx4j_dml.CTNonVisualDrawingProps;
  cNvCxnSpPr: Dep_org_docx4j_dml.CTNonVisualConnectorProperties;
}

export interface CTDrawing {
  TYPE_NAME?: 'org_docx4j_dml_spreadsheetdrawing.CTDrawing';
  egAnchor?: (CTTwoCellAnchor | CTOneCellAnchor | CTAbsoluteAnchor)[];
}

export interface CTGraphicalObjectFrame {
  TYPE_NAME?: 'org_docx4j_dml_spreadsheetdrawing.CTGraphicalObjectFrame';
  nvGraphicFramePr: CTGraphicalObjectFrameNonVisual;
  xfrm: Dep_org_docx4j_dml.CTTransform2D;
  graphic: Dep_org_docx4j_dml.Graphic;
  macro?: string;
  fPublished?: boolean;
}

export interface CTGraphicalObjectFrameNonVisual {
  TYPE_NAME?: 'org_docx4j_dml_spreadsheetdrawing.CTGraphicalObjectFrameNonVisual';
  cNvPr: Dep_org_docx4j_dml.CTNonVisualDrawingProps;
  cNvGraphicFramePr: Dep_org_docx4j_dml.CTNonVisualGraphicFrameProperties;
}

export interface CTGroupShape {
  TYPE_NAME?: 'org_docx4j_dml_spreadsheetdrawing.CTGroupShape';
  nvGrpSpPr: CTGroupShapeNonVisual;
  grpSpPr: Dep_org_docx4j_dml.CTGroupShapeProperties;
  spOrGrpSpOrGraphicFrame?: (CTShape | CTGroupShape | CTGraphicalObjectFrame | CTConnector | CTPicture)[];
}

export interface CTGroupShapeNonVisual {
  TYPE_NAME?: 'org_docx4j_dml_spreadsheetdrawing.CTGroupShapeNonVisual';
  cNvPr: Dep_org_docx4j_dml.CTNonVisualDrawingProps;
  cNvGrpSpPr: Dep_org_docx4j_dml.CTNonVisualGroupDrawingShapeProps;
}

export interface CTMarker {
  TYPE_NAME?: 'org_docx4j_dml_spreadsheetdrawing.CTMarker';
  col: number;
  colOff: number;
  row: number;
  rowOff: number;
}

export interface CTOneCellAnchor {
  TYPE_NAME?: 'org_docx4j_dml_spreadsheetdrawing.CTOneCellAnchor';
  from: CTMarker;
  ext: Dep_org_docx4j_dml.CTPositiveSize2D;
  sp: CTShape;
  grpSp: CTGroupShape;
  graphicFrame: CTGraphicalObjectFrame;
  cxnSp: CTConnector;
  pic: CTPicture;
  clientData: CTAnchorClientData;
}

export interface CTPicture {
  TYPE_NAME?: 'org_docx4j_dml_spreadsheetdrawing.CTPicture';
  nvPicPr: CTPictureNonVisual;
  blipFill: Dep_org_docx4j_dml.CTBlipFillProperties;
  spPr: Dep_org_docx4j_dml.CTShapeProperties;
  style?: Dep_org_docx4j_dml.CTShapeStyle;
  macro?: string;
  fPublished?: boolean;
}

export interface CTPictureNonVisual {
  TYPE_NAME?: 'org_docx4j_dml_spreadsheetdrawing.CTPictureNonVisual';
  cNvPr: Dep_org_docx4j_dml.CTNonVisualDrawingProps;
  cNvPicPr: Dep_org_docx4j_dml.CTNonVisualPictureProperties;
}

export interface CTShape {
  TYPE_NAME?: 'org_docx4j_dml_spreadsheetdrawing.CTShape';
  nvSpPr: CTShapeNonVisual;
  spPr: Dep_org_docx4j_dml.CTShapeProperties;
  style?: Dep_org_docx4j_dml.CTShapeStyle;
  txBody?: Dep_org_docx4j_dml.CTTextBody;
  macro?: string;
  textlink?: string;
  fLocksText?: boolean;
  fPublished?: boolean;
}

export interface CTShapeNonVisual {
  TYPE_NAME?: 'org_docx4j_dml_spreadsheetdrawing.CTShapeNonVisual';
  cNvPr: Dep_org_docx4j_dml.CTNonVisualDrawingProps;
  cNvSpPr: Dep_org_docx4j_dml.CTNonVisualDrawingShapeProps;
}

export interface CTTwoCellAnchor {
  TYPE_NAME?: 'org_docx4j_dml_spreadsheetdrawing.CTTwoCellAnchor';
  from: CTMarker;
  to: CTMarker;
  sp: CTShape;
  grpSp: CTGroupShape;
  graphicFrame: CTGraphicalObjectFrame;
  cxnSp: CTConnector;
  pic: CTPicture;
  clientData: CTAnchorClientData;
  editAs?: STEditAs;
}

export type STEditAs = 'twoCell' | 'oneCell' | 'absolute';

export type FromElement = TypedNamedValue<CTMarker>;

export type ToElement = TypedNamedValue<CTMarker>;

export type WsDrElement = TypedNamedValue<CTDrawing>;

/** Any global element of this mapping, i.e. what an unmarshaller returns. */
export type RootElement = FromElement | ToElement | WsDrElement;

/** The Jsonix mapping [org_docx4j_dml_spreadsheetdrawing] exported by the module's JavaScript file. */
export declare const org_docx4j_dml_spreadsheetdrawing: JsonixMapping<RootElement>;
