// Generated by jsonix-schema-compiler: Jsonix mappings of the module [org_docx4j_com_microsoft_schemas_office_word_x2012_wordprocessingDrawing] as an ES module. Do not edit.
export const org_docx4j_com_microsoft_schemas_office_word_x2012_wordprocessingDrawing = {
  name: 'org_docx4j_com_microsoft_schemas_office_word_x2012_wordprocessingDrawing',
  defaultElementNamespaceURI: 'http:\/\/schemas.microsoft.com\/office\/word\/2012\/wordprocessingDrawing',
  typeInfos: [{
      localName: 'CTWebVideoPr',
      typeName: 'CT_WebVideoPr',
      propertyInfos: [{
          name: 'embeddedHtml',
          defaultValue: '',
          attributeName: {
            localPart: 'embeddedHtml'
          },
          type: 'attribute'
        }, {
          name: 'h',
          typeInfo: 'UnsignedInt',
          defaultValue: 0,
          attributeName: {
            localPart: 'h'
          },
          type: 'attribute'
        }, {
          name: 'w',
          typeInfo: 'UnsignedInt',
          defaultValue: 0,
          attributeName: {
            localPart: 'w'
          },
          type: 'attribute'
        }]
    }],
  elementInfos: [{
      typeInfo: '.CTWebVideoPr',
      elementName: 'webVideoPr'
    }]
};
