var org_docx4j_bibliography_Module_Factory = function () {
  var org_docx4j_bibliography = {
    name: 'org_docx4j_bibliography',
    defaultElementNamespaceURI: 'http:\/\/schemas.openxmlformats.org\/officeDocument\/2006\/bibliography',
    typeInfos: [{
        localName: 'CTAuthorType',
        typeName: 'CT_AuthorType',
        propertyInfos: [{
            name: 'artistOrAuthorOrBookAuthor',
            minOccurs: 0,
            collection: true,
            mixed: false,
            allowDom: false,
            elementTypeInfos: [{
                elementName: 'Artist',
                typeInfo: '.CTNameType'
              }, {
                elementName: 'Author',
                typeInfo: '.CTNameOrCorporateType'
              }, {
                elementName: 'BookAuthor',
                typeInfo: '.CTNameType'
              }, {
                elementName: 'Compiler',
                typeInfo: '.CTNameType'
              }, {
                elementName: 'Composer',
                typeInfo: '.CTNameType'
              }, {
                elementName: 'Conductor',
                typeInfo: '.CTNameType'
              }, {
                elementName: 'Counsel',
                typeInfo: '.CTNameType'
              }, {
                elementName: 'Director',
                typeInfo: '.CTNameType'
              }, {
                elementName: 'Editor',
                typeInfo: '.CTNameType'
              }, {
                elementName: 'Interviewee',
                typeInfo: '.CTNameType'
              }, {
                elementName: 'Interviewer',
                typeInfo: '.CTNameType'
              }, {
                elementName: 'Inventor',
                typeInfo: '.CTNameType'
              }, {
                elementName: 'Performer',
                typeInfo: '.CTNameOrCorporateType'
              }, {
                elementName: 'ProducerName',
                typeInfo: '.CTNameType'
              }, {
                elementName: 'Translator',
                typeInfo: '.CTNameType'
              }, {
                elementName: 'Writer',
                typeInfo: '.CTNameType'
              }],
            type: 'elementRefs'
          }]
      }, {
        localName: 'CTNameListType',
        typeName: 'CT_NameListType',
        propertyInfos: [{
            name: 'person',
            required: true,
            collection: true,
            elementName: 'Person',
            typeInfo: '.CTPersonType'
          }]
      }, {
        localName: 'CTNameOrCorporateType',
        typeName: 'CT_NameOrCorporateType',
        propertyInfos: [{
            name: 'nameList',
            required: true,
            elementName: 'NameList',
            typeInfo: '.CTNameListType'
          }, {
            name: 'corporate',
            required: true,
            elementName: 'Corporate'
          }]
      }, {
        localName: 'CTNameType',
        typeName: 'CT_NameType',
        propertyInfos: [{
            name: 'nameList',
            required: true,
            elementName: 'NameList',
            typeInfo: '.CTNameListType'
          }]
      }, {
        localName: 'CTPersonType',
        typeName: 'CT_PersonType',
        propertyInfos: [{
            name: 'last',
            minOccurs: 0,
            collection: true,
            elementName: 'Last'
          }, {
            name: 'first',
            minOccurs: 0,
            collection: true,
            elementName: 'First'
          }, {
            name: 'middle',
            minOccurs: 0,
            collection: true,
            elementName: 'Middle'
          }]
      }, {
        localName: 'CTSourceType',
        typeName: 'CT_SourceType',
        propertyInfos: [{
            name: 'abbreviatedCaseNumberOrAlbumTitleOrAuthor',
            minOccurs: 0,
            collection: true,
            mixed: false,
            allowDom: false,
            elementTypeInfos: [{
                elementName: 'AbbreviatedCaseNumber'
              }, {
                elementName: 'AlbumTitle'
              }, {
                elementName: 'Author',
                typeInfo: '.CTAuthorType'
              }, {
                elementName: 'BookTitle'
              }, {
                elementName: 'Broadcaster'
              }, {
                elementName: 'BroadcastTitle'
              }, {
                elementName: 'CaseNumber'
              }, {
                elementName: 'ChapterNumber'
              }, {
                elementName: 'City'
              }, {
                elementName: 'Comments'
              }, {
                elementName: 'ConferenceName'
              }, {
                elementName: 'CountryRegion'
              }, {
                elementName: 'Court'
              }, {
                elementName: 'Day'
              }, {
                elementName: 'DayAccessed'
              }, {
                elementName: 'Department'
              }, {
                elementName: 'Distributor'
              }, {
                elementName: 'Edition'
              }, {
                elementName: 'Guid'
              }, {
                elementName: 'Institution'
              }, {
                elementName: 'InternetSiteTitle'
              }, {
                elementName: 'Issue'
              }, {
                elementName: 'JournalName'
              }, {
                elementName: 'LCID'
              }, {
                elementName: 'Medium'
              }, {
                elementName: 'Month'
              }, {
                elementName: 'MonthAccessed'
              }, {
                elementName: 'NumberVolumes'
              }, {
                elementName: 'Pages'
              }, {
                elementName: 'PatentNumber'
              }, {
                elementName: 'PeriodicalTitle'
              }, {
                elementName: 'ProductionCompany'
              }, {
                elementName: 'PublicationTitle'
              }, {
                elementName: 'Publisher'
              }, {
                elementName: 'RecordingNumber'
              }, {
                elementName: 'RefOrder'
              }, {
                elementName: 'Reporter'
              }, {
                elementName: 'SourceType',
                typeInfo: '.STSourceType'
              }, {
                elementName: 'ShortTitle'
              }, {
                elementName: 'StandardNumber'
              }, {
                elementName: 'StateProvince'
              }, {
                elementName: 'Station'
              }, {
                elementName: 'Tag'
              }, {
                elementName: 'Theater'
              }, {
                elementName: 'ThesisType'
              }, {
                elementName: 'Title'
              }, {
                elementName: 'Type'
              }, {
                elementName: 'URL'
              }, {
                elementName: 'Version'
              }, {
                elementName: 'Volume'
              }, {
                elementName: 'Year'
              }, {
                elementName: 'YearAccessed'
              }],
            type: 'elementRefs'
          }]
      }, {
        localName: 'CTSources',
        typeName: 'CT_Sources',
        propertyInfos: [{
            name: 'source',
            minOccurs: 0,
            collection: true,
            elementName: 'Source',
            typeInfo: '.CTSourceType'
          }, {
            name: 'selectedStyle',
            attributeName: {
              localPart: 'SelectedStyle'
            },
            type: 'attribute'
          }, {
            name: 'styleName',
            attributeName: {
              localPart: 'StyleName'
            },
            type: 'attribute'
          }, {
            name: 'uri',
            attributeName: {
              localPart: 'URI'
            },
            type: 'attribute'
          }]
      }, {
        type: 'enumInfo',
        localName: 'STSourceType',
        values: ['ArticleInAPeriodical', 'Book', 'BookSection', 'JournalArticle', 'ConferenceProceedings', 'Report', 'SoundRecording', 'Performance', 'Art', 'DocumentFromInternetSite', 'InternetSite', 'Film', 'Interview', 'Patent', 'ElectronicSource', 'Case', 'Misc']
      }],
    elementInfos: [{
        elementName: 'AbbreviatedCaseNumber',
        scope: '.CTSourceType'
      }, {
        elementName: 'AlbumTitle',
        scope: '.CTSourceType'
      }, {
        typeInfo: '.CTNameType',
        elementName: 'Artist',
        scope: '.CTAuthorType'
      }, {
        typeInfo: '.CTNameOrCorporateType',
        elementName: 'Author',
        scope: '.CTAuthorType'
      }, {
        typeInfo: '.CTAuthorType',
        elementName: 'Author',
        scope: '.CTSourceType'
      }, {
        typeInfo: '.CTNameType',
        elementName: 'BookAuthor',
        scope: '.CTAuthorType'
      }, {
        elementName: 'BookTitle',
        scope: '.CTSourceType'
      }, {
        elementName: 'BroadcastTitle',
        scope: '.CTSourceType'
      }, {
        elementName: 'Broadcaster',
        scope: '.CTSourceType'
      }, {
        elementName: 'CaseNumber',
        scope: '.CTSourceType'
      }, {
        elementName: 'ChapterNumber',
        scope: '.CTSourceType'
      }, {
        elementName: 'City',
        scope: '.CTSourceType'
      }, {
        elementName: 'Comments',
        scope: '.CTSourceType'
      }, {
        typeInfo: '.CTNameType',
        elementName: 'Compiler',
        scope: '.CTAuthorType'
      }, {
        typeInfo: '.CTNameType',
        elementName: 'Composer',
        scope: '.CTAuthorType'
      }, {
        typeInfo: '.CTNameType',
        elementName: 'Conductor',
        scope: '.CTAuthorType'
      }, {
        elementName: 'ConferenceName',
        scope: '.CTSourceType'
      }, {
        typeInfo: '.CTNameType',
        elementName: 'Counsel',
        scope: '.CTAuthorType'
      }, {
        elementName: 'CountryRegion',
        scope: '.CTSourceType'
      }, {
        elementName: 'Court',
        scope: '.CTSourceType'
      }, {
        elementName: 'Day',
        scope: '.CTSourceType'
      }, {
        elementName: 'DayAccessed',
        scope: '.CTSourceType'
      }, {
        elementName: 'Department',
        scope: '.CTSourceType'
      }, {
        typeInfo: '.CTNameType',
        elementName: 'Director',
        scope: '.CTAuthorType'
      }, {
        elementName: 'Distributor',
        scope: '.CTSourceType'
      }, {
        elementName: 'Edition',
        scope: '.CTSourceType'
      }, {
        typeInfo: '.CTNameType',
        elementName: 'Editor',
        scope: '.CTAuthorType'
      }, {
        elementName: 'Guid',
        scope: '.CTSourceType'
      }, {
        elementName: 'Institution',
        scope: '.CTSourceType'
      }, {
        elementName: 'InternetSiteTitle',
        scope: '.CTSourceType'
      }, {
        typeInfo: '.CTNameType',
        elementName: 'Interviewee',
        scope: '.CTAuthorType'
      }, {
        typeInfo: '.CTNameType',
        elementName: 'Interviewer',
        scope: '.CTAuthorType'
      }, {
        typeInfo: '.CTNameType',
        elementName: 'Inventor',
        scope: '.CTAuthorType'
      }, {
        elementName: 'Issue',
        scope: '.CTSourceType'
      }, {
        elementName: 'JournalName',
        scope: '.CTSourceType'
      }, {
        elementName: 'LCID',
        scope: '.CTSourceType'
      }, {
        elementName: 'Medium',
        scope: '.CTSourceType'
      }, {
        elementName: 'Month',
        scope: '.CTSourceType'
      }, {
        elementName: 'MonthAccessed',
        scope: '.CTSourceType'
      }, {
        elementName: 'NumberVolumes',
        scope: '.CTSourceType'
      }, {
        elementName: 'Pages',
        scope: '.CTSourceType'
      }, {
        elementName: 'PatentNumber',
        scope: '.CTSourceType'
      }, {
        typeInfo: '.CTNameOrCorporateType',
        elementName: 'Performer',
        scope: '.CTAuthorType'
      }, {
        elementName: 'PeriodicalTitle',
        scope: '.CTSourceType'
      }, {
        typeInfo: '.CTNameType',
        elementName: 'ProducerName',
        scope: '.CTAuthorType'
      }, {
        elementName: 'ProductionCompany',
        scope: '.CTSourceType'
      }, {
        elementName: 'PublicationTitle',
        scope: '.CTSourceType'
      }, {
        elementName: 'Publisher',
        scope: '.CTSourceType'
      }, {
        elementName: 'RecordingNumber',
        scope: '.CTSourceType'
      }, {
        elementName: 'RefOrder',
        scope: '.CTSourceType'
      }, {
        elementName: 'Reporter',
        scope: '.CTSourceType'
      }, {
        elementName: 'ShortTitle',
        scope: '.CTSourceType'
      }, {
        typeInfo: '.STSourceType',
        elementName: 'SourceType',
        scope: '.CTSourceType'
      }, {
        typeInfo: '.CTSources',
        elementName: 'Sources'
      }, {
        elementName: 'StandardNumber',
        scope: '.CTSourceType'
      }, {
        elementName: 'StateProvince',
        scope: '.CTSourceType'
      }, {
        elementName: 'Station',
        scope: '.CTSourceType'
      }, {
        elementName: 'Tag',
        scope: '.CTSourceType'
      }, {
        elementName: 'Theater',
        scope: '.CTSourceType'
      }, {
        elementName: 'ThesisType',
        scope: '.CTSourceType'
      }, {
        elementName: 'Title',
        scope: '.CTSourceType'
      }, {
        typeInfo: '.CTNameType',
        elementName: 'Translator',
        scope: '.CTAuthorType'
      }, {
        elementName: 'Type',
        scope: '.CTSourceType'
      }, {
        elementName: 'URL',
        scope: '.CTSourceType'
      }, {
        elementName: 'Version',
        scope: '.CTSourceType'
      }, {
        elementName: 'Volume',
        scope: '.CTSourceType'
      }, {
        typeInfo: '.CTNameType',
        elementName: 'Writer',
        scope: '.CTAuthorType'
      }, {
        elementName: 'Year',
        scope: '.CTSourceType'
      }, {
        elementName: 'YearAccessed',
        scope: '.CTSourceType'
      }]
  };
  return {
    org_docx4j_bibliography: org_docx4j_bibliography
  };
};
if (typeof define === 'function' && define.amd) {
  define([], org_docx4j_bibliography_Module_Factory);
}
else {
  var org_docx4j_bibliography_Module = org_docx4j_bibliography_Module_Factory();
  if (typeof module !== 'undefined' && module.exports) {
    module.exports.org_docx4j_bibliography = org_docx4j_bibliography_Module.org_docx4j_bibliography;
  }
  else {
    var org_docx4j_bibliography = org_docx4j_bibliography_Module.org_docx4j_bibliography;
  }
}