// Generated by jsonix-schema-compiler: TypeScript declarations for the Jsonix module [org_xlsx4j_schemas_microsoft_com_office_excel_2008_2_main]. Do not edit.
// Describes the objects Jsonix produces when unmarshalling with this module's mappings.
import type * as Dep_org_xlsx4j_schemas_microsoft_com_office_excel_2006_main from './org_xlsx4j_schemas_microsoft_com_office_excel_2006_main';

/** Jsonix.XML.QName */
export interface XmlQName { namespaceURI: string; localPart: string; prefix?: string; key?: string; string?: string; }
/** Jsonix.XML.Calendar: the representation of date, time and dateTime values; unset fields are NaN. */
export interface XmlCalendar { year?: number; month?: number; day?: number; hour?: number; minute?: number; second?: number; fractionalSecond?: number; timezone?: number; }
/** The representation of xs:duration values. */
export interface XmlDuration { sign?: number; years?: number; months?: number; days?: number; hours?: number; minutes?: number; seconds?: number; }
/** An element as returned by an unmarshaller or held by an elementRef property. */
export interface TypedNamedValue<T> { name: XmlQName; value: T; }
/** A DOM node, allowed where the mapping permits DOM content (allowDom). */
export type XmlDomNode = any;
/** The value of an anyElement property: a typed element, a DOM node or (if mixed) text. */
export type XmlAnyElement = any;
/** The value of an anyAttribute property. */
export interface XmlAnyAttributes { [attributeName: string]: string; }
/** A Jsonix mapping object as consumed by new Jsonix.Context([...]); R is the union of its global element types. */
export interface JsonixMapping<R = unknown> { readonly __rootElement?: R; readonly [key: string]: unknown; }

export interface CTDefinedName {
  TYPE_NAME?: 'org_xlsx4j_schemas_microsoft_com_office_excel_2008_2_main.CTDefinedName';
  readonly PARENT?: CTDefinedNames;
  argumentDescriptions?: CTDefinedNameArgumentDescriptions;
  name: string;
}

export interface CTDefinedNameArgumentDescription {
  TYPE_NAME?: 'org_xlsx4j_schemas_microsoft_com_office_excel_2008_2_main.CTDefinedNameArgumentDescription';
  readonly PARENT?: CTDefinedNameArgumentDescriptions;
  value?: string;
  index: number;
}

export interface CTDefinedNameArgumentDescriptions {
  TYPE_NAME?: 'org_xlsx4j_schemas_microsoft_com_office_excel_2008_2_main.CTDefinedNameArgumentDescriptions';
  readonly PARENT?: CTDefinedName;
  argumentDescription: CTDefinedNameArgumentDescription[];
  count?: number;
}

export interface CTDefinedNames {
  TYPE_NAME?: 'org_xlsx4j_schemas_microsoft_com_office_excel_2008_2_main.CTDefinedNames';
  definedName: CTDefinedName[];
}

export type MacrosheetElement = TypedNamedValue<Dep_org_xlsx4j_schemas_microsoft_com_office_excel_2006_main.CTWorksheet>;

/** Any global element of this mapping, i.e. what an unmarshaller returns. */
export type RootElement = MacrosheetElement;

/** The Jsonix mapping [org_xlsx4j_schemas_microsoft_com_office_excel_2008_2_main] exported by the module's JavaScript file. */
export declare const org_xlsx4j_schemas_microsoft_com_office_excel_2008_2_main: JsonixMapping<RootElement>;
