// Generated by jsonix-schema-compiler: Jsonix mappings of the module [org_docx4j_sharedtypes] as an ES module. Do not edit.
export const org_docx4j_sharedtypes = {
  name: 'org_docx4j_sharedtypes',
  typeInfos: [{
      type: 'enumInfo',
      localName: 'STCalendarType',
      values: ['gregorian', 'gregorianUs', 'gregorianMeFrench', 'gregorianArabic', 'hijri', 'hebrew', 'taiwan', 'japan', 'thai', 'korea', 'saka', 'gregorianXlitEnglish', 'gregorianXlitFrench', 'none']
    }, {
      type: 'enumInfo',
      localName: 'STConformanceClass',
      values: ['strict', 'transitional']
    }, {
      type: 'enumInfo',
      localName: 'STOnOff',
      values: ['true', 'false', 'on', 'off', '0', '1']
    }, {
      type: 'enumInfo',
      localName: 'STVerticalAlignRun',
      values: ['baseline', 'superscript', 'subscript']
    }, {
      type: 'enumInfo',
      localName: 'STXAlign',
      values: ['left', 'center', 'right', 'inside', 'outside']
    }, {
      type: 'enumInfo',
      localName: 'STYAlign',
      values: ['inline', 'top', 'center', 'bottom', 'inside', 'outside']
    }],
  elementInfos: []
};
