// Generated by jsonix-schema-compiler: Jsonix mappings of the module [org_pptx4j_com_microsoft_schemas_office_powerpoint_x201804_main] as an ES module. Do not edit.
export const org_pptx4j_com_microsoft_schemas_office_powerpoint_x201804_main = {
  name: 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x201804_main',
  defaultElementNamespaceURI: 'http:\/\/schemas.microsoft.com\/office\/powerpoint\/2018\/4\/main',
  typeInfos: [{
      localName: 'CTClassificationOutcome',
      typeName: 'CT_ClassificationOutcome',
      propertyInfos: [{
          name: 'val',
          typeInfo: '.STClassificationOutcomeType',
          attributeName: {
            localPart: 'val'
          },
          type: 'attribute'
        }]
    }, {
      type: 'enumInfo',
      localName: 'STClassificationOutcomeType',
      baseTypeInfo: 'Token',
      values: ['none', 'hdr', 'ftr', 'watermark']
    }],
  elementInfos: [{
      typeInfo: '.CTClassificationOutcome',
      elementName: 'classification'
    }]
};
