// Generated by jsonix-schema-compiler: Jsonix mappings of the module [org_docx4j_dml_compatibility] as an ES module. Do not edit.
export const org_docx4j_dml_compatibility = {
  name: 'org_docx4j_dml_compatibility',
  defaultElementNamespaceURI: 'http:\/\/schemas.openxmlformats.org\/drawingml\/2006\/compatibility',
  typeInfos: [{
      localName: 'CTCompat',
      typeName: 'CT_Compat',
      propertyInfos: [{
          name: 'spid',
          required: true,
          typeInfo: 'Token',
          attributeName: {
            localPart: 'spid'
          },
          type: 'attribute'
        }]
    }],
  elementInfos: [{
      typeInfo: '.CTCompat',
      elementName: 'legacyDrawing'
    }]
};
