// Generated by jsonix-schema-compiler: Jsonix mappings of the module [org_docx4j_com_microsoft_schemas_office_drawing_x2014_main] as an ES module. Do not edit.
export const org_docx4j_com_microsoft_schemas_office_drawing_x2014_main = {
  name: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_main',
  defaultElementNamespaceURI: 'http:\/\/schemas.microsoft.com\/office\/drawing\/2014\/main',
  typeInfos: [{
      localName: 'CTConnectableReferences',
      typeName: 'CT_ConnectableReferences',
      propertyInfos: [{
          name: 'end',
          typeInfo: 'Token',
          attributeName: {
            localPart: 'end'
          },
          type: 'attribute'
        }, {
          name: 'st',
          typeInfo: 'Token',
          attributeName: {
            localPart: 'st'
          },
          type: 'attribute'
        }]
    }, {
      localName: 'CTCreationId',
      typeName: 'CT_CreationId',
      propertyInfos: [{
          name: 'id',
          typeInfo: 'Token',
          attributeName: {
            localPart: 'id'
          },
          type: 'attribute'
        }]
    }, {
      localName: 'CTIdentifier',
      typeName: 'CT_Identifier',
      propertyInfos: [{
          name: 'val',
          required: true,
          typeInfo: 'UnsignedInt',
          attributeName: {
            localPart: 'val'
          },
          type: 'attribute'
        }]
    }, {
      localName: 'CTPredecessorDrawingElementReference',
      typeName: 'CT_PredecessorDrawingElementReference',
      propertyInfos: [{
          name: 'pred',
          typeInfo: 'Token',
          attributeName: {
            localPart: 'pred'
          },
          type: 'attribute'
        }]
    }],
  elementInfos: [{
      typeInfo: '.CTIdentifier',
      elementName: 'colId'
    }, {
      typeInfo: '.CTCreationId',
      elementName: 'creationId'
    }, {
      typeInfo: '.CTConnectableReferences',
      elementName: 'cxnDERefs'
    }, {
      typeInfo: '.CTPredecessorDrawingElementReference',
      elementName: 'predDERef'
    }, {
      typeInfo: '.CTIdentifier',
      elementName: 'rowId'
    }]
};
