// Generated by jsonix-schema-compiler: TypeScript declarations for the Jsonix module [org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex]. Do not edit.
// Describes the objects Jsonix produces when unmarshalling with this module's mappings.
import type * as Dep_org_docx4j_dml from './org_docx4j_dml';

/** Jsonix.XML.QName */
export interface XmlQName { namespaceURI: string; localPart: string; prefix?: string; key?: string; string?: string; }
/** Jsonix.XML.Calendar: the representation of date, time and dateTime values; unset fields are NaN. */
export interface XmlCalendar { year?: number; month?: number; day?: number; hour?: number; minute?: number; second?: number; fractionalSecond?: number; timezone?: number; }
/** The representation of xs:duration values. */
export interface XmlDuration { sign?: number; years?: number; months?: number; days?: number; hours?: number; minutes?: number; seconds?: number; }
/** An element as returned by an unmarshaller or held by an elementRef property. */
export interface TypedNamedValue<T> { name: XmlQName; value: T; }
/** A DOM node, allowed where the mapping permits DOM content (allowDom). */
export type XmlDomNode = any;
/** The value of an anyElement property: a typed element, a DOM node or (if mixed) text. */
export type XmlAnyElement = any;
/** The value of an anyAttribute property. */
export interface XmlAnyAttributes { [attributeName: string]: string; }
/** A Jsonix mapping object as consumed by new Jsonix.Context([...]); R is the union of its global element types. */
export interface JsonixMapping<R = unknown> { readonly __rootElement?: R; readonly [key: string]: unknown; }

export interface CTAddress {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTAddress';
  readonly PARENT?: CTGeoLocation;
  address1?: string;
  adminDistrict1?: string;
  adminDistrict2?: string;
  countryRegion?: string;
  isoCountryCode?: string;
  locality?: string;
  postalCode?: string;
}

export interface CTAggregation {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTAggregation';
  readonly PARENT?: CTSeriesLayoutProperties;
}

export interface CTAxis {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTAxis';
  readonly PARENT?: CTPlotArea;
  catScaling: CTCategoryAxisScaling;
  valScaling: CTValueAxisScaling;
  title?: CTAxisTitle;
  units?: CTAxisUnits;
  majorGridlines?: CTGridlines;
  minorGridlines?: CTGridlines;
  majorTickMarks?: CTTickMarks;
  minorTickMarks?: CTTickMarks;
  tickLabels?: CTTickLabels;
  numFmt?: CTNumberFormat;
  spPr?: Dep_org_docx4j_dml.CTShapeProperties;
  txPr?: Dep_org_docx4j_dml.CTTextBody;
  extLst?: CTExtensionList;
  hidden?: boolean;
  id: number;
}

export interface CTAxisId {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTAxisId';
  readonly PARENT?: CTSeries;
  val: number;
}

export interface CTAxisTitle {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTAxisTitle';
  readonly PARENT?: CTAxis;
  tx?: CTText;
  spPr?: Dep_org_docx4j_dml.CTShapeProperties;
  txPr?: Dep_org_docx4j_dml.CTTextBody;
  extLst?: CTExtensionList;
}

export interface CTAxisUnits {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTAxisUnits';
  readonly PARENT?: CTAxis;
  unitsLabel?: CTAxisUnitsLabel;
  extLst?: CTExtensionList;
  unit?: STAxisUnit;
}

export interface CTAxisUnitsLabel {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTAxisUnitsLabel';
  readonly PARENT?: CTAxisUnits;
  tx?: CTText;
  spPr?: Dep_org_docx4j_dml.CTShapeProperties;
  txPr?: Dep_org_docx4j_dml.CTTextBody;
  extLst?: CTExtensionList;
}

export interface CTBinning {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTBinning';
  readonly PARENT?: CTSeriesLayoutProperties;
  binSize: number;
  binCount: number;
  intervalClosed?: STIntervalClosedSide;
  overflow?: string;
  underflow?: string;
}

export interface CTCategoryAxisScaling {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTCategoryAxisScaling';
  readonly PARENT?: CTAxis;
  gapWidth?: string;
}

export interface CTChart {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTChart';
  readonly PARENT?: CTChartSpace;
  title?: CTChartTitle;
  plotArea: CTPlotArea;
  legend?: CTLegend;
  extLst?: CTExtensionList;
}

export interface CTChartData {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTChartData';
  readonly PARENT?: CTChartSpace;
  externalData?: CTExternalData;
  data: CTData[];
  extLst?: CTExtensionList;
}

export interface CTChartSpace {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTChartSpace';
  chartData: CTChartData;
  chart: CTChart;
  spPr?: Dep_org_docx4j_dml.CTShapeProperties;
  txPr?: Dep_org_docx4j_dml.CTTextBody;
  clrMapOvr?: Dep_org_docx4j_dml.CTColorMapping;
  fmtOvrs?: CTFormatOverrides;
  printSettings?: CTPrintSettings;
  extLst?: CTExtensionList;
}

export interface CTChartTitle {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTChartTitle';
  readonly PARENT?: CTChart;
  tx?: CTText;
  spPr?: Dep_org_docx4j_dml.CTShapeProperties;
  txPr?: Dep_org_docx4j_dml.CTTextBody;
  extLst?: CTExtensionList;
  align?: STPosAlign;
  overlay?: boolean;
  pos?: STSidePos;
}

export interface CTClear {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTClear';
  readonly PARENT?: CTGeoCache;
  geoLocationQueryResults?: CTGeoLocationQueryResults;
  geoDataEntityQueryResults?: CTGeoDataEntityQueryResults;
  geoDataPointToEntityQueryResults?: CTGeoDataPointToEntityQueryResults;
  geoChildEntitiesQueryResults?: CTGeoChildEntitiesQueryResults;
  geoParentEntitiesQueryResults?: CTGeoParentEntitiesQueryResults;
}

export interface CTCopyrights {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTCopyrights';
  readonly PARENT?: CTGeoData;
  copyright?: string[];
}

export interface CTData {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTData';
  readonly PARENT?: CTChartData;
  numDimOrStrDim: (CTNumericDimension | CTStringDimension)[];
  extLst?: CTExtensionList;
  id: number;
}

export interface CTDataId {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTDataId';
  readonly PARENT?: CTSeries;
  val: number;
}

export interface CTDataLabel {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTDataLabel';
  readonly PARENT?: CTDataLabels;
  numFmt?: CTNumberFormat;
  spPr?: Dep_org_docx4j_dml.CTShapeProperties;
  txPr?: Dep_org_docx4j_dml.CTTextBody;
  visibility?: CTDataLabelVisibilities;
  separator?: string;
  extLst?: CTExtensionList;
  idx: number;
  pos?: STDataLabelPos;
}

export interface CTDataLabelHidden {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTDataLabelHidden';
  readonly PARENT?: CTDataLabels;
  idx: number;
}

export interface CTDataLabelVisibilities {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTDataLabelVisibilities';
  readonly PARENT?: CTDataLabel | CTDataLabels;
  categoryName?: boolean;
  seriesName?: boolean;
  value?: boolean;
}

export interface CTDataLabels {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTDataLabels';
  readonly PARENT?: CTSeries;
  numFmt?: CTNumberFormat;
  spPr?: Dep_org_docx4j_dml.CTShapeProperties;
  txPr?: Dep_org_docx4j_dml.CTTextBody;
  visibility?: CTDataLabelVisibilities;
  separator?: string;
  dataLabel?: CTDataLabel[];
  dataLabelHidden?: CTDataLabelHidden[];
  extLst?: CTExtensionList;
  pos?: STDataLabelPos;
}

export interface CTDataPoint {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTDataPoint';
  readonly PARENT?: CTSeries;
  spPr?: Dep_org_docx4j_dml.CTShapeProperties;
  extLst?: CTExtensionList;
  idx: number;
}

export interface CTExtension {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTExtension';
  readonly PARENT?: CTExtensionList;
  any: XmlAnyElement;
  uri?: string;
}

export interface CTExtensionList {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTExtensionList';
  readonly PARENT?: CTAxis | CTAxisTitle | CTAxisUnits | CTAxisUnitsLabel | CTChart | CTChartData | CTChartSpace | CTChartTitle | CTData | CTDataLabel | CTDataLabels | CTDataPoint | CTFormatOverride | CTGridlines | CTLegend | CTPlotArea | CTPlotAreaRegion | CTPlotSurface | CTSeries | CTSeriesLayoutProperties | CTTickLabels | CTTickMarks;
  ext?: CTExtension[];
}

export interface CTExternalData {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTExternalData';
  readonly PARENT?: CTChartData;
  autoUpdate?: boolean;
  id: string;
}

export interface CTExtremeValueColorPosition {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTExtremeValueColorPosition';
  readonly PARENT?: CTValueColorEndPosition;
}

export interface CTFormatOverride {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTFormatOverride';
  readonly PARENT?: CTFormatOverrides;
  spPr?: Dep_org_docx4j_dml.CTShapeProperties;
  extLst?: CTExtensionList;
  idx: number;
}

export interface CTFormatOverrides {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTFormatOverrides';
  readonly PARENT?: CTChartSpace;
  fmtOvr?: CTFormatOverride[];
}

export interface CTFormula {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTFormula';
  readonly PARENT?: CTNumericDimension | CTStringDimension | CTTextData;
  value?: string;
  dir?: STFormulaDirection;
}

export interface CTGeoCache {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTGeoCache';
  readonly PARENT?: CTGeography;
  binaryOrClear?: (string | CTClear)[];
  provider: string;
}

export interface CTGeoChildEntities {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTGeoChildEntities';
  readonly PARENT?: CTGeoChildEntitiesQueryResult;
  geoHierarchyEntity?: CTGeoHierarchyEntity[];
}

export interface CTGeoChildEntitiesQuery {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTGeoChildEntitiesQuery';
  readonly PARENT?: CTGeoChildEntitiesQueryResult;
  geoChildTypes?: CTGeoChildTypes;
  entityId: string;
}

export interface CTGeoChildEntitiesQueryResult {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTGeoChildEntitiesQueryResult';
  readonly PARENT?: CTGeoChildEntitiesQueryResults;
  geoChildEntitiesQuery?: CTGeoChildEntitiesQuery;
  geoChildEntities?: CTGeoChildEntities;
}

export interface CTGeoChildEntitiesQueryResults {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTGeoChildEntitiesQueryResults';
  readonly PARENT?: CTClear;
  geoChildEntitiesQueryResult?: CTGeoChildEntitiesQueryResult[];
}

export interface CTGeoChildTypes {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTGeoChildTypes';
  readonly PARENT?: CTGeoChildEntitiesQuery;
  entityType?: STEntityType[];
}

export interface CTGeoData {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTGeoData';
  readonly PARENT?: CTGeoDataEntityQueryResult;
  geoPolygons?: CTGeoPolygons;
  copyrights?: CTCopyrights;
  east: number;
  entityId: string;
  entityName: string;
  north: number;
  south: number;
  west: number;
}

export interface CTGeoDataEntityQuery {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTGeoDataEntityQuery';
  readonly PARENT?: CTGeoDataEntityQueryResult;
  entityId: string;
  entityType: STEntityType;
}

export interface CTGeoDataEntityQueryResult {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTGeoDataEntityQueryResult';
  readonly PARENT?: CTGeoDataEntityQueryResults;
  geoDataEntityQuery?: CTGeoDataEntityQuery;
  geoData?: CTGeoData;
}

export interface CTGeoDataEntityQueryResults {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTGeoDataEntityQueryResults';
  readonly PARENT?: CTClear;
  geoDataEntityQueryResult?: CTGeoDataEntityQueryResult[];
}

export interface CTGeoDataPointQuery {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTGeoDataPointQuery';
  readonly PARENT?: CTGeoDataPointToEntityQueryResult;
  entityType: STEntityType;
  latitude: number;
  longitude: number;
}

export interface CTGeoDataPointToEntityQuery {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTGeoDataPointToEntityQuery';
  readonly PARENT?: CTGeoDataPointToEntityQueryResult;
  entityId: string;
  entityType: STEntityType;
}

export interface CTGeoDataPointToEntityQueryResult {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTGeoDataPointToEntityQueryResult';
  readonly PARENT?: CTGeoDataPointToEntityQueryResults;
  geoDataPointQuery?: CTGeoDataPointQuery;
  geoDataPointToEntityQuery?: CTGeoDataPointToEntityQuery;
}

export interface CTGeoDataPointToEntityQueryResults {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTGeoDataPointToEntityQueryResults';
  readonly PARENT?: CTClear;
  geoDataPointToEntityQueryResult?: CTGeoDataPointToEntityQueryResult[];
}

export interface CTGeoEntity {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTGeoEntity';
  readonly PARENT?: CTGeoParentEntitiesQueryResult;
  entityName: string;
  entityType: STEntityType;
}

export interface CTGeoHierarchyEntity {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTGeoHierarchyEntity';
  readonly PARENT?: CTGeoChildEntities;
  entityId: string;
  entityName: string;
  entityType: STEntityType;
}

export interface CTGeoLocation {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTGeoLocation';
  readonly PARENT?: CTGeoLocations;
  address?: CTAddress;
  entityName: string;
  entityType: STEntityType;
  latitude?: number;
  longitude?: number;
}

export interface CTGeoLocationQuery {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTGeoLocationQuery';
  readonly PARENT?: CTGeoLocationQueryResult;
  adminDistrict1?: string;
  adminDistrict2?: string;
  countryRegion?: string;
  entityType: STEntityType;
  postalCode?: string;
}

export interface CTGeoLocationQueryResult {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTGeoLocationQueryResult';
  readonly PARENT?: CTGeoLocationQueryResults;
  geoLocationQuery?: CTGeoLocationQuery;
  geoLocations?: CTGeoLocations;
}

export interface CTGeoLocationQueryResults {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTGeoLocationQueryResults';
  readonly PARENT?: CTClear;
  geoLocationQueryResult?: CTGeoLocationQueryResult[];
}

export interface CTGeoLocations {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTGeoLocations';
  readonly PARENT?: CTGeoLocationQueryResult;
  geoLocation?: CTGeoLocation;
}

export interface CTGeoParentEntitiesQuery {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTGeoParentEntitiesQuery';
  readonly PARENT?: CTGeoParentEntitiesQueryResult;
  entityId: string;
}

export interface CTGeoParentEntitiesQueryResult {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTGeoParentEntitiesQueryResult';
  readonly PARENT?: CTGeoParentEntitiesQueryResults;
  geoParentEntitiesQuery: CTGeoParentEntitiesQuery;
  geoEntity?: CTGeoEntity;
  geoParentEntity?: CTGeoParentEntity;
}

export interface CTGeoParentEntitiesQueryResults {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTGeoParentEntitiesQueryResults';
  readonly PARENT?: CTClear;
  geoParentEntitiesQueryResult?: CTGeoParentEntitiesQueryResult[];
}

export interface CTGeoParentEntity {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTGeoParentEntity';
  readonly PARENT?: CTGeoParentEntitiesQueryResult;
  entityId: string;
}

export interface CTGeoPolygon {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTGeoPolygon';
  readonly PARENT?: CTGeoPolygons;
  numPoints: number;
  pcaRings: string;
  polygonId: string;
}

export interface CTGeoPolygons {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTGeoPolygons';
  readonly PARENT?: CTGeoData;
  geoPolygon?: CTGeoPolygon[];
}

export interface CTGeography {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTGeography';
  readonly PARENT?: CTSeriesLayoutProperties;
  geoCache?: CTGeoCache;
  attribution: string;
  cultureLanguage: string;
  cultureRegion: string;
  projectionType?: STGeoProjectionType;
  viewedRegionType?: STGeoMappingLevel;
}

export interface CTGridlines {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTGridlines';
  readonly PARENT?: CTAxis;
  spPr?: Dep_org_docx4j_dml.CTShapeProperties;
  extLst?: CTExtensionList;
}

export interface CTHeaderFooter {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTHeaderFooter';
  readonly PARENT?: CTPrintSettings;
  oddHeader?: string;
  oddFooter?: string;
  evenHeader?: string;
  evenFooter?: string;
  firstHeader?: string;
  firstFooter?: string;
  alignWithMargins?: boolean;
  differentFirst?: boolean;
  differentOddEven?: boolean;
}

export interface CTLegend {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTLegend';
  readonly PARENT?: CTChart;
  spPr?: Dep_org_docx4j_dml.CTShapeProperties;
  txPr?: Dep_org_docx4j_dml.CTTextBody;
  extLst?: CTExtensionList;
  align?: STPosAlign;
  overlay?: boolean;
  pos?: STSidePos;
}

export interface CTNumberColorPosition {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTNumberColorPosition';
  readonly PARENT?: CTValueColorEndPosition | CTValueColorMiddlePosition;
  val: number;
}

export interface CTNumberFormat {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTNumberFormat';
  readonly PARENT?: CTAxis | CTDataLabel | CTDataLabels;
  formatCode: string;
  sourceLinked?: boolean;
}

export interface CTNumericDimension {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTNumericDimension';
  readonly PARENT?: CTData;
  content: (TypedNamedValue<CTFormula> | TypedNamedValue<CTNumericLevel>)[];
  type: STNumericDimensionType;
}

export interface CTNumericLevel {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTNumericLevel';
  readonly PARENT?: CTNumericDimension;
  pt?: CTNumericValue[];
  formatCode?: string;
  name?: string;
  ptCount: number;
}

export interface CTNumericValue {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTNumericValue';
  readonly PARENT?: CTNumericLevel;
  value?: number;
  idx: number;
}

export interface CTPageMargins {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTPageMargins';
  readonly PARENT?: CTPrintSettings;
  b: number;
  footer: number;
  header: number;
  l: number;
  r: number;
  t: number;
}

export interface CTPageSetup {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTPageSetup';
  readonly PARENT?: CTPrintSettings;
  blackAndWhite?: boolean;
  copies?: number;
  draft?: boolean;
  firstPageNumber?: number;
  horizontalDpi?: number;
  orientation?: STPageOrientation;
  paperSize?: number;
  useFirstPageNumber?: boolean;
  verticalDpi?: number;
}

export interface CTParentLabelLayout {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTParentLabelLayout';
  readonly PARENT?: CTSeriesLayoutProperties;
  val: STParentLabelLayout;
}

export interface CTPercentageColorPosition {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTPercentageColorPosition';
  readonly PARENT?: CTValueColorEndPosition | CTValueColorMiddlePosition;
  val: number;
}

export interface CTPlotArea {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTPlotArea';
  readonly PARENT?: CTChart;
  plotAreaRegion: CTPlotAreaRegion;
  axis?: CTAxis[];
  spPr?: Dep_org_docx4j_dml.CTShapeProperties;
  extLst?: CTExtensionList;
}

export interface CTPlotAreaRegion {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTPlotAreaRegion';
  readonly PARENT?: CTPlotArea;
  plotSurface?: CTPlotSurface;
  series?: CTSeries[];
  extLst?: CTExtensionList;
}

export interface CTPlotSurface {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTPlotSurface';
  readonly PARENT?: CTPlotAreaRegion;
  spPr?: Dep_org_docx4j_dml.CTShapeProperties;
  extLst?: CTExtensionList;
}

export interface CTPrintSettings {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTPrintSettings';
  readonly PARENT?: CTChartSpace;
  headerFooter?: CTHeaderFooter;
  pageMargins?: CTPageMargins;
  pageSetup?: CTPageSetup;
}

export interface CTRegionLabelLayout {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTRegionLabelLayout';
  readonly PARENT?: CTSeriesLayoutProperties;
  val: STRegionLabelLayout;
}

export interface CTRelId {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTRelId';
  id: string;
}

export interface CTSeries {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTSeries';
  readonly PARENT?: CTPlotAreaRegion;
  tx?: CTText;
  spPr?: Dep_org_docx4j_dml.CTShapeProperties;
  valueColors?: CTValueColors;
  valueColorPositions?: CTValueColorPositions;
  dataPt?: CTDataPoint[];
  dataLabels?: CTDataLabels;
  dataId?: CTDataId;
  layoutPr?: CTSeriesLayoutProperties;
  axisId?: CTAxisId[];
  extLst?: CTExtensionList;
  formatIdx?: number;
  hidden?: boolean;
  layoutId: STSeriesLayout;
  ownerIdx?: number;
  uniqueId?: string;
}

export interface CTSeriesElementVisibilities {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTSeriesElementVisibilities';
  readonly PARENT?: CTSeriesLayoutProperties;
  connectorLines?: boolean;
  meanLine?: boolean;
  meanMarker?: boolean;
  nonoutliers?: boolean;
  outliers?: boolean;
}

export interface CTSeriesLayoutProperties {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTSeriesLayoutProperties';
  readonly PARENT?: CTSeries;
  parentLabelLayout?: CTParentLabelLayout;
  regionLabelLayout?: CTRegionLabelLayout;
  visibility?: CTSeriesElementVisibilities;
  aggregation?: CTAggregation;
  binning?: CTBinning;
  geography?: CTGeography;
  statistics?: CTStatistics;
  subtotals?: CTSubtotals;
  extLst?: CTExtensionList;
}

export interface CTStatistics {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTStatistics';
  readonly PARENT?: CTSeriesLayoutProperties;
  quartileMethod?: STQuartileMethod;
}

export interface CTStringDimension {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTStringDimension';
  readonly PARENT?: CTData;
  content: (TypedNamedValue<CTFormula> | TypedNamedValue<CTStringLevel>)[];
  type: STStringDimensionType;
}

export interface CTStringLevel {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTStringLevel';
  readonly PARENT?: CTStringDimension;
  pt?: CTStringValue[];
  name?: string;
  ptCount: number;
}

export interface CTStringValue {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTStringValue';
  readonly PARENT?: CTStringLevel;
  value?: string;
  idx: number;
}

export interface CTSubtotalIndex {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTSubtotalIndex';
  readonly PARENT?: CTSubtotals;
  val: number;
}

export interface CTSubtotals {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTSubtotals';
  readonly PARENT?: CTSeriesLayoutProperties;
  idx?: CTSubtotalIndex[];
}

export interface CTText {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTText';
  readonly PARENT?: CTAxisTitle | CTAxisUnitsLabel | CTChartTitle | CTSeries;
  txData: CTTextData;
  rich: Dep_org_docx4j_dml.CTTextBody;
}

export interface CTTextData {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTTextData';
  readonly PARENT?: CTText;
  content: (TypedNamedValue<CTFormula> | TypedNamedValue<string>)[];
}

export interface CTTickLabels {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTTickLabels';
  readonly PARENT?: CTAxis;
  extLst?: CTExtensionList;
}

export interface CTTickMarks {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTTickMarks';
  readonly PARENT?: CTAxis;
  extLst?: CTExtensionList;
  type?: STTickMarksType;
}

export interface CTValueAxisScaling {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTValueAxisScaling';
  readonly PARENT?: CTAxis;
  majorUnit?: string;
  max?: string;
  min?: string;
  minorUnit?: string;
}

export interface CTValueColorEndPosition {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTValueColorEndPosition';
  readonly PARENT?: CTValueColorPositions;
  extremeValue: CTExtremeValueColorPosition;
  number: CTNumberColorPosition;
  percent: CTPercentageColorPosition;
}

export interface CTValueColorMiddlePosition {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTValueColorMiddlePosition';
  readonly PARENT?: CTValueColorPositions;
  number: CTNumberColorPosition;
  percent: CTPercentageColorPosition;
}

export interface CTValueColorPositions {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTValueColorPositions';
  readonly PARENT?: CTSeries;
  min?: CTValueColorEndPosition;
  mid?: CTValueColorMiddlePosition;
  max?: CTValueColorEndPosition;
  count?: number;
}

export interface CTValueColors {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTValueColors';
  readonly PARENT?: CTSeries;
  minColor?: Dep_org_docx4j_dml.CTSolidColorFillProperties;
  midColor?: Dep_org_docx4j_dml.CTSolidColorFillProperties;
  maxColor?: Dep_org_docx4j_dml.CTSolidColorFillProperties;
}

export type STAxisUnit = 'hundreds' | 'thousands' | 'tenThousands' | 'hundredThousands' | 'millions' | 'tenMillions' | 'hundredMillions' | 'billions' | 'trillions' | 'percentage';

export type STDataLabelPos = 'bestFit' | 'b' | 'ctr' | 'inBase' | 'inEnd' | 'l' | 'outEnd' | 'r' | 't';

export type STEntityType = 'Address' | 'AdminDistrict' | 'AdminDistrict2' | 'AdminDistrict3' | 'Continent' | 'CountryRegion' | 'Locality' | 'Ocean' | 'Planet' | 'PostalCode' | 'Region' | 'Unsupported';

export type STFormulaDirection = 'col' | 'row';

export type STGeoMappingLevel = 'dataOnly' | 'postalCode' | 'county' | 'state' | 'countryRegion' | 'countryRegionList' | 'world';

export type STGeoProjectionType = 'mercator' | 'miller' | 'robinson' | 'albers';

export type STIntervalClosedSide = 'l' | 'r';

export type STNumericDimensionType = 'val' | 'x' | 'y' | 'size' | 'colorVal';

export type STPageOrientation = 'default' | 'portrait' | 'landscape';

export type STParentLabelLayout = 'none' | 'banner' | 'overlapping';

export type STPosAlign = 'min' | 'ctr' | 'max';

export type STQuartileMethod = 'inclusive' | 'exclusive';

export type STRegionLabelLayout = 'none' | 'bestFitOnly' | 'showAll';

export type STSeriesLayout = 'boxWhisker' | 'clusteredColumn' | 'funnel' | 'paretoLine' | 'regionMap' | 'sunburst' | 'treemap' | 'waterfall';

export type STSidePos = 'l' | 't' | 'r' | 'b';

export type STStringDimensionType = 'cat' | 'colorStr' | 'entityId';

export type STTickMarksType = 'in' | 'out' | 'cross' | 'none';

export type ChartElement = TypedNamedValue<CTRelId>;

export type ChartSpaceElement = TypedNamedValue<CTChartSpace>;

/** Any global element of this mapping, i.e. what an unmarshaller returns. */
export type RootElement = ChartElement | ChartSpaceElement;

export namespace CTNumericDimension {
  export type FElement = TypedNamedValue<CTFormula>;

  export type LvlElement = TypedNamedValue<CTNumericLevel>;

  export type NfElement = TypedNamedValue<CTFormula>;
}

export namespace CTStringDimension {
  export type FElement = TypedNamedValue<CTFormula>;

  export type LvlElement = TypedNamedValue<CTStringLevel>;

  export type NfElement = TypedNamedValue<CTFormula>;
}

export namespace CTTextData {
  export type FElement = TypedNamedValue<CTFormula>;

  export type VElement = TypedNamedValue<string>;
}

/** The Jsonix mapping [org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex] exported by the module's JavaScript file. */
export declare const org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex: JsonixMapping<RootElement>;
