// Generated by jsonix-schema-compiler: Jsonix mappings of the module [org_docx4j_dml_diagram] as an ES module. Do not edit.
export const org_docx4j_dml_diagram = {
  name: 'org_docx4j_dml_diagram',
  defaultElementNamespaceURI: 'http:\/\/schemas.openxmlformats.org\/drawingml\/2006\/diagram',
  dependencies: ['org_docx4j_dml'],
  typeInfos: [{
      localName: 'CTAdj',
      typeName: 'CT_Adj',
      propertyInfos: [{
          name: 'idx',
          required: true,
          typeInfo: 'UnsignedInt',
          attributeName: {
            localPart: 'idx'
          },
          type: 'attribute'
        }, {
          name: 'val',
          required: true,
          typeInfo: 'Double',
          attributeName: {
            localPart: 'val'
          },
          type: 'attribute'
        }]
    }, {
      localName: 'CTAdjLst',
      typeName: 'CT_AdjLst',
      propertyInfos: [{
          name: 'adj',
          minOccurs: 0,
          collection: true,
          typeInfo: '.CTAdj'
        }]
    }, {
      localName: 'CTAlgorithm',
      typeName: 'CT_Algorithm',
      propertyInfos: [{
          name: 'param',
          minOccurs: 0,
          collection: true,
          typeInfo: '.CTParameter'
        }, {
          name: 'extLst',
          typeInfo: 'org_docx4j_dml.CTOfficeArtExtensionList'
        }, {
          name: 'rev',
          typeInfo: 'UnsignedInt',
          defaultValue: 0,
          attributeName: {
            localPart: 'rev'
          },
          type: 'attribute'
        }, {
          name: 'type',
          required: true,
          typeInfo: '.STAlgorithmType',
          attributeName: {
            localPart: 'type'
          },
          type: 'attribute'
        }]
    }, {
      localName: 'CTAnimLvl',
      typeName: 'CT_AnimLvl',
      propertyInfos: [{
          name: 'val',
          typeInfo: '.STAnimLvlStr',
          defaultValue: 'none',
          attributeName: {
            localPart: 'val'
          },
          type: 'attribute'
        }]
    }, {
      localName: 'CTAnimOne',
      typeName: 'CT_AnimOne',
      propertyInfos: [{
          name: 'val',
          typeInfo: '.STAnimOneStr',
          defaultValue: 'one',
          attributeName: {
            localPart: 'val'
          },
          type: 'attribute'
        }]
    }, {
      localName: 'CTBulletEnabled',
      typeName: 'CT_BulletEnabled',
      propertyInfos: [{
          name: 'val',
          typeInfo: 'Boolean',
          defaultValue: false,
          attributeName: {
            localPart: 'val'
          },
          type: 'attribute'
        }]
    }, {
      localName: 'CTCTCategories',
      typeName: 'CT_CTCategories',
      propertyInfos: [{
          name: 'cat',
          minOccurs: 0,
          collection: true,
          typeInfo: '.CTCTCategory'
        }]
    }, {
      localName: 'CTCTCategory',
      typeName: 'CT_CTCategory',
      propertyInfos: [{
          name: 'pri',
          required: true,
          typeInfo: 'UnsignedInt',
          attributeName: {
            localPart: 'pri'
          },
          type: 'attribute'
        }, {
          name: 'type',
          required: true,
          attributeName: {
            localPart: 'type'
          },
          type: 'attribute'
        }]
    }, {
      localName: 'CTCTDescription',
      typeName: 'CT_CTDescription',
      propertyInfos: [{
          name: 'lang',
          defaultValue: '',
          attributeName: {
            localPart: 'lang'
          },
          type: 'attribute'
        }, {
          name: 'val',
          required: true,
          attributeName: {
            localPart: 'val'
          },
          type: 'attribute'
        }]
    }, {
      localName: 'CTCTName',
      typeName: 'CT_CTName',
      propertyInfos: [{
          name: 'lang',
          defaultValue: '',
          attributeName: {
            localPart: 'lang'
          },
          type: 'attribute'
        }, {
          name: 'val',
          required: true,
          attributeName: {
            localPart: 'val'
          },
          type: 'attribute'
        }]
    }, {
      localName: 'CTCTStyleLabel',
      typeName: 'CT_CTStyleLabel',
      propertyInfos: [{
          name: 'fillClrLst',
          typeInfo: '.CTColors'
        }, {
          name: 'linClrLst',
          typeInfo: '.CTColors'
        }, {
          name: 'effectClrLst',
          typeInfo: '.CTColors'
        }, {
          name: 'txLinClrLst',
          typeInfo: '.CTColors'
        }, {
          name: 'txFillClrLst',
          typeInfo: '.CTColors'
        }, {
          name: 'txEffectClrLst',
          typeInfo: '.CTColors'
        }, {
          name: 'extLst',
          typeInfo: 'org_docx4j_dml.CTOfficeArtExtensionList'
        }, {
          name: 'name',
          required: true,
          attributeName: {
            localPart: 'name'
          },
          type: 'attribute'
        }]
    }, {
      localName: 'CTCategories',
      typeName: 'CT_Categories',
      propertyInfos: [{
          name: 'cat',
          minOccurs: 0,
          collection: true,
          typeInfo: '.CTCategory'
        }]
    }, {
      localName: 'CTCategory',
      typeName: 'CT_Category',
      propertyInfos: [{
          name: 'pri',
          required: true,
          typeInfo: 'UnsignedInt',
          attributeName: {
            localPart: 'pri'
          },
          type: 'attribute'
        }, {
          name: 'type',
          required: true,
          attributeName: {
            localPart: 'type'
          },
          type: 'attribute'
        }]
    }, {
      localName: 'CTChildMax',
      typeName: 'CT_ChildMax',
      propertyInfos: [{
          name: 'val',
          typeInfo: 'Int',
          defaultValue: -1,
          attributeName: {
            localPart: 'val'
          },
          type: 'attribute'
        }]
    }, {
      localName: 'CTChildPref',
      typeName: 'CT_ChildPref',
      propertyInfos: [{
          name: 'val',
          typeInfo: 'Int',
          defaultValue: -1,
          attributeName: {
            localPart: 'val'
          },
          type: 'attribute'
        }]
    }, {
      localName: 'CTChoose',
      typeName: 'CT_Choose',
      propertyInfos: [{
          name: '_if',
          required: true,
          collection: true,
          elementName: 'if',
          typeInfo: '.CTWhen'
        }, {
          name: '_else',
          elementName: 'else',
          typeInfo: '.CTOtherwise'
        }, {
          name: 'name',
          defaultValue: '',
          attributeName: {
            localPart: 'name'
          },
          type: 'attribute'
        }]
    }, {
      localName: 'CTColorTransform',
      typeName: 'CT_ColorTransform',
      propertyInfos: [{
          name: 'title',
          minOccurs: 0,
          collection: true,
          typeInfo: '.CTCTName'
        }, {
          name: 'desc',
          minOccurs: 0,
          collection: true,
          typeInfo: '.CTCTDescription'
        }, {
          name: 'catLst',
          typeInfo: '.CTCTCategories'
        }, {
          name: 'styleLbl',
          minOccurs: 0,
          collection: true,
          typeInfo: '.CTCTStyleLabel'
        }, {
          name: 'extLst',
          typeInfo: 'org_docx4j_dml.CTOfficeArtExtensionList'
        }, {
          name: 'minVer',
          defaultValue: 'http:\/\/schemas.openxmlformats.org\/drawingml\/2006\/diagram',
          attributeName: {
            localPart: 'minVer'
          },
          type: 'attribute'
        }, {
          name: 'uniqueId',
          defaultValue: '',
          attributeName: {
            localPart: 'uniqueId'
          },
          type: 'attribute'
        }]
    }, {
      localName: 'CTColorTransformHeader',
      typeName: 'CT_ColorTransformHeader',
      propertyInfos: [{
          name: 'title',
          required: true,
          collection: true,
          typeInfo: '.CTCTName'
        }, {
          name: 'desc',
          required: true,
          collection: true,
          typeInfo: '.CTCTDescription'
        }, {
          name: 'catLst',
          typeInfo: '.CTCTCategories'
        }, {
          name: 'extLst',
          typeInfo: 'org_docx4j_dml.CTOfficeArtExtensionList'
        }, {
          name: 'minVer',
          defaultValue: 'http:\/\/schemas.openxmlformats.org\/drawingml\/2006\/diagram',
          attributeName: {
            localPart: 'minVer'
          },
          type: 'attribute'
        }, {
          name: 'resId',
          typeInfo: 'Int',
          defaultValue: 0,
          attributeName: {
            localPart: 'resId'
          },
          type: 'attribute'
        }, {
          name: 'uniqueId',
          required: true,
          attributeName: {
            localPart: 'uniqueId'
          },
          type: 'attribute'
        }]
    }, {
      localName: 'CTColorTransformHeaderLst',
      typeName: 'CT_ColorTransformHeaderLst',
      propertyInfos: [{
          name: 'colorsDefHdr',
          minOccurs: 0,
          collection: true,
          typeInfo: '.CTColorTransformHeader'
        }]
    }, {
      localName: 'CTColors',
      typeName: 'CT_Colors',
      propertyInfos: [{
          name: 'egColorChoice',
          minOccurs: 0,
          collection: true,
          elementTypeInfos: [{
              elementName: {
                localPart: 'scrgbClr',
                namespaceURI: 'http:\/\/schemas.openxmlformats.org\/drawingml\/2006\/main'
              },
              typeInfo: 'org_docx4j_dml.CTScRgbColor'
            }, {
              elementName: {
                localPart: 'srgbClr',
                namespaceURI: 'http:\/\/schemas.openxmlformats.org\/drawingml\/2006\/main'
              },
              typeInfo: 'org_docx4j_dml.CTSRgbColor'
            }, {
              elementName: {
                localPart: 'hslClr',
                namespaceURI: 'http:\/\/schemas.openxmlformats.org\/drawingml\/2006\/main'
              },
              typeInfo: 'org_docx4j_dml.CTHslColor'
            }, {
              elementName: {
                localPart: 'sysClr',
                namespaceURI: 'http:\/\/schemas.openxmlformats.org\/drawingml\/2006\/main'
              },
              typeInfo: 'org_docx4j_dml.CTSystemColor'
            }, {
              elementName: {
                localPart: 'schemeClr',
                namespaceURI: 'http:\/\/schemas.openxmlformats.org\/drawingml\/2006\/main'
              },
              typeInfo: 'org_docx4j_dml.CTSchemeColor'
            }, {
              elementName: {
                localPart: 'prstClr',
                namespaceURI: 'http:\/\/schemas.openxmlformats.org\/drawingml\/2006\/main'
              },
              typeInfo: 'org_docx4j_dml.CTPresetColor'
            }],
          type: 'elements'
        }, {
          name: 'hueDir',
          typeInfo: '.STHueDir',
          defaultValue: 'cw',
          attributeName: {
            localPart: 'hueDir'
          },
          type: 'attribute'
        }, {
          name: 'meth',
          typeInfo: '.STClrAppMethod',
          defaultValue: 'span',
          attributeName: {
            localPart: 'meth'
          },
          type: 'attribute'
        }]
    }, {
      localName: 'CTConstraint',
      typeName: 'CT_Constraint',
      propertyInfos: [{
          name: 'extLst',
          typeInfo: 'org_docx4j_dml.CTOfficeArtExtensionList'
        }, {
          name: 'fact',
          typeInfo: 'Double',
          defaultValue: 1,
          attributeName: {
            localPart: 'fact'
          },
          type: 'attribute'
        }, {
          name: '_for',
          typeInfo: '.STConstraintRelationship',
          defaultValue: 'self',
          attributeName: {
            localPart: 'for'
          },
          type: 'attribute'
        }, {
          name: 'forName',
          defaultValue: '',
          attributeName: {
            localPart: 'forName'
          },
          type: 'attribute'
        }, {
          name: 'op',
          typeInfo: '.STBoolOperator',
          defaultValue: 'none',
          attributeName: {
            localPart: 'op'
          },
          type: 'attribute'
        }, {
          name: 'ptType',
          typeInfo: '.STElementType',
          defaultValue: 'all',
          attributeName: {
            localPart: 'ptType'
          },
          type: 'attribute'
        }, {
          name: 'refFor',
          typeInfo: '.STConstraintRelationship',
          defaultValue: 'self',
          attributeName: {
            localPart: 'refFor'
          },
          type: 'attribute'
        }, {
          name: 'refForName',
          defaultValue: '',
          attributeName: {
            localPart: 'refForName'
          },
          type: 'attribute'
        }, {
          name: 'refPtType',
          typeInfo: '.STElementType',
          defaultValue: 'all',
          attributeName: {
            localPart: 'refPtType'
          },
          type: 'attribute'
        }, {
          name: 'refType',
          typeInfo: '.STConstraintType',
          defaultValue: 'none',
          attributeName: {
            localPart: 'refType'
          },
          type: 'attribute'
        }, {
          name: 'type',
          required: true,
          typeInfo: '.STConstraintType',
          attributeName: {
            localPart: 'type'
          },
          type: 'attribute'
        }, {
          name: 'val',
          typeInfo: 'Double',
          defaultValue: 0,
          attributeName: {
            localPart: 'val'
          },
          type: 'attribute'
        }]
    }, {
      localName: 'CTConstraints',
      typeName: 'CT_Constraints',
      propertyInfos: [{
          name: 'constr',
          minOccurs: 0,
          collection: true,
          typeInfo: '.CTConstraint'
        }]
    }, {
      localName: 'CTCxn',
      typeName: 'CT_Cxn',
      propertyInfos: [{
          name: 'extLst',
          typeInfo: 'org_docx4j_dml.CTOfficeArtExtensionList'
        }, {
          name: 'destId',
          required: true,
          attributeName: {
            localPart: 'destId'
          },
          type: 'attribute'
        }, {
          name: 'destOrd',
          required: true,
          typeInfo: 'UnsignedInt',
          attributeName: {
            localPart: 'destOrd'
          },
          type: 'attribute'
        }, {
          name: 'modelId',
          required: true,
          attributeName: {
            localPart: 'modelId'
          },
          type: 'attribute'
        }, {
          name: 'parTransId',
          defaultValue: '0',
          attributeName: {
            localPart: 'parTransId'
          },
          type: 'attribute'
        }, {
          name: 'presId',
          defaultValue: '',
          attributeName: {
            localPart: 'presId'
          },
          type: 'attribute'
        }, {
          name: 'sibTransId',
          defaultValue: '0',
          attributeName: {
            localPart: 'sibTransId'
          },
          type: 'attribute'
        }, {
          name: 'srcId',
          required: true,
          attributeName: {
            localPart: 'srcId'
          },
          type: 'attribute'
        }, {
          name: 'srcOrd',
          required: true,
          typeInfo: 'UnsignedInt',
          attributeName: {
            localPart: 'srcOrd'
          },
          type: 'attribute'
        }, {
          name: 'type',
          typeInfo: '.STCxnType',
          defaultValue: 'parOf',
          attributeName: {
            localPart: 'type'
          },
          type: 'attribute'
        }]
    }, {
      localName: 'CTCxnList',
      typeName: 'CT_CxnList',
      propertyInfos: [{
          name: 'cxn',
          minOccurs: 0,
          collection: true,
          typeInfo: '.CTCxn'
        }]
    }, {
      localName: 'CTDataModel',
      typeName: 'CT_DataModel',
      propertyInfos: [{
          name: 'ptLst',
          required: true,
          typeInfo: '.CTPtList'
        }, {
          name: 'cxnLst',
          typeInfo: '.CTCxnList'
        }, {
          name: 'bg',
          typeInfo: 'org_docx4j_dml.CTBackgroundFormatting'
        }, {
          name: 'whole',
          typeInfo: 'org_docx4j_dml.CTWholeE2OFormatting'
        }, {
          name: 'extLst',
          typeInfo: 'org_docx4j_dml.CTOfficeArtExtensionList'
        }]
    }, {
      localName: 'CTDescription',
      typeName: 'CT_Description',
      propertyInfos: [{
          name: 'lang',
          defaultValue: '',
          attributeName: {
            localPart: 'lang'
          },
          type: 'attribute'
        }, {
          name: 'val',
          required: true,
          attributeName: {
            localPart: 'val'
          },
          type: 'attribute'
        }]
    }, {
      localName: 'CTDiagramDefinition',
      typeName: 'CT_DiagramDefinition',
      propertyInfos: [{
          name: 'title',
          minOccurs: 0,
          collection: true,
          typeInfo: '.CTName'
        }, {
          name: 'desc',
          minOccurs: 0,
          collection: true,
          typeInfo: '.CTDescription'
        }, {
          name: 'catLst',
          typeInfo: '.CTCategories'
        }, {
          name: 'sampData',
          typeInfo: '.CTSampleData'
        }, {
          name: 'styleData',
          typeInfo: '.CTSampleData'
        }, {
          name: 'clrData',
          typeInfo: '.CTSampleData'
        }, {
          name: 'layoutNode',
          required: true,
          typeInfo: '.CTLayoutNode'
        }, {
          name: 'extLst',
          typeInfo: 'org_docx4j_dml.CTOfficeArtExtensionList'
        }, {
          name: 'defStyle',
          defaultValue: '',
          attributeName: {
            localPart: 'defStyle'
          },
          type: 'attribute'
        }, {
          name: 'minVer',
          defaultValue: 'http:\/\/schemas.openxmlformats.org\/drawingml\/2006\/diagram',
          attributeName: {
            localPart: 'minVer'
          },
          type: 'attribute'
        }, {
          name: 'uniqueId',
          defaultValue: '',
          attributeName: {
            localPart: 'uniqueId'
          },
          type: 'attribute'
        }]
    }, {
      localName: 'CTDiagramDefinitionHeader',
      typeName: 'CT_DiagramDefinitionHeader',
      propertyInfos: [{
          name: 'title',
          required: true,
          collection: true,
          typeInfo: '.CTName'
        }, {
          name: 'desc',
          required: true,
          collection: true,
          typeInfo: '.CTDescription'
        }, {
          name: 'catLst',
          typeInfo: '.CTCategories'
        }, {
          name: 'extLst',
          typeInfo: 'org_docx4j_dml.CTOfficeArtExtensionList'
        }, {
          name: 'defStyle',
          defaultValue: '',
          attributeName: {
            localPart: 'defStyle'
          },
          type: 'attribute'
        }, {
          name: 'minVer',
          defaultValue: 'http:\/\/schemas.openxmlformats.org\/drawingml\/2006\/diagram',
          attributeName: {
            localPart: 'minVer'
          },
          type: 'attribute'
        }, {
          name: 'resId',
          typeInfo: 'Int',
          defaultValue: 0,
          attributeName: {
            localPart: 'resId'
          },
          type: 'attribute'
        }, {
          name: 'uniqueId',
          required: true,
          attributeName: {
            localPart: 'uniqueId'
          },
          type: 'attribute'
        }]
    }, {
      localName: 'CTDiagramDefinitionHeaderLst',
      typeName: 'CT_DiagramDefinitionHeaderLst',
      propertyInfos: [{
          name: 'layoutDefHdr',
          minOccurs: 0,
          collection: true,
          typeInfo: '.CTDiagramDefinitionHeader'
        }]
    }, {
      localName: 'CTDirection',
      typeName: 'CT_Direction',
      propertyInfos: [{
          name: 'val',
          typeInfo: '.STDirection',
          defaultValue: 'norm',
          attributeName: {
            localPart: 'val'
          },
          type: 'attribute'
        }]
    }, {
      localName: 'CTElemPropSet',
      typeName: 'CT_ElemPropSet',
      propertyInfos: [{
          name: 'presLayoutVars',
          typeInfo: '.CTLayoutVariablePropertySet'
        }, {
          name: 'style',
          typeInfo: 'org_docx4j_dml.CTShapeStyle'
        }, {
          name: 'coherent3DOff',
          typeInfo: 'Boolean',
          attributeName: {
            localPart: 'coherent3DOff'
          },
          type: 'attribute'
        }, {
          name: 'csCatId',
          attributeName: {
            localPart: 'csCatId'
          },
          type: 'attribute'
        }, {
          name: 'csTypeId',
          attributeName: {
            localPart: 'csTypeId'
          },
          type: 'attribute'
        }, {
          name: 'custAng',
          typeInfo: 'Int',
          attributeName: {
            localPart: 'custAng'
          },
          type: 'attribute'
        }, {
          name: 'custFlipHor',
          typeInfo: 'Boolean',
          attributeName: {
            localPart: 'custFlipHor'
          },
          type: 'attribute'
        }, {
          name: 'custFlipVert',
          typeInfo: 'Boolean',
          attributeName: {
            localPart: 'custFlipVert'
          },
          type: 'attribute'
        }, {
          name: 'custLinFactNeighborX',
          typeInfo: 'Int',
          attributeName: {
            localPart: 'custLinFactNeighborX'
          },
          type: 'attribute'
        }, {
          name: 'custLinFactNeighborY',
          typeInfo: 'Int',
          attributeName: {
            localPart: 'custLinFactNeighborY'
          },
          type: 'attribute'
        }, {
          name: 'custLinFactX',
          typeInfo: 'Int',
          attributeName: {
            localPart: 'custLinFactX'
          },
          type: 'attribute'
        }, {
          name: 'custLinFactY',
          typeInfo: 'Int',
          attributeName: {
            localPart: 'custLinFactY'
          },
          type: 'attribute'
        }, {
          name: 'custRadScaleInc',
          typeInfo: 'Int',
          attributeName: {
            localPart: 'custRadScaleInc'
          },
          type: 'attribute'
        }, {
          name: 'custRadScaleRad',
          typeInfo: 'Int',
          attributeName: {
            localPart: 'custRadScaleRad'
          },
          type: 'attribute'
        }, {
          name: 'custScaleX',
          typeInfo: 'Int',
          attributeName: {
            localPart: 'custScaleX'
          },
          type: 'attribute'
        }, {
          name: 'custScaleY',
          typeInfo: 'Int',
          attributeName: {
            localPart: 'custScaleY'
          },
          type: 'attribute'
        }, {
          name: 'custSzX',
          typeInfo: 'Int',
          attributeName: {
            localPart: 'custSzX'
          },
          type: 'attribute'
        }, {
          name: 'custSzY',
          typeInfo: 'Int',
          attributeName: {
            localPart: 'custSzY'
          },
          type: 'attribute'
        }, {
          name: 'custT',
          typeInfo: 'Boolean',
          attributeName: {
            localPart: 'custT'
          },
          type: 'attribute'
        }, {
          name: 'loCatId',
          attributeName: {
            localPart: 'loCatId'
          },
          type: 'attribute'
        }, {
          name: 'loTypeId',
          attributeName: {
            localPart: 'loTypeId'
          },
          type: 'attribute'
        }, {
          name: 'phldr',
          typeInfo: 'Boolean',
          attributeName: {
            localPart: 'phldr'
          },
          type: 'attribute'
        }, {
          name: 'phldrT',
          attributeName: {
            localPart: 'phldrT'
          },
          type: 'attribute'
        }, {
          name: 'presAssocID',
          attributeName: {
            localPart: 'presAssocID'
          },
          type: 'attribute'
        }, {
          name: 'presName',
          attributeName: {
            localPart: 'presName'
          },
          type: 'attribute'
        }, {
          name: 'presStyleCnt',
          typeInfo: 'Int',
          attributeName: {
            localPart: 'presStyleCnt'
          },
          type: 'attribute'
        }, {
          name: 'presStyleIdx',
          typeInfo: 'Int',
          attributeName: {
            localPart: 'presStyleIdx'
          },
          type: 'attribute'
        }, {
          name: 'presStyleLbl',
          attributeName: {
            localPart: 'presStyleLbl'
          },
          type: 'attribute'
        }, {
          name: 'qsCatId',
          attributeName: {
            localPart: 'qsCatId'
          },
          type: 'attribute'
        }, {
          name: 'qsTypeId',
          attributeName: {
            localPart: 'qsTypeId'
          },
          type: 'attribute'
        }]
    }, {
      localName: 'CTForEach',
      typeName: 'CT_ForEach',
      propertyInfos: [{
          name: 'algOrShapeOrPresOf',
          minOccurs: 0,
          collection: true,
          elementTypeInfos: [{
              elementName: 'alg',
              typeInfo: '.CTAlgorithm'
            }, {
              elementName: 'shape',
              typeInfo: '.CTShape'
            }, {
              elementName: 'presOf',
              typeInfo: '.CTPresentationOf'
            }, {
              elementName: 'constrLst',
              typeInfo: '.CTConstraints'
            }, {
              elementName: 'ruleLst',
              typeInfo: '.CTRules'
            }, {
              elementName: 'forEach',
              typeInfo: '.CTForEach'
            }, {
              elementName: 'layoutNode',
              typeInfo: '.CTLayoutNode'
            }, {
              elementName: 'choose',
              typeInfo: '.CTChoose'
            }, {
              elementName: 'extLst',
              typeInfo: 'org_docx4j_dml.CTOfficeArtExtensionList'
            }],
          type: 'elements'
        }, {
          name: 'axis',
          typeInfo: {
            type: 'list',
            baseTypeInfo: '.STAxisType'
          },
          attributeName: {
            localPart: 'axis'
          },
          type: 'attribute'
        }, {
          name: 'cnt',
          typeInfo: {
            type: 'list',
            baseTypeInfo: 'UnsignedInt'
          },
          attributeName: {
            localPart: 'cnt'
          },
          type: 'attribute'
        }, {
          name: 'hideLastTrans',
          typeInfo: {
            type: 'list',
            baseTypeInfo: 'Boolean'
          },
          attributeName: {
            localPart: 'hideLastTrans'
          },
          type: 'attribute'
        }, {
          name: 'name',
          defaultValue: '',
          attributeName: {
            localPart: 'name'
          },
          type: 'attribute'
        }, {
          name: 'ptType',
          typeInfo: {
            type: 'list',
            baseTypeInfo: '.STElementType'
          },
          attributeName: {
            localPart: 'ptType'
          },
          type: 'attribute'
        }, {
          name: 'ref',
          defaultValue: '',
          attributeName: {
            localPart: 'ref'
          },
          type: 'attribute'
        }, {
          name: 'st',
          typeInfo: {
            type: 'list',
            baseTypeInfo: 'Int'
          },
          attributeName: {
            localPart: 'st'
          },
          type: 'attribute'
        }, {
          name: 'step',
          typeInfo: {
            type: 'list',
            baseTypeInfo: 'Int'
          },
          attributeName: {
            localPart: 'step'
          },
          type: 'attribute'
        }]
    }, {
      localName: 'CTHierBranchStyle',
      typeName: 'CT_HierBranchStyle',
      propertyInfos: [{
          name: 'val',
          typeInfo: '.STHierBranchStyle',
          defaultValue: 'std',
          attributeName: {
            localPart: 'val'
          },
          type: 'attribute'
        }]
    }, {
      localName: 'CTLayoutNode',
      typeName: 'CT_LayoutNode',
      propertyInfos: [{
          name: 'algOrShapeOrPresOf',
          minOccurs: 0,
          collection: true,
          elementTypeInfos: [{
              elementName: 'alg',
              typeInfo: '.CTAlgorithm'
            }, {
              elementName: 'shape',
              typeInfo: '.CTShape'
            }, {
              elementName: 'presOf',
              typeInfo: '.CTPresentationOf'
            }, {
              elementName: 'constrLst',
              typeInfo: '.CTConstraints'
            }, {
              elementName: 'ruleLst',
              typeInfo: '.CTRules'
            }, {
              elementName: 'varLst',
              typeInfo: '.CTLayoutVariablePropertySet'
            }, {
              elementName: 'forEach',
              typeInfo: '.CTForEach'
            }, {
              elementName: 'layoutNode',
              typeInfo: '.CTLayoutNode'
            }, {
              elementName: 'choose',
              typeInfo: '.CTChoose'
            }, {
              elementName: 'extLst',
              typeInfo: 'org_docx4j_dml.CTOfficeArtExtensionList'
            }],
          type: 'elements'
        }, {
          name: 'chOrder',
          typeInfo: '.STChildOrderType',
          defaultValue: 'b',
          attributeName: {
            localPart: 'chOrder'
          },
          type: 'attribute'
        }, {
          name: 'moveWith',
          defaultValue: '',
          attributeName: {
            localPart: 'moveWith'
          },
          type: 'attribute'
        }, {
          name: 'name',
          defaultValue: '',
          attributeName: {
            localPart: 'name'
          },
          type: 'attribute'
        }, {
          name: 'styleLbl',
          defaultValue: '',
          attributeName: {
            localPart: 'styleLbl'
          },
          type: 'attribute'
        }]
    }, {
      localName: 'CTLayoutVariablePropertySet',
      typeName: 'CT_LayoutVariablePropertySet',
      propertyInfos: [{
          name: 'orgChart',
          typeInfo: '.CTOrgChart'
        }, {
          name: 'chMax',
          typeInfo: '.CTChildMax'
        }, {
          name: 'chPref',
          typeInfo: '.CTChildPref'
        }, {
          name: 'bulletEnabled',
          typeInfo: '.CTBulletEnabled'
        }, {
          name: 'dir',
          typeInfo: '.CTDirection'
        }, {
          name: 'hierBranch',
          typeInfo: '.CTHierBranchStyle'
        }, {
          name: 'animOne',
          typeInfo: '.CTAnimOne'
        }, {
          name: 'animLvl',
          typeInfo: '.CTAnimLvl'
        }, {
          name: 'resizeHandles',
          typeInfo: '.CTResizeHandles'
        }]
    }, {
      localName: 'CTName',
      typeName: 'CT_Name',
      propertyInfos: [{
          name: 'lang',
          defaultValue: '',
          attributeName: {
            localPart: 'lang'
          },
          type: 'attribute'
        }, {
          name: 'val',
          required: true,
          attributeName: {
            localPart: 'val'
          },
          type: 'attribute'
        }]
    }, {
      localName: 'CTNumericRule',
      typeName: 'CT_NumericRule',
      propertyInfos: [{
          name: 'extLst',
          typeInfo: 'org_docx4j_dml.CTOfficeArtExtensionList'
        }, {
          name: 'fact',
          typeInfo: 'Double',
          defaultValue: NaN,
          attributeName: {
            localPart: 'fact'
          },
          type: 'attribute'
        }, {
          name: '_for',
          typeInfo: '.STConstraintRelationship',
          defaultValue: 'self',
          attributeName: {
            localPart: 'for'
          },
          type: 'attribute'
        }, {
          name: 'forName',
          defaultValue: '',
          attributeName: {
            localPart: 'forName'
          },
          type: 'attribute'
        }, {
          name: 'max',
          typeInfo: 'Double',
          defaultValue: NaN,
          attributeName: {
            localPart: 'max'
          },
          type: 'attribute'
        }, {
          name: 'ptType',
          typeInfo: '.STElementType',
          defaultValue: 'all',
          attributeName: {
            localPart: 'ptType'
          },
          type: 'attribute'
        }, {
          name: 'type',
          required: true,
          typeInfo: '.STConstraintType',
          attributeName: {
            localPart: 'type'
          },
          type: 'attribute'
        }, {
          name: 'val',
          typeInfo: 'Double',
          defaultValue: NaN,
          attributeName: {
            localPart: 'val'
          },
          type: 'attribute'
        }]
    }, {
      localName: 'CTOrgChart',
      typeName: 'CT_OrgChart',
      propertyInfos: [{
          name: 'val',
          typeInfo: 'Boolean',
          defaultValue: false,
          attributeName: {
            localPart: 'val'
          },
          type: 'attribute'
        }]
    }, {
      localName: 'CTOtherwise',
      typeName: 'CT_Otherwise',
      propertyInfos: [{
          name: 'algOrShapeOrPresOf',
          minOccurs: 0,
          collection: true,
          elementTypeInfos: [{
              elementName: 'alg',
              typeInfo: '.CTAlgorithm'
            }, {
              elementName: 'shape',
              typeInfo: '.CTShape'
            }, {
              elementName: 'presOf',
              typeInfo: '.CTPresentationOf'
            }, {
              elementName: 'constrLst',
              typeInfo: '.CTConstraints'
            }, {
              elementName: 'ruleLst',
              typeInfo: '.CTRules'
            }, {
              elementName: 'forEach',
              typeInfo: '.CTForEach'
            }, {
              elementName: 'layoutNode',
              typeInfo: '.CTLayoutNode'
            }, {
              elementName: 'choose',
              typeInfo: '.CTChoose'
            }, {
              elementName: 'extLst',
              typeInfo: 'org_docx4j_dml.CTOfficeArtExtensionList'
            }],
          type: 'elements'
        }, {
          name: 'name',
          defaultValue: '',
          attributeName: {
            localPart: 'name'
          },
          type: 'attribute'
        }]
    }, {
      localName: 'CTParameter',
      typeName: 'CT_Parameter',
      propertyInfos: [{
          name: 'type',
          required: true,
          typeInfo: '.STParameterId',
          attributeName: {
            localPart: 'type'
          },
          type: 'attribute'
        }, {
          name: 'val',
          required: true,
          attributeName: {
            localPart: 'val'
          },
          type: 'attribute'
        }]
    }, {
      localName: 'CTPresentationOf',
      typeName: 'CT_PresentationOf',
      propertyInfos: [{
          name: 'extLst',
          typeInfo: 'org_docx4j_dml.CTOfficeArtExtensionList'
        }, {
          name: 'axis',
          typeInfo: {
            type: 'list',
            baseTypeInfo: '.STAxisType'
          },
          attributeName: {
            localPart: 'axis'
          },
          type: 'attribute'
        }, {
          name: 'cnt',
          typeInfo: {
            type: 'list',
            baseTypeInfo: 'UnsignedInt'
          },
          attributeName: {
            localPart: 'cnt'
          },
          type: 'attribute'
        }, {
          name: 'hideLastTrans',
          typeInfo: {
            type: 'list',
            baseTypeInfo: 'Boolean'
          },
          attributeName: {
            localPart: 'hideLastTrans'
          },
          type: 'attribute'
        }, {
          name: 'ptType',
          typeInfo: {
            type: 'list',
            baseTypeInfo: '.STElementType'
          },
          attributeName: {
            localPart: 'ptType'
          },
          type: 'attribute'
        }, {
          name: 'st',
          typeInfo: {
            type: 'list',
            baseTypeInfo: 'Int'
          },
          attributeName: {
            localPart: 'st'
          },
          type: 'attribute'
        }, {
          name: 'step',
          typeInfo: {
            type: 'list',
            baseTypeInfo: 'Int'
          },
          attributeName: {
            localPart: 'step'
          },
          type: 'attribute'
        }]
    }, {
      localName: 'CTPt',
      typeName: 'CT_Pt',
      propertyInfos: [{
          name: 'prSet',
          typeInfo: '.CTElemPropSet'
        }, {
          name: 'spPr',
          typeInfo: 'org_docx4j_dml.CTShapeProperties'
        }, {
          name: 't',
          typeInfo: 'org_docx4j_dml.CTTextBody'
        }, {
          name: 'extLst',
          typeInfo: 'org_docx4j_dml.CTOfficeArtExtensionList'
        }, {
          name: 'cxnId',
          defaultValue: '0',
          attributeName: {
            localPart: 'cxnId'
          },
          type: 'attribute'
        }, {
          name: 'modelId',
          required: true,
          attributeName: {
            localPart: 'modelId'
          },
          type: 'attribute'
        }, {
          name: 'type',
          typeInfo: '.STPtType',
          defaultValue: 'node',
          attributeName: {
            localPart: 'type'
          },
          type: 'attribute'
        }]
    }, {
      localName: 'CTPtList',
      typeName: 'CT_PtList',
      propertyInfos: [{
          name: 'pt',
          minOccurs: 0,
          collection: true,
          typeInfo: '.CTPt'
        }]
    }, {
      localName: 'CTRelIds',
      typeName: 'CT_RelIds',
      propertyInfos: [{
          name: 'cs',
          required: true,
          defaultValue: '',
          attributeName: {
            localPart: 'cs',
            namespaceURI: 'http:\/\/schemas.openxmlformats.org\/officeDocument\/2006\/relationships'
          },
          type: 'attribute'
        }, {
          name: 'dm',
          required: true,
          defaultValue: '',
          attributeName: {
            localPart: 'dm',
            namespaceURI: 'http:\/\/schemas.openxmlformats.org\/officeDocument\/2006\/relationships'
          },
          type: 'attribute'
        }, {
          name: 'lo',
          required: true,
          defaultValue: '',
          attributeName: {
            localPart: 'lo',
            namespaceURI: 'http:\/\/schemas.openxmlformats.org\/officeDocument\/2006\/relationships'
          },
          type: 'attribute'
        }, {
          name: 'qs',
          required: true,
          defaultValue: '',
          attributeName: {
            localPart: 'qs',
            namespaceURI: 'http:\/\/schemas.openxmlformats.org\/officeDocument\/2006\/relationships'
          },
          type: 'attribute'
        }]
    }, {
      localName: 'CTResizeHandles',
      typeName: 'CT_ResizeHandles',
      propertyInfos: [{
          name: 'val',
          typeInfo: '.STResizeHandlesStr',
          defaultValue: 'rel',
          attributeName: {
            localPart: 'val'
          },
          type: 'attribute'
        }]
    }, {
      localName: 'CTRules',
      typeName: 'CT_Rules',
      propertyInfos: [{
          name: 'rule',
          minOccurs: 0,
          collection: true,
          typeInfo: '.CTNumericRule'
        }]
    }, {
      localName: 'CTSDCategories',
      typeName: 'CT_SDCategories',
      propertyInfos: [{
          name: 'cat',
          minOccurs: 0,
          collection: true,
          typeInfo: '.CTSDCategory'
        }]
    }, {
      localName: 'CTSDCategory',
      typeName: 'CT_SDCategory',
      propertyInfos: [{
          name: 'pri',
          required: true,
          typeInfo: 'UnsignedInt',
          attributeName: {
            localPart: 'pri'
          },
          type: 'attribute'
        }, {
          name: 'type',
          required: true,
          attributeName: {
            localPart: 'type'
          },
          type: 'attribute'
        }]
    }, {
      localName: 'CTSDDescription',
      typeName: 'CT_SDDescription',
      propertyInfos: [{
          name: 'lang',
          defaultValue: '',
          attributeName: {
            localPart: 'lang'
          },
          type: 'attribute'
        }, {
          name: 'val',
          required: true,
          attributeName: {
            localPart: 'val'
          },
          type: 'attribute'
        }]
    }, {
      localName: 'CTSDName',
      typeName: 'CT_SDName',
      propertyInfos: [{
          name: 'lang',
          defaultValue: '',
          attributeName: {
            localPart: 'lang'
          },
          type: 'attribute'
        }, {
          name: 'val',
          required: true,
          attributeName: {
            localPart: 'val'
          },
          type: 'attribute'
        }]
    }, {
      localName: 'CTSampleData',
      typeName: 'CT_SampleData',
      propertyInfos: [{
          name: 'dataModel',
          typeInfo: '.CTDataModel'
        }, {
          name: 'useDef',
          typeInfo: 'Boolean',
          defaultValue: false,
          attributeName: {
            localPart: 'useDef'
          },
          type: 'attribute'
        }]
    }, {
      localName: 'CTShape',
      typeName: 'CT_Shape',
      propertyInfos: [{
          name: 'adjLst',
          typeInfo: '.CTAdjLst'
        }, {
          name: 'extLst',
          typeInfo: 'org_docx4j_dml.CTOfficeArtExtensionList'
        }, {
          name: 'blipPhldr',
          typeInfo: 'Boolean',
          defaultValue: false,
          attributeName: {
            localPart: 'blipPhldr'
          },
          type: 'attribute'
        }, {
          name: 'hideGeom',
          typeInfo: 'Boolean',
          defaultValue: false,
          attributeName: {
            localPart: 'hideGeom'
          },
          type: 'attribute'
        }, {
          name: 'lkTxEntry',
          typeInfo: 'Boolean',
          defaultValue: false,
          attributeName: {
            localPart: 'lkTxEntry'
          },
          type: 'attribute'
        }, {
          name: 'rot',
          typeInfo: 'Double',
          defaultValue: 0,
          attributeName: {
            localPart: 'rot'
          },
          type: 'attribute'
        }, {
          name: 'type',
          defaultValue: 'none',
          attributeName: {
            localPart: 'type'
          },
          type: 'attribute'
        }, {
          name: 'zOrderOff',
          typeInfo: 'Int',
          defaultValue: 0,
          attributeName: {
            localPart: 'zOrderOff'
          },
          type: 'attribute'
        }, {
          name: 'blip',
          defaultValue: '',
          attributeName: {
            localPart: 'blip',
            namespaceURI: 'http:\/\/schemas.openxmlformats.org\/officeDocument\/2006\/relationships'
          },
          type: 'attribute'
        }]
    }, {
      localName: 'CTStyleDefinition',
      typeName: 'CT_StyleDefinition',
      propertyInfos: [{
          name: 'title',
          minOccurs: 0,
          collection: true,
          typeInfo: '.CTSDName'
        }, {
          name: 'desc',
          minOccurs: 0,
          collection: true,
          typeInfo: '.CTSDDescription'
        }, {
          name: 'catLst',
          typeInfo: '.CTSDCategories'
        }, {
          name: 'scene3D',
          elementName: 'scene3d',
          typeInfo: 'org_docx4j_dml.CTScene3D'
        }, {
          name: 'styleLbl',
          required: true,
          collection: true,
          typeInfo: '.CTStyleLabel'
        }, {
          name: 'extLst',
          typeInfo: 'org_docx4j_dml.CTOfficeArtExtensionList'
        }, {
          name: 'minVer',
          defaultValue: 'http:\/\/schemas.openxmlformats.org\/drawingml\/2006\/diagram',
          attributeName: {
            localPart: 'minVer'
          },
          type: 'attribute'
        }, {
          name: 'uniqueId',
          defaultValue: '',
          attributeName: {
            localPart: 'uniqueId'
          },
          type: 'attribute'
        }]
    }, {
      localName: 'CTStyleDefinitionHeader',
      typeName: 'CT_StyleDefinitionHeader',
      propertyInfos: [{
          name: 'title',
          required: true,
          collection: true,
          typeInfo: '.CTSDName'
        }, {
          name: 'desc',
          required: true,
          collection: true,
          typeInfo: '.CTSDDescription'
        }, {
          name: 'catLst',
          typeInfo: '.CTSDCategories'
        }, {
          name: 'extLst',
          typeInfo: 'org_docx4j_dml.CTOfficeArtExtensionList'
        }, {
          name: 'minVer',
          defaultValue: 'http:\/\/schemas.openxmlformats.org\/drawingml\/2006\/diagram',
          attributeName: {
            localPart: 'minVer'
          },
          type: 'attribute'
        }, {
          name: 'resId',
          typeInfo: 'Int',
          defaultValue: 0,
          attributeName: {
            localPart: 'resId'
          },
          type: 'attribute'
        }, {
          name: 'uniqueId',
          required: true,
          attributeName: {
            localPart: 'uniqueId'
          },
          type: 'attribute'
        }]
    }, {
      localName: 'CTStyleDefinitionHeaderLst',
      typeName: 'CT_StyleDefinitionHeaderLst',
      propertyInfos: [{
          name: 'styleDefHdr',
          minOccurs: 0,
          collection: true,
          typeInfo: '.CTStyleDefinitionHeader'
        }]
    }, {
      localName: 'CTStyleLabel',
      typeName: 'CT_StyleLabel',
      propertyInfos: [{
          name: 'scene3D',
          elementName: 'scene3d',
          typeInfo: 'org_docx4j_dml.CTScene3D'
        }, {
          name: 'sp3D',
          elementName: 'sp3d',
          typeInfo: 'org_docx4j_dml.CTShape3D'
        }, {
          name: 'txPr',
          typeInfo: '.CTTextProps'
        }, {
          name: 'style',
          typeInfo: 'org_docx4j_dml.CTShapeStyle'
        }, {
          name: 'extLst',
          typeInfo: 'org_docx4j_dml.CTOfficeArtExtensionList'
        }, {
          name: 'name',
          required: true,
          attributeName: {
            localPart: 'name'
          },
          type: 'attribute'
        }]
    }, {
      localName: 'CTTextProps',
      typeName: 'CT_TextProps',
      propertyInfos: [{
          name: 'sp3D',
          required: true,
          elementName: {
            localPart: 'sp3d',
            namespaceURI: 'http:\/\/schemas.openxmlformats.org\/drawingml\/2006\/main'
          },
          typeInfo: 'org_docx4j_dml.CTShape3D'
        }, {
          name: 'flatTx',
          required: true,
          elementName: {
            localPart: 'flatTx',
            namespaceURI: 'http:\/\/schemas.openxmlformats.org\/drawingml\/2006\/main'
          },
          typeInfo: 'org_docx4j_dml.CTFlatText'
        }]
    }, {
      localName: 'CTWhen',
      typeName: 'CT_When',
      propertyInfos: [{
          name: 'algOrShapeOrPresOf',
          minOccurs: 0,
          collection: true,
          elementTypeInfos: [{
              elementName: 'alg',
              typeInfo: '.CTAlgorithm'
            }, {
              elementName: 'shape',
              typeInfo: '.CTShape'
            }, {
              elementName: 'presOf',
              typeInfo: '.CTPresentationOf'
            }, {
              elementName: 'constrLst',
              typeInfo: '.CTConstraints'
            }, {
              elementName: 'ruleLst',
              typeInfo: '.CTRules'
            }, {
              elementName: 'forEach',
              typeInfo: '.CTForEach'
            }, {
              elementName: 'layoutNode',
              typeInfo: '.CTLayoutNode'
            }, {
              elementName: 'choose',
              typeInfo: '.CTChoose'
            }, {
              elementName: 'extLst',
              typeInfo: 'org_docx4j_dml.CTOfficeArtExtensionList'
            }],
          type: 'elements'
        }, {
          name: 'arg',
          defaultValue: 'none',
          attributeName: {
            localPart: 'arg'
          },
          type: 'attribute'
        }, {
          name: 'axis',
          typeInfo: {
            type: 'list',
            baseTypeInfo: '.STAxisType'
          },
          attributeName: {
            localPart: 'axis'
          },
          type: 'attribute'
        }, {
          name: 'cnt',
          typeInfo: {
            type: 'list',
            baseTypeInfo: 'UnsignedInt'
          },
          attributeName: {
            localPart: 'cnt'
          },
          type: 'attribute'
        }, {
          name: 'func',
          required: true,
          typeInfo: '.STFunctionType',
          attributeName: {
            localPart: 'func'
          },
          type: 'attribute'
        }, {
          name: 'hideLastTrans',
          typeInfo: {
            type: 'list',
            baseTypeInfo: 'Boolean'
          },
          attributeName: {
            localPart: 'hideLastTrans'
          },
          type: 'attribute'
        }, {
          name: 'name',
          defaultValue: '',
          attributeName: {
            localPart: 'name'
          },
          type: 'attribute'
        }, {
          name: 'op',
          required: true,
          typeInfo: '.STFunctionOperator',
          attributeName: {
            localPart: 'op'
          },
          type: 'attribute'
        }, {
          name: 'ptType',
          typeInfo: {
            type: 'list',
            baseTypeInfo: '.STElementType'
          },
          attributeName: {
            localPart: 'ptType'
          },
          type: 'attribute'
        }, {
          name: 'st',
          typeInfo: {
            type: 'list',
            baseTypeInfo: 'Int'
          },
          attributeName: {
            localPart: 'st'
          },
          type: 'attribute'
        }, {
          name: 'step',
          typeInfo: {
            type: 'list',
            baseTypeInfo: 'Int'
          },
          attributeName: {
            localPart: 'step'
          },
          type: 'attribute'
        }, {
          name: 'val',
          required: true,
          attributeName: {
            localPart: 'val'
          },
          type: 'attribute'
        }]
    }, {
      type: 'enumInfo',
      localName: 'STAlgorithmType',
      baseTypeInfo: 'Token',
      values: ['composite', 'conn', 'cycle', 'hierChild', 'hierRoot', 'pyra', 'lin', 'sp', 'tx', 'snake']
    }, {
      type: 'enumInfo',
      localName: 'STAnimLvlStr',
      baseTypeInfo: 'Token',
      values: ['none', 'lvl', 'ctr']
    }, {
      type: 'enumInfo',
      localName: 'STAnimOneStr',
      baseTypeInfo: 'Token',
      values: ['none', 'one', 'branch']
    }, {
      type: 'enumInfo',
      localName: 'STArrowheadStyle',
      baseTypeInfo: 'Token',
      values: ['auto', 'arr', 'noArr']
    }, {
      type: 'enumInfo',
      localName: 'STAutoTextRotation',
      baseTypeInfo: 'Token',
      values: ['none', 'upr', 'grav']
    }, {
      type: 'enumInfo',
      localName: 'STAxisType',
      baseTypeInfo: 'Token',
      values: ['self', 'ch', 'des', 'desOrSelf', 'par', 'ancst', 'ancstOrSelf', 'followSib', 'precedSib', 'follow', 'preced', 'root', 'none']
    }, {
      type: 'enumInfo',
      localName: 'STBendPoint',
      baseTypeInfo: 'Token',
      values: ['beg', 'def', 'end']
    }, {
      type: 'enumInfo',
      localName: 'STBoolOperator',
      baseTypeInfo: 'Token',
      values: ['none', 'equ', 'gte', 'lte']
    }, {
      type: 'enumInfo',
      localName: 'STBreakpoint',
      baseTypeInfo: 'Token',
      values: ['endCnv', 'bal', 'fixed']
    }, {
      type: 'enumInfo',
      localName: 'STCenterShapeMapping',
      baseTypeInfo: 'Token',
      values: ['none', 'fNode']
    }, {
      type: 'enumInfo',
      localName: 'STChildAlignment',
      baseTypeInfo: 'Token',
      values: ['t', 'b', 'l', 'r']
    }, {
      type: 'enumInfo',
      localName: 'STChildDirection',
      baseTypeInfo: 'Token',
      values: ['horz', 'vert']
    }, {
      type: 'enumInfo',
      localName: 'STChildOrderType',
      baseTypeInfo: 'Token',
      values: ['b', 't']
    }, {
      type: 'enumInfo',
      localName: 'STClrAppMethod',
      baseTypeInfo: 'Token',
      values: ['span', 'cycle', 'repeat']
    }, {
      type: 'enumInfo',
      localName: 'STConnectorPoint',
      baseTypeInfo: 'Token',
      values: ['auto', 'bCtr', 'ctr', 'midL', 'midR', 'tCtr', 'bL', 'bR', 'tL', 'tR', 'radial']
    }, {
      type: 'enumInfo',
      localName: 'STConnectorRouting',
      baseTypeInfo: 'Token',
      values: ['stra', 'bend', 'curve', 'longCurve']
    }, {
      type: 'enumInfo',
      localName: 'STConstraintRelationship',
      baseTypeInfo: 'Token',
      values: ['self', 'ch', 'des']
    }, {
      type: 'enumInfo',
      localName: 'STConstraintType',
      baseTypeInfo: 'Token',
      values: ['none', 'alignOff', 'begMarg', 'bendDist', 'begPad', 'b', 'bMarg', 'bOff', 'ctrX', 'ctrXOff', 'ctrY', 'ctrYOff', 'connDist', 'diam', 'endMarg', 'endPad', 'h', 'hArH', 'hOff', 'l', 'lMarg', 'lOff', 'r', 'rMarg', 'rOff', 'primFontSz', 'pyraAcctRatio', 'secFontSz', 'sibSp', 'secSibSp', 'sp', 'stemThick', 't', 'tMarg', 'tOff', 'userA', 'userB', 'userC', 'userD', 'userE', 'userF', 'userG', 'userH', 'userI', 'userJ', 'userK', 'userL', 'userM', 'userN', 'userO', 'userP', 'userQ', 'userR', 'userS', 'userT', 'userU', 'userV', 'userW', 'userX', 'userY', 'userZ', 'w', 'wArH', 'wOff']
    }, {
      type: 'enumInfo',
      localName: 'STContinueDirection',
      baseTypeInfo: 'Token',
      values: ['revDir', 'sameDir']
    }, {
      type: 'enumInfo',
      localName: 'STCxnType',
      baseTypeInfo: 'Token',
      values: ['parOf', 'presOf', 'presParOf', 'unknownRelationship']
    }, {
      type: 'enumInfo',
      localName: 'STDirection',
      baseTypeInfo: 'Token',
      values: ['norm', 'rev']
    }, {
      type: 'enumInfo',
      localName: 'STElementType',
      baseTypeInfo: 'Token',
      values: ['all', 'doc', 'node', 'norm', 'nonNorm', 'asst', 'nonAsst', 'parTrans', 'pres', 'sibTrans']
    }, {
      type: 'enumInfo',
      localName: 'STFlowDirection',
      baseTypeInfo: 'Token',
      values: ['row', 'col']
    }, {
      type: 'enumInfo',
      localName: 'STFunctionOperator',
      baseTypeInfo: 'Token',
      values: ['equ', 'neq', 'gt', 'lt', 'gte', 'lte']
    }, {
      type: 'enumInfo',
      localName: 'STFunctionType',
      baseTypeInfo: 'Token',
      values: ['cnt', 'pos', 'revPos', 'posEven', 'posOdd', 'var', 'depth', 'maxDepth']
    }, {
      type: 'enumInfo',
      localName: 'STGrowDirection',
      baseTypeInfo: 'Token',
      values: ['tL', 'tR', 'bL', 'bR']
    }, {
      type: 'enumInfo',
      localName: 'STHierBranchStyle',
      baseTypeInfo: 'Token',
      values: ['l', 'r', 'hang', 'std', 'init']
    }, {
      type: 'enumInfo',
      localName: 'STHierarchyAlignment',
      baseTypeInfo: 'Token',
      values: ['tL', 'tR', 'tCtrCh', 'tCtrDes', 'bL', 'bR', 'bCtrCh', 'bCtrDes', 'lT', 'lB', 'lCtrCh', 'lCtrDes', 'rT', 'rB', 'rCtrCh', 'rCtrDes']
    }, {
      type: 'enumInfo',
      localName: 'STHorizontalAlignment',
      baseTypeInfo: 'Token',
      values: ['l', 'ctr', 'r', 'none']
    }, {
      type: 'enumInfo',
      localName: 'STHueDir',
      baseTypeInfo: 'Token',
      values: ['cw', 'ccw']
    }, {
      type: 'enumInfo',
      localName: 'STLinearDirection',
      baseTypeInfo: 'Token',
      values: ['fromL', 'fromR', 'fromT', 'fromB']
    }, {
      type: 'enumInfo',
      localName: 'STNodeHorizontalAlignment',
      baseTypeInfo: 'Token',
      values: ['l', 'ctr', 'r']
    }, {
      type: 'enumInfo',
      localName: 'STNodeVerticalAlignment',
      baseTypeInfo: 'Token',
      values: ['t', 'mid', 'b']
    }, {
      type: 'enumInfo',
      localName: 'STOffset',
      baseTypeInfo: 'Token',
      values: ['ctr', 'off']
    }, {
      type: 'enumInfo',
      localName: 'STOutputShapeType',
      baseTypeInfo: 'Token',
      values: ['none', 'conn']
    }, {
      type: 'enumInfo',
      localName: 'STParameterId',
      baseTypeInfo: 'Token',
      values: ['horzAlign', 'vertAlign', 'chDir', 'chAlign', 'secChAlign', 'linDir', 'secLinDir', 'stElem', 'bendPt', 'connRout', 'begSty', 'endSty', 'dim', 'rotPath', 'ctrShpMap', 'nodeHorzAlign', 'nodeVertAlign', 'fallback', 'txDir', 'pyraAcctPos', 'pyraAcctTxMar', 'txBlDir', 'txAnchorHorz', 'txAnchorVert', 'txAnchorHorzCh', 'txAnchorVertCh', 'parTxLTRAlign', 'parTxRTLAlign', 'shpTxLTRAlignCh', 'shpTxRTLAlignCh', 'autoTxRot', 'grDir', 'flowDir', 'contDir', 'bkpt', 'off', 'hierAlign', 'bkPtFixedVal', 'stBulletLvl', 'stAng', 'spanAng', 'ar', 'lnSpPar', 'lnSpAfParP', 'lnSpCh', 'lnSpAfChP', 'rtShortDist', 'alignTx', 'pyraLvlNode', 'pyraAcctBkgdNode', 'pyraAcctTxNode', 'srcNode', 'dstNode', 'begPts', 'endPts']
    }, {
      type: 'enumInfo',
      localName: 'STPtType',
      baseTypeInfo: 'Token',
      values: ['node', 'asst', 'doc', 'pres', 'parTrans', 'sibTrans']
    }, {
      type: 'enumInfo',
      localName: 'STPyramidAccentPosition',
      baseTypeInfo: 'Token',
      values: ['bef', 'aft']
    }, {
      type: 'enumInfo',
      localName: 'STPyramidAccentTextMargin',
      baseTypeInfo: 'Token',
      values: ['step', 'stack']
    }, {
      type: 'enumInfo',
      localName: 'STResizeHandlesStr',
      baseTypeInfo: 'Token',
      values: ['exact', 'rel']
    }, {
      type: 'enumInfo',
      localName: 'STRotationPath',
      baseTypeInfo: 'Token',
      values: ['none', 'alongPath']
    }, {
      type: 'enumInfo',
      localName: 'STSecondaryChildAlignment',
      baseTypeInfo: 'Token',
      values: ['none', 't', 'b', 'l', 'r']
    }, {
      type: 'enumInfo',
      localName: 'STSecondaryLinearDirection',
      baseTypeInfo: 'Token',
      values: ['none', 'fromL', 'fromR', 'fromT', 'fromB']
    }, {
      type: 'enumInfo',
      localName: 'STStartingElement',
      baseTypeInfo: 'Token',
      values: ['node', 'trans']
    }, {
      type: 'enumInfo',
      localName: 'STTextAlignment',
      baseTypeInfo: 'Token',
      values: ['l', 'ctr', 'r']
    }, {
      type: 'enumInfo',
      localName: 'STTextAnchorHorizontal',
      baseTypeInfo: 'Token',
      values: ['none', 'ctr']
    }, {
      type: 'enumInfo',
      localName: 'STTextAnchorVertical',
      baseTypeInfo: 'Token',
      values: ['t', 'mid', 'b']
    }, {
      type: 'enumInfo',
      localName: 'STTextBlockDirection',
      baseTypeInfo: 'Token',
      values: ['horz', 'vert']
    }, {
      type: 'enumInfo',
      localName: 'STTextDirection',
      baseTypeInfo: 'Token',
      values: ['fromT', 'fromB']
    }, {
      type: 'enumInfo',
      localName: 'STVariableType',
      baseTypeInfo: 'Token',
      values: ['none', 'orgChart', 'chMax', 'chPref', 'bulEnabled', 'dir', 'hierBranch', 'animOne', 'animLvl', 'resizeHandles']
    }, {
      type: 'enumInfo',
      localName: 'STVerticalAlignment',
      baseTypeInfo: 'Token',
      values: ['t', 'mid', 'b', 'none']
    }],
  elementInfos: [{
      typeInfo: '.CTColorTransform',
      elementName: 'colorsDef'
    }, {
      typeInfo: '.CTColorTransformHeader',
      elementName: 'colorsDefHdr'
    }, {
      typeInfo: '.CTColorTransformHeaderLst',
      elementName: 'colorsDefHdrLst'
    }, {
      typeInfo: '.CTDataModel',
      elementName: 'dataModel'
    }, {
      typeInfo: '.CTDiagramDefinition',
      elementName: 'layoutDef'
    }, {
      typeInfo: '.CTDiagramDefinitionHeader',
      elementName: 'layoutDefHdr'
    }, {
      typeInfo: '.CTDiagramDefinitionHeaderLst',
      elementName: 'layoutDefHdrLst'
    }, {
      typeInfo: '.CTRelIds',
      elementName: 'relIds'
    }, {
      typeInfo: '.CTStyleDefinition',
      elementName: 'styleDef'
    }, {
      typeInfo: '.CTStyleDefinitionHeader',
      elementName: 'styleDefHdr'
    }, {
      typeInfo: '.CTStyleDefinitionHeaderLst',
      elementName: 'styleDefHdrLst'
    }, {
      typeInfo: 'org_docx4j_dml.CTTextBody',
      elementName: 't'
    }]
};
