var org_docx4j_w14_Module_Factory = function () {
  var org_docx4j_w14 = {
    name: 'org_docx4j_w14',
    defaultElementNamespaceURI: 'http:\/\/schemas.microsoft.com\/office\/word\/2010\/wordml',
    defaultAttributeNamespaceURI: 'http:\/\/schemas.microsoft.com\/office\/word\/2010\/wordml',
    dependencies: ['org_docx4j_com_microsoft_schemas_office_drawing_x2010_main', 'org_docx4j_dml', 'org_docx4j_wml'],
    typeInfos: [{
        localName: 'CTBevel',
        typeName: 'CT_Bevel',
        propertyInfos: [{
            name: 'w',
            typeInfo: 'Long',
            type: 'attribute'
          }, {
            name: 'h',
            typeInfo: 'Long',
            type: 'attribute'
          }, {
            name: 'prst',
            typeInfo: '.STBevelPresetType',
            type: 'attribute'
          }]
      }, {
        localName: 'CTCamera',
        typeName: 'CT_Camera',
        propertyInfos: [{
            name: 'prst',
            required: true,
            typeInfo: '.STPresetCameraType',
            type: 'attribute'
          }]
      }, {
        localName: 'CTColor',
        typeName: 'CT_Color',
        propertyInfos: [{
            name: 'srgbClr',
            required: true,
            typeInfo: '.CTSRgbColor'
          }, {
            name: 'schemeClr',
            required: true,
            typeInfo: '.CTSchemeColor'
          }]
      }, {
        localName: 'CTDefaultImageDpi',
        typeName: 'CT_DefaultImageDpi',
        propertyInfos: [{
            name: 'val',
            required: true,
            typeInfo: 'Integer',
            type: 'attribute'
          }]
      }, {
        localName: 'CTFillTextEffect',
        typeName: 'CT_FillTextEffect',
        propertyInfos: [{
            name: 'noFill',
            required: true,
            typeInfo: 'org_docx4j_wml.CTEmpty'
          }, {
            name: 'solidFill',
            required: true,
            typeInfo: '.CTSolidColorFillProperties'
          }, {
            name: 'gradFill',
            required: true,
            typeInfo: '.CTGradientFillProperties'
          }]
      }, {
        localName: 'CTGlow',
        typeName: 'CT_Glow',
        propertyInfos: [{
            name: 'srgbClr',
            required: true,
            typeInfo: '.CTSRgbColor'
          }, {
            name: 'schemeClr',
            required: true,
            typeInfo: '.CTSchemeColor'
          }, {
            name: 'rad',
            typeInfo: 'Long',
            type: 'attribute'
          }]
      }, {
        localName: 'CTGradientFillProperties',
        typeName: 'CT_GradientFillProperties',
        propertyInfos: [{
            name: 'gsLst',
            typeInfo: '.CTGradientStopList'
          }, {
            name: 'lin',
            required: true,
            typeInfo: '.CTLinearShadeProperties'
          }, {
            name: 'path',
            required: true,
            typeInfo: '.CTPathShadeProperties'
          }]
      }, {
        localName: 'CTGradientStop',
        typeName: 'CT_GradientStop',
        propertyInfos: [{
            name: 'srgbClr',
            required: true,
            typeInfo: '.CTSRgbColor'
          }, {
            name: 'schemeClr',
            required: true,
            typeInfo: '.CTSchemeColor'
          }, {
            name: 'pos',
            required: true,
            typeInfo: 'Int',
            type: 'attribute'
          }]
      }, {
        localName: 'CTGradientStopList',
        typeName: 'CT_GradientStopList',
        propertyInfos: [{
            name: 'gs',
            required: true,
            minOccurs: 2,
            maxOccurs: 10,
            collection: true,
            typeInfo: '.CTGradientStop'
          }]
      }, {
        localName: 'CTLigatures',
        typeName: 'CT_Ligatures',
        propertyInfos: [{
            name: 'val',
            required: true,
            typeInfo: '.STLigatures',
            type: 'attribute'
          }]
      }, {
        localName: 'CTLightRig',
        typeName: 'CT_LightRig',
        propertyInfos: [{
            name: 'rot',
            typeInfo: '.CTSphereCoords'
          }, {
            name: 'rig',
            required: true,
            typeInfo: '.STLightRigType',
            type: 'attribute'
          }, {
            name: 'dir',
            required: true,
            typeInfo: '.STLightRigDirection',
            type: 'attribute'
          }]
      }, {
        localName: 'CTLineJoinMiterProperties',
        typeName: 'CT_LineJoinMiterProperties',
        propertyInfos: [{
            name: 'lim',
            typeInfo: 'Int',
            type: 'attribute'
          }]
      }, {
        localName: 'CTLinearShadeProperties',
        typeName: 'CT_LinearShadeProperties',
        propertyInfos: [{
            name: 'ang',
            typeInfo: 'Int',
            type: 'attribute'
          }, {
            name: 'scaled',
            values: ['true', 'false', '0', '1'],
            type: 'attribute'
          }]
      }, {
        localName: 'CTLongHexNumber',
        typeName: 'CT_LongHexNumber',
        propertyInfos: [{
            name: 'val',
            required: true,
            type: 'attribute'
          }]
      }, {
        localName: 'CTNumForm',
        typeName: 'CT_NumForm',
        propertyInfos: [{
            name: 'val',
            required: true,
            typeInfo: '.STNumForm',
            type: 'attribute'
          }]
      }, {
        localName: 'CTNumSpacing',
        typeName: 'CT_NumSpacing',
        propertyInfos: [{
            name: 'val',
            required: true,
            typeInfo: '.STNumSpacing',
            type: 'attribute'
          }]
      }, {
        localName: 'CTOnOff',
        typeName: 'CT_OnOff',
        propertyInfos: [{
            name: 'val',
            values: ['true', 'false', '0', '1'],
            type: 'attribute'
          }]
      }, {
        localName: 'CTPathShadeProperties',
        typeName: 'CT_PathShadeProperties',
        propertyInfos: [{
            name: 'fillToRect',
            typeInfo: '.CTRelativeRect'
          }, {
            name: 'path',
            typeInfo: '.STPathShadeType',
            type: 'attribute'
          }]
      }, {
        localName: 'CTPercentage',
        typeName: 'CT_Percentage',
        propertyInfos: [{
            name: 'val',
            required: true,
            typeInfo: 'Int',
            type: 'attribute'
          }]
      }, {
        localName: 'CTPositiveFixedPercentage',
        typeName: 'CT_PositiveFixedPercentage',
        propertyInfos: [{
            name: 'val',
            required: true,
            typeInfo: 'Int',
            type: 'attribute'
          }]
      }, {
        localName: 'CTPositivePercentage',
        typeName: 'CT_PositivePercentage',
        propertyInfos: [{
            name: 'val',
            required: true,
            typeInfo: 'Int',
            type: 'attribute'
          }]
      }, {
        localName: 'CTPresetLineDashProperties',
        typeName: 'CT_PresetLineDashProperties',
        propertyInfos: [{
            name: 'val',
            typeInfo: '.STPresetLineDashVal',
            type: 'attribute'
          }]
      }, {
        localName: 'CTProps3D',
        typeName: 'CT_Props3D',
        propertyInfos: [{
            name: 'bevelT',
            typeInfo: '.CTBevel'
          }, {
            name: 'bevelB',
            typeInfo: '.CTBevel'
          }, {
            name: 'extrusionClr',
            typeInfo: '.CTColor'
          }, {
            name: 'contourClr',
            typeInfo: '.CTColor'
          }, {
            name: 'extrusionH',
            typeInfo: 'Long',
            type: 'attribute'
          }, {
            name: 'contourW',
            typeInfo: 'Long',
            type: 'attribute'
          }, {
            name: 'prstMaterial',
            typeInfo: '.STPresetMaterialType',
            type: 'attribute'
          }]
      }, {
        localName: 'CTReflection',
        typeName: 'CT_Reflection',
        propertyInfos: [{
            name: 'blurRad',
            typeInfo: 'Long',
            type: 'attribute'
          }, {
            name: 'stA',
            typeInfo: 'Int',
            type: 'attribute'
          }, {
            name: 'stPos',
            typeInfo: 'Int',
            type: 'attribute'
          }, {
            name: 'endA',
            typeInfo: 'Int',
            type: 'attribute'
          }, {
            name: 'endPos',
            typeInfo: 'Int',
            type: 'attribute'
          }, {
            name: 'dist',
            typeInfo: 'Long',
            type: 'attribute'
          }, {
            name: 'dir',
            typeInfo: 'Int',
            type: 'attribute'
          }, {
            name: 'fadeDir',
            typeInfo: 'Int',
            type: 'attribute'
          }, {
            name: 'sx',
            typeInfo: 'Int',
            type: 'attribute'
          }, {
            name: 'sy',
            typeInfo: 'Int',
            type: 'attribute'
          }, {
            name: 'kx',
            typeInfo: 'Int',
            type: 'attribute'
          }, {
            name: 'ky',
            typeInfo: 'Int',
            type: 'attribute'
          }, {
            name: 'algn',
            typeInfo: '.STRectAlignment',
            type: 'attribute'
          }]
      }, {
        localName: 'CTRelativeRect',
        typeName: 'CT_RelativeRect',
        propertyInfos: [{
            name: 'l',
            typeInfo: 'Int',
            type: 'attribute'
          }, {
            name: 't',
            typeInfo: 'Int',
            type: 'attribute'
          }, {
            name: 'r',
            typeInfo: 'Int',
            type: 'attribute'
          }, {
            name: 'b',
            typeInfo: 'Int',
            type: 'attribute'
          }]
      }, {
        localName: 'CTSRgbColor',
        typeName: 'CT_SRgbColor',
        propertyInfos: [{
            name: 'egColorTransform',
            minOccurs: 0,
            collection: true,
            mixed: false,
            allowDom: false,
            elementTypeInfos: [{
                elementName: 'tint',
                typeInfo: '.CTPositiveFixedPercentage'
              }, {
                elementName: 'shade',
                typeInfo: '.CTPositiveFixedPercentage'
              }, {
                elementName: 'alpha',
                typeInfo: '.CTPositiveFixedPercentage'
              }, {
                elementName: 'hueMod',
                typeInfo: '.CTPositivePercentage'
              }, {
                elementName: 'sat',
                typeInfo: '.CTPercentage'
              }, {
                elementName: 'satOff',
                typeInfo: '.CTPercentage'
              }, {
                elementName: 'satMod',
                typeInfo: '.CTPercentage'
              }, {
                elementName: 'lum',
                typeInfo: '.CTPercentage'
              }, {
                elementName: 'lumOff',
                typeInfo: '.CTPercentage'
              }, {
                elementName: 'lumMod',
                typeInfo: '.CTPercentage'
              }],
            type: 'elementRefs'
          }, {
            name: 'val',
            required: true,
            typeInfo: 'HexBinary',
            type: 'attribute'
          }]
      }, {
        localName: 'CTScene3D',
        typeName: 'CT_Scene3D',
        propertyInfos: [{
            name: 'camera',
            required: true,
            typeInfo: '.CTCamera'
          }, {
            name: 'lightRig',
            required: true,
            typeInfo: '.CTLightRig'
          }]
      }, {
        localName: 'CTSchemeColor',
        typeName: 'CT_SchemeColor',
        propertyInfos: [{
            name: 'egColorTransform',
            minOccurs: 0,
            collection: true,
            mixed: false,
            allowDom: false,
            elementTypeInfos: [{
                elementName: 'tint',
                typeInfo: '.CTPositiveFixedPercentage'
              }, {
                elementName: 'shade',
                typeInfo: '.CTPositiveFixedPercentage'
              }, {
                elementName: 'alpha',
                typeInfo: '.CTPositiveFixedPercentage'
              }, {
                elementName: 'hueMod',
                typeInfo: '.CTPositivePercentage'
              }, {
                elementName: 'sat',
                typeInfo: '.CTPercentage'
              }, {
                elementName: 'satOff',
                typeInfo: '.CTPercentage'
              }, {
                elementName: 'satMod',
                typeInfo: '.CTPercentage'
              }, {
                elementName: 'lum',
                typeInfo: '.CTPercentage'
              }, {
                elementName: 'lumOff',
                typeInfo: '.CTPercentage'
              }, {
                elementName: 'lumMod',
                typeInfo: '.CTPercentage'
              }],
            type: 'elementRefs'
          }, {
            name: 'val',
            required: true,
            typeInfo: '.STSchemeColorVal',
            type: 'attribute'
          }]
      }, {
        localName: 'CTSdtCheckbox',
        typeName: 'CT_SdtCheckbox',
        propertyInfos: [{
            name: 'checked',
            typeInfo: '.CTOnOff'
          }, {
            name: 'checkedState',
            typeInfo: '.CTSdtCheckboxSymbol'
          }, {
            name: 'uncheckedState',
            typeInfo: '.CTSdtCheckboxSymbol'
          }]
      }, {
        localName: 'CTSdtCheckboxSymbol',
        typeName: 'CT_SdtCheckboxSymbol',
        propertyInfos: [{
            name: 'font',
            type: 'attribute'
          }, {
            name: 'val',
            type: 'attribute'
          }]
      }, {
        localName: 'CTShadow',
        typeName: 'CT_Shadow',
        propertyInfos: [{
            name: 'srgbClr',
            required: true,
            typeInfo: '.CTSRgbColor'
          }, {
            name: 'schemeClr',
            required: true,
            typeInfo: '.CTSchemeColor'
          }, {
            name: 'blurRad',
            typeInfo: 'Long',
            type: 'attribute'
          }, {
            name: 'dist',
            typeInfo: 'Long',
            type: 'attribute'
          }, {
            name: 'dir',
            typeInfo: 'Int',
            type: 'attribute'
          }, {
            name: 'sx',
            typeInfo: 'Int',
            type: 'attribute'
          }, {
            name: 'sy',
            typeInfo: 'Int',
            type: 'attribute'
          }, {
            name: 'kx',
            typeInfo: 'Int',
            type: 'attribute'
          }, {
            name: 'ky',
            typeInfo: 'Int',
            type: 'attribute'
          }, {
            name: 'algn',
            typeInfo: '.STRectAlignment',
            type: 'attribute'
          }]
      }, {
        localName: 'CTSolidColorFillProperties',
        typeName: 'CT_SolidColorFillProperties',
        propertyInfos: [{
            name: 'srgbClr',
            required: true,
            typeInfo: '.CTSRgbColor'
          }, {
            name: 'schemeClr',
            required: true,
            typeInfo: '.CTSchemeColor'
          }]
      }, {
        localName: 'CTSphereCoords',
        typeName: 'CT_SphereCoords',
        propertyInfos: [{
            name: 'lat',
            required: true,
            typeInfo: 'Int',
            type: 'attribute'
          }, {
            name: 'lon',
            required: true,
            typeInfo: 'Int',
            type: 'attribute'
          }, {
            name: 'rev',
            required: true,
            typeInfo: 'Int',
            type: 'attribute'
          }]
      }, {
        localName: 'CTStyleSet',
        typeName: 'CT_StyleSet',
        propertyInfos: [{
            name: 'id',
            required: true,
            typeInfo: 'UnsignedLong',
            type: 'attribute'
          }, {
            name: 'val',
            values: ['true', 'false', '0', '1'],
            type: 'attribute'
          }]
      }, {
        localName: 'CTStylisticSets',
        typeName: 'CT_StylisticSets',
        propertyInfos: [{
            name: 'styleSet',
            minOccurs: 0,
            collection: true,
            typeInfo: '.CTStyleSet'
          }]
      }, {
        localName: 'CTTextOutlineEffect',
        typeName: 'CT_TextOutlineEffect',
        propertyInfos: [{
            name: 'noFill',
            required: true,
            typeInfo: 'org_docx4j_wml.CTEmpty'
          }, {
            name: 'solidFill',
            required: true,
            typeInfo: '.CTSolidColorFillProperties'
          }, {
            name: 'gradFill',
            required: true,
            typeInfo: '.CTGradientFillProperties'
          }, {
            name: 'prstDash',
            required: true,
            typeInfo: '.CTPresetLineDashProperties'
          }, {
            name: 'round',
            required: true,
            typeInfo: 'org_docx4j_wml.CTEmpty'
          }, {
            name: 'bevel',
            required: true,
            typeInfo: 'org_docx4j_wml.CTEmpty'
          }, {
            name: 'miter',
            required: true,
            typeInfo: '.CTLineJoinMiterProperties'
          }, {
            name: 'w',
            typeInfo: 'Int',
            type: 'attribute'
          }, {
            name: 'cap',
            typeInfo: '.STLineCap',
            type: 'attribute'
          }, {
            name: 'cmpd',
            typeInfo: '.STCompoundLine',
            type: 'attribute'
          }, {
            name: 'algn',
            typeInfo: '.STPenAlignment',
            type: 'attribute'
          }]
      }, {
        localName: 'CTWordContentPart',
        typeName: 'CT_WordContentPart',
        propertyInfos: [{
            name: 'nvContentPartPr',
            typeInfo: '.CTWordContentPartNonVisual'
          }, {
            name: 'xfrm',
            typeInfo: 'org_docx4j_dml.CTTransform2D'
          }, {
            name: 'extLst',
            typeInfo: 'org_docx4j_dml.CTOfficeArtExtensionList'
          }, {
            name: 'bwMode',
            typeInfo: 'org_docx4j_dml.STBlackWhiteMode',
            attributeName: {
              localPart: 'bwMode'
            },
            type: 'attribute'
          }, {
            name: 'id',
            required: true,
            attributeName: {
              localPart: 'id',
              namespaceURI: 'http:\/\/schemas.openxmlformats.org\/officeDocument\/2006\/relationships'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'CTWordContentPartNonVisual',
        typeName: 'CT_WordContentPartNonVisual',
        propertyInfos: [{
            name: 'cNvPr',
            typeInfo: 'org_docx4j_dml.CTNonVisualDrawingProps'
          }, {
            name: 'cNvContentPartPr',
            typeInfo: 'org_docx4j_com_microsoft_schemas_office_drawing_x2010_main.CTNonVisualInkContentPartProperties'
          }]
      }, {
        type: 'enumInfo',
        localName: 'STBevelPresetType',
        baseTypeInfo: 'Token',
        values: ['relaxedInset', 'circle', 'slope', 'cross', 'angle', 'softRound', 'convex', 'coolSlant', 'divot', 'riblet', 'hardEdge', 'artDeco']
      }, {
        type: 'enumInfo',
        localName: 'STCompoundLine',
        values: ['sng', 'dbl', 'thickThin', 'thinThick', 'tri']
      }, {
        type: 'enumInfo',
        localName: 'STLigatures',
        values: ['none', 'standard', 'contextual', 'historical', 'discretional', 'standardContextual', 'standardHistorical', 'contextualHistorical', 'standardDiscretional', 'contextualDiscretional', 'historicalDiscretional', 'standardContextualHistorical', 'standardContextualDiscretional', 'standardHistoricalDiscretional', 'contextualHistoricalDiscretional', 'all']
      }, {
        type: 'enumInfo',
        localName: 'STLightRigDirection',
        baseTypeInfo: 'Token',
        values: ['tl', 't', 'tr', 'l', 'r', 'bl', 'b', 'br']
      }, {
        type: 'enumInfo',
        localName: 'STLightRigType',
        baseTypeInfo: 'Token',
        values: ['legacyFlat1', 'legacyFlat2', 'legacyFlat3', 'legacyFlat4', 'legacyNormal1', 'legacyNormal2', 'legacyNormal3', 'legacyNormal4', 'legacyHarsh1', 'legacyHarsh2', 'legacyHarsh3', 'legacyHarsh4', 'threePt', 'balanced', 'soft', 'harsh', 'flood', 'contrasting', 'morning', 'sunrise', 'sunset', 'chilly', 'freezing', 'flat', 'twoPt', 'glow', 'brightRoom']
      }, {
        type: 'enumInfo',
        localName: 'STLineCap',
        values: ['rnd', 'sq', 'flat']
      }, {
        type: 'enumInfo',
        localName: 'STNumForm',
        values: ['default', 'lining', 'oldStyle']
      }, {
        type: 'enumInfo',
        localName: 'STNumSpacing',
        values: ['default', 'proportional', 'tabular']
      }, {
        type: 'enumInfo',
        localName: 'STPathShadeType',
        values: ['shape', 'circle', 'rect']
      }, {
        type: 'enumInfo',
        localName: 'STPenAlignment',
        values: ['ctr', 'in']
      }, {
        type: 'enumInfo',
        localName: 'STPresetCameraType',
        baseTypeInfo: 'Token',
        values: ['legacyObliqueTopLeft', 'legacyObliqueTop', 'legacyObliqueTopRight', 'legacyObliqueLeft', 'legacyObliqueFront', 'legacyObliqueRight', 'legacyObliqueBottomLeft', 'legacyObliqueBottom', 'legacyObliqueBottomRight', 'legacyPerspectiveTopLeft', 'legacyPerspectiveTop', 'legacyPerspectiveTopRight', 'legacyPerspectiveLeft', 'legacyPerspectiveFront', 'legacyPerspectiveRight', 'legacyPerspectiveBottomLeft', 'legacyPerspectiveBottom', 'legacyPerspectiveBottomRight', 'orthographicFront', 'isometricTopUp', 'isometricTopDown', 'isometricBottomUp', 'isometricBottomDown', 'isometricLeftUp', 'isometricLeftDown', 'isometricRightUp', 'isometricRightDown', 'isometricOffAxis1Left', 'isometricOffAxis1Right', 'isometricOffAxis1Top', 'isometricOffAxis2Left', 'isometricOffAxis2Right', 'isometricOffAxis2Top', 'isometricOffAxis3Left', 'isometricOffAxis3Right', 'isometricOffAxis3Bottom', 'isometricOffAxis4Left', 'isometricOffAxis4Right', 'isometricOffAxis4Bottom', 'obliqueTopLeft', 'obliqueTop', 'obliqueTopRight', 'obliqueLeft', 'obliqueRight', 'obliqueBottomLeft', 'obliqueBottom', 'obliqueBottomRight', 'perspectiveFront', 'perspectiveLeft', 'perspectiveRight', 'perspectiveAbove', 'perspectiveBelow', 'perspectiveAboveLeftFacing', 'perspectiveAboveRightFacing', 'perspectiveContrastingLeftFacing', 'perspectiveContrastingRightFacing', 'perspectiveHeroicLeftFacing', 'perspectiveHeroicRightFacing', 'perspectiveHeroicExtremeLeftFacing', 'perspectiveHeroicExtremeRightFacing', 'perspectiveRelaxed', 'perspectiveRelaxedModerately']
      }, {
        type: 'enumInfo',
        localName: 'STPresetLineDashVal',
        values: ['solid', 'dot', 'sysDot', 'dash', 'sysDash', 'lgDash', 'dashDot', 'sysDashDot', 'lgDashDot', 'lgDashDotDot', 'sysDashDotDot']
      }, {
        type: 'enumInfo',
        localName: 'STPresetMaterialType',
        baseTypeInfo: 'Token',
        values: ['legacyMatte', 'legacyPlastic', 'legacyMetal', 'legacyWireframe', 'matte', 'plastic', 'metal', 'warmMatte', 'translucentPowder', 'powder', 'dkEdge', 'softEdge', 'clear', 'flat', 'softmetal', 'none']
      }, {
        type: 'enumInfo',
        localName: 'STRectAlignment',
        values: ['none', 'tl', 't', 'tr', 'l', 'ctr', 'r', 'bl', 'b', 'br']
      }, {
        type: 'enumInfo',
        localName: 'STSchemeColorVal',
        values: ['bg1', 'tx1', 'bg2', 'tx2', 'accent1', 'accent2', 'accent3', 'accent4', 'accent5', 'accent6', 'hlink', 'folHlink', 'dk1', 'lt1', 'dk2', 'lt2', 'phClr']
      }],
    elementInfos: [{
        typeInfo: '.CTPositiveFixedPercentage',
        elementName: 'alpha',
        scope: '.CTSRgbColor'
      }, {
        typeInfo: '.CTPositiveFixedPercentage',
        elementName: 'alpha',
        scope: '.CTSchemeColor'
      }, {
        typeInfo: '.CTSdtCheckbox',
        elementName: 'checkbox'
      }, {
        typeInfo: '.CTOnOff',
        elementName: 'conflictMode'
      }, {
        typeInfo: '.CTWordContentPart',
        elementName: 'contentPart'
      }, {
        typeInfo: 'org_docx4j_wml.CTMarkup',
        elementName: 'customXmlConflictDelRangeEnd'
      }, {
        typeInfo: 'org_docx4j_wml.CTTrackChange',
        elementName: 'customXmlConflictDelRangeStart'
      }, {
        typeInfo: 'org_docx4j_wml.CTMarkup',
        elementName: 'customXmlConflictInsRangeEnd'
      }, {
        typeInfo: 'org_docx4j_wml.CTTrackChange',
        elementName: 'customXmlConflictInsRangeStart'
      }, {
        typeInfo: '.CTDefaultImageDpi',
        elementName: 'defaultImageDpi'
      }, {
        typeInfo: '.CTOnOff',
        elementName: 'discardImageEditingData'
      }, {
        typeInfo: '.CTLongHexNumber',
        elementName: 'docId'
      }, {
        typeInfo: 'org_docx4j_wml.CTEmpty',
        elementName: 'entityPicker'
      }, {
        typeInfo: '.CTPositivePercentage',
        elementName: 'hueMod',
        scope: '.CTSRgbColor'
      }, {
        typeInfo: '.CTPositivePercentage',
        elementName: 'hueMod',
        scope: '.CTSchemeColor'
      }, {
        typeInfo: '.CTPercentage',
        elementName: 'lum',
        scope: '.CTSRgbColor'
      }, {
        typeInfo: '.CTPercentage',
        elementName: 'lum',
        scope: '.CTSchemeColor'
      }, {
        typeInfo: '.CTPercentage',
        elementName: 'lumMod',
        scope: '.CTSRgbColor'
      }, {
        typeInfo: '.CTPercentage',
        elementName: 'lumMod',
        scope: '.CTSchemeColor'
      }, {
        typeInfo: '.CTPercentage',
        elementName: 'lumOff',
        scope: '.CTSRgbColor'
      }, {
        typeInfo: '.CTPercentage',
        elementName: 'lumOff',
        scope: '.CTSchemeColor'
      }, {
        typeInfo: '.CTPercentage',
        elementName: 'sat',
        scope: '.CTSRgbColor'
      }, {
        typeInfo: '.CTPercentage',
        elementName: 'sat',
        scope: '.CTSchemeColor'
      }, {
        typeInfo: '.CTPercentage',
        elementName: 'satMod',
        scope: '.CTSRgbColor'
      }, {
        typeInfo: '.CTPercentage',
        elementName: 'satMod',
        scope: '.CTSchemeColor'
      }, {
        typeInfo: '.CTPercentage',
        elementName: 'satOff',
        scope: '.CTSRgbColor'
      }, {
        typeInfo: '.CTPercentage',
        elementName: 'satOff',
        scope: '.CTSchemeColor'
      }, {
        typeInfo: '.CTPositiveFixedPercentage',
        elementName: 'shade',
        scope: '.CTSRgbColor'
      }, {
        typeInfo: '.CTPositiveFixedPercentage',
        elementName: 'shade',
        scope: '.CTSchemeColor'
      }, {
        typeInfo: '.CTShadow',
        elementName: 'shadow'
      }, {
        typeInfo: '.CTPositiveFixedPercentage',
        elementName: 'tint',
        scope: '.CTSRgbColor'
      }, {
        typeInfo: '.CTPositiveFixedPercentage',
        elementName: 'tint',
        scope: '.CTSchemeColor'
      }]
  };
  return {
    org_docx4j_w14: org_docx4j_w14
  };
};
if (typeof define === 'function' && define.amd) {
  define([], org_docx4j_w14_Module_Factory);
}
else {
  var org_docx4j_w14_Module = org_docx4j_w14_Module_Factory();
  if (typeof module !== 'undefined' && module.exports) {
    module.exports.org_docx4j_w14 = org_docx4j_w14_Module.org_docx4j_w14;
  }
  else {
    var org_docx4j_w14 = org_docx4j_w14_Module.org_docx4j_w14;
  }
}