// Generated by jsonix-schema-compiler: TypeScript declarations for the Jsonix module [org_docx4j_com_microsoft_schemas_office_drawing_x2013_main_command]. Do not edit.
// Describes the objects Jsonix produces when unmarshalling with this module's mappings.
import type * as Dep_org_docx4j_dml from './org_docx4j_dml';

/** Jsonix.XML.QName */
export interface XmlQName { namespaceURI: string; localPart: string; prefix?: string; key?: string; string?: string; }
/** Jsonix.XML.Calendar: the representation of date, time and dateTime values; unset fields are NaN. */
export interface XmlCalendar { year?: number; month?: number; day?: number; hour?: number; minute?: number; second?: number; fractionalSecond?: number; timezone?: number; }
/** The representation of xs:duration values. */
export interface XmlDuration { sign?: number; years?: number; months?: number; days?: number; hours?: number; minutes?: number; seconds?: number; }
/** An element as returned by an unmarshaller or held by an elementRef property. */
export interface TypedNamedValue<T> { name: XmlQName; value: T; }
/** A DOM node, allowed where the mapping permits DOM content (allowDom). */
export type XmlDomNode = any;
/** The value of an anyElement property: a typed element, a DOM node or (if mixed) text. */
export type XmlAnyElement = any;
/** The value of an anyAttribute property. */
export interface XmlAnyAttributes { [attributeName: string]: string; }
/** A Jsonix mapping object as consumed by new Jsonix.Context([...]); R is the union of its global element types. */
export interface JsonixMapping<R = unknown> { readonly __rootElement?: R; readonly [key: string]: unknown; }

export interface CTChangesData {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2013_main_command.CTChangesData';
  extLst?: Dep_org_docx4j_dml.CTOfficeArtExtensionList;
  actId?: number;
  dt?: XmlCalendar;
  v?: number;
  id?: string;
  name?: string;
  userId?: string;
  providerId?: string;
  clId?: string;
  email?: string;
}

export interface CTConnectorChanges {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2013_main_command.CTConnectorChanges';
  chgData?: CTChangesData;
  cxnSpMkLst: CTConnectorMonikerList;
  extLst?: Dep_org_docx4j_dml.CTOfficeArtExtensionList;
  chg: STConnectorChangeBit[];
}

export interface CTConnectorMoniker {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2013_main_command.CTConnectorMoniker';
  id: number;
  creationId?: string;
}

export interface CTConnectorMonikerList {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2013_main_command.CTConnectorMonikerList';
  any?: XmlAnyElement[];
}

export interface CTGraphicFrameChanges {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2013_main_command.CTGraphicFrameChanges';
  chgData?: CTChangesData;
  graphicFrameMkLst: CTGraphicFrameMonikerList;
  extLst?: Dep_org_docx4j_dml.CTOfficeArtExtensionList;
  chg: STGraphicFrameChangeBit[];
}

export interface CTGraphicFrameMoniker {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2013_main_command.CTGraphicFrameMoniker';
  id: number;
  creationId?: string;
}

export interface CTGraphicFrameMonikerList {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2013_main_command.CTGraphicFrameMonikerList';
  any?: XmlAnyElement[];
}

export interface CTGroupShapeChanges {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2013_main_command.CTGroupShapeChanges';
  chgData?: CTChangesData;
  grpSpMkLst: CTGroupShapeMonikerList;
  extLst?: Dep_org_docx4j_dml.CTOfficeArtExtensionList;
  chg: STGroupShapeChangeBit[];
}

export interface CTGroupShapeMoniker {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2013_main_command.CTGroupShapeMoniker';
  id: number;
  creationId?: string;
}

export interface CTGroupShapeMonikerList {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2013_main_command.CTGroupShapeMonikerList';
  any?: XmlAnyElement[];
}

export interface CTInkChanges {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2013_main_command.CTInkChanges';
  chgData?: CTChangesData;
  inkMkLst: CTInkMonikerList;
  extLst?: Dep_org_docx4j_dml.CTOfficeArtExtensionList;
  chg: STInkChangeBit[];
}

export interface CTInkMoniker {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2013_main_command.CTInkMoniker';
  id: number;
  creationId?: string;
}

export interface CTInkMonikerList {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2013_main_command.CTInkMonikerList';
  any?: XmlAnyElement[];
}

export interface CTPictureChanges {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2013_main_command.CTPictureChanges';
  chgData?: CTChangesData;
  picMkLst: CTPictureMonikerList;
  extLst?: Dep_org_docx4j_dml.CTOfficeArtExtensionList;
  chg: STPictureChangeBit[];
}

export interface CTPictureMoniker {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2013_main_command.CTPictureMoniker';
  id: number;
  creationId?: string;
}

export interface CTPictureMonikerList {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2013_main_command.CTPictureMonikerList';
  any?: XmlAnyElement[];
}

export interface CTShapeChanges {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2013_main_command.CTShapeChanges';
  chgData?: CTChangesData;
  spMkLst: CTShapeMonikerList;
  extLst?: Dep_org_docx4j_dml.CTOfficeArtExtensionList;
  chg: STShapeChangeBit[];
}

export interface CTShapeMoniker {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2013_main_command.CTShapeMoniker';
  id: number;
  creationId?: string;
}

export interface CTShapeMonikerList {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2013_main_command.CTShapeMonikerList';
  any?: XmlAnyElement[];
}

export type STConnectorChangeBit = 'add' | 'del' | 'mod' | 'ord' | 'topLvl' | 'modVis' | 'replST' | 'delST' | 'replId';

export type STGraphicFrameChangeBit = 'add' | 'del' | 'mod' | 'ord' | 'topLvl' | 'modVis' | 'replST' | 'delST' | 'replId' | 'modGraphic';

export type STGroupShapeChangeBit = 'add' | 'del' | 'mod' | 'ord' | 'topLvl' | 'modVis' | 'replST' | 'delST' | 'replId';

export type STInkChangeBit = 'add' | 'del' | 'mod' | 'ord' | 'topLvl' | 'modVis' | 'replST' | 'delST' | 'replId' | 'reco' | 'modStrokes';

export type STPictureChangeBit = 'add' | 'del' | 'mod' | 'ord' | 'topLvl' | 'modVis' | 'replST' | 'delST' | 'replId' | 'modCrop';

export type STShapeChangeBit = 'add' | 'del' | 'mod' | 'ord' | 'topLvl' | 'modVis' | 'replST' | 'delST' | 'replId' | 'modCrop';

export type CxnSpMkLstElement = TypedNamedValue<CTConnectorMonikerList>;

export type GraphicFrameMkLstElement = TypedNamedValue<CTGraphicFrameMonikerList>;

export type GrpMkLstElement = TypedNamedValue<CTGroupShapeMonikerList>;

export type InkMkLstElement = TypedNamedValue<CTInkMonikerList>;

export type PicMkLstElement = TypedNamedValue<CTPictureMonikerList>;

export type SpMkLstElement = TypedNamedValue<CTShapeMonikerList>;

/** Any global element of this mapping, i.e. what an unmarshaller returns. */
export type RootElement = CxnSpMkLstElement | GraphicFrameMkLstElement | GrpMkLstElement | InkMkLstElement | PicMkLstElement | SpMkLstElement;

/** The Jsonix mapping [org_docx4j_com_microsoft_schemas_office_drawing_x2013_main_command] exported by the module's JavaScript file. */
export declare const org_docx4j_com_microsoft_schemas_office_drawing_x2013_main_command: JsonixMapping<RootElement>;
