// Generated by jsonix-schema-compiler: TypeScript declarations for the Jsonix module [org_docx4j_w14]. Do not edit.
// Describes the objects Jsonix produces when unmarshalling with this module's mappings.
import type * as Dep_org_docx4j_wml from './org_docx4j_wml';
import type * as Dep_org_docx4j_com_microsoft_schemas_office_word_x2010_wordprocessingCanvas from './org_docx4j_com_microsoft_schemas_office_word_x2010_wordprocessingCanvas';
import type * as Dep_org_docx4j_dml from './org_docx4j_dml';
import type * as Dep_org_docx4j_com_microsoft_schemas_office_drawing_x2010_main from './org_docx4j_com_microsoft_schemas_office_drawing_x2010_main';

/** Jsonix.XML.QName */
export interface XmlQName { namespaceURI: string; localPart: string; prefix?: string; key?: string; string?: string; }
/** Jsonix.XML.Calendar: the representation of date, time and dateTime values; unset fields are NaN. */
export interface XmlCalendar { year?: number; month?: number; day?: number; hour?: number; minute?: number; second?: number; fractionalSecond?: number; timezone?: number; }
/** The representation of xs:duration values. */
export interface XmlDuration { sign?: number; years?: number; months?: number; days?: number; hours?: number; minutes?: number; seconds?: number; }
/** An element as returned by an unmarshaller or held by an elementRef property. */
export interface TypedNamedValue<T> { name: XmlQName; value: T; }
/** A DOM node, allowed where the mapping permits DOM content (allowDom). */
export type XmlDomNode = any;
/** The value of an anyElement property: a typed element, a DOM node or (if mixed) text. */
export type XmlAnyElement = any;
/** The value of an anyAttribute property. */
export interface XmlAnyAttributes { [attributeName: string]: string; }
/** A Jsonix mapping object as consumed by new Jsonix.Context([...]); R is the union of its global element types. */
export interface JsonixMapping<R = unknown> { readonly __rootElement?: R; readonly [key: string]: unknown; }

export interface CTBevel {
  TYPE_NAME?: 'org_docx4j_w14.CTBevel';
  readonly PARENT?: CTProps3D;
  h?: number;
  prst?: STBevelPresetType;
  w?: number;
}

export interface CTCamera {
  TYPE_NAME?: 'org_docx4j_w14.CTCamera';
  readonly PARENT?: CTScene3D;
  prst: STPresetCameraType;
}

export interface CTColor {
  TYPE_NAME?: 'org_docx4j_w14.CTColor';
  readonly PARENT?: CTProps3D;
  srgbClr: CTSRgbColor;
  schemeClr: CTSchemeColor;
}

export interface CTDefaultImageDpi {
  TYPE_NAME?: 'org_docx4j_w14.CTDefaultImageDpi';
  readonly PARENT?: Dep_org_docx4j_wml.CTSettings;
  val: number;
}

export interface CTFillTextEffect {
  TYPE_NAME?: 'org_docx4j_w14.CTFillTextEffect';
  readonly PARENT?: Dep_org_docx4j_wml.CTParaRPrOriginal | Dep_org_docx4j_wml.CTRPrChange.RPr | Dep_org_docx4j_wml.ParaRPr | Dep_org_docx4j_wml.RPr;
  noFill: Dep_org_docx4j_wml.CTEmpty;
  solidFill: CTSolidColorFillProperties;
  gradFill: CTGradientFillProperties;
}

export interface CTGlow {
  TYPE_NAME?: 'org_docx4j_w14.CTGlow';
  readonly PARENT?: Dep_org_docx4j_wml.CTParaRPrOriginal | Dep_org_docx4j_wml.CTRPrChange.RPr | Dep_org_docx4j_wml.ParaRPr | Dep_org_docx4j_wml.RPr;
  srgbClr: CTSRgbColor;
  schemeClr: CTSchemeColor;
  rad?: number;
}

export interface CTGradientFillProperties {
  TYPE_NAME?: 'org_docx4j_w14.CTGradientFillProperties';
  readonly PARENT?: CTFillTextEffect | CTTextOutlineEffect;
  gsLst?: CTGradientStopList;
  lin: CTLinearShadeProperties;
  path: CTPathShadeProperties;
}

export interface CTGradientStop {
  TYPE_NAME?: 'org_docx4j_w14.CTGradientStop';
  readonly PARENT?: CTGradientStopList;
  srgbClr: CTSRgbColor;
  schemeClr: CTSchemeColor;
  pos: number;
}

export interface CTGradientStopList {
  TYPE_NAME?: 'org_docx4j_w14.CTGradientStopList';
  readonly PARENT?: CTGradientFillProperties;
  gs: CTGradientStop[];
}

export interface CTLigatures {
  TYPE_NAME?: 'org_docx4j_w14.CTLigatures';
  readonly PARENT?: Dep_org_docx4j_wml.CTParaRPrOriginal | Dep_org_docx4j_wml.CTRPrChange.RPr | Dep_org_docx4j_wml.ParaRPr | Dep_org_docx4j_wml.RPr;
  val: STLigatures;
}

export interface CTLightRig {
  TYPE_NAME?: 'org_docx4j_w14.CTLightRig';
  readonly PARENT?: CTScene3D;
  rot?: CTSphereCoords;
  dir: STLightRigDirection;
  rig: STLightRigType;
}

export interface CTLineJoinMiterProperties {
  TYPE_NAME?: 'org_docx4j_w14.CTLineJoinMiterProperties';
  readonly PARENT?: CTTextOutlineEffect;
  lim?: number;
}

export interface CTLinearShadeProperties {
  TYPE_NAME?: 'org_docx4j_w14.CTLinearShadeProperties';
  readonly PARENT?: CTGradientFillProperties;
  ang?: number;
  scaled?: string;
}

export interface CTLongHexNumber {
  TYPE_NAME?: 'org_docx4j_w14.CTLongHexNumber';
  readonly PARENT?: Dep_org_docx4j_wml.CTSettings;
  val: string;
}

export interface CTNumForm {
  TYPE_NAME?: 'org_docx4j_w14.CTNumForm';
  readonly PARENT?: Dep_org_docx4j_wml.CTParaRPrOriginal | Dep_org_docx4j_wml.CTRPrChange.RPr | Dep_org_docx4j_wml.ParaRPr | Dep_org_docx4j_wml.RPr;
  val: STNumForm;
}

export interface CTNumSpacing {
  TYPE_NAME?: 'org_docx4j_w14.CTNumSpacing';
  readonly PARENT?: Dep_org_docx4j_wml.CTParaRPrOriginal | Dep_org_docx4j_wml.CTRPrChange.RPr | Dep_org_docx4j_wml.ParaRPr | Dep_org_docx4j_wml.RPr;
  val: STNumSpacing;
}

export interface CTOnOff {
  TYPE_NAME?: 'org_docx4j_w14.CTOnOff';
  readonly PARENT?: CTSdtCheckbox | Dep_org_docx4j_wml.CTParaRPrOriginal | Dep_org_docx4j_wml.CTRPrChange.RPr | Dep_org_docx4j_wml.CTSettings | Dep_org_docx4j_wml.ParaRPr | Dep_org_docx4j_wml.RPr;
  val?: string;
}

export interface CTPathShadeProperties {
  TYPE_NAME?: 'org_docx4j_w14.CTPathShadeProperties';
  readonly PARENT?: CTGradientFillProperties;
  fillToRect?: CTRelativeRect;
  path?: STPathShadeType;
}

export interface CTPercentage {
  TYPE_NAME?: 'org_docx4j_w14.CTPercentage';
  readonly PARENT?: CTSRgbColor | CTSchemeColor;
  val: number;
}

export interface CTPositiveFixedPercentage {
  TYPE_NAME?: 'org_docx4j_w14.CTPositiveFixedPercentage';
  readonly PARENT?: CTSRgbColor | CTSchemeColor;
  val: number;
}

export interface CTPositivePercentage {
  TYPE_NAME?: 'org_docx4j_w14.CTPositivePercentage';
  readonly PARENT?: CTSRgbColor | CTSchemeColor;
  val: number;
}

export interface CTPresetLineDashProperties {
  TYPE_NAME?: 'org_docx4j_w14.CTPresetLineDashProperties';
  readonly PARENT?: CTTextOutlineEffect;
  val?: STPresetLineDashVal;
}

export interface CTProps3D {
  TYPE_NAME?: 'org_docx4j_w14.CTProps3D';
  readonly PARENT?: Dep_org_docx4j_wml.CTParaRPrOriginal | Dep_org_docx4j_wml.CTRPrChange.RPr | Dep_org_docx4j_wml.ParaRPr | Dep_org_docx4j_wml.RPr;
  bevelT?: CTBevel;
  bevelB?: CTBevel;
  extrusionClr?: CTColor;
  contourClr?: CTColor;
  contourW?: number;
  extrusionH?: number;
  prstMaterial?: STPresetMaterialType;
}

export interface CTReflection {
  TYPE_NAME?: 'org_docx4j_w14.CTReflection';
  readonly PARENT?: Dep_org_docx4j_wml.CTParaRPrOriginal | Dep_org_docx4j_wml.CTRPrChange.RPr | Dep_org_docx4j_wml.ParaRPr | Dep_org_docx4j_wml.RPr;
  algn?: STRectAlignment;
  blurRad?: number;
  dir?: number;
  dist?: number;
  endA?: number;
  endPos?: number;
  fadeDir?: number;
  kx?: number;
  ky?: number;
  stA?: number;
  stPos?: number;
  sx?: number;
  sy?: number;
}

export interface CTRelativeRect {
  TYPE_NAME?: 'org_docx4j_w14.CTRelativeRect';
  readonly PARENT?: CTPathShadeProperties;
  b?: number;
  l?: number;
  r?: number;
  t?: number;
}

export interface CTSRgbColor {
  TYPE_NAME?: 'org_docx4j_w14.CTSRgbColor';
  readonly PARENT?: CTColor | CTGlow | CTGradientStop | CTShadow | CTSolidColorFillProperties;
  egColorTransform?: (TypedNamedValue<CTPositiveFixedPercentage> | TypedNamedValue<CTPositivePercentage> | TypedNamedValue<CTPercentage>)[];
  val: string;
}

export interface CTScene3D {
  TYPE_NAME?: 'org_docx4j_w14.CTScene3D';
  readonly PARENT?: Dep_org_docx4j_wml.CTParaRPrOriginal | Dep_org_docx4j_wml.CTRPrChange.RPr | Dep_org_docx4j_wml.ParaRPr | Dep_org_docx4j_wml.RPr;
  camera: CTCamera;
  lightRig: CTLightRig;
}

export interface CTSchemeColor {
  TYPE_NAME?: 'org_docx4j_w14.CTSchemeColor';
  readonly PARENT?: CTColor | CTGlow | CTGradientStop | CTShadow | CTSolidColorFillProperties;
  egColorTransform?: (TypedNamedValue<CTPositiveFixedPercentage> | TypedNamedValue<CTPositivePercentage> | TypedNamedValue<CTPercentage>)[];
  val: STSchemeColorVal;
}

export interface CTSdtCheckbox {
  TYPE_NAME?: 'org_docx4j_w14.CTSdtCheckbox';
  readonly PARENT?: Dep_org_docx4j_wml.SdtPr;
  checked?: CTOnOff;
  checkedState?: CTSdtCheckboxSymbol;
  uncheckedState?: CTSdtCheckboxSymbol;
}

export interface CTSdtCheckboxSymbol {
  TYPE_NAME?: 'org_docx4j_w14.CTSdtCheckboxSymbol';
  readonly PARENT?: CTSdtCheckbox;
  font?: string;
  val?: string;
}

export interface CTShadow {
  TYPE_NAME?: 'org_docx4j_w14.CTShadow';
  readonly PARENT?: Dep_org_docx4j_wml.CTParaRPrOriginal | Dep_org_docx4j_wml.CTRPrChange.RPr | Dep_org_docx4j_wml.ParaRPr | Dep_org_docx4j_wml.RPr;
  srgbClr: CTSRgbColor;
  schemeClr: CTSchemeColor;
  algn?: STRectAlignment;
  blurRad?: number;
  dir?: number;
  dist?: number;
  kx?: number;
  ky?: number;
  sx?: number;
  sy?: number;
}

export interface CTSolidColorFillProperties {
  TYPE_NAME?: 'org_docx4j_w14.CTSolidColorFillProperties';
  readonly PARENT?: CTFillTextEffect | CTTextOutlineEffect;
  srgbClr: CTSRgbColor;
  schemeClr: CTSchemeColor;
}

export interface CTSphereCoords {
  TYPE_NAME?: 'org_docx4j_w14.CTSphereCoords';
  readonly PARENT?: CTLightRig;
  lat: number;
  lon: number;
  rev: number;
}

export interface CTStyleSet {
  TYPE_NAME?: 'org_docx4j_w14.CTStyleSet';
  readonly PARENT?: CTStylisticSets;
  id: number;
  val?: string;
}

export interface CTStylisticSets {
  TYPE_NAME?: 'org_docx4j_w14.CTStylisticSets';
  readonly PARENT?: Dep_org_docx4j_wml.CTParaRPrOriginal | Dep_org_docx4j_wml.CTRPrChange.RPr | Dep_org_docx4j_wml.ParaRPr | Dep_org_docx4j_wml.RPr;
  styleSet?: CTStyleSet[];
}

export interface CTTextOutlineEffect {
  TYPE_NAME?: 'org_docx4j_w14.CTTextOutlineEffect';
  readonly PARENT?: Dep_org_docx4j_wml.CTParaRPrOriginal | Dep_org_docx4j_wml.CTRPrChange.RPr | Dep_org_docx4j_wml.ParaRPr | Dep_org_docx4j_wml.RPr;
  noFill: Dep_org_docx4j_wml.CTEmpty;
  solidFill: CTSolidColorFillProperties;
  gradFill: CTGradientFillProperties;
  prstDash: CTPresetLineDashProperties;
  round: Dep_org_docx4j_wml.CTEmpty;
  bevel: Dep_org_docx4j_wml.CTEmpty;
  miter: CTLineJoinMiterProperties;
  algn?: STPenAlignment;
  cap?: STLineCap;
  cmpd?: STCompoundLine;
  w?: number;
}

export interface CTWordContentPart {
  TYPE_NAME?: 'org_docx4j_w14.CTWordContentPart';
  readonly PARENT?: Dep_org_docx4j_com_microsoft_schemas_office_word_x2010_wordprocessingCanvas.CTWordprocessingCanvas;
  nvContentPartPr?: CTWordContentPartNonVisual;
  xfrm?: Dep_org_docx4j_dml.CTTransform2D;
  extLst?: Dep_org_docx4j_dml.CTOfficeArtExtensionList;
  bwMode?: Dep_org_docx4j_dml.STBlackWhiteMode;
  id: string;
}

export interface CTWordContentPartNonVisual {
  TYPE_NAME?: 'org_docx4j_w14.CTWordContentPartNonVisual';
  readonly PARENT?: CTWordContentPart;
  cNvPr?: Dep_org_docx4j_dml.CTNonVisualDrawingProps;
  cNvContentPartPr?: Dep_org_docx4j_com_microsoft_schemas_office_drawing_x2010_main.CTNonVisualInkContentPartProperties;
}

export type STBevelPresetType = 'relaxedInset' | 'circle' | 'slope' | 'cross' | 'angle' | 'softRound' | 'convex' | 'coolSlant' | 'divot' | 'riblet' | 'hardEdge' | 'artDeco';

export type STCompoundLine = 'sng' | 'dbl' | 'thickThin' | 'thinThick' | 'tri';

export type STLigatures = 'none' | 'standard' | 'contextual' | 'historical' | 'discretional' | 'standardContextual' | 'standardHistorical' | 'contextualHistorical' | 'standardDiscretional' | 'contextualDiscretional' | 'historicalDiscretional' | 'standardContextualHistorical' | 'standardContextualDiscretional' | 'standardHistoricalDiscretional' | 'contextualHistoricalDiscretional' | 'all';

export type STLightRigDirection = 'tl' | 't' | 'tr' | 'l' | 'r' | 'bl' | 'b' | 'br';

export type STLightRigType = 'legacyFlat1' | 'legacyFlat2' | 'legacyFlat3' | 'legacyFlat4' | 'legacyNormal1' | 'legacyNormal2' | 'legacyNormal3' | 'legacyNormal4' | 'legacyHarsh1' | 'legacyHarsh2' | 'legacyHarsh3' | 'legacyHarsh4' | 'threePt' | 'balanced' | 'soft' | 'harsh' | 'flood' | 'contrasting' | 'morning' | 'sunrise' | 'sunset' | 'chilly' | 'freezing' | 'flat' | 'twoPt' | 'glow' | 'brightRoom';

export type STLineCap = 'rnd' | 'sq' | 'flat';

export type STNumForm = 'default' | 'lining' | 'oldStyle';

export type STNumSpacing = 'default' | 'proportional' | 'tabular';

export type STPathShadeType = 'shape' | 'circle' | 'rect';

export type STPenAlignment = 'ctr' | 'in';

export type STPresetCameraType = 'legacyObliqueTopLeft' | 'legacyObliqueTop' | 'legacyObliqueTopRight' | 'legacyObliqueLeft' | 'legacyObliqueFront' | 'legacyObliqueRight' | 'legacyObliqueBottomLeft' | 'legacyObliqueBottom' | 'legacyObliqueBottomRight' | 'legacyPerspectiveTopLeft' | 'legacyPerspectiveTop' | 'legacyPerspectiveTopRight' | 'legacyPerspectiveLeft' | 'legacyPerspectiveFront' | 'legacyPerspectiveRight' | 'legacyPerspectiveBottomLeft' | 'legacyPerspectiveBottom' | 'legacyPerspectiveBottomRight' | 'orthographicFront' | 'isometricTopUp' | 'isometricTopDown' | 'isometricBottomUp' | 'isometricBottomDown' | 'isometricLeftUp' | 'isometricLeftDown' | 'isometricRightUp' | 'isometricRightDown' | 'isometricOffAxis1Left' | 'isometricOffAxis1Right' | 'isometricOffAxis1Top' | 'isometricOffAxis2Left' | 'isometricOffAxis2Right' | 'isometricOffAxis2Top' | 'isometricOffAxis3Left' | 'isometricOffAxis3Right' | 'isometricOffAxis3Bottom' | 'isometricOffAxis4Left' | 'isometricOffAxis4Right' | 'isometricOffAxis4Bottom' | 'obliqueTopLeft' | 'obliqueTop' | 'obliqueTopRight' | 'obliqueLeft' | 'obliqueRight' | 'obliqueBottomLeft' | 'obliqueBottom' | 'obliqueBottomRight' | 'perspectiveFront' | 'perspectiveLeft' | 'perspectiveRight' | 'perspectiveAbove' | 'perspectiveBelow' | 'perspectiveAboveLeftFacing' | 'perspectiveAboveRightFacing' | 'perspectiveContrastingLeftFacing' | 'perspectiveContrastingRightFacing' | 'perspectiveHeroicLeftFacing' | 'perspectiveHeroicRightFacing' | 'perspectiveHeroicExtremeLeftFacing' | 'perspectiveHeroicExtremeRightFacing' | 'perspectiveRelaxed' | 'perspectiveRelaxedModerately';

export type STPresetLineDashVal = 'solid' | 'dot' | 'sysDot' | 'dash' | 'sysDash' | 'lgDash' | 'dashDot' | 'sysDashDot' | 'lgDashDot' | 'lgDashDotDot' | 'sysDashDotDot';

export type STPresetMaterialType = 'legacyMatte' | 'legacyPlastic' | 'legacyMetal' | 'legacyWireframe' | 'matte' | 'plastic' | 'metal' | 'warmMatte' | 'translucentPowder' | 'powder' | 'dkEdge' | 'softEdge' | 'clear' | 'flat' | 'softmetal' | 'none';

export type STRectAlignment = 'none' | 'tl' | 't' | 'tr' | 'l' | 'ctr' | 'r' | 'bl' | 'b' | 'br';

export type STSchemeColorVal = 'bg1' | 'tx1' | 'bg2' | 'tx2' | 'accent1' | 'accent2' | 'accent3' | 'accent4' | 'accent5' | 'accent6' | 'hlink' | 'folHlink' | 'dk1' | 'lt1' | 'dk2' | 'lt2' | 'phClr';

export type CheckboxElement = TypedNamedValue<CTSdtCheckbox>;

export type ConflictModeElement = TypedNamedValue<CTOnOff>;

export type ContentPartElement = TypedNamedValue<CTWordContentPart>;

export type CustomXmlConflictDelRangeEndElement = TypedNamedValue<Dep_org_docx4j_wml.CTMarkup>;

export type CustomXmlConflictDelRangeStartElement = TypedNamedValue<Dep_org_docx4j_wml.CTTrackChange>;

export type CustomXmlConflictInsRangeEndElement = TypedNamedValue<Dep_org_docx4j_wml.CTMarkup>;

export type CustomXmlConflictInsRangeStartElement = TypedNamedValue<Dep_org_docx4j_wml.CTTrackChange>;

export type DefaultImageDpiElement = TypedNamedValue<CTDefaultImageDpi>;

export type DiscardImageEditingDataElement = TypedNamedValue<CTOnOff>;

export type DocIdElement = TypedNamedValue<CTLongHexNumber>;

export type EntityPickerElement = TypedNamedValue<Dep_org_docx4j_wml.CTEmpty>;

export type ShadowElement = TypedNamedValue<CTShadow>;

/** Any global element of this mapping, i.e. what an unmarshaller returns. */
export type RootElement = CheckboxElement | ConflictModeElement | ContentPartElement | CustomXmlConflictDelRangeEndElement | CustomXmlConflictDelRangeStartElement | CustomXmlConflictInsRangeEndElement | CustomXmlConflictInsRangeStartElement | DefaultImageDpiElement | DiscardImageEditingDataElement | DocIdElement | EntityPickerElement | ShadowElement;

export namespace CTSRgbColor {
  export type AlphaElement = TypedNamedValue<CTPositiveFixedPercentage>;

  export type HueModElement = TypedNamedValue<CTPositivePercentage>;

  export type LumElement = TypedNamedValue<CTPercentage>;

  export type LumModElement = TypedNamedValue<CTPercentage>;

  export type LumOffElement = TypedNamedValue<CTPercentage>;

  export type SatElement = TypedNamedValue<CTPercentage>;

  export type SatModElement = TypedNamedValue<CTPercentage>;

  export type SatOffElement = TypedNamedValue<CTPercentage>;

  export type ShadeElement = TypedNamedValue<CTPositiveFixedPercentage>;

  export type TintElement = TypedNamedValue<CTPositiveFixedPercentage>;
}

export namespace CTSchemeColor {
  export type AlphaElement = TypedNamedValue<CTPositiveFixedPercentage>;

  export type HueModElement = TypedNamedValue<CTPositivePercentage>;

  export type LumElement = TypedNamedValue<CTPercentage>;

  export type LumModElement = TypedNamedValue<CTPercentage>;

  export type LumOffElement = TypedNamedValue<CTPercentage>;

  export type SatElement = TypedNamedValue<CTPercentage>;

  export type SatModElement = TypedNamedValue<CTPercentage>;

  export type SatOffElement = TypedNamedValue<CTPercentage>;

  export type ShadeElement = TypedNamedValue<CTPositiveFixedPercentage>;

  export type TintElement = TypedNamedValue<CTPositiveFixedPercentage>;
}

/** The Jsonix mapping [org_docx4j_w14] exported by the module's JavaScript file. */
export declare const org_docx4j_w14: JsonixMapping<RootElement>;
