// Generated by jsonix-schema-compiler: TypeScript declarations for the Jsonix module [org_docx4j_com_microsoft_schemas_office_word_x2010_wordprocessingGroup]. Do not edit.
// Describes the objects Jsonix produces when unmarshalling with this module's mappings.
import type * as Dep_org_docx4j_dml from './org_docx4j_dml';
import type * as Dep_org_docx4j_com_microsoft_schemas_office_word_x2010_wordprocessingShape from './org_docx4j_com_microsoft_schemas_office_word_x2010_wordprocessingShape';
import type * as Dep_org_docx4j_dml_picture from './org_docx4j_dml_picture';

/** Jsonix.XML.QName */
export interface XmlQName { namespaceURI: string; localPart: string; prefix?: string; key?: string; string?: string; }
/** Jsonix.XML.Calendar: the representation of date, time and dateTime values; unset fields are NaN. */
export interface XmlCalendar { year?: number; month?: number; day?: number; hour?: number; minute?: number; second?: number; fractionalSecond?: number; timezone?: number; }
/** The representation of xs:duration values. */
export interface XmlDuration { sign?: number; years?: number; months?: number; days?: number; hours?: number; minutes?: number; seconds?: number; }
/** An element as returned by an unmarshaller or held by an elementRef property. */
export interface TypedNamedValue<T> { name: XmlQName; value: T; }
/** A DOM node, allowed where the mapping permits DOM content (allowDom). */
export type XmlDomNode = any;
/** The value of an anyElement property: a typed element, a DOM node or (if mixed) text. */
export type XmlAnyElement = any;
/** The value of an anyAttribute property. */
export interface XmlAnyAttributes { [attributeName: string]: string; }
/** A Jsonix mapping object as consumed by new Jsonix.Context([...]); R is the union of its global element types. */
export interface JsonixMapping<R = unknown> { readonly __rootElement?: R; readonly [key: string]: unknown; }

export interface CTGraphicFrame {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_word_x2010_wordprocessingGroup.CTGraphicFrame';
  cNvPr: Dep_org_docx4j_dml.CTNonVisualDrawingProps;
  cNvFrPr: Dep_org_docx4j_dml.CTNonVisualGraphicFrameProperties;
  xfrm: Dep_org_docx4j_dml.CTTransform2D;
  graphic: Dep_org_docx4j_dml.Graphic;
  extLst?: Dep_org_docx4j_dml.CTOfficeArtExtensionList;
}

export interface CTWordprocessingGroup {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_word_x2010_wordprocessingGroup.CTWordprocessingGroup';
  cNvPr?: Dep_org_docx4j_dml.CTNonVisualDrawingProps;
  cNvGrpSpPr: Dep_org_docx4j_dml.CTNonVisualGroupDrawingShapeProps;
  grpSpPr: Dep_org_docx4j_dml.CTGroupShapeProperties;
  wspOrGrpSpOrGraphicFrame?: (Dep_org_docx4j_com_microsoft_schemas_office_word_x2010_wordprocessingShape.CTWordprocessingShape | CTWordprocessingGroup | CTGraphicFrame | Dep_org_docx4j_dml_picture.Pic)[];
  extLst?: Dep_org_docx4j_dml.CTOfficeArtExtensionList;
}

export type WgpElement = TypedNamedValue<CTWordprocessingGroup>;

/** Any global element of this mapping, i.e. what an unmarshaller returns. */
export type RootElement = WgpElement;

/** The Jsonix mapping [org_docx4j_com_microsoft_schemas_office_word_x2010_wordprocessingGroup] exported by the module's JavaScript file. */
export declare const org_docx4j_com_microsoft_schemas_office_word_x2010_wordprocessingGroup: JsonixMapping<RootElement>;
