// Generated by jsonix-schema-compiler: Jsonix mappings of the module [org_docx4j_docProps_coverPageProps] as an ES module. Do not edit.
export const org_docx4j_docProps_coverPageProps = {
  name: 'org_docx4j_docProps_coverPageProps',
  defaultElementNamespaceURI: 'http:\/\/schemas.microsoft.com\/office\/2006\/coverPageProps',
  typeInfos: [{
      localName: 'CoverPageProperties',
      typeName: null,
      propertyInfos: [{
          name: 'publishDate',
          required: true,
          elementName: 'PublishDate'
        }, {
          name: '_abstract',
          required: true,
          elementName: 'Abstract'
        }, {
          name: 'companyAddress',
          required: true,
          elementName: 'CompanyAddress'
        }, {
          name: 'companyPhone',
          required: true,
          elementName: 'CompanyPhone'
        }, {
          name: 'companyFax',
          required: true,
          elementName: 'CompanyFax'
        }, {
          name: 'companyEmail',
          required: true,
          elementName: 'CompanyEmail'
        }]
    }],
  elementInfos: [{
      typeInfo: '.CoverPageProperties',
      elementName: 'CoverPageProperties'
    }]
};
