// Generated by jsonix-schema-compiler: TypeScript declarations for the Jsonix module [org_docx4j_com_microsoft_schemas_office_drawing_x2017_model3d]. Do not edit.
// Describes the objects Jsonix produces when unmarshalling with this module's mappings.
import type * as Dep_org_docx4j_dml from './org_docx4j_dml';
import type * as Dep_org_docx4j_com_microsoft_schemas_office_drawing_x201611_main from './org_docx4j_com_microsoft_schemas_office_drawing_x201611_main';

/** Jsonix.XML.QName */
export interface XmlQName { namespaceURI: string; localPart: string; prefix?: string; key?: string; string?: string; }
/** Jsonix.XML.Calendar: the representation of date, time and dateTime values; unset fields are NaN. */
export interface XmlCalendar { year?: number; month?: number; day?: number; hour?: number; minute?: number; second?: number; fractionalSecond?: number; timezone?: number; }
/** The representation of xs:duration values. */
export interface XmlDuration { sign?: number; years?: number; months?: number; days?: number; hours?: number; minutes?: number; seconds?: number; }
/** An element as returned by an unmarshaller or held by an elementRef property. */
export interface TypedNamedValue<T> { name: XmlQName; value: T; }
/** A DOM node, allowed where the mapping permits DOM content (allowDom). */
export type XmlDomNode = any;
/** The value of an anyElement property: a typed element, a DOM node or (if mixed) text. */
export type XmlAnyElement = any;
/** The value of an anyAttribute property. */
export interface XmlAnyAttributes { [attributeName: string]: string; }
/** A Jsonix mapping object as consumed by new Jsonix.Context([...]); R is the union of its global element types. */
export interface JsonixMapping<R = unknown> { readonly __rootElement?: R; readonly [key: string]: unknown; }

export interface CTAmbientLight {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2017_model3d.CTAmbientLight';
  readonly PARENT?: CTModel3D;
  clr: Dep_org_docx4j_dml.CTColor;
  illuminance: CTPositiveRatio;
  extLst?: Dep_org_docx4j_dml.CTOfficeArtExtensionList;
  enabled?: boolean;
}

export interface CTDirectionalLight {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2017_model3d.CTDirectionalLight';
  readonly PARENT?: CTModel3D;
  clr: Dep_org_docx4j_dml.CTColor;
  illuminance: CTPositiveRatio;
  pos: Dep_org_docx4j_dml.CTPoint3D;
  lookAt: Dep_org_docx4j_dml.CTPoint3D;
  extLst?: Dep_org_docx4j_dml.CTOfficeArtExtensionList;
  enabled?: boolean;
  angularRad: number;
}

export interface CTModel3D {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2017_model3d.CTModel3D';
  spPr: Dep_org_docx4j_dml.CTShapeProperties;
  camera: CTModel3DCamera;
  trans: CTModel3DTransform;
  attrSrcUrl?: Dep_org_docx4j_com_microsoft_schemas_office_drawing_x201611_main.CTPictureAttributionSourceURL;
  raster?: CTModel3DRaster;
  extLst?: Dep_org_docx4j_dml.CTOfficeArtExtensionList;
  objViewport: CTObjectViewport;
  winViewport: CTWindowViewport;
  ambientLight?: CTAmbientLight;
  ptLightOrSpotLightOrDirLight?: (CTPointLight | CTSpotLight | CTDirectionalLight | CTUnknownLight)[];
  embed?: string;
  link?: string;
}

export interface CTModel3DCamera {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2017_model3d.CTModel3DCamera';
  readonly PARENT?: CTModel3D;
  pos: Dep_org_docx4j_dml.CTPoint3D;
  up: Dep_org_docx4j_dml.CTVector3D;
  lookAt: Dep_org_docx4j_dml.CTPoint3D;
  orthographic: CTOrthographicProjection;
  perspective: CTPerspectiveProjection;
  extLst?: Dep_org_docx4j_dml.CTOfficeArtExtensionList;
}

export interface CTModel3DRaster {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2017_model3d.CTModel3DRaster';
  readonly PARENT?: CTModel3D;
  blip?: Dep_org_docx4j_dml.CTBlip;
  rName: string;
  rVer: string;
}

export interface CTModel3DTransform {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2017_model3d.CTModel3DTransform';
  readonly PARENT?: CTModel3D;
  meterPerModelUnit?: CTPositiveRatio;
  preTrans?: Dep_org_docx4j_dml.CTVector3D;
  scale?: CTScale3D;
  rot?: CTRotate3D;
  postTrans?: Dep_org_docx4j_dml.CTVector3D;
  extLst?: Dep_org_docx4j_dml.CTOfficeArtExtensionList;
}

export interface CTObjectViewport {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2017_model3d.CTObjectViewport';
  readonly PARENT?: CTModel3D;
  extLst?: Dep_org_docx4j_dml.CTOfficeArtExtensionList;
  viewportSz: number;
}

export interface CTOrthographicProjection {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2017_model3d.CTOrthographicProjection';
  readonly PARENT?: CTModel3DCamera;
  sz: CTPositiveRatio;
  extLst?: Dep_org_docx4j_dml.CTOfficeArtExtensionList;
}

export interface CTPerspectiveProjection {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2017_model3d.CTPerspectiveProjection';
  readonly PARENT?: CTModel3DCamera;
  extLst?: Dep_org_docx4j_dml.CTOfficeArtExtensionList;
  fov: number;
}

export interface CTPointLight {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2017_model3d.CTPointLight';
  readonly PARENT?: CTModel3D;
  clr: Dep_org_docx4j_dml.CTColor;
  intensity: CTPositiveRatio;
  pos: Dep_org_docx4j_dml.CTPoint3D;
  extLst?: Dep_org_docx4j_dml.CTOfficeArtExtensionList;
  enabled?: boolean;
  rad: number;
}

export interface CTPositiveRatio {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2017_model3d.CTPositiveRatio';
  readonly PARENT?: CTAmbientLight | CTDirectionalLight | CTModel3DTransform | CTOrthographicProjection | CTPointLight | CTSpotLight;
  n: number;
  d: number;
}

export interface CTRotate3D {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2017_model3d.CTRotate3D';
  readonly PARENT?: CTModel3DTransform;
  ax?: number;
  ay?: number;
  az?: number;
}

export interface CTScale3D {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2017_model3d.CTScale3D';
  readonly PARENT?: CTModel3DTransform;
  sx: Dep_org_docx4j_dml.CTRatio;
  sy: Dep_org_docx4j_dml.CTRatio;
  sz: Dep_org_docx4j_dml.CTRatio;
}

export interface CTSpotLight {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2017_model3d.CTSpotLight';
  readonly PARENT?: CTModel3D;
  clr: Dep_org_docx4j_dml.CTColor;
  intensity: CTPositiveRatio;
  pos: Dep_org_docx4j_dml.CTPoint3D;
  lookAt: Dep_org_docx4j_dml.CTPoint3D;
  extLst?: Dep_org_docx4j_dml.CTOfficeArtExtensionList;
  enabled?: boolean;
  rad: number;
  spotAng: number;
}

export interface CTUnknownLight {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2017_model3d.CTUnknownLight';
  readonly PARENT?: CTModel3D;
}

export interface CTWindowViewport {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_drawing_x2017_model3d.CTWindowViewport';
  readonly PARENT?: CTModel3D;
  extLst?: Dep_org_docx4j_dml.CTOfficeArtExtensionList;
}

export type Model3DElement = TypedNamedValue<CTModel3D>;

/** Any global element of this mapping, i.e. what an unmarshaller returns. */
export type RootElement = Model3DElement;

/** The Jsonix mapping [org_docx4j_com_microsoft_schemas_office_drawing_x2017_model3d] exported by the module's JavaScript file. */
export declare const org_docx4j_com_microsoft_schemas_office_drawing_x2017_model3d: JsonixMapping<RootElement>;
