// Generated by jsonix-schema-compiler: Jsonix mappings of the module [org_docx4j_com_microsoft_schemas_office_drawing_x2010_picture] as an ES module. Do not edit.
export const org_docx4j_com_microsoft_schemas_office_drawing_x2010_picture = {
  name: 'org_docx4j_com_microsoft_schemas_office_drawing_x2010_picture',
  defaultElementNamespaceURI: 'http:\/\/schemas.microsoft.com\/office\/drawing\/2010\/picture',
  dependencies: ['org_docx4j_dml'],
  typeInfos: [],
  elementInfos: [{
      typeInfo: 'org_docx4j_dml.CTOfficeArtExtensionList',
      elementName: 'extLst'
    }, {
      typeInfo: 'org_docx4j_dml.CTShapeStyle',
      elementName: 'style'
    }]
};
