var org_docx4j_com_microsoft_schemas_office_drawing_x2012_chartStyle_Module_Factory = function () {
  var org_docx4j_com_microsoft_schemas_office_drawing_x2012_chartStyle = {
    name: 'org_docx4j_com_microsoft_schemas_office_drawing_x2012_chartStyle',
    defaultElementNamespaceURI: 'http:\/\/schemas.openxmlformats.org\/drawingml\/2006\/main',
    dependencies: ['org_docx4j_dml'],
    typeInfos: [{
        localName: 'CTChartStyle',
        typeName: {
          namespaceURI: 'http:\/\/schemas.microsoft.com\/office\/drawing\/2012\/chartStyle',
          localPart: 'CT_ChartStyle'
        },
        propertyInfos: [{
            name: 'axisTitle',
            required: true,
            elementName: {
              localPart: 'axisTitle',
              namespaceURI: 'http:\/\/schemas.microsoft.com\/office\/drawing\/2012\/chartStyle'
            },
            typeInfo: '.CTStyleEntry'
          }, {
            name: 'categoryAxis',
            required: true,
            elementName: {
              localPart: 'categoryAxis',
              namespaceURI: 'http:\/\/schemas.microsoft.com\/office\/drawing\/2012\/chartStyle'
            },
            typeInfo: '.CTStyleEntry'
          }, {
            name: 'chartArea',
            required: true,
            elementName: {
              localPart: 'chartArea',
              namespaceURI: 'http:\/\/schemas.microsoft.com\/office\/drawing\/2012\/chartStyle'
            },
            typeInfo: '.CTStyleEntry'
          }, {
            name: 'dataLabel',
            required: true,
            elementName: {
              localPart: 'dataLabel',
              namespaceURI: 'http:\/\/schemas.microsoft.com\/office\/drawing\/2012\/chartStyle'
            },
            typeInfo: '.CTStyleEntry'
          }, {
            name: 'dataLabelCallout',
            elementName: {
              localPart: 'dataLabelCallout',
              namespaceURI: 'http:\/\/schemas.microsoft.com\/office\/drawing\/2012\/chartStyle'
            },
            typeInfo: '.CTStyleEntry'
          }, {
            name: 'dataPoint',
            required: true,
            elementName: {
              localPart: 'dataPoint',
              namespaceURI: 'http:\/\/schemas.microsoft.com\/office\/drawing\/2012\/chartStyle'
            },
            typeInfo: '.CTStyleEntry'
          }, {
            name: 'dataPoint3D',
            required: true,
            elementName: {
              localPart: 'dataPoint3D',
              namespaceURI: 'http:\/\/schemas.microsoft.com\/office\/drawing\/2012\/chartStyle'
            },
            typeInfo: '.CTStyleEntry'
          }, {
            name: 'dataPointLine',
            required: true,
            elementName: {
              localPart: 'dataPointLine',
              namespaceURI: 'http:\/\/schemas.microsoft.com\/office\/drawing\/2012\/chartStyle'
            },
            typeInfo: '.CTStyleEntry'
          }, {
            name: 'dataPointMarker',
            required: true,
            elementName: {
              localPart: 'dataPointMarker',
              namespaceURI: 'http:\/\/schemas.microsoft.com\/office\/drawing\/2012\/chartStyle'
            },
            typeInfo: '.CTStyleEntry'
          }, {
            name: 'dataPointMarkerLayout',
            elementName: {
              localPart: 'dataPointMarkerLayout',
              namespaceURI: 'http:\/\/schemas.microsoft.com\/office\/drawing\/2012\/chartStyle'
            },
            typeInfo: '.CTMarkerLayout'
          }, {
            name: 'dataPointWireframe',
            required: true,
            elementName: {
              localPart: 'dataPointWireframe',
              namespaceURI: 'http:\/\/schemas.microsoft.com\/office\/drawing\/2012\/chartStyle'
            },
            typeInfo: '.CTStyleEntry'
          }, {
            name: 'dataTable',
            required: true,
            elementName: {
              localPart: 'dataTable',
              namespaceURI: 'http:\/\/schemas.microsoft.com\/office\/drawing\/2012\/chartStyle'
            },
            typeInfo: '.CTStyleEntry'
          }, {
            name: 'downBar',
            required: true,
            elementName: {
              localPart: 'downBar',
              namespaceURI: 'http:\/\/schemas.microsoft.com\/office\/drawing\/2012\/chartStyle'
            },
            typeInfo: '.CTStyleEntry'
          }, {
            name: 'dropLine',
            required: true,
            elementName: {
              localPart: 'dropLine',
              namespaceURI: 'http:\/\/schemas.microsoft.com\/office\/drawing\/2012\/chartStyle'
            },
            typeInfo: '.CTStyleEntry'
          }, {
            name: 'errorBar',
            required: true,
            elementName: {
              localPart: 'errorBar',
              namespaceURI: 'http:\/\/schemas.microsoft.com\/office\/drawing\/2012\/chartStyle'
            },
            typeInfo: '.CTStyleEntry'
          }, {
            name: 'floor',
            required: true,
            elementName: {
              localPart: 'floor',
              namespaceURI: 'http:\/\/schemas.microsoft.com\/office\/drawing\/2012\/chartStyle'
            },
            typeInfo: '.CTStyleEntry'
          }, {
            name: 'gridlineMajor',
            required: true,
            elementName: {
              localPart: 'gridlineMajor',
              namespaceURI: 'http:\/\/schemas.microsoft.com\/office\/drawing\/2012\/chartStyle'
            },
            typeInfo: '.CTStyleEntry'
          }, {
            name: 'gridlineMinor',
            required: true,
            elementName: {
              localPart: 'gridlineMinor',
              namespaceURI: 'http:\/\/schemas.microsoft.com\/office\/drawing\/2012\/chartStyle'
            },
            typeInfo: '.CTStyleEntry'
          }, {
            name: 'hiLoLine',
            required: true,
            elementName: {
              localPart: 'hiLoLine',
              namespaceURI: 'http:\/\/schemas.microsoft.com\/office\/drawing\/2012\/chartStyle'
            },
            typeInfo: '.CTStyleEntry'
          }, {
            name: 'leaderLine',
            required: true,
            elementName: {
              localPart: 'leaderLine',
              namespaceURI: 'http:\/\/schemas.microsoft.com\/office\/drawing\/2012\/chartStyle'
            },
            typeInfo: '.CTStyleEntry'
          }, {
            name: 'legend',
            required: true,
            elementName: {
              localPart: 'legend',
              namespaceURI: 'http:\/\/schemas.microsoft.com\/office\/drawing\/2012\/chartStyle'
            },
            typeInfo: '.CTStyleEntry'
          }, {
            name: 'plotArea',
            required: true,
            elementName: {
              localPart: 'plotArea',
              namespaceURI: 'http:\/\/schemas.microsoft.com\/office\/drawing\/2012\/chartStyle'
            },
            typeInfo: '.CTStyleEntry'
          }, {
            name: 'plotArea3D',
            required: true,
            elementName: {
              localPart: 'plotArea3D',
              namespaceURI: 'http:\/\/schemas.microsoft.com\/office\/drawing\/2012\/chartStyle'
            },
            typeInfo: '.CTStyleEntry'
          }, {
            name: 'seriesAxis',
            required: true,
            elementName: {
              localPart: 'seriesAxis',
              namespaceURI: 'http:\/\/schemas.microsoft.com\/office\/drawing\/2012\/chartStyle'
            },
            typeInfo: '.CTStyleEntry'
          }, {
            name: 'seriesLine',
            required: true,
            elementName: {
              localPart: 'seriesLine',
              namespaceURI: 'http:\/\/schemas.microsoft.com\/office\/drawing\/2012\/chartStyle'
            },
            typeInfo: '.CTStyleEntry'
          }, {
            name: 'title',
            required: true,
            elementName: {
              localPart: 'title',
              namespaceURI: 'http:\/\/schemas.microsoft.com\/office\/drawing\/2012\/chartStyle'
            },
            typeInfo: '.CTStyleEntry'
          }, {
            name: 'trendline',
            required: true,
            elementName: {
              localPart: 'trendline',
              namespaceURI: 'http:\/\/schemas.microsoft.com\/office\/drawing\/2012\/chartStyle'
            },
            typeInfo: '.CTStyleEntry'
          }, {
            name: 'trendlineLabel',
            required: true,
            elementName: {
              localPart: 'trendlineLabel',
              namespaceURI: 'http:\/\/schemas.microsoft.com\/office\/drawing\/2012\/chartStyle'
            },
            typeInfo: '.CTStyleEntry'
          }, {
            name: 'upBar',
            required: true,
            elementName: {
              localPart: 'upBar',
              namespaceURI: 'http:\/\/schemas.microsoft.com\/office\/drawing\/2012\/chartStyle'
            },
            typeInfo: '.CTStyleEntry'
          }, {
            name: 'valueAxis',
            required: true,
            elementName: {
              localPart: 'valueAxis',
              namespaceURI: 'http:\/\/schemas.microsoft.com\/office\/drawing\/2012\/chartStyle'
            },
            typeInfo: '.CTStyleEntry'
          }, {
            name: 'wall',
            required: true,
            elementName: {
              localPart: 'wall',
              namespaceURI: 'http:\/\/schemas.microsoft.com\/office\/drawing\/2012\/chartStyle'
            },
            typeInfo: '.CTStyleEntry'
          }, {
            name: 'extLst',
            elementName: {
              localPart: 'extLst',
              namespaceURI: 'http:\/\/schemas.microsoft.com\/office\/drawing\/2012\/chartStyle'
            },
            typeInfo: 'org_docx4j_dml.CTOfficeArtExtensionList'
          }, {
            name: 'id',
            typeInfo: 'UnsignedInt',
            attributeName: {
              localPart: 'id'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'CTColorStyle',
        typeName: {
          namespaceURI: 'http:\/\/schemas.microsoft.com\/office\/drawing\/2012\/chartStyle',
          localPart: 'CT_ColorStyle'
        },
        propertyInfos: [{
            name: 'egColorChoice',
            required: true,
            collection: true,
            elementTypeInfos: [{
                elementName: 'scrgbClr',
                typeInfo: 'org_docx4j_dml.CTScRgbColor'
              }, {
                elementName: 'srgbClr',
                typeInfo: 'org_docx4j_dml.CTSRgbColor'
              }, {
                elementName: 'hslClr',
                typeInfo: 'org_docx4j_dml.CTHslColor'
              }, {
                elementName: 'sysClr',
                typeInfo: 'org_docx4j_dml.CTSystemColor'
              }, {
                elementName: 'schemeClr',
                typeInfo: 'org_docx4j_dml.CTSchemeColor'
              }, {
                elementName: 'prstClr',
                typeInfo: 'org_docx4j_dml.CTPresetColor'
              }],
            type: 'elements'
          }, {
            name: 'variation',
            minOccurs: 0,
            collection: true,
            elementName: {
              localPart: 'variation',
              namespaceURI: 'http:\/\/schemas.microsoft.com\/office\/drawing\/2012\/chartStyle'
            },
            typeInfo: '.CTColorStyleVariation'
          }, {
            name: 'extLst',
            elementName: {
              localPart: 'extLst',
              namespaceURI: 'http:\/\/schemas.microsoft.com\/office\/drawing\/2012\/chartStyle'
            },
            typeInfo: 'org_docx4j_dml.CTOfficeArtExtensionList'
          }, {
            name: 'meth',
            required: true,
            attributeName: {
              localPart: 'meth'
            },
            type: 'attribute'
          }, {
            name: 'id',
            typeInfo: 'UnsignedInt',
            attributeName: {
              localPart: 'id'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'CTColorStyleVariation',
        typeName: {
          namespaceURI: 'http:\/\/schemas.microsoft.com\/office\/drawing\/2012\/chartStyle',
          localPart: 'CT_ColorStyleVariation'
        },
        propertyInfos: [{
            name: 'egColorTransform',
            minOccurs: 0,
            collection: true,
            mixed: false,
            allowDom: false,
            elementTypeInfos: [{
                elementName: 'tint',
                typeInfo: 'org_docx4j_dml.CTPositiveFixedPercentage'
              }, {
                elementName: 'shade',
                typeInfo: 'org_docx4j_dml.CTPositiveFixedPercentage'
              }, {
                elementName: 'comp',
                typeInfo: 'org_docx4j_dml.CTComplementTransform'
              }, {
                elementName: 'inv',
                typeInfo: 'org_docx4j_dml.CTInverseTransform'
              }, {
                elementName: 'gray',
                typeInfo: 'org_docx4j_dml.CTGrayscaleTransform'
              }, {
                elementName: 'alpha',
                typeInfo: 'org_docx4j_dml.CTPositiveFixedPercentage'
              }, {
                elementName: 'alphaOff',
                typeInfo: 'org_docx4j_dml.CTFixedPercentage'
              }, {
                elementName: 'alphaMod',
                typeInfo: 'org_docx4j_dml.CTPositivePercentage'
              }, {
                elementName: 'hue',
                typeInfo: 'org_docx4j_dml.CTPositiveFixedAngle'
              }, {
                elementName: 'hueOff',
                typeInfo: 'org_docx4j_dml.CTAngle'
              }, {
                elementName: 'hueMod',
                typeInfo: 'org_docx4j_dml.CTPositivePercentage'
              }, {
                elementName: 'sat',
                typeInfo: 'org_docx4j_dml.CTPercentage'
              }, {
                elementName: 'satOff',
                typeInfo: 'org_docx4j_dml.CTPercentage'
              }, {
                elementName: 'satMod',
                typeInfo: 'org_docx4j_dml.CTPercentage'
              }, {
                elementName: 'lum',
                typeInfo: 'org_docx4j_dml.CTPercentage'
              }, {
                elementName: 'lumOff',
                typeInfo: 'org_docx4j_dml.CTPercentage'
              }, {
                elementName: 'lumMod',
                typeInfo: 'org_docx4j_dml.CTPercentage'
              }, {
                elementName: 'red',
                typeInfo: 'org_docx4j_dml.CTPercentage'
              }, {
                elementName: 'redOff',
                typeInfo: 'org_docx4j_dml.CTPercentage'
              }, {
                elementName: 'redMod',
                typeInfo: 'org_docx4j_dml.CTPercentage'
              }, {
                elementName: 'green',
                typeInfo: 'org_docx4j_dml.CTPercentage'
              }, {
                elementName: 'greenOff',
                typeInfo: 'org_docx4j_dml.CTPercentage'
              }, {
                elementName: 'greenMod',
                typeInfo: 'org_docx4j_dml.CTPercentage'
              }, {
                elementName: 'blue',
                typeInfo: 'org_docx4j_dml.CTPercentage'
              }, {
                elementName: 'blueOff',
                typeInfo: 'org_docx4j_dml.CTPercentage'
              }, {
                elementName: 'blueMod',
                typeInfo: 'org_docx4j_dml.CTPercentage'
              }, {
                elementName: 'gamma',
                typeInfo: 'org_docx4j_dml.CTGammaTransform'
              }, {
                elementName: 'invGamma',
                typeInfo: 'org_docx4j_dml.CTInverseGammaTransform'
              }],
            type: 'elementRefs'
          }]
      }, {
        localName: 'CTFontReference',
        typeName: {
          namespaceURI: 'http:\/\/schemas.microsoft.com\/office\/drawing\/2012\/chartStyle',
          localPart: 'CT_FontReference'
        },
        propertyInfos: [{
            name: 'scrgbClr',
            required: true,
            typeInfo: 'org_docx4j_dml.CTScRgbColor'
          }, {
            name: 'srgbClr',
            required: true,
            typeInfo: 'org_docx4j_dml.CTSRgbColor'
          }, {
            name: 'hslClr',
            required: true,
            typeInfo: 'org_docx4j_dml.CTHslColor'
          }, {
            name: 'sysClr',
            required: true,
            typeInfo: 'org_docx4j_dml.CTSystemColor'
          }, {
            name: 'schemeClr',
            required: true,
            typeInfo: 'org_docx4j_dml.CTSchemeColor'
          }, {
            name: 'prstClr',
            required: true,
            typeInfo: 'org_docx4j_dml.CTPresetColor'
          }, {
            name: 'styleClr',
            elementName: {
              localPart: 'styleClr',
              namespaceURI: 'http:\/\/schemas.microsoft.com\/office\/drawing\/2012\/chartStyle'
            },
            typeInfo: '.CTStyleColor'
          }, {
            name: 'idx',
            required: true,
            typeInfo: 'org_docx4j_dml.STFontCollectionIndex',
            attributeName: {
              localPart: 'idx'
            },
            type: 'attribute'
          }, {
            name: 'mods',
            typeInfo: {
              type: 'list'
            },
            attributeName: {
              localPart: 'mods'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'CTMarkerLayout',
        typeName: {
          namespaceURI: 'http:\/\/schemas.microsoft.com\/office\/drawing\/2012\/chartStyle',
          localPart: 'CT_MarkerLayout'
        },
        propertyInfos: [{
            name: 'symbol',
            typeInfo: '.STMarkerStyle',
            attributeName: {
              localPart: 'symbol'
            },
            type: 'attribute'
          }, {
            name: 'size',
            typeInfo: 'UnsignedByte',
            attributeName: {
              localPart: 'size'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'CTStyleColor',
        typeName: {
          namespaceURI: 'http:\/\/schemas.microsoft.com\/office\/drawing\/2012\/chartStyle',
          localPart: 'CT_StyleColor'
        },
        propertyInfos: [{
            name: 'egColorTransform',
            minOccurs: 0,
            collection: true,
            mixed: false,
            allowDom: false,
            elementTypeInfos: [{
                elementName: 'tint',
                typeInfo: 'org_docx4j_dml.CTPositiveFixedPercentage'
              }, {
                elementName: 'shade',
                typeInfo: 'org_docx4j_dml.CTPositiveFixedPercentage'
              }, {
                elementName: 'comp',
                typeInfo: 'org_docx4j_dml.CTComplementTransform'
              }, {
                elementName: 'inv',
                typeInfo: 'org_docx4j_dml.CTInverseTransform'
              }, {
                elementName: 'gray',
                typeInfo: 'org_docx4j_dml.CTGrayscaleTransform'
              }, {
                elementName: 'alpha',
                typeInfo: 'org_docx4j_dml.CTPositiveFixedPercentage'
              }, {
                elementName: 'alphaOff',
                typeInfo: 'org_docx4j_dml.CTFixedPercentage'
              }, {
                elementName: 'alphaMod',
                typeInfo: 'org_docx4j_dml.CTPositivePercentage'
              }, {
                elementName: 'hue',
                typeInfo: 'org_docx4j_dml.CTPositiveFixedAngle'
              }, {
                elementName: 'hueOff',
                typeInfo: 'org_docx4j_dml.CTAngle'
              }, {
                elementName: 'hueMod',
                typeInfo: 'org_docx4j_dml.CTPositivePercentage'
              }, {
                elementName: 'sat',
                typeInfo: 'org_docx4j_dml.CTPercentage'
              }, {
                elementName: 'satOff',
                typeInfo: 'org_docx4j_dml.CTPercentage'
              }, {
                elementName: 'satMod',
                typeInfo: 'org_docx4j_dml.CTPercentage'
              }, {
                elementName: 'lum',
                typeInfo: 'org_docx4j_dml.CTPercentage'
              }, {
                elementName: 'lumOff',
                typeInfo: 'org_docx4j_dml.CTPercentage'
              }, {
                elementName: 'lumMod',
                typeInfo: 'org_docx4j_dml.CTPercentage'
              }, {
                elementName: 'red',
                typeInfo: 'org_docx4j_dml.CTPercentage'
              }, {
                elementName: 'redOff',
                typeInfo: 'org_docx4j_dml.CTPercentage'
              }, {
                elementName: 'redMod',
                typeInfo: 'org_docx4j_dml.CTPercentage'
              }, {
                elementName: 'green',
                typeInfo: 'org_docx4j_dml.CTPercentage'
              }, {
                elementName: 'greenOff',
                typeInfo: 'org_docx4j_dml.CTPercentage'
              }, {
                elementName: 'greenMod',
                typeInfo: 'org_docx4j_dml.CTPercentage'
              }, {
                elementName: 'blue',
                typeInfo: 'org_docx4j_dml.CTPercentage'
              }, {
                elementName: 'blueOff',
                typeInfo: 'org_docx4j_dml.CTPercentage'
              }, {
                elementName: 'blueMod',
                typeInfo: 'org_docx4j_dml.CTPercentage'
              }, {
                elementName: 'gamma',
                typeInfo: 'org_docx4j_dml.CTGammaTransform'
              }, {
                elementName: 'invGamma',
                typeInfo: 'org_docx4j_dml.CTInverseGammaTransform'
              }],
            type: 'elementRefs'
          }, {
            name: 'val',
            attributeName: {
              localPart: 'val'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'CTStyleEntry',
        typeName: {
          namespaceURI: 'http:\/\/schemas.microsoft.com\/office\/drawing\/2012\/chartStyle',
          localPart: 'CT_StyleEntry'
        },
        propertyInfos: [{
            name: 'lnRef',
            required: true,
            elementName: {
              localPart: 'lnRef',
              namespaceURI: 'http:\/\/schemas.microsoft.com\/office\/drawing\/2012\/chartStyle'
            },
            typeInfo: '.CTStyleReference'
          }, {
            name: 'lineWidthScale',
            elementName: {
              localPart: 'lineWidthScale',
              namespaceURI: 'http:\/\/schemas.microsoft.com\/office\/drawing\/2012\/chartStyle'
            },
            typeInfo: 'Double',
            defaultValue: 1.0
          }, {
            name: 'fillRef',
            required: true,
            elementName: {
              localPart: 'fillRef',
              namespaceURI: 'http:\/\/schemas.microsoft.com\/office\/drawing\/2012\/chartStyle'
            },
            typeInfo: '.CTStyleReference'
          }, {
            name: 'effectRef',
            required: true,
            elementName: {
              localPart: 'effectRef',
              namespaceURI: 'http:\/\/schemas.microsoft.com\/office\/drawing\/2012\/chartStyle'
            },
            typeInfo: '.CTStyleReference'
          }, {
            name: 'fontRef',
            required: true,
            elementName: {
              localPart: 'fontRef',
              namespaceURI: 'http:\/\/schemas.microsoft.com\/office\/drawing\/2012\/chartStyle'
            },
            typeInfo: '.CTFontReference'
          }, {
            name: 'spPr',
            elementName: {
              localPart: 'spPr',
              namespaceURI: 'http:\/\/schemas.microsoft.com\/office\/drawing\/2012\/chartStyle'
            },
            typeInfo: 'org_docx4j_dml.CTShapeProperties'
          }, {
            name: 'defRPr',
            elementName: {
              localPart: 'defRPr',
              namespaceURI: 'http:\/\/schemas.microsoft.com\/office\/drawing\/2012\/chartStyle'
            },
            typeInfo: 'org_docx4j_dml.CTTextCharacterProperties'
          }, {
            name: 'bodyPr',
            elementName: {
              localPart: 'bodyPr',
              namespaceURI: 'http:\/\/schemas.microsoft.com\/office\/drawing\/2012\/chartStyle'
            },
            typeInfo: 'org_docx4j_dml.CTTextBodyProperties'
          }, {
            name: 'extLst',
            elementName: {
              localPart: 'extLst',
              namespaceURI: 'http:\/\/schemas.microsoft.com\/office\/drawing\/2012\/chartStyle'
            },
            typeInfo: 'org_docx4j_dml.CTOfficeArtExtensionList'
          }, {
            name: 'mods',
            typeInfo: {
              type: 'list'
            },
            attributeName: {
              localPart: 'mods'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'CTStyleReference',
        typeName: {
          namespaceURI: 'http:\/\/schemas.microsoft.com\/office\/drawing\/2012\/chartStyle',
          localPart: 'CT_StyleReference'
        },
        propertyInfos: [{
            name: 'scrgbClr',
            required: true,
            typeInfo: 'org_docx4j_dml.CTScRgbColor'
          }, {
            name: 'srgbClr',
            required: true,
            typeInfo: 'org_docx4j_dml.CTSRgbColor'
          }, {
            name: 'hslClr',
            required: true,
            typeInfo: 'org_docx4j_dml.CTHslColor'
          }, {
            name: 'sysClr',
            required: true,
            typeInfo: 'org_docx4j_dml.CTSystemColor'
          }, {
            name: 'schemeClr',
            required: true,
            typeInfo: 'org_docx4j_dml.CTSchemeColor'
          }, {
            name: 'prstClr',
            required: true,
            typeInfo: 'org_docx4j_dml.CTPresetColor'
          }, {
            name: 'styleClr',
            elementName: {
              localPart: 'styleClr',
              namespaceURI: 'http:\/\/schemas.microsoft.com\/office\/drawing\/2012\/chartStyle'
            },
            typeInfo: '.CTStyleColor'
          }, {
            name: 'idx',
            required: true,
            typeInfo: 'UnsignedInt',
            attributeName: {
              localPart: 'idx'
            },
            type: 'attribute'
          }, {
            name: 'mods',
            typeInfo: {
              type: 'list'
            },
            attributeName: {
              localPart: 'mods'
            },
            type: 'attribute'
          }]
      }, {
        type: 'enumInfo',
        localName: 'STColorStyleMethodEnum',
        baseTypeInfo: 'Token',
        values: ['cycle', 'withinLinear', 'acrossLinear', 'withinLinearReversed', 'acrossLinearReversed']
      }, {
        type: 'enumInfo',
        localName: 'STMarkerStyle',
        baseTypeInfo: 'Token',
        values: ['circle', 'dash', 'diamond', 'dot', 'plus', 'square', 'star', 'triangle', 'x']
      }, {
        type: 'enumInfo',
        localName: 'STStyleColorEnum',
        baseTypeInfo: 'Token',
        values: ['auto']
      }, {
        type: 'enumInfo',
        localName: 'STStyleEntryModifierEnum',
        baseTypeInfo: 'Token',
        values: ['allowNoFillOverride', 'allowNoLineOverride']
      }, {
        type: 'enumInfo',
        localName: 'STStyleReferenceModifierEnum',
        baseTypeInfo: 'Token',
        values: ['ignoreCSTransforms']
      }],
    elementInfos: [{
        typeInfo: '.CTChartStyle',
        elementName: {
          localPart: 'chartStyle',
          namespaceURI: 'http:\/\/schemas.microsoft.com\/office\/drawing\/2012\/chartStyle'
        }
      }, {
        typeInfo: '.CTColorStyle',
        elementName: {
          localPart: 'colorStyle',
          namespaceURI: 'http:\/\/schemas.microsoft.com\/office\/drawing\/2012\/chartStyle'
        }
      }, {
        typeInfo: 'org_docx4j_dml.CTPositiveFixedPercentage',
        elementName: 'alpha',
        scope: '.CTColorStyleVariation'
      }, {
        typeInfo: 'org_docx4j_dml.CTPositiveFixedPercentage',
        elementName: 'alpha',
        scope: '.CTStyleColor'
      }, {
        typeInfo: 'org_docx4j_dml.CTPositivePercentage',
        elementName: 'alphaMod',
        scope: '.CTColorStyleVariation'
      }, {
        typeInfo: 'org_docx4j_dml.CTPositivePercentage',
        elementName: 'alphaMod',
        scope: '.CTStyleColor'
      }, {
        typeInfo: 'org_docx4j_dml.CTFixedPercentage',
        elementName: 'alphaOff',
        scope: '.CTColorStyleVariation'
      }, {
        typeInfo: 'org_docx4j_dml.CTFixedPercentage',
        elementName: 'alphaOff',
        scope: '.CTStyleColor'
      }, {
        typeInfo: 'org_docx4j_dml.CTPercentage',
        elementName: 'blue',
        scope: '.CTColorStyleVariation'
      }, {
        typeInfo: 'org_docx4j_dml.CTPercentage',
        elementName: 'blue',
        scope: '.CTStyleColor'
      }, {
        typeInfo: 'org_docx4j_dml.CTPercentage',
        elementName: 'blueMod',
        scope: '.CTColorStyleVariation'
      }, {
        typeInfo: 'org_docx4j_dml.CTPercentage',
        elementName: 'blueMod',
        scope: '.CTStyleColor'
      }, {
        typeInfo: 'org_docx4j_dml.CTPercentage',
        elementName: 'blueOff',
        scope: '.CTColorStyleVariation'
      }, {
        typeInfo: 'org_docx4j_dml.CTPercentage',
        elementName: 'blueOff',
        scope: '.CTStyleColor'
      }, {
        typeInfo: 'org_docx4j_dml.CTComplementTransform',
        elementName: 'comp',
        scope: '.CTColorStyleVariation'
      }, {
        typeInfo: 'org_docx4j_dml.CTComplementTransform',
        elementName: 'comp',
        scope: '.CTStyleColor'
      }, {
        typeInfo: 'org_docx4j_dml.CTGammaTransform',
        elementName: 'gamma',
        scope: '.CTColorStyleVariation'
      }, {
        typeInfo: 'org_docx4j_dml.CTGammaTransform',
        elementName: 'gamma',
        scope: '.CTStyleColor'
      }, {
        typeInfo: 'org_docx4j_dml.CTGrayscaleTransform',
        elementName: 'gray',
        scope: '.CTColorStyleVariation'
      }, {
        typeInfo: 'org_docx4j_dml.CTGrayscaleTransform',
        elementName: 'gray',
        scope: '.CTStyleColor'
      }, {
        typeInfo: 'org_docx4j_dml.CTPercentage',
        elementName: 'green',
        scope: '.CTColorStyleVariation'
      }, {
        typeInfo: 'org_docx4j_dml.CTPercentage',
        elementName: 'green',
        scope: '.CTStyleColor'
      }, {
        typeInfo: 'org_docx4j_dml.CTPercentage',
        elementName: 'greenMod',
        scope: '.CTColorStyleVariation'
      }, {
        typeInfo: 'org_docx4j_dml.CTPercentage',
        elementName: 'greenMod',
        scope: '.CTStyleColor'
      }, {
        typeInfo: 'org_docx4j_dml.CTPercentage',
        elementName: 'greenOff',
        scope: '.CTColorStyleVariation'
      }, {
        typeInfo: 'org_docx4j_dml.CTPercentage',
        elementName: 'greenOff',
        scope: '.CTStyleColor'
      }, {
        typeInfo: 'org_docx4j_dml.CTPositiveFixedAngle',
        elementName: 'hue',
        scope: '.CTColorStyleVariation'
      }, {
        typeInfo: 'org_docx4j_dml.CTPositiveFixedAngle',
        elementName: 'hue',
        scope: '.CTStyleColor'
      }, {
        typeInfo: 'org_docx4j_dml.CTPositivePercentage',
        elementName: 'hueMod',
        scope: '.CTColorStyleVariation'
      }, {
        typeInfo: 'org_docx4j_dml.CTPositivePercentage',
        elementName: 'hueMod',
        scope: '.CTStyleColor'
      }, {
        typeInfo: 'org_docx4j_dml.CTAngle',
        elementName: 'hueOff',
        scope: '.CTColorStyleVariation'
      }, {
        typeInfo: 'org_docx4j_dml.CTAngle',
        elementName: 'hueOff',
        scope: '.CTStyleColor'
      }, {
        typeInfo: 'org_docx4j_dml.CTInverseTransform',
        elementName: 'inv',
        scope: '.CTColorStyleVariation'
      }, {
        typeInfo: 'org_docx4j_dml.CTInverseTransform',
        elementName: 'inv',
        scope: '.CTStyleColor'
      }, {
        typeInfo: 'org_docx4j_dml.CTInverseGammaTransform',
        elementName: 'invGamma',
        scope: '.CTColorStyleVariation'
      }, {
        typeInfo: 'org_docx4j_dml.CTInverseGammaTransform',
        elementName: 'invGamma',
        scope: '.CTStyleColor'
      }, {
        typeInfo: 'org_docx4j_dml.CTPercentage',
        elementName: 'lum',
        scope: '.CTColorStyleVariation'
      }, {
        typeInfo: 'org_docx4j_dml.CTPercentage',
        elementName: 'lum',
        scope: '.CTStyleColor'
      }, {
        typeInfo: 'org_docx4j_dml.CTPercentage',
        elementName: 'lumMod',
        scope: '.CTColorStyleVariation'
      }, {
        typeInfo: 'org_docx4j_dml.CTPercentage',
        elementName: 'lumMod',
        scope: '.CTStyleColor'
      }, {
        typeInfo: 'org_docx4j_dml.CTPercentage',
        elementName: 'lumOff',
        scope: '.CTColorStyleVariation'
      }, {
        typeInfo: 'org_docx4j_dml.CTPercentage',
        elementName: 'lumOff',
        scope: '.CTStyleColor'
      }, {
        typeInfo: 'org_docx4j_dml.CTPercentage',
        elementName: 'red',
        scope: '.CTColorStyleVariation'
      }, {
        typeInfo: 'org_docx4j_dml.CTPercentage',
        elementName: 'red',
        scope: '.CTStyleColor'
      }, {
        typeInfo: 'org_docx4j_dml.CTPercentage',
        elementName: 'redMod',
        scope: '.CTColorStyleVariation'
      }, {
        typeInfo: 'org_docx4j_dml.CTPercentage',
        elementName: 'redMod',
        scope: '.CTStyleColor'
      }, {
        typeInfo: 'org_docx4j_dml.CTPercentage',
        elementName: 'redOff',
        scope: '.CTColorStyleVariation'
      }, {
        typeInfo: 'org_docx4j_dml.CTPercentage',
        elementName: 'redOff',
        scope: '.CTStyleColor'
      }, {
        typeInfo: 'org_docx4j_dml.CTPercentage',
        elementName: 'sat',
        scope: '.CTColorStyleVariation'
      }, {
        typeInfo: 'org_docx4j_dml.CTPercentage',
        elementName: 'sat',
        scope: '.CTStyleColor'
      }, {
        typeInfo: 'org_docx4j_dml.CTPercentage',
        elementName: 'satMod',
        scope: '.CTColorStyleVariation'
      }, {
        typeInfo: 'org_docx4j_dml.CTPercentage',
        elementName: 'satMod',
        scope: '.CTStyleColor'
      }, {
        typeInfo: 'org_docx4j_dml.CTPercentage',
        elementName: 'satOff',
        scope: '.CTColorStyleVariation'
      }, {
        typeInfo: 'org_docx4j_dml.CTPercentage',
        elementName: 'satOff',
        scope: '.CTStyleColor'
      }, {
        typeInfo: 'org_docx4j_dml.CTPositiveFixedPercentage',
        elementName: 'shade',
        scope: '.CTColorStyleVariation'
      }, {
        typeInfo: 'org_docx4j_dml.CTPositiveFixedPercentage',
        elementName: 'shade',
        scope: '.CTStyleColor'
      }, {
        typeInfo: 'org_docx4j_dml.CTPositiveFixedPercentage',
        elementName: 'tint',
        scope: '.CTColorStyleVariation'
      }, {
        typeInfo: 'org_docx4j_dml.CTPositiveFixedPercentage',
        elementName: 'tint',
        scope: '.CTStyleColor'
      }]
  };
  return {
    org_docx4j_com_microsoft_schemas_office_drawing_x2012_chartStyle: org_docx4j_com_microsoft_schemas_office_drawing_x2012_chartStyle
  };
};
if (typeof define === 'function' && define.amd) {
  define([], org_docx4j_com_microsoft_schemas_office_drawing_x2012_chartStyle_Module_Factory);
}
else {
  var org_docx4j_com_microsoft_schemas_office_drawing_x2012_chartStyle_Module = org_docx4j_com_microsoft_schemas_office_drawing_x2012_chartStyle_Module_Factory();
  if (typeof module !== 'undefined' && module.exports) {
    module.exports.org_docx4j_com_microsoft_schemas_office_drawing_x2012_chartStyle = org_docx4j_com_microsoft_schemas_office_drawing_x2012_chartStyle_Module.org_docx4j_com_microsoft_schemas_office_drawing_x2012_chartStyle;
  }
  else {
    var org_docx4j_com_microsoft_schemas_office_drawing_x2012_chartStyle = org_docx4j_com_microsoft_schemas_office_drawing_x2012_chartStyle_Module.org_docx4j_com_microsoft_schemas_office_drawing_x2012_chartStyle;
  }
}