// Generated by jsonix-schema-compiler: Jsonix mappings of the module [org_docx4j_com_microsoft_schemas_office_drawing_x2017_decorative] as an ES module. Do not edit.
export const org_docx4j_com_microsoft_schemas_office_drawing_x2017_decorative = {
  name: 'org_docx4j_com_microsoft_schemas_office_drawing_x2017_decorative',
  defaultElementNamespaceURI: 'http:\/\/schemas.microsoft.com\/office\/drawing\/2017\/decorative',
  typeInfos: [{
      localName: 'CTDecorative',
      typeName: 'CT_Decorative',
      propertyInfos: [{
          name: 'val',
          typeInfo: 'Boolean',
          attributeName: {
            localPart: 'val'
          },
          type: 'attribute'
        }]
    }],
  elementInfos: [{
      typeInfo: '.CTDecorative',
      elementName: 'decorative'
    }]
};
