// Generated by jsonix-schema-compiler: TypeScript declarations for the Jsonix module [org_docx4j_com_microsoft_schemas_office_word_x2010_wordprocessingShape]. Do not edit.
// Describes the objects Jsonix produces when unmarshalling with this module's mappings.
import type * as Dep_org_docx4j_dml from './org_docx4j_dml';
import type * as Dep_org_docx4j_wml from './org_docx4j_wml';

/** Jsonix.XML.QName */
export interface XmlQName { namespaceURI: string; localPart: string; prefix?: string; key?: string; string?: string; }
/** Jsonix.XML.Calendar: the representation of date, time and dateTime values; unset fields are NaN. */
export interface XmlCalendar { year?: number; month?: number; day?: number; hour?: number; minute?: number; second?: number; fractionalSecond?: number; timezone?: number; }
/** The representation of xs:duration values. */
export interface XmlDuration { sign?: number; years?: number; months?: number; days?: number; hours?: number; minutes?: number; seconds?: number; }
/** An element as returned by an unmarshaller or held by an elementRef property. */
export interface TypedNamedValue<T> { name: XmlQName; value: T; }
/** A DOM node, allowed where the mapping permits DOM content (allowDom). */
export type XmlDomNode = any;
/** The value of an anyElement property: a typed element, a DOM node or (if mixed) text. */
export type XmlAnyElement = any;
/** The value of an anyAttribute property. */
export interface XmlAnyAttributes { [attributeName: string]: string; }
/** A Jsonix mapping object as consumed by new Jsonix.Context([...]); R is the union of its global element types. */
export interface JsonixMapping<R = unknown> { readonly __rootElement?: R; readonly [key: string]: unknown; }

export interface CTLinkedTextboxInformation {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_word_x2010_wordprocessingShape.CTLinkedTextboxInformation';
  extLst?: Dep_org_docx4j_dml.CTOfficeArtExtensionList;
  id: number;
  seq: number;
}

export interface CTTextboxInfo {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_word_x2010_wordprocessingShape.CTTextboxInfo';
  txbxContent?: Dep_org_docx4j_wml.CTTxbxContent;
  extLst?: Dep_org_docx4j_dml.CTOfficeArtExtensionList;
  id?: number;
}

export interface CTWordprocessingShape {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_word_x2010_wordprocessingShape.CTWordprocessingShape';
  cNvPr?: Dep_org_docx4j_dml.CTNonVisualDrawingProps;
  cNvSpPr: Dep_org_docx4j_dml.CTNonVisualDrawingShapeProps;
  cNvCnPr: Dep_org_docx4j_dml.CTNonVisualConnectorProperties;
  spPr: Dep_org_docx4j_dml.CTShapeProperties;
  style?: Dep_org_docx4j_dml.CTShapeStyle;
  extLst?: Dep_org_docx4j_dml.CTOfficeArtExtensionList;
  txbx: CTTextboxInfo;
  linkedTxbx: CTLinkedTextboxInformation;
  bodyPr: Dep_org_docx4j_dml.CTTextBodyProperties;
  normalEastAsianFlow?: boolean;
}

export type WspElement = TypedNamedValue<CTWordprocessingShape>;

/** Any global element of this mapping, i.e. what an unmarshaller returns. */
export type RootElement = WspElement;

/** The Jsonix mapping [org_docx4j_com_microsoft_schemas_office_word_x2010_wordprocessingShape] exported by the module's JavaScript file. */
export declare const org_docx4j_com_microsoft_schemas_office_word_x2010_wordprocessingShape: JsonixMapping<RootElement>;
