// Generated by jsonix-schema-compiler: TypeScript declarations for the Jsonix module [org_docx4j_com_microsoft_schemas_office_x2006_encryption]. Do not edit.
// Describes the objects Jsonix produces when unmarshalling with this module's mappings.
import type * as Dep_org_docx4j_com_microsoft_schemas_office_x2006_keyEncryptor_password from './org_docx4j_com_microsoft_schemas_office_x2006_keyEncryptor_password';
import type * as Dep_org_docx4j_com_microsoft_schemas_office_x2006_keyEncryptor_certificate from './org_docx4j_com_microsoft_schemas_office_x2006_keyEncryptor_certificate';

/** Jsonix.XML.QName */
export interface XmlQName { namespaceURI: string; localPart: string; prefix?: string; key?: string; string?: string; }
/** Jsonix.XML.Calendar: the representation of date, time and dateTime values; unset fields are NaN. */
export interface XmlCalendar { year?: number; month?: number; day?: number; hour?: number; minute?: number; second?: number; fractionalSecond?: number; timezone?: number; }
/** The representation of xs:duration values. */
export interface XmlDuration { sign?: number; years?: number; months?: number; days?: number; hours?: number; minutes?: number; seconds?: number; }
/** An element as returned by an unmarshaller or held by an elementRef property. */
export interface TypedNamedValue<T> { name: XmlQName; value: T; }
/** A DOM node, allowed where the mapping permits DOM content (allowDom). */
export type XmlDomNode = any;
/** The value of an anyElement property: a typed element, a DOM node or (if mixed) text. */
export type XmlAnyElement = any;
/** The value of an anyAttribute property. */
export interface XmlAnyAttributes { [attributeName: string]: string; }
/** A Jsonix mapping object as consumed by new Jsonix.Context([...]); R is the union of its global element types. */
export interface JsonixMapping<R = unknown> { readonly __rootElement?: R; readonly [key: string]: unknown; }

export interface CTDataIntegrity {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_x2006_encryption.CTDataIntegrity';
  encryptedHmacKey: string;
  encryptedHmacValue: string;
}

export interface CTEncryption {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_x2006_encryption.CTEncryption';
  keyData: CTKeyData;
  dataIntegrity: CTDataIntegrity;
  keyEncryptors: CTKeyEncryptors;
}

export interface CTKeyData {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_x2006_encryption.CTKeyData';
  saltSize: number;
  blockSize: number;
  keyBits: number;
  hashSize: number;
  cipherAlgorithm: string;
  cipherChaining: STCipherChaining;
  hashAlgorithm: STHashAlgorithm;
  saltValue: string;
}

export interface CTKeyEncryptor {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_x2006_encryption.CTKeyEncryptor';
  encryptedPasswordKey: Dep_org_docx4j_com_microsoft_schemas_office_x2006_keyEncryptor_password.CTPasswordKeyEncryptor;
  encryptedCertificateKey: Dep_org_docx4j_com_microsoft_schemas_office_x2006_keyEncryptor_certificate.CTCertificateKeyEncryptor;
  uri?: string;
}

export interface CTKeyEncryptors {
  TYPE_NAME?: 'org_docx4j_com_microsoft_schemas_office_x2006_encryption.CTKeyEncryptors';
  keyEncryptor: CTKeyEncryptor[];
}

export type STCipherChaining = 'ChainingModeCBC' | 'ChainingModeCFB';

export type STHashAlgorithm = 'SHA1' | 'SHA256' | 'SHA384' | 'SHA512' | 'MD5' | 'MD4' | 'MD2' | 'RIPEMD-128' | 'RIPEMD-160' | 'WHIRLPOOL';

export type EncryptionElement = TypedNamedValue<CTEncryption>;

/** Any global element of this mapping, i.e. what an unmarshaller returns. */
export type RootElement = EncryptionElement;

/** The Jsonix mapping [org_docx4j_com_microsoft_schemas_office_x2006_encryption] exported by the module's JavaScript file. */
export declare const org_docx4j_com_microsoft_schemas_office_x2006_encryption: JsonixMapping<RootElement>;
