// Generated by jsonix-schema-compiler: TypeScript declarations for the Jsonix module [org_docx4j_sharedtypes]. Do not edit.
// Describes the objects Jsonix produces when unmarshalling with this module's mappings.

/** Jsonix.XML.QName */
export interface XmlQName { namespaceURI: string; localPart: string; prefix?: string; key?: string; string?: string; }
/** Jsonix.XML.Calendar: the representation of date, time and dateTime values; unset fields are NaN. */
export interface XmlCalendar { year?: number; month?: number; day?: number; hour?: number; minute?: number; second?: number; fractionalSecond?: number; timezone?: number; }
/** The representation of xs:duration values. */
export interface XmlDuration { sign?: number; years?: number; months?: number; days?: number; hours?: number; minutes?: number; seconds?: number; }
/** An element as returned by an unmarshaller or held by an elementRef property. */
export interface TypedNamedValue<T> { name: XmlQName; value: T; }
/** A DOM node, allowed where the mapping permits DOM content (allowDom). */
export type XmlDomNode = any;
/** The value of an anyElement property: a typed element, a DOM node or (if mixed) text. */
export type XmlAnyElement = any;
/** The value of an anyAttribute property. */
export interface XmlAnyAttributes { [attributeName: string]: string; }
/** A Jsonix mapping object as consumed by new Jsonix.Context([...]); R is the union of its global element types. */
export interface JsonixMapping<R = unknown> { readonly __rootElement?: R; readonly [key: string]: unknown; }

export type STCalendarType = 'gregorian' | 'gregorianUs' | 'gregorianMeFrench' | 'gregorianArabic' | 'hijri' | 'hebrew' | 'taiwan' | 'japan' | 'thai' | 'korea' | 'saka' | 'gregorianXlitEnglish' | 'gregorianXlitFrench' | 'none';

export type STConformanceClass = 'strict' | 'transitional';

export type STOnOff = 'true' | 'false' | 'on' | 'off' | '0' | '1';

export type STVerticalAlignRun = 'baseline' | 'superscript' | 'subscript';

export type STXAlign = 'left' | 'center' | 'right' | 'inside' | 'outside';

export type STYAlign = 'inline' | 'top' | 'center' | 'bottom' | 'inside' | 'outside';

/** The Jsonix mapping [org_docx4j_sharedtypes] exported by the module's JavaScript file. */
export declare const org_docx4j_sharedtypes: JsonixMapping;
