// Generated by jsonix-schema-compiler: Jsonix mappings of the module [org_docx4j_dml_lockedCanvas] as an ES module. Do not edit.
export const org_docx4j_dml_lockedCanvas = {
  name: 'org_docx4j_dml_lockedCanvas',
  defaultElementNamespaceURI: 'http:\/\/schemas.openxmlformats.org\/drawingml\/2006\/lockedCanvas',
  dependencies: ['org_docx4j_dml'],
  typeInfos: [],
  elementInfos: [{
      typeInfo: 'org_docx4j_dml.CTGvmlGroupShape',
      elementName: 'lockedCanvas'
    }]
};
