// Generated by jsonix-schema-compiler: TypeScript declarations for the Jsonix module [org_docx4j_mce]. Do not edit.
// Describes the objects Jsonix produces when unmarshalling with this module's mappings.
import type * as Dep_org_pptx4j_pml from './org_pptx4j_pml';
import type * as Dep_org_docx4j_wml from './org_docx4j_wml';
import type * as Dep_org_docx4j_math from './org_docx4j_math';
import type * as Dep_org_xlsx4j_sml from './org_xlsx4j_sml';

/** Jsonix.XML.QName */
export interface XmlQName { namespaceURI: string; localPart: string; prefix?: string; key?: string; string?: string; }
/** Jsonix.XML.Calendar: the representation of date, time and dateTime values; unset fields are NaN. */
export interface XmlCalendar { year?: number; month?: number; day?: number; hour?: number; minute?: number; second?: number; fractionalSecond?: number; timezone?: number; }
/** The representation of xs:duration values. */
export interface XmlDuration { sign?: number; years?: number; months?: number; days?: number; hours?: number; minutes?: number; seconds?: number; }
/** An element as returned by an unmarshaller or held by an elementRef property. */
export interface TypedNamedValue<T> { name: XmlQName; value: T; }
/** A DOM node, allowed where the mapping permits DOM content (allowDom). */
export type XmlDomNode = any;
/** The value of an anyElement property: a typed element, a DOM node or (if mixed) text. */
export type XmlAnyElement = any;
/** The value of an anyAttribute property. */
export interface XmlAnyAttributes { [attributeName: string]: string; }
/** A Jsonix mapping object as consumed by new Jsonix.Context([...]); R is the union of its global element types. */
export interface JsonixMapping<R = unknown> { readonly __rootElement?: R; readonly [key: string]: unknown; }

export interface AlternateContent {
  TYPE_NAME?: 'org_docx4j_mce.AlternateContent';
  readonly PARENT?: Dep_org_docx4j_math.CTR | Dep_org_docx4j_wml.CTMathRunTrackChange | Dep_org_docx4j_wml.R | Dep_org_pptx4j_pml.CTControlList | Dep_org_pptx4j_pml.GroupShape | Dep_org_xlsx4j_sml.Workbook;
  choice?: AlternateContent.Choice[];
  fallback?: AlternateContent.Fallback;
  ignorable?: string;
  mustUnderstand?: string;
  processContent?: string;
}

export type AlternateContentElement = TypedNamedValue<AlternateContent>;

/** Any global element of this mapping, i.e. what an unmarshaller returns. */
export type RootElement = AlternateContentElement;

export namespace AlternateContent {
  export interface Choice {
    TYPE_NAME?: 'org_docx4j_mce.AlternateContent.Choice';
    readonly PARENT?: AlternateContent;
    any?: XmlAnyElement[];
    requires: string;
    ignorable?: string;
    mustUnderstand?: string;
    processContent?: string;
  }

  export interface Fallback {
    TYPE_NAME?: 'org_docx4j_mce.AlternateContent.Fallback';
    readonly PARENT?: AlternateContent;
    any?: XmlAnyElement[];
    ignorable?: string;
    mustUnderstand?: string;
    processContent?: string;
  }
}

/** The Jsonix mapping [org_docx4j_mce] exported by the module's JavaScript file. */
export declare const org_docx4j_mce: JsonixMapping<RootElement>;
