// Generated by jsonix-schema-compiler: declarations of the per-name element wrappers for the Jsonix module [PurchaseOrder]. Do not edit.
import type * as M from './PurchaseOrder.js';
import type { XmlQName, XmlCalendar, XmlDuration, XmlDomNode, XmlAnyElement, XmlAnyAttributes } from './PurchaseOrder.js';

/** The element comment. */
export function comment(value: string): M.TypedNamedValue<string>;
/** The element purchaseOrder. */
export function purchaseOrder(value: M.PurchaseOrderType): M.TypedNamedValue<M.PurchaseOrderType>;
